/** Texte des Agent-Tabs (8.16d1: Seite und tabs/agent.ts). */
import type { Texte } from "../i18n.js";

export const agent: Texte = {
  emptySub: { de: "Stell eine Frage. Du zahlst pro Anfrage.", en: "Ask a question. You pay per request." },
  emptyHint: { de: "Modell wählen · Werkzeuge anhängen", en: "Choose a model · attach tools" },
  aiPlaceholder: { de: "Nachricht an den Agenten", en: "Message the agent" },
  send: { de: "Senden", en: "Send" },
  // Stand eines Auftrags (setTypingStatus/showTyping)
  thinking: { de: "denkt nach…", en: "thinking…" },
  connecting: { de: "verbindet…", en: "connecting…" },
  researching: { de: "recherchiert…", en: "researching…" },
  creating: { de: "erstellt…", en: "creating…" },
  copyLast: { de: "Letzte kopieren", en: "Copy last" },
  copyAll: { de: "Alle kopieren", en: "Copy all" },
  bid: { de: "Gebot (sats)", en: "Bid (sats)" },
  tierFree: { de: "Free — kleines Modell", en: "Free — small model" },
  tierClassic: { de: "Classic — ausgewogen", en: "Classic — balanced" },
  tierPro: { de: "Pro — vertrauenswürdige Anbieter", en: "Pro — trusted providers" },
  tierMax: { de: "Max — schnellster gewinnt", en: "Max — fastest wins" },
  tierSwarm: { de: "Swarm — bestes aus mehreren", en: "Swarm — best of several" },
  // Seite (index.html)
  "agent.neueAufgabe": { de: "Neue Aufgabe", en: "New task" },
  "agent.tabAufgaben": { de: "Aufgaben", en: "Tasks" },
  "agent.tabModelle": { de: "Modelle", en: "Models" },
  "agent.tabRepos": { de: "Repos", en: "Repos" },
  "agent.pruefauftraege": { de: "Prüfaufträge", en: "Review requests" },
  "agent.pruefauftraegeText": { de: "Jemand aus deinem Netz hat dich als Prüfer einer Reklamation genannt. Dein Urteil geht versiegelt nur an den Kunden und den Provider und gilt nur zwischen ihnen – eine Erstattung zahlt der Provider selbst.", en: "Someone in your network named you as the reviewer of a complaint. Your verdict goes sealed only to the customer and the provider and applies only between them – any refund is paid by the provider." },
  "agent.reklamationen": { de: "Deine Reklamationen", en: "Your complaints" },
  "agent.reklamationenText": { de: "Den Prüfer hast du aus deinem Netz gewählt. Sein Urteil gilt nur zwischen dir und dem Provider – erstatten muss der Provider selbst.", en: "You chose the reviewer from your network. Their verdict applies only between you and the provider – the provider has to refund you." },
  "agent.nachUrteilen": { de: "nach Urteilen sehen", en: "check for verdicts" },
  "agent.modelleImNetz": { de: "Modelle im Netz", en: "Models in the network" },
  "agent.modelleText": { de: "Was im Netz vorgehalten wird. Modelle mit nur einem Seeder sind gefährdet. Selbst vorhalten oder ankündigen: Verdienen › Hosten.", en: "What the network keeps available. Models with only one seeder are at risk. To seed or announce one yourself: Earn › Host." },
  "agent.lade": { de: "lade …", en: "loading …" },
  "agent.aktualisieren": { de: "aktualisieren", en: "refresh" },
  "agent.modellVorhalten": { de: "Modell vorhalten", en: "Seed a model" },
  "agent.modellAnkuendigen": { de: "Modell ankündigen", en: "Announce a model" },
  "agent.kataloge": { de: "Modellkataloge", en: "Model catalogs" },
  "agent.katalogeText": { de: "Ein Katalog ist die Liste eines Kurators (NIP-51): welche Modelle er empfiehlt. Voreingestellt ist keiner – du abonnierst, wem du folgst, auch mehrere, und vergleichst sie mit dem, was Provider gerade anbieten. Ein Katalog sagt nur, wer ein Modell empfiehlt, nicht, ob es gut ist. Die App lädt alle Kataloge und wählt selbst aus; die Relays erfahren nicht, welche du abonniert hast.", en: "A catalog is a curator's list (NIP-51): which models they recommend. None is preset – you subscribe to whom you follow, even several, and compare them with what providers currently offer. A catalog only says who recommends a model, not whether it is good. The app loads all catalogs and selects locally; the relays don't learn which ones you subscribed to." },
  "agent.katalogVeroeffentlichen": { de: "eigenen Katalog veröffentlichen", en: "publish your own catalog" },
  "agent.repositories": { de: "Repositories", en: "Repositories" },
  "agent.reposText": { de: "Git-Bundles liegen im Speichernetz; Zusammenarbeit (Patches, Annahme) läuft nach NIP-34.", en: "Git bundles live in the storage network; collaboration (patches, acceptance) follows NIP-34." },
  "agent.repoNamePh": { de: "Repo-Name", en: "repo name" },
  "agent.bundlePublizieren": { de: "⇪ Bundle publizieren", en: "⇪ Publish bundle" },
  "agent.nip34Text1": { de: "Ankündigungen, Patches und Annahmen sind öffentlich und mit deinem Schlüssel signiert – wie bei jedem Git-Projekt. Andere Nostr-Clients (ngit, gitworkshop) lesen sie auch. Einen Patch erzeugst du mit", en: "Announcements, patches and acceptances are public and signed with your key – like in any Git project. Other Nostr clients (ngit, gitworkshop) read them too. You create a patch with" },
  "agent.nip34Text2": { de: "; angenommen ist er, wenn Eigentümer oder Maintainer es sagen.", en: "; it is accepted when the owner or a maintainer says so." },
  "agent.repoKennungPh": { de: "Repo-Kennung", en: "repo identifier" },
  "agent.klonPh": { de: "Klon-Adressen (https://…, rad:…), mit Komma", en: "Clone addresses (https://…, rad:…), comma-separated" },
  "agent.repoAnkuendigen": { de: "Repo ankündigen", en: "Announce repo" },
  "agent.quotaTitel": { de: "Gratis-Kontingent heute", en: "Free quota today" },
  "agent.quota": { de: "Gratis-Kontingent", en: "Free quota" },
  "agent.beispiel1": { de: "„Erkläre mir das Nostr-Protokoll…“", en: "“Explain the Nostr protocol…”" },
  "agent.beispiel1Prompt": { de: "Erkläre mir das Nostr-Protokoll in einem Satz.", en: "Explain the Nostr protocol in one sentence." },
  "agent.beispiel2": { de: "„Vorteile von Lightning…“", en: "“Benefits of Lightning…”" },
  "agent.beispiel2Prompt": { de: "Schreibe eine kurze Zusammenfassung der wichtigsten Vorteile von Lightning.", en: "Write a short summary of the main benefits of Lightning." },
  "agent.beispiel3": { de: "„Bild: Leuchtturm bei Nacht…“", en: "“Image: lighthouse at night…”" },
  "agent.beispiel3Prompt": { de: "Erstelle ein Bild: ein Leuchtturm bei Nacht.", en: "Create an image: a lighthouse at night." },
  "agent.anhangBild": { de: "Bild", en: "image" },
  "agent.anhangDatei": { de: "Datei", en: "file" },
  "agent.anhangAudio": { de: "Audio", en: "audio" },
  "agent.anhangVideo": { de: "Video", en: "video" },
  "agent.anhangKamera": { de: "Kamera", en: "camera" },
  // Namen für Vorleser (C-4)
  "agent.stufeAria": { de: "Stufe der Antwort", en: "Answer tier" },
  "agent.anhaengenAria": { de: "Anhang hinzufügen", en: "Add attachment" },
  "agent.werkzeugWeb": { de: "Web", en: "web" },
  "agent.werkzeugBrowser": { de: "Browser", en: "browser" },
  "agent.werkzeugBild": { de: "Bild", en: "image" },
  "agent.werkzeugVideo": { de: "Video", en: "video" },
  "agent.laenge": { de: "Länge", en: "Length" },
  "agent.qualitaet": { de: "Qualität", en: "Quality" },
  "agent.kopierenLetzte": { de: "Letzte Antwort kopieren", en: "Copy last answer" },
  "agent.kopierenAlle": { de: "Ganze Unterhaltung kopieren", en: "Copy whole conversation" },
  "agent.modellWaehlen": { de: "Modell wählen", en: "Choose model" },
  "agent.autoSchnellste": { de: "auto (schnellste)", en: "auto (fastest)" },
  "agent.arbeitsbereich": { de: "Arbeitsbereich", en: "Workspace" },
  "agent.keinRepo": { de: "Kein Repository verbunden.", en: "No repository connected." },
  "agent.werkzeuge": { de: "Werkzeuge", en: "Tools" },
  "agent.nochKeineWerkzeuge": { de: "Noch keine in dieser Sitzung.", en: "None in this session yet." },
  "agent.kosten": { de: "Kosten", en: "Costs" },
  // Modellwahl
  "agent.schnell": { de: "⚡⚡ schnell", en: "⚡⚡ fast" },
  "agent.mittel": { de: "⚡ mittel", en: "⚡ medium" },
  "agent.tief": { de: "🐢 tiefgründig", en: "🐢 thorough" },
  "agent.auto": { de: "Auto", en: "Auto" },
  "agent.schnellste": { de: "schnellste", en: "fastest" },
  "agent.autoSub": { de: "Netz wählt das beste verfügbare Modell", en: "the network picks the best available model" },
  "agent.mcSub": { de: "~{preis} /1k Tokens · {n} Provider", en: "~{preis} /1k tokens · {n} provider(s)" },
  "agent.inKatalog": { de: "in {n} Katalog", en: "in {n} catalog" },
  "agent.inKatalogen": { de: "in {n} Katalogen", en: "in {n} catalogs" },
  // Verlauf, Seitenleiste
  "agent.aufgabe": { de: "Aufgabe", en: "Task" },
  "agent.keineAufgaben": { de: "Noch keine Aufgaben.", en: "No tasks yet." },
  "agent.heute": { de: "Heute", en: "Today" },
  "agent.frueher": { de: "Früher", en: "Earlier" },
  "agent.nachrichten": { de: "{n} Nachrichten", en: "{n} messages" },
  "agent.dieseSitzung": { de: "Diese Sitzung", en: "This session" },
  "agent.gebuehrVorschau": { de: "{betrag} → Provider mind. {provider} / Anteile höchstens {anteile}", en: "{betrag} → provider at least {provider} / shares at most {anteile}" },
  "agent.schaetzung": { de: "~{tokens} Tokens ≈ {preis}", en: "~{tokens} tokens ≈ {preis}" },
  // Fehler
  "agent.fehlerRelay": { de: "Relay-Verbindung fehlgeschlagen — Internet prüfen oder später erneut versuchen", en: "Relay connection failed — check your internet or try again later" },
  "agent.fehlerKeinProvider": { de: "Kein Provider erreichbar — alle Kandidaten haben nicht rechtzeitig geantwortet", en: "No provider reachable — no candidate answered in time" },
  "agent.fehlerGebot": { de: "Gebot zu niedrig und kein Gratis-Kontingent mehr — Gebot erhöhen oder morgen wieder gratis testen", en: "Bid too low and no free quota left — raise the bid or try for free again tomorrow" },
  "agent.fehlerIdentitaet": { de: "Identität fehlt — bitte neu anmelden", en: "Identity missing — please sign in again" },
  "agent.fehlerTimeout": { de: "Zeitüberschreitung — Provider zu langsam oder offline", en: "Timeout — provider too slow or offline" },
  "agent.fehlerComfy": { de: "ComfyUI nicht erreichbar (Port 8188) — Bild und Video brauchen ein laufendes ComfyUI", en: "ComfyUI not reachable (port 8188) — images and video need a running ComfyUI" },
  "agent.fehlerNetz": { de: "Netzwerkfehler — Verbindung zum Relay oder Server unterbrochen", en: "Network error — connection to the relay or server interrupted" },
  "agent.fehler": { de: "⚠️ Fehler", en: "⚠️ Error" },
  "agent.ursache": { de: "Ursache:", en: "Cause:" },
  "agent.erneut": { de: "↻ erneut versuchen", en: "↻ try again" },
  "agent.stop": { de: "■ Stopp", en: "■ Stop" },
  "agent.kontingentAufgebraucht": { de: "Gratis-Kontingent aufgebraucht — erst Guthaben einzahlen", en: "Free quota used up — deposit funds first" },
  "agent.providerLehntAb": { de: "Provider lehnt ab ({grund}) — nächster…", en: "Provider declines ({grund}) — next…" },
  "agent.providerLangsam": { de: "Provider {pk} langsam — der nächste bekommt den Auftrag zusätzlich…", en: "Provider {pk} slow — the next one gets the job as well…" },
  "agent.keinProviderAntwort": { de: "Kein Provider im Netz hat geantwortet", en: "No provider in the network answered" },
  "agent.abgebrochen": { de: "[abgebrochen]", en: "[cancelled]" },
  "agent.funkKeinGateway": { de: "Kein Funk-Gateway gemerkt – wähle eines, solange du Netz hast (Seite Netz).", en: "No radio gateway saved – choose one while you are online (Network page)." },
  "agent.funkOhneKurs": { de: "Das gemerkte Gateway nennt keinen SOL-Kurs – bezahlt geht über Funk so nichts. Gratis (Gebot 0) geht.", en: "The saved gateway names no SOL rate – paid requests via radio are not possible this way. Free (bid 0) works." },
  "agent.funkNurKanal": { de: "Über Funk zahlt die App nur über einen Zahlkanal zu diesem Provider – Lightning braucht Netz. Öffne einen Kanal, solange du Netz hast, oder frag gratis (Gebot 0).", en: "Via radio the app only pays through a payment channel to this provider – Lightning needs a network. Open a channel while you are online, or ask for free (bid 0)." },
  "agent.funkKeinGeraet": { de: "Kein Funkgerät verbunden (Seite Netz → Mesh).", en: "No radio connected (Network page → Mesh)." },
  "agent.funkRueckmeldung": { de: "Über Funk: Der Provider lehnt ab – {grund}", en: "Via radio: the provider declines – {grund}" },
  "agent.ueberFunk": { de: "über Funk", en: "via radio" },
  // KI auf diesem Gerät (B-1)
  "agent.gruppeNetz": { de: "Netz", en: "Network" },
  "agent.gruppeGeraet": { de: "Dieses Gerät", en: "This device" },
  "agent.gruppeKnoten": { de: "Mein Knoten", en: "My node" },
  "agent.knotenKurz": { de: "mein Knoten", en: "my node" },
  "agent.knotenStandard": { de: "Modell des Knotens", en: "Node's model" },
  "agent.knotenModellSub": { de: "gratis · nur dein Knoten {knoten}, kein Ausweichen", en: "free · only your node {knoten}, no fallback" },
  "agent.knotenOhneAngebot": { de: "Angebot von {knoten} nicht gefunden – die Frage geht trotzdem nur an deinen Knoten", en: "No offer from {knoten} found – the question still goes only to your node" },
  "agent.knotenNichtGekoppelt": { de: "Kein Knoten gekoppelt – Settings → Geräte → „Mein Knoten koppeln“", en: "No node paired – Settings → Devices → “Pair my node”" },
  "agent.knotenSchweigt": { de: "Dein Knoten {knoten} hat nicht geantwortet. Die Frage ging an keinen anderen Provider.", en: "Your node {knoten} did not answer. The question went to no other provider." },
  "agent.knotenLehntAb": { de: "Dein Knoten lehnt ab: {grund}", en: "Your node declines: {grund}" },
  "agent.knotenGratis": { de: "gratis · mein Knoten", en: "free · my node" },
  "agent.knotenOhneRelay": { de: "Mein Knoten nennt kein Relay – mit „Alles über meinen Knoten“ geht die Frage nicht hinaus (Settings → Geräte)", en: "My node names no relay – with “Everything through my node” the question does not go out (Settings → Devices)" },
  "agent.lokalKurz": { de: "dieses Gerät", en: "this device" },
  "agent.lokalSuchen": { de: "Modell auf diesem Gerät suchen", en: "Look for a model on this device" },
  "agent.lokalSuchenSub": { de: "Ollama, llama.cpp oder LM Studio – gratis, ohne Netz, die Frage bleibt auf dem Gerät. Der Browser fragt eventuell um Erlaubnis.", en: "Ollama, llama.cpp or LM Studio – free, without a network, the question stays on the device. The browser may ask for permission." },
  "agent.lokalSucht": { de: "sucht …", en: "searching …" },
  "agent.lokalModellSub": { de: "gratis · die Frage bleibt auf dem Gerät", en: "free · the question stays on the device" },
  "agent.lokalKeine": { de: "Unter {adresse} läuft ein Dienst, aber ohne Modell. Lade eines, z. B. mit „ollama pull llama3.2“.", en: "A service runs at {adresse}, but without a model. Load one, e.g. with “ollama pull llama3.2”." },
  "agent.lokalOrigins": { de: "Ollama nimmt Anfragen dieser Seite erst mit OLLAMA_ORIGINS={herkunft} an.", en: "Ollama only accepts requests from this page with OLLAMA_ORIGINS={herkunft}." },
  "agent.lokalErneut": { de: "Erneut suchen", en: "Search again" },
  "agent.lokalAdresse": { de: "Adresse: {adresse} – ändern", en: "Address: {adresse} – change" },
  "agent.lokalAdresseTitel": { de: "Modell auf diesem Gerät", en: "Model on this device" },
  "agent.lokalAdresseLabel": { de: "Adresse (nur localhost, 127.0.0.1 oder [::1])", en: "Address (only localhost, 127.0.0.1 or [::1])" },
  "agent.lokalAdresseFremd": { de: "Nur Adressen dieses Rechners: localhost, 127.0.0.1 oder [::1].", en: "Only addresses of this computer: localhost, 127.0.0.1 or [::1]." },
  "agent.lokalNichtErreichbar": { de: "Unter {adresse} antwortet kein Modell – läuft Ollama, llama.cpp oder LM Studio?", en: "No model answers at {adresse} – is Ollama, llama.cpp or LM Studio running?" },
  "agent.lokalHttp": { de: "Das Modell auf diesem Gerät antwortet mit HTTP {status}.", en: "The model on this device answers with HTTP {status}." },
  "agent.lokalLeer": { de: "Das Modell auf diesem Gerät hat keine Antwort geliefert.", en: "The model on this device returned no answer." },
  "agent.lokalZeit": { de: "Das Modell auf diesem Gerät hat länger als drei Minuten gebraucht.", en: "The model on this device took longer than three minutes." },
  "agent.lokalAbgebrochen": { de: "Abgebrochen.", en: "Cancelled." },
  "agent.lokalOhneWerkzeuge": { de: "Dieses Gerät: ohne Werkzeuge – Websuche und Browser gibt es nur über das Netz.", en: "This device: without tools – web search and browser are only available via the network." },
  "agent.lokalMeta": { de: "dieses Gerät · {tokens} Tokens · gratis", en: "this device · {tokens} tokens · free" },
  "agent.lokalGratis": { de: "gratis · dieses Gerät", en: "free · this device" },
  "agent.ueberFunkTitel": { de: "Frage über dein Funkgerät an das gemerkte Gateway – kurze Antwort, höchstens 500 Zeichen", en: "Ask via your radio through the saved gateway – short answer, at most 500 characters" },
  "agent.funkLabel": { de: "KI über Funk", en: "AI via radio" },
  "agent.funkUnterwegs": { de: "Über Funk unterwegs. Die Antwort (höchstens 500 Zeichen) kommt in einigen Minuten – nur, solange die App offen bleibt. Ein Gateway schafft rund zwei Antworten je Stunde.", en: "On its way via radio. The answer (at most 500 characters) arrives within a few minutes – only while the app stays open. A gateway manages about two answers per hour." },
  "agent.funkMeta": { de: "über Funk · auf „{frage}“", en: "via radio · to “{frage}”" },
  "agent.keinPrivaterProvider": { de: "Kein Provider für private Anfragen gefunden – die Knoten brauchen mindestens Stand 3.1.", en: "No provider for private requests found – nodes need at least version 3.1." },
  // Video (ComfyUI)
  "agent.videoWird": { de: "[Video] wird erstellt ({breite}×{hoehe}, ~{dauer} s) — das dauert ~1–2 min", en: "[video] being generated ({breite}×{hoehe}, ~{dauer} s) — this takes ~1–2 min" },
  "agent.videoFertig": { de: "✅ Video fertig:", en: "✅ Video ready:" },
  "agent.videoFehler": { de: "(Video-Fehler: {grund})", en: "(video error: {grund})" },
  "agent.unbekannt": { de: "unbekannt", en: "unknown" },
  "agent.videoTimeout": { de: "(Video-Zeitüberschreitung — versuch es kürzer oder später)", en: "(video timeout — try shorter or later)" },
  // Max und Swarm
  "agent.maxKeinProvider": { de: "Kein Provider in der Stufe „Max“ erreichbar", en: "No provider in the “Max” tier reachable" },
  "agent.maxStart": { de: "Max: {n} Provider treten an — bezahlt wird die schnellste Antwort", en: "Max: {n} providers race — only the fastest answer is paid" },
  "agent.maxGewinner": { de: "{pk} ist am schnellsten", en: "{pk} is fastest" },
  "agent.maxKeiner": { de: "Max: kein Provider hat geantwortet", en: "Max: no provider answered" },
  "agent.swarmKeinProvider": { de: "Kein Provider für Swarm — der FreedomStack-Knoten läuft nicht", en: "No provider for swarm — the FreedomStack node isn't running" },
  "agent.swarmStart": { de: "Swarm: beide Modelle (nemotron + qwen3.8:27b) denken parallel…", en: "Swarm: both models (nemotron + qwen3.8:27b) think in parallel…" },
  "agent.swarmTimeout": { de: "Swarm: der Provider antwortet nicht — Zeitüberschreitung", en: "Swarm: the provider doesn't answer — timeout" },
  // Vergleich (Redundanz-Konsens, A-7)
  "agent.konsens": { de: "vergleichen", en: "compare" },
  "agent.konsensWahlTitel": { de: "Diese Frage an mehrere Provider stellen und die Antworten vergleichen – kostet ein Mehrfaches, gilt nur für diese Frage", en: "Ask several providers this question and compare the answers – costs a multiple, applies to this question only" },
  "agent.konsensTitel": { de: "Frage an {n} Provider?", en: "Ask {n} providers?" },
  "agent.konsensKosten": { de: "Jeder der {n} Provider sieht die Frage und wird bis zu deinem Gebot bezahlt – zusammen höchstens {betrag}. Danach siehst du, ob die Antworten übereinstimmen.", en: "Each of the {n} providers sees the question and is paid up to your bid – at most {betrag} in total. Afterwards you see whether the answers agree." },
  "agent.konsensSenden": { de: "An {n} senden", en: "Send to {n}" },
  "agent.konsensZuWenige": { de: "Für einen Vergleich braucht es mindestens zwei Provider – erreichbar: {n}. Die Frage ging nicht hinaus.", en: "A comparison needs at least two providers – reachable: {n}. The question was not sent." },
  "agent.konsensStart": { de: "Vergleich: {n} Provider bekommen die Frage", en: "Comparison: {n} providers get the question" },
  "agent.konsensEinig": { de: "Vergleich: Alle {n} Antworten stimmen inhaltlich überein.", en: "Comparison: all {n} answers agree in substance." },
  "agent.konsensMehrheit": { de: "Vergleich: {einig} von {n} Antworten stimmen überein, abweichend: {wer}. Abweichung heißt nicht Betrug – nur, dass hier jemand etwas anderes geliefert hat als die übrigen.", en: "Comparison: {einig} of {n} answers agree, differing: {wer}. A difference doesn't mean fraud – only that someone delivered something other than the rest." },
  "agent.konsensUneinig": { de: "Vergleich: Die {n} Antworten gehen auseinander, keine hat eine Mehrheit. Bei einer wichtigen Frage: genauer fragen oder neu stellen.", en: "Comparison: the {n} answers diverge, none has a majority. For an important question: ask more precisely or ask again." },
  "agent.konsensZuWenigeAntworten": { de: "Vergleich: {n} von {gefragt} Providern haben geantwortet – zu wenige für eine Aussage.", en: "Comparison: {n} of {gefragt} providers answered – too few for a statement." },
  "agent.konsensHinweis": { de: "Übereinstimmung heißt stimmig, nicht richtig: Nutzen alle dasselbe Modell, teilen sie auch dessen Irrtümer.", en: "Agreement means consistent, not correct: if all use the same model, they share its mistakes too." },
  "agent.modellGewechselt": { de: "⇄ Modell gewechselt zu", en: "⇄ switched model to" },
  "agent.kontextMit": { de: "der Kontext wird mitgegeben ({n} Nachrichten)", en: "the context is passed along ({n} messages)" },
  // Antwort, Zahlung
  "agent.providerKurz": { de: "Provider {pk}…", en: "provider {pk}…" },
  "agent.providerVerlangte": { de: "Provider verlangte {sats} sats – mehr als dein Gebot; die App zahlt höchstens das Gebot", en: "Provider asked for {sats} sats – more than your bid; the app pays at most the bid" },
  "agent.bezahlt": { de: "bezahlt: {sats} sats an den Provider", en: "paid: {sats} sats to the provider" },
  "agent.zahlungUnklar": { de: "Zahlung an den Provider unklar – sieh in deiner Wallet nach. In dieser Sitzung zahlt die App nicht noch einmal.", en: "Payment to the provider unclear – check your wallet. The app won't pay again in this session." },
  "agent.belegGesammelt": { de: "Beleg gespeichert – gezahlt wird gesammelt ab {sats} sats", en: "Receipt saved – paid in bulk from {sats} sats" },
  "agent.belegNichtBezahlt": { de: "Beleg gespeichert, nicht bezahlt: {grund}", en: "Receipt saved, not paid: {grund}" },
  "agent.anteilUnklar": { de: "Eine gesammelte Zahlung ist unklar – unter Währung › Zahlen prüfen.", en: "A bulk payment is unclear – check under Wallet › Pay." },
  "agent.keineSitzung": { de: "Noch keine Sitzung. Die erste Anfrage startet eine.", en: "No session yet. The first request starts one." },
  "agent.sitzung": { de: "Sitzung: {bezahlt}/{max} sats ({pct} %)", en: "session: {bezahlt}/{max} sats ({pct}%)" },
  // Reklamation
  "agent.keinPruefer": { de: "Kein Prüfer in deinem Netz – die Reklamation geht nur an den Provider. Prüfen kann ein Kontakt oder ein eigener Provider.", en: "No reviewer in your network – the complaint goes only to the provider. A contact or one of your own providers can review." },
  "agent.ohneBezug": { de: "Ohne Bezug zur Antwort nicht reklamierbar", en: "Can't complain without a reference to the answer" },
  // Reklamation im Dialog (C-1f)
  "agent.reklamierenTitel": { de: "Auftrag reklamieren", en: "Complain about the job" },
  "agent.weiter": { de: "Weiter", en: "Continue" },
  "agent.problemFrage": { de: "Was war das Problem?", en: "What was the problem?" },
  "agent.prueferFrage": { de: "Wer aus deinem Netz soll nachprüfen? Er bekommt die Reklamation versiegelt; sein Urteil gilt nur zwischen dir und dem Provider.", en: "Who in your network should review? They get the complaint sealed; their verdict applies only between you and the provider." },
  "agent.nurProvider": { de: "niemand – nur der Provider", en: "nobody – only the provider" },
  "agent.materialFrage": { de: "Frage und Antwort", en: "Question and answer" },
  "agent.materialHaken": { de: "dem Prüfer mitschicken – ohne sie sieht er nur Grund und Notiz. Der Provider bekommt sie nicht noch einmal, Relays sehen sie nicht.", en: "send them to the reviewer – without them they only see reason and note. The provider doesn't get them again, relays don't see them." },
  "agent.beschreibung": { de: "Kurze Beschreibung (nur für Provider und Prüfer):", en: "Short description (only for provider and reviewer):" },
  "agent.reklamiert": { de: "Reklamiert. {info}", en: "Complaint filed. {info}" },
  "agent.reklamiertMit": { de: "Reklamiert – Provider und {name} benachrichtigt. {info}", en: "Complaint filed – provider and {name} notified. {info}" },
  // Kosten einer Antwort
  "agent.antwort": { de: "Antwort", en: "Answer" },
  "agent.tokensMeta": { de: "{n} Tokens · {sat} sat", en: "{n} tokens · {sat} sat" },
  "agent.modell": { de: "Modell", en: "Model" },
  "agent.provider": { de: "Provider", en: "Provider" },
  "agent.tokens": { de: "Tokens", en: "Tokens" },
  "agent.reinRaus": { de: "{rein} rein, {raus} raus", en: "{rein} in, {raus} out" },
  "agent.dieseAntwort": { de: "Diese Antwort", en: "This answer" },
  "agent.sitzungGesamt": { de: "Sitzung gesamt", en: "Session total" },
  "agent.reklamieren": { de: "Reklamieren", en: "Complain" },
  "agent.details": { de: "{pfeil} Details · {sats} sats", en: "{pfeil} details · {sats} sats" },
  "agent.anteilEntwicklung": { de: "Entwicklung", en: "Development" },
  "agent.anteilRelays": { de: "Relay", en: "Relay" },
  "agent.anteilWerberKunde": { de: "Dein Werber", en: "Your referrer" },
  "agent.anteilWerberProvider": { de: "Werber des Providers", en: "Provider's referrer" },
  "agent.anteilHosting": { de: "Hosting", en: "Hosting" },
  "agent.gesammelt": { de: "{betrag} · gesammelt", en: "{betrag} · collected" },
  "agent.anDenProvider": { de: "An den Provider", en: "To the provider" },
  "agent.weitereAnteile": { de: "Weitere Anteile", en: "Other shares" },
  "agent.keinEmpfaenger": { de: "kein Empfänger – beim Provider", en: "no recipient – stays with the provider" },
  // Schritte
  "agent.schrittVerbinden": { de: "Verbinde mit dem Provider-Netz", en: "Connecting to the provider network" },
  "agent.schrittRecherche": { de: "Recherchiert online (web_search / browser)", en: "Researching online (web_search / browser)" },
  "agent.schrittModell": { de: "Modell verarbeitet die Anfrage", en: "Model processes the request" },
  "agent.schrittMedien": { de: "Erstellt Medien (Bild/Video)", en: "Creating media (image/video)" },
  "agent.suchtWeb": { de: "sucht im Web…", en: "searching the web…" },
  "agent.liestSeiten": { de: "liest Webseiten…", en: "reading web pages…" },
  "agent.erstelltBild": { de: "erstellt Bild…", en: "creating image…" },
  "agent.erstelltVideo": { de: "erstellt Video…", en: "creating video…" },
  "agent.angehaengt": { de: "{name} angehängt", en: "{name} attached" },
  // Modelle, Kataloge, Repos (agent-netz.ts, 8.16e)
  "agent.keineModelle": { de: "Noch keine Modelle angekündigt.", en: "No models announced yet." },
  "agent.notizWeg": { de: "Niemand hält dieses Modell mehr vor.", en: "Nobody keeps this model available anymore." },
  "agent.notizFehlen": { de: "{n} Datei(en) fehlen im Netz – so nicht ladbar, auch wenn es {seeder} Seeder gibt.", en: "{n} file(s) missing in the network – not loadable like this, even with {seeder} seeders." },
  "agent.notizGut": { de: "{n} Seeder, vollständig.", en: "{n} seeders, complete." },
  "agent.notizKnapp": { de: "Nur {n} Seeder. Fällt einer aus, wird es eng.", en: "Only {n} seeders. If one drops out, it gets tight." },
  "agent.notizEiner": { de: "Ein einziger Seeder. Verschwindet er, ist das Modell weg.", en: "A single seeder. If it disappears, the model is gone." },
  "agent.gefaehrdet": { de: "Gefährdet: {namen}{mehr} – wer sie vorhält, hält sie im Netz.", en: "At risk: {namen}{mehr} – whoever keeps them available keeps them in the network." },
  "agent.undWeitere": { de: " und {n} weitere", en: " and {n} more" },
  "agent.nichtAbrufbar": { de: "Nicht abrufbar: {fehler}", en: "Not available: {fehler}" },
  // Dialoge statt prompt() (C-1b)
  "agent.modellKennungFrage": { de: "Modell-Kennung (z. B. qwen3.5:9b-q4)", en: "Model identifier (e.g. qwen3.5:9b-q4)" },
  "agent.dateienFrage": { de: "Dateien, je Zeile: name sha256 größe", en: "Files, one per line: name sha256 size" },
  "agent.dateienHinweis": { de: "Die Prüfsummen sind der ganze Sinn – ohne sie kann niemand prüfen, ob die geladene Datei die angekündigte ist.", en: "The checksums are the whole point – without them nobody can check that the downloaded file is the announced one." },
  "agent.ankuendigen": { de: "Ankündigen", en: "Announce" },
  "agent.keineZeileBrauchbar": { de: "Keine Zeile war brauchbar – Format: name sha256 größe", en: "No line was usable – format: name sha256 size" },
  "agent.dateienAngekuendigt": { de: "{n} Datei(en) angekündigt", en: "{n} file(s) announced" },
  "agent.welchesModell": { de: "Welches Modell hältst du vor?", en: "Which model do you keep available?" },
  "agent.welcheDateien": { de: "Welche Dateien? (kommagetrennt, leer = alle)", en: "Which files? (comma-separated, empty = all)" },
  "agent.vorhaltenMelden": { de: "Melden", en: "Report" },
  "agent.keinManifest": { de: "Für dieses Modell gibt es kein Manifest – erst ankündigen", en: "There is no manifest for this model – announce it first" },
  "agent.dateienGemeldet": { de: "{n} Datei(en) gemeldet", en: "{n} file(s) reported" },
  "agent.keinAbo": { de: "Noch kein Katalog abonniert – unten einen wählen.", en: "No catalog subscribed yet – choose one below." },
  "agent.katalogZeile": { de: "{titel} · von {kurator} · {n} Modelle", en: "{titel} · by {kurator} · {n} models" },
  "agent.katalogFehlt": { de: "{kennung}… · auf den Relays nicht gefunden", en: "{kennung}… · not found on the relays" },
  "agent.abbestellen": { de: "abbestellen", en: "unsubscribe" },
  "agent.abonnieren": { de: "abonnieren", en: "subscribe" },
  "agent.gemeinsam": { de: "Gemeinsam: {n}", en: "In common: {n}" },
  "agent.nurIn": { de: "nur in „{titel}“: {n}", en: "only in “{titel}”: {n}" },
  "agent.abTausend": { de: "ab (1.000 Tokens)", en: "from (1,000 tokens)" },
  "agent.keinAngebot": { de: "kein Angebot", en: "no offer" },
  "agent.keineKataloge": { de: "Keine weiteren Kataloge gefunden.", en: "No other catalogs found." },
  "agent.gefundeneKataloge": { de: "Gefundene Kataloge:", en: "Catalogs found:" },
  "agent.nurHauptKatalog": { de: "Einen Katalog veröffentlicht nur die Hauptidentität, nicht ein Gerät", en: "Only the main identity publishes a catalog, not a device" },
  "agent.katalogVeroeffentlichenTitel": { de: "Katalog veröffentlichen", en: "Publish a catalog" },
  "agent.katalogBeispiel": { de: "Ein gleicher Titel ersetzt deinen alten Katalog. Beispiel für die Modelle: qwen3.5:9b gut für Code; llama3.2:3b", en: "The same title replaces your old catalog. Example for the models: qwen3.5:9b good for code; llama3.2:3b" },
  "agent.katalogTitelFrage": { de: "Titel des Katalogs", en: "Catalog title" },
  "agent.katalogModelleFrage": { de: "Modelle, getrennt durch „;“ oder je Zeile – je Modell optional eine Notiz dahinter", en: "Models, separated by “;” or one per line – optionally a note after each model" },
  "agent.veroeffentlichen": { de: "Veröffentlichen", en: "Publish" },
  "agent.katalogVeroeffentlicht": { de: "Katalog „{titel}“ mit {n} Modellen veröffentlicht", en: "Catalog “{titel}” with {n} models published" },
  "agent.keineKatalogAdresse": { de: "Keine Katalog-Adresse", en: "Not a catalog address" },
  "agent.hoechstensKataloge": { de: "Höchstens {n} Kataloge – erst einen abbestellen", en: "At most {n} catalogs – unsubscribe one first" },
  "agent.bundleKaputt": { de: "Bundle nicht rekonstruierbar", en: "Bundle could not be reconstructed" },
  "agent.bundleGeladen": { de: "Bundle geladen – git clone {datei}", en: "Bundle downloaded – git clone {datei}" },
  "agent.fehlerText": { de: "Fehler: {fehler}", en: "Error: {fehler}" },
  // Werkzeugpreise (werkzeug-preise.ts)
  "agent.preisUnbekannt": { de: "Preis unbekannt", en: "Price unknown" },
  "agent.jeAufruf": { de: "{preis} je Aufruf", en: "{preis} per call" },
  "agent.jeAufrufRichtpreis": { de: "{preis} je Aufruf (Richtpreis)", en: "{preis} per call (guide price)" },
  // Streitfall (streitfall.ts, streitfall-ui.ts, pruefauftraege-ui.ts)
  "agent.prueferKontakt": { de: "Kontakt", en: "contact" },
  "agent.prueferProvider": { de: "eigener Provider", en: "own provider" },
  "agent.grundNichts": { de: "gar keine Antwort", en: "no answer at all" },
  "agent.grundUnbrauchbar": { de: "Antwort unbrauchbar", en: "answer unusable" },
  "agent.grundModell": { de: "anderes Modell als vereinbart", en: "different model than agreed" },
  "agent.grundAbgebrochen": { de: "mittendrin abgebrochen", en: "cut off midway" },
  "agent.urteilErstattet": { de: "gibt dir recht", en: "rules in your favor" },
  "agent.urteilBestaetigt": { de: "gibt dem Provider recht", en: "rules in the provider's favor" },
  "agent.urteilGeteilt": { de: "schlägt vor, den Betrag zu teilen", en: "suggests splitting the amount" },
  "agent.urteilUnentschieden": { de: "kann es nicht beurteilen", en: "can't judge it" },
  "agent.wartetAufUrteil": { de: "wartet auf das Urteil von {name}", en: "waiting for the verdict of {name}" },
  "agent.urteilZurueck": { de: " – {sats} sats zurück", en: " – {sats} sats back" },
  "agent.urteilZeile": { de: "{name} {was}{betrag}. Das gilt nur zwischen dir und dem Provider; erstatten muss er selbst.", en: "{name} {was}{betrag}. This applies only between you and the provider; the provider has to refund you." },
  "agent.reklamationZeile": { de: "Auftrag {auftrag}… · {sats} sats: {text}", en: "Job {auftrag}… · {sats} sats: {text}" },
  "agent.einUrteilDa": { de: "Ein Urteil zu deiner Reklamation ist da (Agent → Aufgaben)", en: "A verdict on your complaint has arrived (Agent → Tasks)" },
  "agent.urteileDa": { de: "{n} Urteile zu deinen Reklamationen sind da", en: "{n} verdicts on your complaints have arrived" },
  "agent.knopfKunde": { de: "Kunde hat recht", en: "Customer is right" },
  "agent.knopfProvider": { de: "Provider hat recht", en: "Provider is right" },
  "agent.knopfTeilen": { de: "teilen", en: "split" },
  "agent.knopfUnklar": { de: "kann ich nicht beurteilen", en: "can't judge" },
  "agent.auftragZeile": { de: "Reklamation gegen Provider {provider} · {grund} · {sats} sats", en: "Complaint against provider {provider} · {grund} · {sats} sats" },
  "agent.auftragNotiz": { de: "Notiz: {notiz}", en: "Note: {notiz}" },
  "agent.frageUndAntwort": { de: "Frage und Antwort", en: "Question and answer" },
  "agent.auftragFrage": { de: "Frage: {text}", en: "Question: {text}" },
  "agent.auftragAntwort": { de: "Antwort: {text}", en: "Answer: {text}" },
  "agent.ohneMaterial": { de: "Frage und Antwort hat der Kunde nicht mitgeschickt.", en: "The customer didn't include question and answer." },
  "agent.begruendungFrage": { de: "Kurze Begründung (nur für Kunde und Provider)", en: "Short reasoning (only for customer and provider)" },
  "agent.urteilTitel": { de: "Urteil", en: "Verdict" },
  "agent.urteilSenden": { de: "Urteil senden", en: "Send verdict" },
  "agent.urteilGesendet": { de: "Urteil versiegelt an Kunde und Provider geschickt – es gilt nur zwischen ihnen", en: "Verdict sent sealed to customer and provider – it applies only between them" },
  "agent.modellGewaehlt": { de: "Modell: {modell}", en: "Model: {modell}" },
  "agent.modellAuto": { de: "Modell: automatisch", en: "Model: automatic" },
};
