/** Texte des Agent-Tabs (8.16d1: Seite und tabs/agent.ts). */
import type { Texte } from "../i18n.js";

export const agent: Texte = {
  emptySub: { de: "Stell eine Frage. Du zahlst pro Anfrage.", en: "Ask a question. You pay per request." },
  emptyHint: { de: "Modell wählen · Werkzeuge anhängen", en: "Choose a model · attach tools" },
  aiPlaceholder: { de: "Nachricht an den Agenten", en: "Message the agent" },
  send: { de: "Senden", en: "Send" },
  // Stand eines Auftrags (setTypingStatus/showTyping)
  thinking: { de: "denkt nach…", en: "thinking…" },
  connecting: { de: "verbindet…", en: "connecting…" },
  researching: { de: "recherchiert…", en: "researching…" },
  creating: { de: "erstellt…", en: "creating…" },
  copyLast: { de: "Letzte kopieren", en: "Copy last" },
  copyAll: { de: "Alle kopieren", en: "Copy all" },
  bid: { de: "Gebot (sats)", en: "Bid (sats)" },
  tierFree: { de: "Free — kleines Modell", en: "Free — small model" },
  tierClassic: { de: "Classic — ausgewogen", en: "Classic — balanced" },
  tierPro: { de: "Pro — vertrauenswürdige Anbieter", en: "Pro — trusted providers" },
  tierMax: { de: "Max — schnellster gewinnt", en: "Max — fastest wins" },
  tierSwarm: { de: "Swarm — bestes aus mehreren", en: "Swarm — best of several" },
  // Seite (index.html)
  "agent.neueAufgabe": { de: "Neue Aufgabe", en: "New task" },
  "agent.tabAufgaben": { de: "Aufgaben", en: "Tasks" },
  "agent.tabModelle": { de: "Modelle", en: "Models" },
  "agent.tabRepos": { de: "Repos", en: "Repos" },
  "agent.pruefauftraege": { de: "Prüfaufträge", en: "Review requests" },
  "agent.pruefauftraegeText": { de: "Jemand aus deinem Netz hat dich als Prüfer einer Reklamation genannt. Dein Urteil geht versiegelt nur an den Kunden und den Provider und gilt nur zwischen ihnen – eine Erstattung zahlt der Provider selbst.", en: "Someone in your network named you as the reviewer of a complaint. Your verdict goes sealed only to the customer and the provider and applies only between them – any refund is paid by the provider." },
  "agent.reklamationen": { de: "Deine Reklamationen", en: "Your complaints" },
  "agent.reklamationenText": { de: "Den Prüfer hast du aus deinem Netz gewählt. Sein Urteil gilt nur zwischen dir und dem Provider – erstatten muss der Provider selbst.", en: "You chose the reviewer from your network. Their verdict applies only between you and the provider – the provider has to refund you." },
  "agent.nachUrteilen": { de: "nach Urteilen sehen", en: "check for verdicts" },
  "agent.modelleImNetz": { de: "Modelle im Netz", en: "Models in the network" },
  "agent.modelleText": { de: "Was im Netz vorgehalten wird. Modelle mit nur einem Seeder sind gefährdet.", en: "What the network keeps available. Models with only one seeder are at risk." },
  "agent.lade": { de: "lade …", en: "loading …" },
  "agent.aktualisieren": { de: "aktualisieren", en: "refresh" },
  "agent.modellVorhalten": { de: "Modell vorhalten", en: "Seed a model" },
  "agent.modellAnkuendigen": { de: "Modell ankündigen", en: "Announce a model" },
  "agent.kataloge": { de: "Modellkataloge", en: "Model catalogs" },
  "agent.katalogeText": { de: "Ein Katalog ist die Liste eines Kurators (NIP-51): welche Modelle er empfiehlt. Voreingestellt ist keiner – du abonnierst, wem du folgst, auch mehrere, und vergleichst sie mit dem, was Provider gerade anbieten. Ein Katalog sagt nur, wer ein Modell empfiehlt, nicht, ob es gut ist. Die App lädt alle Kataloge und wählt selbst aus; die Relays erfahren nicht, welche du abonniert hast.", en: "A catalog is a curator's list (NIP-51): which models they recommend. None is preset – you subscribe to whom you follow, even several, and compare them with what providers currently offer. A catalog only says who recommends a model, not whether it is good. The app loads all catalogs and selects locally; the relays don't learn which ones you subscribed to." },
  "agent.katalogVeroeffentlichen": { de: "eigenen Katalog veröffentlichen", en: "publish your own catalog" },
  "agent.repositories": { de: "Repositories", en: "Repositories" },
  "agent.reposText": { de: "Git-Bundles liegen im Speichernetz; Zusammenarbeit (Patches, Annahme) läuft nach NIP-34.", en: "Git bundles live in the storage network; collaboration (patches, acceptance) follows NIP-34." },
  "agent.repoNamePh": { de: "Repo-Name", en: "repo name" },
  "agent.bundlePublizieren": { de: "⇪ Bundle publizieren", en: "⇪ Publish bundle" },
  "agent.zusammenarbeit": { de: "Zusammenarbeit (NIP-34)", en: "Collaboration (NIP-34)" },
  "agent.nip34Text1": { de: "Ankündigungen, Patches und Annahmen sind öffentlich und mit deinem Schlüssel signiert – wie bei jedem Git-Projekt. Andere Nostr-Clients (ngit, gitworkshop) lesen sie auch. Einen Patch erzeugst du mit", en: "Announcements, patches and acceptances are public and signed with your key – like in any Git project. Other Nostr clients (ngit, gitworkshop) read them too. You create a patch with" },
  "agent.nip34Text2": { de: "; angenommen ist er, wenn Eigentümer oder Maintainer es sagen.", en: "; it is accepted when the owner or a maintainer says so." },
  "agent.repoKennungPh": { de: "Repo-Kennung", en: "repo identifier" },
  "agent.klonPh": { de: "Klon-Adressen (https://…, rad:…), mit Komma", en: "Clone addresses (https://…, rad:…), comma-separated" },
  "agent.repoAnkuendigen": { de: "Repo ankündigen", en: "Announce repo" },
  "agent.quotaTitel": { de: "Gratis-Kontingent heute", en: "Free quota today" },
  "agent.quota": { de: "Gratis-Kontingent", en: "Free quota" },
  "agent.beispiel1": { de: "„Erkläre mir das Nostr-Protokoll…“", en: "“Explain the Nostr protocol…”" },
  "agent.beispiel1Prompt": { de: "Erkläre mir das Nostr-Protokoll in einem Satz.", en: "Explain the Nostr protocol in one sentence." },
  "agent.beispiel2": { de: "„Vorteile von Lightning…“", en: "“Benefits of Lightning…”" },
  "agent.beispiel2Prompt": { de: "Schreibe eine kurze Zusammenfassung der wichtigsten Vorteile von Lightning.", en: "Write a short summary of the main benefits of Lightning." },
  "agent.beispiel3": { de: "„Bild: Leuchtturm bei Nacht…“", en: "“Image: lighthouse at night…”" },
  "agent.beispiel3Prompt": { de: "Erstelle ein Bild: ein Leuchtturm bei Nacht.", en: "Create an image: a lighthouse at night." },
  "agent.anhangBild": { de: "Bild", en: "image" },
  "agent.anhangDatei": { de: "Datei", en: "file" },
  "agent.anhangAudio": { de: "Audio", en: "audio" },
  "agent.anhangVideo": { de: "Video", en: "video" },
  "agent.anhangKamera": { de: "Kamera", en: "camera" },
  "agent.werkzeugWeb": { de: "Web", en: "web" },
  "agent.werkzeugBrowser": { de: "Browser", en: "browser" },
  "agent.werkzeugBild": { de: "Bild", en: "image" },
  "agent.werkzeugVideo": { de: "Video", en: "video" },
  "agent.laenge": { de: "Länge", en: "Length" },
  "agent.qualitaet": { de: "Qualität", en: "Quality" },
  "agent.kopierenLetzte": { de: "Letzte Antwort kopieren", en: "Copy last answer" },
  "agent.kopierenAlle": { de: "Ganze Unterhaltung kopieren", en: "Copy whole conversation" },
  "agent.modellWaehlen": { de: "Modell wählen", en: "Choose model" },
  "agent.autoSchnellste": { de: "auto (schnellste)", en: "auto (fastest)" },
  "agent.arbeitsbereich": { de: "Arbeitsbereich", en: "Workspace" },
  "agent.keinRepo": { de: "Kein Repository verbunden.", en: "No repository connected." },
  "agent.werkzeuge": { de: "Werkzeuge", en: "Tools" },
  "agent.nochKeineWerkzeuge": { de: "Noch keine in dieser Sitzung.", en: "None in this session yet." },
  "agent.kosten": { de: "Kosten", en: "Costs" },
  // Modellwahl
  "agent.schnell": { de: "⚡⚡ schnell", en: "⚡⚡ fast" },
  "agent.mittel": { de: "⚡ mittel", en: "⚡ medium" },
  "agent.tief": { de: "🐢 tiefgründig", en: "🐢 thorough" },
  "agent.auto": { de: "Auto", en: "Auto" },
  "agent.schnellste": { de: "schnellste", en: "fastest" },
  "agent.autoSub": { de: "Netz wählt das beste verfügbare Modell", en: "the network picks the best available model" },
  "agent.mcSub": { de: "~{preis} /1k Tokens · {n} Provider", en: "~{preis} /1k tokens · {n} provider(s)" },
  "agent.inKatalog": { de: "in {n} Katalog", en: "in {n} catalog" },
  "agent.inKatalogen": { de: "in {n} Katalogen", en: "in {n} catalogs" },
  // Verlauf, Seitenleiste
  "agent.aufgabe": { de: "Aufgabe", en: "Task" },
  "agent.keineAufgaben": { de: "Noch keine Aufgaben.", en: "No tasks yet." },
  "agent.heute": { de: "Heute", en: "Today" },
  "agent.frueher": { de: "Früher", en: "Earlier" },
  "agent.nachrichten": { de: "{n} Nachrichten", en: "{n} messages" },
  "agent.dieseSitzung": { de: "Diese Sitzung", en: "This session" },
  "agent.gebuehrVorschau": { de: "{betrag} → Provider mind. {provider} / Anteile höchstens {anteile}", en: "{betrag} → provider at least {provider} / shares at most {anteile}" },
  "agent.schaetzung": { de: "~{tokens} Tokens ≈ {preis}", en: "~{tokens} tokens ≈ {preis}" },
  // Fehler
  "agent.fehlerRelay": { de: "Relay-Verbindung fehlgeschlagen — Internet prüfen oder später erneut versuchen", en: "Relay connection failed — check your internet or try again later" },
  "agent.fehlerKeinProvider": { de: "Kein Provider erreichbar — alle Kandidaten haben nicht rechtzeitig geantwortet", en: "No provider reachable — no candidate answered in time" },
  "agent.fehlerGebot": { de: "Gebot zu niedrig und kein Gratis-Kontingent mehr — Gebot erhöhen oder morgen wieder gratis testen", en: "Bid too low and no free quota left — raise the bid or try for free again tomorrow" },
  "agent.fehlerIdentitaet": { de: "Identität fehlt — bitte neu anmelden", en: "Identity missing — please sign in again" },
  "agent.fehlerTimeout": { de: "Zeitüberschreitung — Provider zu langsam oder offline", en: "Timeout — provider too slow or offline" },
  "agent.fehlerComfy": { de: "ComfyUI nicht erreichbar (Port 8188) — Bild und Video brauchen ein laufendes ComfyUI", en: "ComfyUI not reachable (port 8188) — images and video need a running ComfyUI" },
  "agent.fehlerNetz": { de: "Netzwerkfehler — Verbindung zum Relay oder Server unterbrochen", en: "Network error — connection to the relay or server interrupted" },
  "agent.fehler": { de: "⚠️ Fehler", en: "⚠️ Error" },
  "agent.ursache": { de: "Ursache:", en: "Cause:" },
  "agent.erneut": { de: "↻ erneut versuchen", en: "↻ try again" },
  "agent.stop": { de: "■ Stopp", en: "■ Stop" },
  "agent.kontingentAufgebraucht": { de: "Gratis-Kontingent aufgebraucht — erst Guthaben einzahlen", en: "Free quota used up — deposit funds first" },
  "agent.providerLehntAb": { de: "Provider lehnt ab ({grund}) — nächster…", en: "Provider declines ({grund}) — next…" },
  "agent.providerLangsam": { de: "Provider {pk} langsam — der nächste bekommt den Auftrag zusätzlich…", en: "Provider {pk} slow — the next one gets the job as well…" },
  "agent.keinProviderAntwort": { de: "Kein Provider im Netz hat geantwortet", en: "No provider in the network answered" },
  "agent.abgebrochen": { de: "[abgebrochen]", en: "[cancelled]" },
  "agent.keinPrivaterProvider": { de: "Kein Provider für private Anfragen gefunden – die Knoten brauchen mindestens Stand 3.1.", en: "No provider for private requests found – nodes need at least version 3.1." },
  // Video (ComfyUI)
  "agent.videoWird": { de: "[Video] wird erstellt ({breite}×{hoehe}, ~{dauer} s) — das dauert ~1–2 min", en: "[video] being generated ({breite}×{hoehe}, ~{dauer} s) — this takes ~1–2 min" },
  "agent.videoFertig": { de: "✅ Video fertig:", en: "✅ Video ready:" },
  "agent.videoFehler": { de: "(Video-Fehler: {grund})", en: "(video error: {grund})" },
  "agent.unbekannt": { de: "unbekannt", en: "unknown" },
  "agent.videoTimeout": { de: "(Video-Zeitüberschreitung — versuch es kürzer oder später)", en: "(video timeout — try shorter or later)" },
  // Max und Swarm
  "agent.maxKeinProvider": { de: "Kein Provider in der Stufe „Max“ erreichbar", en: "No provider in the “Max” tier reachable" },
  "agent.maxStart": { de: "Max: {n} Provider treten an — bezahlt wird die schnellste Antwort", en: "Max: {n} providers race — only the fastest answer is paid" },
  "agent.maxGewinner": { de: "{pk} ist am schnellsten", en: "{pk} is fastest" },
  "agent.maxKeiner": { de: "Max: kein Provider hat geantwortet", en: "Max: no provider answered" },
  "agent.swarmKeinProvider": { de: "Kein Provider für Swarm — der FreedomStack-Knoten läuft nicht", en: "No provider for swarm — the FreedomStack node isn't running" },
  "agent.swarmStart": { de: "Swarm: beide Modelle (nemotron + qwen3.8:27b) denken parallel…", en: "Swarm: both models (nemotron + qwen3.8:27b) think in parallel…" },
  "agent.swarmTimeout": { de: "Swarm: der Provider antwortet nicht — Zeitüberschreitung", en: "Swarm: the provider doesn't answer — timeout" },
  "agent.modellGewechselt": { de: "⇄ Modell gewechselt zu", en: "⇄ switched model to" },
  "agent.kontextMit": { de: "der Kontext wird mitgegeben ({n} Nachrichten)", en: "the context is passed along ({n} messages)" },
  // Antwort, Zahlung
  "agent.providerKurz": { de: "Provider {pk}…", en: "provider {pk}…" },
  "agent.lebenszeichen": { de: "Lebenszeichen gesendet — laufende Vorgänge sind abgebrochen", en: "Heartbeat sent — pending processes are cancelled" },
  "agent.providerVerlangte": { de: "Provider verlangte {sats} sats – mehr als dein Gebot; die App zahlt höchstens das Gebot", en: "Provider asked for {sats} sats – more than your bid; the app pays at most the bid" },
  "agent.bezahlt": { de: "bezahlt: {sats} sats an den Provider", en: "paid: {sats} sats to the provider" },
  "agent.zahlungUnklar": { de: "Zahlung an den Provider unklar – sieh in deiner Wallet nach. In dieser Sitzung zahlt die App nicht noch einmal.", en: "Payment to the provider unclear – check your wallet. The app won't pay again in this session." },
  "agent.belegGesammelt": { de: "Beleg gespeichert – gezahlt wird gesammelt ab {sats} sats", en: "Receipt saved – paid in bulk from {sats} sats" },
  "agent.belegNichtBezahlt": { de: "Beleg gespeichert, nicht bezahlt: {grund}", en: "Receipt saved, not paid: {grund}" },
  "agent.anteilUnklar": { de: "Eine gesammelte Zahlung ist unklar – in den Settings unter Gebühren prüfen.", en: "A bulk payment is unclear – check under fees in the settings." },
  "agent.keineSitzung": { de: "Noch keine Sitzung. Die erste Anfrage startet eine.", en: "No session yet. The first request starts one." },
  "agent.sitzung": { de: "Sitzung: {bezahlt}/{max} sats ({pct} %)", en: "session: {bezahlt}/{max} sats ({pct}%)" },
  // Reklamation
  "agent.keinPruefer": { de: "Kein Prüfer in deinem Netz – die Reklamation geht nur an den Provider. Prüfen kann ein Kontakt oder ein eigener Provider.", en: "No reviewer in your network – the complaint goes only to the provider. A contact or one of your own providers can review." },
  "agent.werPrueft": { de: "Wer aus deinem Netz soll nachprüfen? Er bekommt die Reklamation versiegelt; sein Urteil gilt nur zwischen dir und dem Provider.\n{liste}\n  leer = nur der Provider", en: "Who in your network should review? They get the complaint sealed; their verdict applies only between you and the provider.\n{liste}\n  empty = only the provider" },
  "agent.ohneBezug": { de: "Ohne Bezug zur Antwort nicht reklamierbar", en: "Can't complain without a reference to the answer" },
  "agent.problem": { de: "Was war das Problem?\n  1 = gar keine Antwort\n  2 = Antwort unbrauchbar\n  3 = anderes Modell als vereinbart\n  4 = mittendrin abgebrochen", en: "What was the problem?\n  1 = no answer at all\n  2 = answer unusable\n  3 = different model than agreed\n  4 = cut off midway" },
  "agent.materialMitschicken": { de: "Frage und Antwort an {name} mitschicken? Ohne sie sieht der Prüfer nur Grund und Notiz. Der Provider bekommt sie nicht noch einmal, Relays sehen sie nicht.", en: "Send question and answer to {name}? Without them the reviewer only sees reason and note. The provider doesn't get them again, relays don't see them." },
  "agent.beschreibung": { de: "Kurze Beschreibung (nur für Provider und Prüfer):", en: "Short description (only for provider and reviewer):" },
  "agent.reklamiert": { de: "Reklamiert. {info}", en: "Complaint filed. {info}" },
  "agent.reklamiertMit": { de: "Reklamiert – Provider und {name} benachrichtigt. {info}", en: "Complaint filed – provider and {name} notified. {info}" },
  // Kosten einer Antwort
  "agent.antwort": { de: "Antwort", en: "Answer" },
  "agent.tokensMeta": { de: "{n} Tokens · {sat} sat", en: "{n} tokens · {sat} sat" },
  "agent.modell": { de: "Modell", en: "Model" },
  "agent.provider": { de: "Provider", en: "Provider" },
  "agent.tokens": { de: "Tokens", en: "Tokens" },
  "agent.reinRaus": { de: "{rein} rein, {raus} raus", en: "{rein} in, {raus} out" },
  "agent.dieseAntwort": { de: "Diese Antwort", en: "This answer" },
  "agent.sitzungGesamt": { de: "Sitzung gesamt", en: "Session total" },
  "agent.reklamieren": { de: "Reklamieren", en: "Complain" },
  "agent.details": { de: "{pfeil} Details · {sats} sats", en: "{pfeil} details · {sats} sats" },
  "agent.anteilEntwicklung": { de: "Entwicklung", en: "Development" },
  "agent.anteilRelays": { de: "Relay", en: "Relay" },
  "agent.anteilWerberKunde": { de: "Dein Werber", en: "Your referrer" },
  "agent.anteilWerberProvider": { de: "Werber des Providers", en: "Provider's referrer" },
  "agent.anteilHosting": { de: "Hosting", en: "Hosting" },
  "agent.gesammelt": { de: "{betrag} · gesammelt", en: "{betrag} · collected" },
  "agent.anDenProvider": { de: "An den Provider", en: "To the provider" },
  "agent.weitereAnteile": { de: "Weitere Anteile", en: "Other shares" },
  "agent.keinEmpfaenger": { de: "kein Empfänger – beim Provider", en: "no recipient – stays with the provider" },
  // Schritte
  "agent.schrittVerbinden": { de: "Verbinde mit dem Provider-Netz", en: "Connecting to the provider network" },
  "agent.schrittRecherche": { de: "Recherchiert online (web_search / browser)", en: "Researching online (web_search / browser)" },
  "agent.schrittModell": { de: "Modell verarbeitet die Anfrage", en: "Model processes the request" },
  "agent.schrittMedien": { de: "Erstellt Medien (Bild/Video)", en: "Creating media (image/video)" },
  "agent.suchtWeb": { de: "sucht im Web…", en: "searching the web…" },
  "agent.liestSeiten": { de: "liest Webseiten…", en: "reading web pages…" },
  "agent.erstelltBild": { de: "erstellt Bild…", en: "creating image…" },
  "agent.erstelltVideo": { de: "erstellt Video…", en: "creating video…" },
  "agent.angehaengt": { de: "{name} angehängt", en: "{name} attached" },
};
