/** Texte der übrigen Bausteine (8.16g2a): lokale Werkzeuge, Mesh, MLS, private Räume, Hinweise im Datenschutzbericht. */
import type { Texte } from "../i18n.js";

export const bausteine: Texte = {
  // Lokale Werkzeuge (local-tools.ts)
  "bau.urlUngueltig": { de: "keine gültige URL", en: "not a valid URL" },
  "bau.nurHttp": { de: "nur http und https", en: "only http and https" },
  "bau.keineZugangsdaten": { de: "keine Zugangsdaten in der URL", en: "no credentials in the URL" },
  "bau.lokalesZiel": { de: "lokales Ziel", en: "local target" },
  "bau.privateAdresse": { de: "private Adresse", en: "private address" },
  "bau.keineAntwort": { de: "keine Instant-Answer gefunden — versuche eine spezifischere Frage", en: "no instant answer found — try a more specific question" },
  "bau.sucheFehler": { de: "web_search-Fehler: {fehler}", en: "web_search error: {fehler}" },
  "bau.abrufAbgelehnt": { de: "Abruf abgelehnt: {grund}", en: "Fetch refused: {grund}" },
  "bau.keinText": { de: "kein Text ({typ})", en: "not text ({typ})" },
  "bau.browserFehler": { de: "Browser-Fehler (ggf. CORS): {fehler}", en: "browser error (possibly CORS): {fehler}" },
  "bau.lokalNicht": { de: "{name} lokal nicht verfügbar", en: "{name} not available locally" },
  "bau.ollamaHttp": { de: "Ollama HTTP {status}", en: "Ollama HTTP {status}" },
  // Mesh (mesh-radio.ts, mesh-transfer.ts)
  "bau.wegSeriell": { de: "USB-Gerät anschließen und verbinden — der zuverlässigste Weg.", en: "Plug in the USB device and connect — the most reliable way." },
  "bau.wegBluetooth": { de: "Funkgerät per Bluetooth koppeln.", en: "Pair the radio via Bluetooth." },
  "bau.wegDatei": { de: "Dieser Browser kann keine Geräte ansprechen (auf iOS die Regel). Nachrichten lassen sich als Datei exportieren und per Stick, Kamera oder anderem Weg übergeben.", en: "This browser cannot talk to devices (the rule on iOS). Messages can be exported as a file and handed over by stick, camera or another way." },
  "bau.keinSeriell": { de: "Dieser Browser unterstützt keine serielle Verbindung.", en: "This browser does not support serial connections." },
  "bau.usbFunk": { de: "USB-Funkgerät", en: "USB radio" },
  "bau.rahmenZuGross": { de: "Rahmen zu groß für Funk: {n} > {max} Byte", en: "Frame too large for radio: {n} > {max} bytes" },
  "bau.keinBluetooth": { de: "Dieser Browser kann kein Bluetooth. Auf iOS ist das die Regel — nimm den Datei-Weg.", en: "This browser cannot do Bluetooth. On iOS that is the rule — use the file route." },
  "bau.bluetoothGeraet": { de: "Bluetooth-Gerät", en: "Bluetooth device" },
  "bau.dateiQr": { de: "Datei / QR", en: "File / QR" },
  "bau.bestand": { de: "Bestand", en: "Inventory" },
  "bau.abgleich": { de: "Abgleich {kind}", en: "Sync {kind}" },
  "bau.nichtGesendet": { de: "nicht gesendet: {fehler}", en: "not sent: {fehler}" },
  "bau.empfangen": { de: "empfangen: {n} Pakete, {bytes} Byte", en: "received: {n} packets, {bytes} bytes" },
  "bau.weitergabe": { de: "Weitergabe", en: "Relay" },
  "bau.sendefehler": { de: "Sendefehler: {fehler}", en: "Send error: {fehler}" },
  "bau.keinJson": { de: "keine gültige JSON-Datei", en: "not a valid JSON file" },
  "bau.keinBundle": { de: "kein freedom-mesh-Bündel", en: "not a freedom-mesh bundle" },
  // MLS (mls-engine.ts, mls-keypackage.ts, mls-speicher.ts, shell/mls-konto.ts)
  "bau.mlsEntpacken": { de: "Dieser Browser kann die MLS-Engine nicht entpacken (DecompressionStream fehlt).", en: "This browser cannot unpack the MLS engine (DecompressionStream missing)." },
  "bau.mlsWasm": { de: "Dieser Browser kann kein WebAssembly – MLS nicht verfügbar.", en: "This browser cannot run WebAssembly – MLS not available." },
  "bau.mlsStartet": { de: "MLS-Engine startet nicht ({name}).", en: "MLS engine does not start ({name})." },
  "bau.mlsStartetHierNicht": { de: "Die MLS-Engine startet in diesem Browser nicht.", en: "The MLS engine does not start in this browser." },
  "bau.mlsBeitritt": { de: "Beitritt scheiterte.", en: "Joining failed." },
  "bau.mlsUnverschluesselt": { de: "Nachricht nicht verschlüsselt.", en: "Message not encrypted." },
  "bau.mlsNichtAngekommen": { de: "Nachricht kam nicht an.", en: "Message did not arrive." },
  "bau.mlsOk": { de: "Gruppe angelegt, eingeladen, Nachricht verschlüsselt und gelesen.", en: "Group created, invited, message encrypted and read." },
  "bau.mlsAblauf": { de: "Der Ablauf scheiterte.", en: "The sequence failed." },
  "bau.keyPackageRelay": { de: "KeyPackage: kein Relay nahm es an", en: "KeyPackage: no relay accepted it" },
  "bau.mlsSchluessel": { de: "MLS-Schlüssel beschädigt", en: "MLS key damaged" },
  "bau.mlsZustand": { de: "MLS-Zustand beschädigt oder mit anderem Schlüssel verschlüsselt", en: "MLS state damaged or encrypted with a different key" },
  "bau.mlsVerlauf": { de: "MLS-Verlauf beschädigt", en: "MLS history damaged" },
  "bau.mlsKeineIdentitaet": { de: "keine Identität", en: "no identity" },
  "bau.mlsBunker": { de: "mit Bunker (NIP-46) nicht möglich – der Kontobeweis braucht den Schlüssel auf diesem Gerät", en: "not possible with a bunker (NIP-46) – the account proof needs the key on this device" },
  "bau.mlsTresor": { de: "nur mit Tresor – richte ihn in den Settings unter Sicherheit ein", en: "only with a vault – set it up in Settings under Security" },
  // Private Räume (shell/raum-mls.ts)
  "bau.raeumeGesperrt": { de: "Private Räume: {grund}", en: "Private rooms: {grund}" },
  "bau.raeumeNichtAngelegt": { de: "Private Räume: keine eigenen Relays oder Gruppe nicht angelegt", en: "Private rooms: no own relays or group not created" },
  "bau.kanaeleNichtGesendet": { de: "Raum angelegt, aber Kanäle nicht gesendet – kein Relay nahm an", en: "Room created, but channels not sent – no relay accepted" },
  "bau.einladungKeinAdmin": { de: "kein Admin", en: "not an admin" },
  "bau.einladungKeinKeyPackage": { de: "kein KeyPackage", en: "no KeyPackage" },
  "bau.einladungNichtZugestellt": { de: "nicht zugestellt", en: "not delivered" },
  "bau.einladungOhneRaumstand": { de: "eingeladen – Raumstand nicht gesendet", en: "invited – room state not sent" },
  // Datenschutzbericht (shell/datenschutz.ts)
  "bau.pruefeOnion": { de: "Prüfe, ob dieser Browser ein .onion-Relay erreicht (höchstens 10 Sekunden) …", en: "Checking whether this browser reaches a .onion relay (at most 10 seconds) …" },
  "bau.mixnetzHinweis": { de: "Mixnetz: Ob du eines nutzt, kann die App nicht prüfen. Deine IP-Adresse ist nur verborgen, wenn du die App selbst hinter einem Mixnetz öffnest – der Bericht rechnet deshalb mit der direkten Verbindung.", en: "Mixnet: the app cannot check whether you use one. Your IP address is only hidden if you open the app itself behind a mixnet – so the report assumes the direct connection." },
  "bau.torTipp": { de: "Tipp: Dein Browser läuft über Tor. Mit „.onion-Relays bevorzugen“ gehen Verbindungen zuerst an Onion-Dienste – ohne Tor-Ausgang dazwischen.", en: "Tip: your browser runs over Tor. With “prefer .onion relays” connections go to onion services first – without a Tor exit in between." },
  "bau.berichtFehler": { de: "Bericht nicht erstellbar: {fehler}", en: "Report cannot be created: {fehler}" },
  "bau.verbunden": { de: "verbunden: {name}", en: "connected: {name}" },
  "bau.verworfen": { de: "verworfen: {grund}", en: "discarded: {grund}" },
};
