/** Texte des Earn-Tabs (8.16; vollständig ab 8.16d). */
import type { Texte } from "../i18n.js";

export const earn: Texte = {
  copy: { de: "Kopieren", en: "Copy" },
  referral: { de: "Werben", en: "Referrals" },
  hostReward: { de: "App verbreiten", en: "Distribute the app" },
  hostSub: {
    de: "Leg freedom.html auf einen eigenen Server, IPFS oder Tor – mehr Kopien sind schwerer zu sperren. Legst du freedom-spiegel.json mit deinen Adressen daneben, bekommst du 1 % jeder KI-Zahlung, die über deine Kopie läuft.",
    en: "Put freedom.html on your own server, IPFS or Tor – more copies are harder to block. Put freedom-spiegel.json with your addresses next to it and you get 1% of every AI payment made through your copy.",
  },
  // Seite (8.16f)
  "earn.untertitel": { de: "Rechenzeit, Speicher und Relays gegen Sats.", en: "Compute, storage and relays for sats." },
  "earn.tabHosten": { de: "Hosten", en: "Host" },
  "earn.tabKarte": { de: "Karte", en: "Map" },
  "earn.einnahmen": { de: "Einnahmen", en: "Earnings" },
  "earn.werbenText": { de: "Du bekommst 0,5 % jeder KI-Zahlung deiner Geworbenen – die App des Geworbenen zahlt es dir direkt, eine Ebene, keine Stufen. Dafür trägt dein Werbelink deine Lightning-Adresse aus dem Profil; ohne sie – oder bei Geworbenen über einen älteren Link ohne Adresse – bleibt der Anteil beim Provider. Wer über deinen Link kommt, entscheidet bei der Einrichtung selbst, ob er dich öffentlich als Werber nennt; ohne seine Zustimmung zählt er nicht. Das gilt für die Zählung unten – deinen Anteil zahlt seine App auch ohne Nennung. Was ankommt, siehst du in deiner Lightning-Wallet; die App erfährt es nicht.", en: "You get 0.5% of every AI payment by the people you referred – their app pays you directly, one level, no tiers. For this your referral link carries the Lightning address from your profile; without it – or for people who came via an older link without an address – the share stays with the provider. Whoever comes via your link decides during setup whether to name you publicly as their referrer; without their consent they don't count. That applies to the count below – their app pays your share even without being named. What arrives you see in your Lightning wallet; the app doesn't learn it." },
  "earn.werbenNichts": { de: "Für das Anwerben allein gibt es nichts.", en: "Referring alone earns nothing." },
  "earn.mitwirkende": { de: "Mitwirkende", en: "Contributors" },
  "earn.mitwirkendeText": { de: "Wer mitarbeitet und ob das Projekt an einer Person hängt. Gezählt werden aktive Tage.", en: "Who contributes and whether the project depends on one person. Active days are counted." },
  "earn.lade": { de: "lade …", en: "loading …" },
  "earn.abdeckung": { de: "Abdeckung", en: "Coverage" },
  "earn.abdeckungText": { de: "Wo es Provider und Funk gibt. Funkknoten erscheinen erst ab drei pro Gebiet, damit sich niemand verorten lässt. Ein Eintrag trägt einen Wegwerfschlüssel, nicht deine Identität, und läuft nach 7 Tagen ab. Auf den Relays ist jeder Eintrag einzeln sichtbar – die Schwelle gilt nur für die Anzeige hier.", en: "Where there are providers and radio. Radio nodes only appear from three per area, so nobody can be located. An entry carries a throwaway key, not your identity, and expires after 7 days. On the relays every entry is visible individually – the threshold only applies to the display here." },
  "earn.aktualisieren": { de: "aktualisieren", en: "refresh" },
  "earn.eintragen": { de: "selbst eintragen", en: "add myself" },
  "earn.austragen": { de: "austragen", en: "remove myself" },
  // tabs/earn.ts
  "earn.aktiveTage": { de: "aktive Tage: {tage} · Beiträge: {n}", en: "active days: {tage} · contributions: {n}" },
  "earn.gebiete": { de: "{n} Gebiet(e)", en: "{n} area(s)" },
  "earn.keineEintraege": { de: "Noch keine Einträge. Eintragen ist freiwillig – es kann trotzdem Abdeckung geben.", en: "No entries yet. Adding yourself is voluntary – there may be coverage anyway." },
  "earn.verborgen": { de: "{n} Gebiet(e) nicht angezeigt: zu wenige Knoten, um niemanden zu verorten.", en: "{n} area(s) not shown: too few nodes to avoid locating anyone." },
  "earn.standortGebraucht": { de: "Für die Anzeige, ob es hier Abdeckung gibt, wird dein Standort gebraucht – nur lokal, nichts wird gesendet.", en: "To show whether there is coverage here, your location is needed – only locally, nothing is sent." },
  "earn.abdeckungFehler": { de: "Abdeckung nicht abrufbar: {fehler}", en: "Coverage not available: {fehler}" },
  "earn.wasEintragen": { de: "Was trägst du ein?", en: "What do you add?" },
  "earn.eingetragen": { de: "Eingetragen – mit Wegwerfschlüssel, 7 Tage gültig, jederzeit widerrufbar", en: "Added – with a throwaway key, valid for 7 days, revocable at any time" },
  "earn.standortFehlt": { de: "Standort nicht verfügbar", en: "Location not available" },
  "earn.keinEintrag": { de: "Kein eigener Eintrag auf diesem Gerät", en: "No entry of yours on this device" },
  "earn.widerrufen": { de: "Widerrufen – Relays, die Löschwünsche beachten, entfernen den Eintrag; spätestens nach 7 Tagen läuft er ab", en: "Revoked – relays that honor deletion requests remove the entry; it expires after 7 days at the latest" },
  "earn.einheiten": { de: "{n} Einheiten", en: "{n} units" },
  "earn.knotenPh": { de: "Dein Knoten: npub oder Hex – leer: deine Identität", en: "Your node: npub or hex – empty: your identity" },
  "earn.knotenUngueltig": { de: "Kein gültiger Schlüssel (npub oder 64 Hex-Zeichen).", en: "Not a valid key (npub or 64 hex characters)." },
  "earn.lightning": { de: "Lightning – wie dein Knoten es meldet", en: "Lightning – as your node reports it" },
  "earn.sol": { de: "SOL – Zahlkanäle, von der Kette gelesen", en: "SOL – payment channels, read from the chain" },
  "earn.solHinweis": { de: "Dein Knoten hat eine SOL-Adresse: Alle Kanäle an ihn und seine Auszahlungen an deine Auszahlungsadresse sind auf der Kette verbunden. Was er angenommen, aber noch nicht eingelöst hat, weiß nur er – er löst vor der Frist ein; was bis dahin nicht eingelöst ist, bekommt der Kunde zurück. Kanäle, die der Kunde nach dem Ablauf geschlossen hat, zählen hier nicht mehr. Die Abfrage nennt dem RPC-Anbieter die Adresse deines Knotens.", en: "Your node has one SOL address: all channels to it and its payouts to your payout address are linked on the chain. What it accepted but has not redeemed yet only the node knows – it redeems before the deadline; whatever is not redeemed by then goes back to the customer. Channels the customer closed after expiry no longer count here. The query tells the RPC provider your node's address." },
  "earn.solKeinKanal": { de: "Dein Knoten nimmt keine Zahlkanäle an – sein Angebot nennt keinen (ZAHLKANAL=1 und NODE_SOL_ADDRESS setzen).", en: "Your node does not accept payment channels – its offer names none (set ZAHLKANAL=1 and NODE_SOL_ADDRESS)." },
  "earn.solAnderesProgramm": { de: "Dein Knoten nennt ein anderes Kanal-Programm als diese App.", en: "Your node names a different channel program than this app." },
  "earn.solProgrammFehlt": { de: "Das Zahlkanal-Programm liegt auf dieser Kette noch nicht.", en: "The payment channel program is not on this chain yet." },
  "earn.solStand": { de: "Adresse {adresse}: dein Teil eingelöst {deins} · {laufend} laufende Kanäle · nächste Frist {frist} · Guthaben der Adresse {guthaben}", en: "Address {adresse}: your part redeemed {deins} · {laufend} running channels · next deadline {frist} · address balance {guthaben}" },
  "earn.kanalLaeuft": { de: "Kanal bis {bis}: eingezahlt {eingezahlt}, dein Teil eingelöst {deins}, noch nicht eingelöst {offen}", en: "Channel until {bis}: deposited {eingezahlt}, your part redeemed {deins}, not redeemed yet {offen}" },
  "earn.kanalVorbei": { de: "Kanal abgelaufen am {bis}: dein Teil {deins} – den Rest holt der Kunde zurück", en: "Channel expired on {bis}: your part {deins} – the customer takes back the rest" },
  "earn.keineEinnahmen": { de: "Noch keine Einnahmen. Sie erscheinen, sobald dein Provider-Knoten Jobs erledigt.", en: "No earnings yet. They appear as soon as your provider node completes jobs." },
  "earn.linkKopiert": { de: "Werbelink kopiert", en: "Referral link copied" },
  "earn.codeMitAdresse": { de: "dein Code: {code} – mit deiner Lightning-Adresse", en: "your code: {code} – with your Lightning address" },
  // Eigene Adresse der App (11.2a)
  "earn.adresseLabel": { de: "Eigene Adresse der App – leer: die, unter der sie gerade läuft", en: "Your own address of the app – empty: the one it is running at now" },
  "earn.adressePh": { de: "https://…", en: "https://…" },
  "earn.adresseSetzen": { de: "Übernehmen", en: "Apply" },
  "earn.adressePruefen": { de: "Prüfen", en: "Check" },
  "earn.adresseText": { de: "Liegt dort deine Kopie von freedom.html, laden Geworbene die App von dort. Legst du freedom-spiegel.json mit deinen Adressen daneben, bekommst du zusätzlich 1 % jeder KI-Zahlung über diese Kopie. „Prüfen“ fragt die Adresse ab – der Server sieht dabei deine IP.", en: "If your copy of freedom.html is there, referred people load the app from there. Put freedom-spiegel.json with your addresses next to it and you also get 1 % of every AI payment through this copy. “Check” queries the address – the server sees your IP." },
  "earn.adresseLeer": { de: "Bitte eine Adresse eingeben.", en: "Please enter an address." },
  "earn.adresseUngueltig": { de: "Keine gültige Adresse – vollständig mit https:// eingeben.", en: "Not a valid address – enter it in full with https://." },
  "earn.adresseKeinHttps": { de: "Nur https: Über http könnte unterwegs jeder die App austauschen.", en: "https only: over http anyone on the way could swap the app." },
  "earn.adresseZugang": { de: "Ohne Benutzername und Passwort in der Adresse.", en: "No user name or password in the address." },
  "earn.adresseLokal": { de: "Eine lokale Adresse erreichen Geworbene nicht.", en: "Referred people can't reach a local address." },
  "earn.adresseGesetzt": { de: "Übernommen – der Werbelink trägt jetzt diese Adresse.", en: "Applied – the referral link now carries this address." },
  "earn.adresseZurueck": { de: "Der Werbelink trägt wieder die Adresse, unter der die App gerade läuft.", en: "The referral link carries the address the app is running at again." },
  "earn.adresseErst": { de: "Erst eine eigene Adresse übernehmen.", en: "Apply your own address first." },
  "earn.adressePruefe": { de: "Prüfe …", en: "Checking …" },
  "earn.kopieDort": { de: "Dort: {text}", en: "There: {text}" },
  "earn.kopieNichtErreichbar": { de: "Nicht geprüft: Die Adresse antwortet nicht oder erlaubt keine Abfrage aus dem Browser (CORS).", en: "Not checked: the address doesn't answer or doesn't allow queries from the browser (CORS)." },
  "earn.kopieZuGross": { de: "Nicht geprüft: Die Datei dort ist zu groß für freedom.html.", en: "Not checked: the file there is too large for freedom.html." },
  "earn.hostingDort": { de: "Hosting-Anteil laut freedom-spiegel.json an: {ziel}", en: "Hosting share per freedom-spiegel.json goes to: {ziel}" },
  "earn.hostingFehlt": { de: "Keine gültige freedom-spiegel.json dort – der Hosting-Anteil bleibt beim Provider.", en: "No valid freedom-spiegel.json there – the hosting share stays with the provider." },
  "earn.werbelinkQr": { de: "Werbelink als QR-Code", en: "Referral link as QR code" },
  "earn.codeOhneAdresse": { de: "dein Code: {code} – ohne Lightning-Adresse im Profil kommt dein Anteil nicht an", en: "your code: {code} – without a Lightning address in your profile your share doesn't arrive" },
  "earn.keineNennung": { de: "Noch niemand nennt dich öffentlich als Werber.", en: "Nobody names you publicly as referrer yet." },
  "earn.nennungen": { de: "{n} Geworbene nennen dich öffentlich als Werber.", en: "{n} referred people name you publicly as referrer." },
  "earn.spaeterGezaehlt": { de: "Wird beim nächsten Netzkontakt gezählt.", en: "Counted at the next network contact." },
  // Sätze des Protokolls (protokoll-texte.ts) – Deutsch wortgleich mit dem Protokoll
  "earn.repoUnbekannt": { de: "Keine veröffentlichten Beiträge — das Repo kann trotzdem existieren.", en: "No published contributions — the repo may exist anyway." },
  "earn.repoAktiv": { de: "Zuletzt vor {n} Tag(en) etwas veröffentlicht.", en: "Last published something {n} day(s) ago." },
  "earn.repoRuhig": { de: "Seit {n} Tagen nichts Neues. Kann fertig sein oder eingeschlafen.", en: "Nothing new for {n} days. May be finished or dormant." },
  "earn.repoVerwaist": { de: "Seit über {n} Monaten nichts. Wer hier mitarbeiten will, sollte mit keiner Antwort rechnen.", en: "Nothing for more than {n} months. Whoever wants to contribute here should expect no answer." },
  "earn.busNiemand": { de: "Niemand.", en: "Nobody." },
  "earn.busAllein": { de: "Eine Person allein. Fällt sie aus, steht das Projekt.", en: "One person alone. If they drop out, the project stops." },
  "earn.busEineTraegt": { de: "Eine Person trägt mehr als die Hälfte. {n} weitere helfen mit.", en: "One person carries more than half. {n} others help." },
  "earn.busMehrere": { de: "{n} Personen tragen zusammen die Hälfte der Arbeit.", en: "{n} people together carry half of the work." },
  "earn.ebeneOnline": { de: "Provider im Netz", en: "Providers online" },
  "earn.ebeneLora": { de: "Funk (LoRa)", en: "Radio (LoRa)" },
  "earn.ebeneBluetooth": { de: "Bluetooth", en: "Bluetooth" },
  "earn.stufeViele": { de: "viele", en: "many" },
  "earn.stufeMehrere": { de: "mehrere", en: "several" },
  "earn.stufeWenige": { de: "wenige", en: "few" },
  "earn.teilProvider": { de: "Provider", en: "Providers" },
  "earn.teilFunk": { de: "Funk", en: "radio" },
  "earn.teilBluetooth": { de: "Bluetooth", en: "Bluetooth" },
  "earn.hierNichts": { de: "In deiner Gegend ist noch nichts eingetragen. Das heißt nicht, dass nichts da ist — Eintragen ist freiwillig.", en: "Nothing is registered in your area yet. That doesn't mean nothing is there — adding yourself is voluntary." },
  "earn.hierVorhanden": { de: "{teile} in deiner Gegend vorhanden.", en: "{teile} available in your area." },
  "earn.hierOhneFunk": { de: " Bei einem Netzausfall gibt es hier keine Funkabdeckung — ein Knoten würde die Lücke schließen.", en: " In a network outage there is no radio coverage here — a node would close the gap." },
  "earn.hierOhneProvider": { de: " Kein Provider in der Nähe; Anfragen laufen über weiter entfernte.", en: " No provider nearby; requests go through more distant ones." },
  "earn.einwilligungBluetooth": { de: "Bluetooth reicht nur wenige Meter.\n\nDeshalb wird deine Zelle GRÖBER angezeigt als bei Funk, nicht feiner:\nDie Karte sagt „hier gibt es Leute mit Bluetooth-Geräten“, nicht wo.\n\nErst ab {k} Knoten in derselben Zelle erscheint überhaupt etwas.\n\nIm Zweifel: nicht eintragen. Der Austausch funktioniert auch ohne Karte —\nman muss sich ohnehin begegnen.", en: "Bluetooth only reaches a few meters.\n\nThat is why your cell is shown COARSER than for radio, not finer:\nthe map says “there are people with Bluetooth devices here”, not where.\n\nOnly from {k} nodes in the same cell does anything appear at all.\n\nIf in doubt: don't add yourself. The exchange works without a map too —\nyou have to meet anyway." },
  "earn.einwilligungOnline": { de: "Du wirst mit einer groben Region auf der Karte erscheinen (etwa 200 km).\nDeine Adresse ist als Provider ohnehin sichtbar, sobald sich jemand\nverbindet — die Karte fügt wenig hinzu.\n\nJederzeit widerrufbar.", en: "You will appear on the map with a rough region (about 200 km).\nAs a provider your address is visible anyway as soon as someone\nconnects — the map adds little.\n\nRevocable at any time." },
  "earn.einwilligungFunk": { de: "ÜBERLEG DIR DAS.\n\nEine Karte von Funkknoten ist eine Karte von Menschen, die Funktechnik\nbesitzen und zensurresistente Infrastruktur betreiben. In manchen Ländern\nist das ein Risiko — und dort ist das Netz am wichtigsten.\n\nWas geschützt wird:\n  · Nur eine grobe Zelle (~55 km), nie Koordinaten.\n  · Erst ab {k} Knoten in derselben Zelle wird überhaupt etwas angezeigt.\n  · Kein Verlauf — nur der aktuelle Stand, keine Bewegungsmuster.\n\nWas NICHT geschützt wird:\n  · Wer über längere Zeit mitliest, sieht Veränderungen.\n  · Deine Zelle plus Funkreichweite grenzt das Gebiet weiter ein.\n\nIm Zweifel: nicht eintragen. Das Netz funktioniert auch ohne Karte.", en: "THINK ABOUT THIS.\n\nA map of radio nodes is a map of people who own radio equipment\nand run censorship-resistant infrastructure. In some countries\nthat is a risk — and there the network matters most.\n\nWhat is protected:\n  · Only a rough cell (~55 km), never coordinates.\n  · Only from {k} nodes in the same cell is anything shown at all.\n  · No history — only the current state, no movement patterns.\n\nWhat is NOT protected:\n  · Whoever reads along over a longer time sees changes.\n  · Your cell plus radio range narrows the area further.\n\nIf in doubt: don't add yourself. The network works without a map too." },
  "earn.einwilligungRelays": { de: "Dein Eintrag trägt einen Wegwerfschlüssel, nicht deine Identität, und läuft\nnach {tage} Tagen ab – danach trägst du dich neu ein.\nAber: Auf den Relays ist jeder Eintrag einzeln sichtbar. Die Schwelle von\n{k} Knoten gilt nur für die Anzeige in der App – wer die Relays direkt\nliest, sieht auch eine Zelle mit einem einzigen Eintrag.", en: "Your entry carries a throwaway key, not your identity, and expires\nafter {tage} days – then you add yourself again.\nBut: on the relays every entry is visible individually. The threshold of\n{k} nodes only applies to the display in the app – whoever reads the relays\ndirectly also sees a cell with a single entry." },
};
