/** Texte für Einstieg und Dialoge (8.16g): Führung, Start, Tresor, Identität, Nachfolge, Notfall, Bunker, Einrichtung. */
import type { Texte } from "../i18n.js";

export const einstieg: Texte = {
  // Führung (onboarding.ts)
  "ein.losTitel": { de: "Stell einfach eine Frage", en: "Just ask a question" },
  "ein.losGratis": { de: "Im Gratis-Tarif kostet eine Anfrage kein Geld, solange Provider ihn anbieten — dein Gerät rechnet dafür kurz. Du brauchst nichts einzurichten; danach entscheidest du, ob du eine Wallet verbindest.", en: "In the free tier a request costs nothing as long as providers offer it — your device computes briefly for it. You don't need to set anything up; afterwards you decide whether to connect a wallet." },
  "ein.losProbier": { de: "Probier es aus. Falls gerade kein Provider gratis antwortet, findest du unter „Wallet“ heraus, wie du bezahlst.", en: "Try it. If no provider answers for free right now, you'll find out how to pay under “Wallet”." },
  "ein.losAktion": { de: "Zur KI", en: "To the AI" },
  "ein.sichernTitel": { de: "Sichere deinen Zugang", en: "Secure your access" },
  "ein.sichernText": { de: "Du hast jetzt eine Identität mit Verlauf und Reputation. Wenn du deine Browserdaten löschst, ist beides weg — es gibt niemanden, der das zurücksetzen kann.", en: "You now have an identity with history and reputation. If you delete your browser data, both are gone — there is nobody who can reset that." },
  "ein.sichernWoerter": { de: "Zwölf Wörter aufschreiben genügt.", en: "Writing down twelve words is enough." },
  "ein.sichernDatei": { de: "Speichere die Sicherungsdatei an einem Ort außerhalb dieses Browsers.", en: "Save the backup file somewhere outside this browser." },
  "ein.merkphraseAnzeigen": { de: "Merkphrase anzeigen", en: "Show recovery phrase" },
  "ein.dateiSpeichern": { de: "Sicherungsdatei speichern", en: "Save backup file" },
  "ein.tresorTitel": { de: "Schütze deinen Schlüssel", en: "Protect your key" },
  "ein.tresorText": { de: "Noch liegt dein Schlüssel unverschlüsselt im Browser — jede Erweiterung mit Seitenzugriff kann ihn lesen. Eine Passphrase verschlüsselt ihn auf diesem Gerät; beim Start fragt die App danach.", en: "Your key is still unencrypted in the browser — any extension with page access can read it. A passphrase encrypts it on this device; the app asks for it at start." },
  "ein.tresorAktion": { de: "Tresor einrichten", en: "Set up vault" },
  "ein.vermietenTitel": { de: "Rechner vermieten", en: "Rent out your computer" },
  "ein.vermietenText": { de: "Ein Befehl richtet alles ein: Modell, Dienst, Auszahlungsadresse. Ohne eigene GPU lohnt es sich kaum — mit einer läuft er, während du nichts damit machst.", en: "One command sets everything up: model, service, payout address. Without your own GPU it's hardly worth it — with one it runs while you aren't using it." },
  "ein.anleitung": { de: "Anleitung", en: "Guide" },
  "ein.walletNoetig": { de: "Gerade antwortet kein Provider gratis. Zum Weitermachen brauchst du eine Lightning-Wallet — verbinden dauert eine Minute und funktioniert auf Handy und Rechner gleich.", en: "No provider answers for free right now. To continue you need a Lightning wallet — connecting takes a minute and works the same on phone and computer." },
  "ein.walletSpaeter": { de: "Später: Wallet verbinden", en: "Later: connect a wallet" },
  "ein.walletSpaeterText": { de: "Solange Provider gratis antworten, brauchst du keine Wallet — du kannst sie jetzt verbinden oder warten, bis du sie brauchst.", en: "As long as providers answer for free, you don't need a wallet — you can connect it now or wait until you need it." },
  "ein.fertigTitel": { de: "Alles eingerichtet", en: "All set up" },
  "ein.fertigText": { de: "Identität gesichert, Wallet verbunden. Nichts weiter zu tun.", en: "Identity secured, wallet connected. Nothing else to do." },
  "ein.pitchNutzen": { de: "KI ohne Konto", en: "AI without an account" },
  "ein.pitchNutzen1": { de: "Keine Anmeldung, keine E-Mail, keine Kreditkarte.", en: "No sign-up, no email, no credit card." },
  "ein.pitchNutzen2": { de: "Bezahlt wird pro Anfrage in Sats oder SOL — im Gratis-Tarif gar nicht.", en: "You pay per request in sats or SOL — in the free tier not at all." },
  "ein.pitchNutzen3": { de: "Kein Anbieter, der dich sperren kann: Fällt einer aus, übernimmt ein anderer.", en: "No provider who can block you: if one drops out, another takes over." },
  "ein.pitchVerdienen": { de: "Rechenzeit vermieten", en: "Rent out compute" },
  "ein.pitchVerdienen1": { de: "Deine GPU arbeitet, während du sie nicht brauchst.", en: "Your GPU works while you don't need it." },
  "ein.pitchVerdienen2": { de: "Auszahlung direkt an deine Lightning-Adresse, kein Zwischenkonto.", en: "Payout directly to your Lightning address, no intermediate account." },
  "ein.pitchVerdienen3": { de: "Wo erst wenige Provider arbeiten, hilft ein neuer Knoten am meisten.", en: "Where only a few providers work yet, a new node helps the most." },
  "ein.pitchKommunizieren": { de: "Nachrichten, die weiterlaufen", en: "Messages that keep going" },
  "ein.pitchKommunizieren1": { de: "Verschlüsselt, ohne Telefonnummer.", en: "Encrypted, without a phone number." },
  "ein.pitchKommunizieren2": { de: "Läuft weiter, wenn das Netz ausfällt — über Funk oder per Datei.", en: "Keeps working when the network fails — over radio or as a file." },
  "ein.pitchKommunizieren3": { de: "Deine Kontakte gehören dir, nicht einer Plattform.", en: "Your contacts belong to you, not to a platform." },
  "ein.pitch": { de: "KI, Nachrichten und Zahlungen — ohne Anbieter dazwischen", en: "AI, messages and payments — with no provider in between" },
  "ein.pitch1": { de: "Nichts einzurichten zum Ausprobieren.", en: "Nothing to set up to try it." },
  "ein.pitch2": { de: "Läuft weiter, wenn einzelne Teile ausfallen.", en: "Keeps working when individual parts fail." },
  "ein.pitch3": { de: "Du behältst deine Schlüssel.", en: "You keep your keys." },
  "ein.provAdresse": { de: "Zuerst: Auszahlungsadresse", en: "First: payout address" },
  "ein.provAdresseText": { de: "Ohne Lightning-Adresse gibt es niemanden, an den ausgezahlt werden kann. Eine beliebige Wallet mit Adresse der Form name@anbieter.tld genügt — das ist in fünf Minuten erledigt.", en: "Without a Lightning address there is nobody to pay out to. Any wallet with an address of the form name@provider.tld is enough — done in five minutes." },
  "ein.provOllama": { de: "Inferenz-Software fehlt", en: "Inference software missing" },
  "ein.provOllamaText": { de: "Ollama führt die Modelle aus. Der Installer richtet danach alles Weitere ein — oder du nimmst gleich das Container-Paket, das beides zusammen startet.", en: "Ollama runs the models. The installer then sets up everything else — or you take the container package right away, which starts both together." },
  "ein.provLangsam": { de: "Läuft, aber langsam", en: "Runs, but slowly" },
  "ein.provLangsamText": { de: "Ohne GPU rechnet der Knoten auf dem Prozessor. Das funktioniert, ist aber so langsam, dass sich kaum ein Kunde dafür entscheidet. Ehrlicher Hinweis vorab, statt später Enttäuschung.", en: "Without a GPU the node computes on the processor. That works, but it is so slow that hardly any customer chooses it. An honest note up front instead of disappointment later." },
  "ein.provBereit": { de: "Bereit", en: "Ready" },
  "ein.provBereitText": { de: "Ein Befehl richtet Dienst, Modell und Region ein.", en: "One command sets up service, model and region." },

  // Start, Sicherung und Menü (shell/app.ts)
  "ein.phraseTitel": { de: "Deine Wiederherstellungs-Phrase", en: "Your recovery phrase" },
  "ein.phraseText": { de: "Diese zwölf Wörter sind deine Identität. Wer sie hat, ist du. Wer sie verliert, verliert Reputation, Nachrichten und gesperrte Beträge — es gibt niemanden, der sie zurücksetzen kann.", en: "These twelve words are your identity. Whoever has them is you. Whoever loses them loses reputation, messages and locked amounts — there is nobody who can reset them." },
  "ein.kopieren": { de: "kopieren", en: "copy" },
  "ein.alsDatei": { de: "als Datei sichern", en: "save as file" },
  "ein.zurBestaetigung": { de: "Zur Bestätigung: gib diese Wörter ein.", en: "To confirm: enter these words." },
  "ein.nummer": { de: "Nr. {n}", en: "No. {n}" },
  "ein.bestaetigen": { de: "bestätigen", en: "confirm" },
  "ein.spaeterBestaetigen": { de: "später bestätigen", en: "confirm later" },
  "ein.bisBestaetigt": { de: "Bis du bestätigst, bleiben die Wörter auf diesem Gerät (im Tresor, sobald du einen einrichtest), und die App erinnert dich.", en: "Until you confirm, the words stay on this device (in the vault once you set one up), and the app reminds you." },
  "ein.phraseKopiert": { de: "Phrase kopiert", en: "Phrase copied" },
  "ein.falschesWort": { de: "Falsch: Wort {n}. Nochmal vergleichen.", en: "Wrong: word {n}. Compare again." },
  "ein.identitaetGesichert": { de: "Identität gesichert", en: "Identity secured" },
  "ein.nurImSigner": { de: "Mit Bunker liegt der Schlüssel nicht in der App – sichern und exportieren geht nur im Signer", en: "With a bunker the key is not in the app – backing up and exporting only works in the signer" },
  "ein.fuerSicherungsdatei": { de: "Die Sicherungsdatei", en: "The backup file" },
  "ein.dateiGeladen": { de: "Sicherungsdatei heruntergeladen — sicher aufbewahren", en: "Backup file downloaded — keep it safe" },
  "ein.fuerExport": { de: "Der Export", en: "The export" },
  "ein.nsecKopiert": { de: "nsec (hex) kopiert — sicher aufbewahren!", en: "nsec (hex) copied — keep it safe!" },
  "ein.erstAbmelden": { de: "Erst vom Bunker abmelden (Settings → Geräte)", en: "Sign out of the bunker first (Settings → Devices)" },
  "ein.importFrage": { de: "Merkphrase, nsec1…, 64 Zeichen Hex oder Gerätecode einfügen:", en: "Paste recovery phrase, nsec1…, 64 hex characters or device code:" },
  "ein.nichtGespeichert": { de: "nicht gespeichert: {fehler}", en: "not saved: {fehler}" },
  "ein.alsGeraet": { de: "Als Gerät angemeldet – für {person}", en: "Signed in as a device – for {person}" },
  "ein.importiert": { de: "Identität importiert", en: "Identity imported" },
  "ein.importTitel": { de: "Identität importieren", en: "Import identity" },
  "ein.importOk": { de: "Importieren", en: "Import" },
  "ein.spaeter": { de: "später", en: "later" },
  "ein.eigenerProvider": { de: "Eigener Provider aktiv: {pk}", en: "Own provider active: {pk}" },
  "ein.erstChat": { de: "Wähle erst einen Chat", en: "Choose a chat first" },
  "ein.zapsNur11": { de: "Zaps nur in 1:1-Chats", en: "Zaps only in 1:1 chats" },
  "ein.raeumeNichtMesh": { de: "Räume gehen (noch) nicht als Datei oder über Funk – nur 1:1-Unterhaltungen.", en: "Rooms don't (yet) go as a file or over radio – only 1:1 conversations." },
  "ein.keineUmschlaege": { de: "Keine Umschläge für diesen Kontakt gefunden.", en: "No envelopes found for this contact." },
  "ein.umschlaegeExportiert": { de: "{n} verschlüsselte Umschläge als Datei – ohne deinen Schlüssel. Auf einem Gerät mit Netz einlesen.", en: "{n} encrypted envelopes as a file – without your key. Load them on a device with network." },
  "ein.exportFehler": { de: "Export-Fehler: {fehler}", en: "Export error: {fehler}" },
  "ein.umschlaegeImportiert": { de: "{ok}/{n} Umschläge ans Netz gegeben", en: "{ok}/{n} envelopes handed to the network" },
  "ein.unverschluesseltAbgelehnt": { de: " – {n} unverschlüsselt abgelehnt", en: " – {n} unencrypted rejected" },
  "ein.importFehler": { de: "Import-Fehler: {fehler}", en: "Import error: {fehler}" },
  "ein.pubkeyKopiert": { de: "Öffentlicher Schlüssel kopiert", en: "Public key copied" },
  "ein.pubkey": { de: "Öffentlicher Schlüssel:", en: "Public key:" },
  "ein.lebenszeichenGesendet": { de: "Lebenszeichen gesendet — laufende Vorgänge sind abgebrochen", en: "Sign of life sent — running processes are cancelled" },
  "ein.keineAntwort": { de: "keine Antwort zum Kopieren", en: "no answer to copy" },
  "ein.antwortKopiert": { de: "letzte Antwort kopiert", en: "last answer copied" },
  "ein.keineKonversation": { de: "keine Unterhaltung", en: "no conversation" },
  "ein.konversationKopiert": { de: "Unterhaltung kopiert", en: "Conversation copied" },

  // Identität (identity.ts)
  "ein.erwartetNsec": { de: "Erwartet wurde ein nsec, gefunden: {prefix}", en: "Expected an nsec, found: {prefix}" },
  "ein.nsecLaenge": { de: "nsec hat nicht 32 Bytes", en: "nsec does not have 32 bytes" },
  "ein.erwartetNpub": { de: "Erwartet wurde ein npub, gefunden: {prefix}", en: "Expected an npub, found: {prefix}" },
  "ein.phraseUngueltig": { de: "Die Merkphrase ist ungültig. Prüfe Reihenfolge und Schreibweise — BIP-39 erkennt einzelne Tippfehler an der Prüfsumme.", en: "The recovery phrase is invalid. Check order and spelling — BIP-39 detects single typos by the checksum." },
  "ein.ableitungFehlgeschlagen": { de: "Ableitung fehlgeschlagen", en: "Derivation failed" },
  "ein.nichtsEingegeben": { de: "Nichts eingegeben.", en: "Nothing entered." },
  "ein.istNpub": { de: "Das ist ein öffentlicher Schlüssel (npub) — damit lässt sich nicht signieren. Nötig ist die Merkphrase oder der nsec.", en: "That is a public key (npub) — it cannot sign. You need the recovery phrase or the nsec." },
  "ein.unbekanntesFormat": { de: "Unbekanntes Format. Akzeptiert werden: 12-Wort-Merkphrase, nsec1… oder 64 Zeichen Hex.", en: "Unknown format. Accepted: 12-word recovery phrase, nsec1… or 64 hex characters." },
  "ein.ohnePhrase": { de: "Diese Identität stammt aus einer älteren Version und hat keine Merkphrase. Sichere den nsec — er ist der einzige Weg zurück.", en: "This identity comes from an older version and has no recovery phrase. Back up the nsec — it is the only way back." },
  "ein.nichtBestaetigt": { de: "Die Merkphrase ist noch nicht bestätigt. Ohne Sicherung sind bei Verlust der Browserdaten Reputation und gesperrte Beträge weg.", en: "The recovery phrase is not confirmed yet. Without a backup, reputation and locked amounts are gone if the browser data is lost." },
  "ein.dateiWarnung": { de: "Wer diese Datei hat, ist du: Nachrichten, Reputation, Guthaben. Nicht in eine Cloud legen, nicht per Messenger senden, nicht ausdrucken lassen.", en: "Whoever has this file is you: messages, reputation, balance. Don't put it in a cloud, don't send it via messenger, don't have it printed." },
  "ein.keineSicherungsdatei": { de: "Das ist keine FreedomStack-Sicherungsdatei.", en: "This is not a FreedomStack backup file." },
  "ein.dateiOhneSchluessel": { de: "Die Sicherungsdatei enthält weder Merkphrase noch nsec.", en: "The backup file contains neither recovery phrase nor nsec." },

  // Tresor (shell/tresor.ts, vault.ts)
  "ein.tresorGesperrt": { de: "Tresor gesperrt", en: "Vault locked" },
  "ein.passMin": { de: "Mindestens {n} Zeichen – besser ein kurzer Satz.", en: "At least {n} characters – better a short sentence." },
  "ein.passUngleich": { de: "Die beiden Eingaben stimmen nicht überein.", en: "The two entries don't match." },
  "ein.tresorSchon": { de: "Der Tresor ist schon eingerichtet", en: "The vault is already set up" },
  "ein.tresorErklaerung": { de: "Eine Passphrase verschlüsselt deinen Schlüssel, Wallet-Zugänge, Swap-Geheimnisse und Unterhaltungen auf diesem Gerät. Beim Start fragt die App danach. Vergisst du sie, hilft nur deine Merkphrase (12 Wörter) – sichere sie vorher.", en: "A passphrase encrypts your key, wallet access, swap secrets and conversations on this device. The app asks for it at start. If you forget it, only your recovery phrase (12 words) helps – back it up first." },
  "ein.passNeu": { de: "Passphrase (mind. 8 Zeichen)", en: "Passphrase (at least 8 characters)" },
  "ein.nochEinmal": { de: "noch einmal", en: "once more" },
  "ein.einrichten": { de: "einrichten", en: "set up" },
  "ein.abbrechen": { de: "abbrechen", en: "cancel" },
  "ein.keinSchluessel": { de: "Kein Schlüssel zum Übernehmen gefunden – nichts geändert.", en: "No key found to take over – nothing changed." },
  "ein.richteEin": { de: "richte ein – das dauert einen Moment …", en: "setting up – this takes a moment …" },
  "ein.tresorEingerichtet": { de: "Tresor eingerichtet – deine Geheimnisse liegen jetzt verschlüsselt", en: "Vault set up – your secrets are now encrypted" },
  "ein.nichtEingerichtet": { de: "Nicht eingerichtet: {fehler}", en: "Not set up: {fehler}" },
  "ein.tresorZuerst": { de: "Für {wofuer} braucht die App zuerst den Tresor: Das Geheimnis dazu soll nicht unverschlüsselt im Browser liegen.", en: "For {wofuer} the app needs the vault first: the secret for it should not sit unencrypted in the browser." },
  "ein.entsperrenTitel": { de: "Tresor entsperren", en: "Unlock vault" },
  "ein.liegtVerschluesselt": { de: "Dein Schlüssel liegt verschlüsselt auf diesem Gerät.", en: "Your key is stored encrypted on this device." },
  "ein.passphrase": { de: "Passphrase", en: "Passphrase" },
  "ein.entsperren": { de: "entsperren", en: "unlock" },
  "ein.vergessen": { de: "Passphrase vergessen?", en: "Forgot passphrase?" },
  "ein.pruefe": { de: "prüfe …", en: "checking …" },
  "ein.passFalsch": { de: "Passphrase falsch.", en: "Wrong passphrase." },
  "ein.entsperrFehler": { de: "{fehler} – über „Passphrase vergessen?“ mit der Merkphrase neu beginnen.", en: "{fehler} – start over with the recovery phrase via “Forgot passphrase?”." },
  "ein.neuTitel": { de: "Mit der Merkphrase neu beginnen", en: "Start over with the recovery phrase" },
  "ein.neuText": { de: "Der alte Tresor wird gelöscht. Deine Identität kommt aus den 12 Wörtern (oder dem nsec) zurück. Unterhaltungen und Räume holst du danach über die verschlüsselte Sicherung zurück (Settings → Sicherheit).", en: "The old vault is deleted. Your identity comes back from the 12 words (or the nsec). Afterwards you restore conversations and rooms from the encrypted backup (Settings → Security)." },
  "ein.phraseOderNsec": { de: "12 Wörter oder nsec1…", en: "12 words or nsec1…" },
  "ein.passNeuNeu": { de: "neue Passphrase (mind. 8 Zeichen)", en: "new passphrase (at least 8 characters)" },
  "ein.neuEinrichten": { de: "neu einrichten", en: "set up again" },
  "ein.zurueck": { de: "zurück", en: "back" },
  "ein.richteNeuEin": { de: "richte neu ein – das dauert einen Moment …", en: "setting up again – this takes a moment …" },
  "ein.tresorNeu": { de: "Tresor neu eingerichtet", en: "Vault set up again" },
  "ein.sperreAus": { de: "Automatische Sperre aus", en: "Automatic lock off" },
  "ein.sperrtNach": { de: "Sperrt nach {n} Minuten ohne Eingabe", en: "Locks after {n} minutes without input" },
  "ein.passFalschOderVeraendert": { de: "Passphrase falsch oder Tresor verändert", en: "Wrong passphrase or vault modified" },
  "ein.nurText": { de: "Tresor speichert nur Text", en: "The vault stores text only" },
  "ein.passZuKurz": { de: "Passphrase zu kurz – mindestens {n} Zeichen", en: "Passphrase too short – at least {n} characters" },
  "ein.schonTresor": { de: "Es gibt schon einen Tresor", en: "A vault already exists" },
  "ein.keinTresor": { de: "Kein Tresor vorhanden", en: "No vault present" },
  "ein.uebernahmeUnbestaetigt": { de: "Übernahme nicht bestätigt: {schluessel}", en: "Takeover not confirmed: {schluessel}" },

  // Nachfolge als Vertrauter (shell/nachfolge-ui.ts, nachfolge.ts)
  "ein.vertrauterFuer": { de: "Du bist Vertrauter für:", en: "You are a trustee for:" },
  "ein.anteilOhneTresor": { de: "Ohne Tresor bleibt dein Anteil nur auf den Relays – richte den Tresor ein, damit er auf diesem Gerät bleibt.", en: "Without a vault your share stays only on the relays – set up the vault so it stays on this device." },
  "ein.relaysNichtErreichbar": { de: "Relays nicht erreichbar", en: "Relays not reachable" },
  "ein.anteilZeile": { de: "{wer} · Teil {teil} von {von}, Schwelle {schwelle}", en: "{wer} · share {teil} of {von}, threshold {schwelle}" },
  "ein.planFehlt": { de: "Plan nicht gefunden", en: "Plan not found" },
  "ein.planFehltPunkt": { de: "Plan nicht gefunden.", en: "Plan not found." },
  "ein.aelterePlan": { de: "Dein Anteil gehört zu einem älteren Plan – der Besitzer hat neu eingerichtet.", en: "Your share belongs to an older plan – the owner has set up anew." },
  "ein.melden": { de: "melden", en: "report" },
  "ein.gemeldet": { de: "gemeldet · ", en: "reported · " },
  "ein.anfordern": { de: "Anteile anfordern", en: "Request shares" },
  "ein.beisammen": { de: "{n} von {von} beisammen ", en: "{n} of {von} gathered " },
  "ein.zusammensetzen": { de: "zusammensetzen", en: "combine" },
  "ein.bittetUmAnteil": { de: "{wer} bittet um deinen Anteil. ", en: "{wer} asks for your share. " },
  "ein.uebergeben": { de: "übergeben", en: "hand over" },
  "ein.meldungWarum": { de: "Meldung für {wer}: Warum? (wird veröffentlicht)", en: "Report for {wer}: why? (will be published)" },
  "ein.gemeldetToast": { de: "Gemeldet — ein Lebenszeichen der Person bricht den Vorgang ab", en: "Reported — a sign of life from the person cancels the process" },
  "ein.angefragt": { de: "{n} Vertraute versiegelt angefragt – ihre Apps übergeben erst nach Freigabe", en: "{n} trustees asked (sealed) – their apps only hand over after release" },
  "ein.uebergebenFrage": { de: "Deinen Anteil für {besitzer} an {an} übergeben?\n\nDer Plan ist freigegeben. Mit genug Anteilen kann {an} den Schlüssel zusammensetzen.", en: "Hand over your share for {besitzer} to {an}?\n\nThe plan is released. With enough shares {an} can combine the key." },
  "ein.uebergebenToast": { de: "Anteil versiegelt übergeben", en: "Share handed over (sealed)" },
  "ein.nachfolgeDatei": { de: "Wiederhergestellter Schlüssel von {besitzer}\n\nPrivater Schlüssel (hex):\n{hex}\n\nWer diese Datei hat, IST diese Person im Netz. Sicher aufbewahren und nach dem Import löschen.\nImport: die App in einem eigenen Browserprofil öffnen → „Identität importieren“ → den Hex-Schlüssel einfügen.\n", en: "Recovered key of {besitzer}\n\nPrivate key (hex):\n{hex}\n\nWhoever has this file IS this person on the network. Keep it safe and delete it after importing.\nImport: open the app in a separate browser profile → “Import identity” → paste the hex key.\n" },
  "ein.zusammengesetzt": { de: "Zusammengesetzt und geprüft – der Schlüssel liegt in der Datei", en: "Combined and verified – the key is in the file" },

  // Notfall-Löschung (shell/notfall.ts, protokoll-texte.ts)
  "ein.zweiterDurchgang": { de: "zweiter Durchgang gescheitert", en: "second pass failed" },
  "ein.nichtAllesGeloescht": { de: "Notfall-Löschung: NICHT alles gelöscht – {offen}. Von Hand nachsehen (Browser-Einstellungen → Websitedaten).", en: "Emergency wipe: NOT everything deleted – {offen}. Check by hand (browser settings → site data)." },
  "ein.nachgeprueft": { de: " und nachgeprüft", en: " and verified" },
  "ein.nichtNachgeprueft": { de: " (dieser Browser kann Datenbanken nicht auflisten – nicht nachgeprüft)", en: " (this browser cannot list databases – not verified)" },
  "ein.allesGeloescht": { de: "Alles auf diesem Gerät gelöscht ({n} Einträge und Datenbanken){pruef}. Die App ist leer – Relays haben weiter, was dort liegt.", en: "Everything on this device deleted ({n} entries and databases){pruef}. The app is empty – relays still have what is stored there." },
  "ein.loeschenEintippen": { de: "zum Bestätigen LÖSCHEN eintippen", en: "type DELETE to confirm" },
  "ein.endgueltigLoeschen": { de: "endgültig löschen", en: "delete permanently" },
  "ein.notfallTitel": { de: "Notfall-Löschung", en: "Emergency wipe" },
  "ein.geldLaeuft": { de: "Gerade läuft ein Tausch oder ein Deposit – sein Geld kann verloren sein.", en: "A swap or deposit is running right now – its money may be lost." },
  "ein.loesche": { de: "lösche …", en: "deleting …" },
  "ein.loeschenGescheitert": { de: "Löschen gescheitert: {fehler}", en: "Deleting failed: {fehler}" },
  "ein.wipeText": {
    de: "Alles auf diesem Gerät löschen?\n\nGelöscht werden Schlüssel, Tresor, Unterhaltungen, Suchindex, Räume,\nNamen, Wallet-Verbindung und die eingebaute SOL-Wallet.\nEs gibt KEINE Wiederherstellung.\n\nOhne deine Merkphrase kommst du danach nicht zurück. Geld in laufenden\nTauschvorgängen oder Sperren kann verloren sein – ihre Geheimnisse\nliegen nur hier.\n\nRECHTLICHER HINWEIS: In vielen Ländern ist das Vernichten von\nBeweismitteln strafbar – etwa während eines Verfahrens oder einer\nDurchsuchung. Das ist keine Rechtsberatung.\n\nWas NICHT gelöscht wird: alles, was schon auf Relays liegt.",
    en: "Delete everything on this device?\n\nThis deletes keys, vault, conversations, search index, rooms, names, wallet connection and the built-in SOL wallet.\nThere is NO recovery.\n\nWithout your recovery phrase you cannot come back afterwards. Money in running swaps or locks may be lost – their secrets are only here.\n\nLEGAL NOTICE: In many countries destroying evidence is a crime – for example during proceedings or a search. This is not legal advice.\n\nWhat is NOT deleted: everything already on relays.",
  },

  // Einrichtung beim ersten Start (shell/einrichtung-ui.ts)
  "ein.schrittVon": { de: "Schritt {nr} von {von}", en: "Step {nr} of {von}" },
  "ein.ueberspringen": { de: "Einrichtung überspringen", en: "Skip setup" },
  "ein.schutz": { de: "Schutz", en: "Protection" },
  "ein.schutzText": { de: "Eine Passphrase verschlüsselt deinen Schlüssel, Wallet-Zugänge und Unterhaltungen auf diesem Gerät; beim Start fragt die App danach. Vergisst du sie, hilft nur die Merkphrase.", en: "A passphrase encrypts your key, wallet access and conversations on this device; the app asks for it at start. If you forget it, only the recovery phrase helps." },
  "ein.passFestlegen": { de: "Passphrase festlegen", en: "Set passphrase" },
  "ein.womitZahlen": { de: "Womit zahlst du?", en: "How do you pay?" },
  "ein.womitZahlenText": { de: "Vorgabe für Trinkgeld und Zaps – bei jeder Zahlung änderbar. Die App zahlt nie still in der anderen Währung. Eine Wallet brauchst du erst, wenn du bezahlst.", en: "Default for tips and zaps – changeable with every payment. The app never silently pays in the other currency. You only need a wallet once you pay." },
  "ein.privat": { de: "Privat von Anfang an", en: "Private from the start" },
  "ein.nochNicht": { de: "Noch nicht: {was}", en: "Not yet: {was}" },
  "ein.verbindung": { de: "Verbindung", en: "Connection" },
  "ein.kontakteAbgleichen": { de: "Kontakte verschlüsselt zwischen Geräten abgleichen (Standard: aus)", en: "Sync contacts encrypted between devices (default: off)" },
  "ein.werberNennen": { de: "{wer} öffentlich als meinen Werber nennen", en: "Publicly name {wer} as my referrer" },
  "ein.werberText": { de: "Standard: aus. Öffentlich genannt zählst du in seiner Statistik – und jeder kann sehen, dass ihr verbunden seid. Für seinen Anteil an deinen KI-Zahlungen ist das nicht nötig.", en: "Default: off. Named publicly, you count in their statistics – and anyone can see that you are connected. It is not needed for their share of your AI payments." },
  "ein.spaeterSettings": { de: "Alles später unter Settings → Datenschutz.", en: "Everything later under Settings → Privacy." },
  "ein.weiter": { de: "weiter", en: "continue" },
  "ein.womitAnfangen": { de: "Womit fängst du an?", en: "What do you want to start with?" },
  "ein.leisteDanach": { de: "Die Onboarding-Leiste oben zeigt danach immer genau einen nächsten Schritt.", en: "Afterwards the onboarding bar at the top always shows exactly one next step." },
  "ein.kiFragen": { de: "KI fragen", en: "Ask the AI" },
  "ein.nachrichtenSchreiben": { de: "Nachrichten schreiben", en: "Write messages" },

  // Zustand und Hilfen (shell/state.ts, shell/ui.ts)
  "ein.keineIdentitaet": { de: "Keine Identität – nichts zu signieren", en: "No identity – nothing to sign" },
  "ein.nurMitSchluessel": { de: "{wofuer} geht nur mit dem Schlüssel auf diesem Gerät, nicht über einen Bunker", en: "{wofuer} only works with the key on this device, not via a bunker" },
  "ein.endpunkteGespeichert": { de: "Endpunkte gespeichert", en: "Endpoints saved" },
  "ein.keineAntwortRpc": { de: "keine Antwort", en: "no answer" },
  "ein.poolFehlt": { de: "Pool fehlt", en: "Pool missing" },
  "ein.keineIdentitaetKurz": { de: "nicht verbunden", en: "not connected" },
  "ein.budgetRest": { de: "Rest des Sitzungsbudgets (ohne Verwahrer)", en: "Remaining session budget (non-custodial)" },
  "ein.escrowGuthaben": { de: "Escrow-Guthaben (eingezahlt, für Aufträge nutzbar)", en: "Escrow balance (deposited, usable for jobs)" },
  "ein.kopiert": { de: "kopiert", en: "copied" },
  // Bunker (shell/bunker.ts)
  "ein.bunkerAngemeldet": { de: "Angemeldet über den Bunker {signer} ({relays}). Jede Unterschrift fragt die App dort an.", en: "Signed in via the bunker {signer} ({relays}). The app requests every signature there." },
  "ein.bunkerNicht": { de: "Nicht verbunden – die App nutzt den Schlüssel auf diesem Gerät.", en: "Not connected – the app uses the key on this device." },
  "ein.erstAbschliessen": { de: "Erst den laufenden Tausch oder Auftrag abschließen", en: "Finish the running swap or job first" },
  "ein.bunkerWechsel": { de: "Die App wechselt auf die Identität im Bunker. Der Schlüssel auf diesem Gerät bleibt gespeichert – Abmelden bringt ihn zurück. Weiter?", en: "The app switches to the identity in the bunker. The key on this device stays stored – signing out brings it back. Continue?" },
  "ein.bunkerVerbinde": { de: "verbinde … (falls nötig im Signer bestätigen)", en: "connecting … (confirm in the signer if needed)" },
  "ein.bunkerAls": { de: "Angemeldet als {pk} – lade neu …", en: "Signed in as {pk} – reloading …" },
  "ein.nichtVerbunden": { de: "Nicht verbunden: {fehler}", en: "Not connected: {fehler}" },
  "ein.bunkerAbmelden": { de: "Vom Bunker abmelden? Danach gilt wieder der Schlüssel auf diesem Gerät.", en: "Sign out of the bunker? Afterwards the key on this device applies again." },

  // Darstellung (shell-logic.ts)
  "ein.datei": { de: "datei", en: "file" },
  "ein.anhangSchluessel": { de: "Anhang mit ungültigem Schlüssel: {name}", en: "Attachment with invalid key: {name}" },
  "ein.anhangLink": { de: "Anhang mit nicht unterstütztem Link: {name}", en: "Attachment with unsupported link: {name}" },
  "ein.keineSession": { de: "keine Session — die erste Anfrage startet eine", en: "no session — the first request starts one" },
  "ein.budgetAufgebraucht": { de: "Budget aufgebraucht ({budget}) — Session erneuern", en: "Budget used up ({budget}) — renew session" },
  "ein.budgetUebrig": { de: "{rest} von {budget} übrig", en: "{rest} of {budget} left" },
  "ein.geradeEben": { de: "gerade eben", en: "just now" },
  "ein.vorMin": { de: "vor {n} min", en: "{n} min ago" },
  "ein.vorStd": { de: "vor {n} h", en: "{n} h ago" },
  "ein.vorTagen": { de: "vor {n} d", en: "{n} d ago" },

  // Geräte (geraete-buch.ts, geraete-modus.ts)
  "ein.vonGeraet": { de: "von deinem Gerät „{name}“", en: "from your device “{name}”" },
  "ein.vonGeraetUnbelegt": { de: "von deinem Gerät „{name}“ – Gerät inzwischen entzogen, Zeitpunkt nicht belegt", en: "from your device “{name}” – device revoked since, time not proven" },
  "ein.nachEntzug": { de: "⚠ von deinem Gerät „{name}“ nach dem Entzug – nicht von dir", en: "⚠ from your device “{name}” after revocation – not from you" },
  "ein.bevollmaechtigtAber": { de: "⚠ als Gerät „{name}“ bevollmächtigt, aber: {grund}", en: "⚠ authorized as device “{name}”, but: {grund}" },
  "ein.ueberGeraet": { de: "über Gerät „{name}“", en: "via device “{name}”" },
  "ein.ueberGeraetUnbelegt": { de: "über Gerät „{name}“ – Gerät inzwischen entzogen, Zeitpunkt nicht belegt", en: "via device “{name}” – device revoked since, time not proven" },
  "ein.codeHex": { de: "Person und Schlüssel müssen 64-stelliges Hex sein", en: "Person and key must be 64-digit hex" },
  "ein.keineVollmacht": { de: "Keine Vollmacht der Person für dieses Gerät gefunden.", en: "No authorization from the person found for this device." },
  "ein.geraetStand": { de: "Gerät „{name}“ · {stand}", en: "Device “{name}” · {stand}" },
  "ein.geraetOhneNachrichten": { de: "Gerät „{name}“ darf keine Nachrichten schreiben.", en: "Device “{name}” may not write messages." },

  // Relays, Versand, Suche (relay-satz.ts, shell/versand.ts, suche.ts, shell/suche-ui.ts)
  "ein.relayMindestens": { de: "Mindestens ein Relay – sonst findet dich niemand.", en: "At least one relay – otherwise nobody finds you." },
  "ein.relayAdresse": { de: "Adresse {n}: {grund}", en: "Address {n}: {grund}" },
  "ein.relayNurWss": { de: "Adresse {n}: nur wss:// (unverschlüsselt nur .onion) und kein lokales Netz", en: "Address {n}: only wss:// (unencrypted only .onion) and no local network" },
  "ein.relayHoechstens": { de: "Höchstens {n} Relays – jeder weitere kostet Kontakte eine Verbindung.", en: "At most {n} relays – each additional one costs contacts a connection." },
  "ein.relayPosteingang": { de: "Mindestens eins muss als Posteingang taugen (wss://).", en: "At least one must work as an inbox (wss://)." },
  "ein.nichtZugestellt": { de: "Nachricht nicht zugestellt: {fehler}", en: "Message not delivered: {fehler}" },
  "ein.suchSchluessel": { de: "Suchschlüssel ungültig", en: "Search key invalid" },
  "ein.suchIndex": { de: "Suchindex unlesbar", en: "Search index unreadable" },
  "ein.nichtsGefunden": { de: "Nichts gefunden – gesucht wird nur in Nachrichten, die hier schon geöffnet wurden.", en: "Nothing found – only messages already opened here are searched." },
  // Git-Bündel veröffentlichen (shell/app.ts)
  "ein.gitPubliziere": { de: "publiziere {name} ({kb} KB)…", en: "publishing {name} ({kb} KB)…" },
  "ein.gitPubliziert": { de: "{name} veröffentlicht ({blob}…)", en: "{name} published ({blob}…)" },
  "ein.gitFehler": { de: "Git-Fehler: {fehler}", en: "Git error: {fehler}" },
};
