/** Fehlermeldungen des Protokolls (8.16i1/i2, `ProtokollFehler`) – Deutsch wortgleich mit dem Protokoll (`fehlerText()`, Test). */
import type { Texte } from "../i18n.js";

export const fehler: Texte = {
  // Solana-RPC (RpcPool)
  "pf.rpcUnerreichbar": { de: "Kein Solana-Endpunkt erreichbar ({n} versucht). {details}", en: "No Solana endpoint reachable ({n} tried). {details}" },
  // Lightning-Rechnung (leseBolt11)
  "pf.bolt11Praefix": { de: "kein bolt11-Präfix", en: "not a bolt11 prefix" },
  "pf.bolt11Betrag": { de: "ungültiger Betrag in der Rechnung", en: "invalid amount in the invoice" },
  "pf.bolt11Kurz": { de: "Rechnung zu kurz", en: "invoice too short" },
  "pf.bolt11Feld": { de: "abgeschnittenes Feld", en: "truncated field" },
  "pf.bolt11Hash": { de: "Rechnung ohne Payment-Hash", en: "invoice without a payment hash" },
  "pf.bolt11Recovery": { de: "ungültige Recovery-ID", en: "invalid recovery ID" },
  "pf.bolt11Signatur": { de: "Signatur der Rechnung ungültig", en: "invoice signature invalid" },
  "pf.bolt11Knoten": { de: "Signatur passt nicht zum genannten Knoten", en: "signature does not match the named node" },
  // Wallet über NWC (parseNwcUri, NwcClient)
  "pf.nwcPraefix": { de: "Keine NWC-Verbindung: erwartet wird nostr+walletconnect://…", en: "Not an NWC connection: expected nostr+walletconnect://…" },
  "pf.nwcPubkey": { de: "NWC-URI: Wallet-Pubkey ist kein gültiger 64-stelliger Hex-Wert.", en: "NWC URI: the wallet pubkey is not a valid 64-character hex value." },
  "pf.nwcRelay": { de: "NWC-URI: kein relay angegeben.", en: "NWC URI: no relay given." },
  "pf.nwcSecret": { de: "NWC-URI: secret fehlt oder ist kein 64-stelliger Hex-Wert.", en: "NWC URI: the secret is missing or not a 64-character hex value." },
  "pf.nwcMethode": { de: "Dieses Wallet unterstützt \"{methode}\" nicht.", en: "This wallet does not support \"{methode}\"." },
  "pf.nwcKeinRelay": { de: "Kein Relay hat das Wallet-Kommando angenommen — Netzwerkproblem.", en: "No relay accepted the wallet command — network problem." },
  "pf.nwcGuthaben": { de: "Das Wallet hat nicht genug Guthaben für diese Zahlung.", en: "The wallet does not have enough balance for this payment." },
  "pf.nwcBudget": { de: "Das für diese Verbindung gesetzte Budget ist aufgebraucht. Im Wallet erhöhen.", en: "The budget set for this connection is used up. Raise it in the wallet." },
  "pf.nwcVerboten": { de: "Diese Verbindung darf die angeforderte Aktion nicht ausführen.", en: "This connection may not perform the requested action." },
  "pf.nwcWiderrufen": { de: "Die Verbindung wurde im Wallet widerrufen. Bitte neu verbinden.", en: "The connection was revoked in the wallet. Please reconnect." },
  "pf.nwcNichtUnterstuetzt": { de: "Dieses Wallet unterstützt die angeforderte Funktion nicht.", en: "This wallet does not support the requested function." },
  "pf.nwcZahlung": { de: "Die Zahlung ist fehlgeschlagen — meist fehlt eine Route zum Empfänger.", en: "The payment failed — usually there is no route to the recipient." },
  "pf.nwcZuViele": { de: "Zu viele Anfragen an das Wallet. Kurz warten.", en: "Too many requests to the wallet. Wait a moment." },
  "pf.nwcFehler": { de: "Wallet-Fehler: {code}", en: "Wallet error: {code}" },
  "pf.nwcZeit": { de: "Das Wallet hat in {sekunden}s nicht geantwortet. Ist es online und mit denselben Relays verbunden?", en: "The wallet did not answer within {sekunden}s. Is it online and connected to the same relays?" },
  // Zahlschienen (pruefeAnfrage, waehleRail) und Beträge
  "pf.schieneZiel": { de: "Ziel passt nicht zur Schiene {schiene}", en: "Destination does not match the {schiene} rail" },
  "pf.schieneEinheit": { de: "Betrag in {einheit}, {schiene} rechnet in {rechnet}", en: "Amount in {einheit}, {schiene} works in {rechnet}" },
  "pf.schieneReferenz": { de: "Referenz nur als Solana-Adresse", en: "Reference only as a Solana address" },
  "pf.schieneUnbekannt": { de: "Unbekanntes Zahlungsziel", en: "Unknown payment destination" },
  "pf.schieneFehlt": { de: "Keine Schiene für {schiene}", en: "No rail for {schiene}" },
  "pf.offlineSats": { de: "Offline: Sats gehen erst wieder, wenn Netz da ist – Lightning braucht mehrere Runden Austausch. Nachrichten gehen über Funk oder per Datei.", en: "Offline: sats only work again once the network is back – Lightning needs several rounds of exchange. Messages go over radio or by file." },
  "pf.offlineSol": { de: "Offline: Diese SOL-Zahlung braucht Netz. Ohne Netz zahlst du mit dem Nonce-Konto (Wallet-Tab → Ohne Internet zahlen) – ein Gerät mit Netz reicht ein.", en: "Offline: this SOL payment needs the network. Without network you pay with the nonce account (Wallet tab → Pay without internet) – a device with network submits it." },
  "pf.walletFehltSats": { de: "Keine Lightning-Wallet verbunden – im Wallet-Tab per NWC verbinden.", en: "No Lightning wallet connected – connect one via NWC in the Wallet tab." },
  "pf.walletFehltSol": { de: "Keine Solana-Wallet verbunden – im Wallet-Tab verbinden.", en: "No Solana wallet connected – connect one in the Wallet tab." },
  "pf.betragPositiv": { de: "Betrag muss eine positive ganze Zahl sein", en: "The amount must be a positive whole number" },
  "pf.limitUngueltig": { de: "Limit muss eine nicht negative ganze Zahl sein", en: "The limit must be a non-negative whole number" },
  "pf.kanalBetrag": { de: "Betrag muss größer als 0 sein", en: "The amount must be greater than 0" },
  // SOL ohne Internet (sol-offline)
  "pf.nonceNichtEingerichtet": { de: "Nonce-Konto ist nicht eingerichtet", en: "The nonce account is not set up" },
  "pf.anSichSelbst": { de: "Überweisung an sich selbst", en: "Transfer to yourself" },
  "pf.nonceAndereAdresse": { de: "Das Nonce-Konto gehört einer anderen Adresse", en: "The nonce account belongs to a different address" },
  // Rück-Swap (rueckSwapLamports)
  "pf.rueckBetrag": { de: "Betrag in sats ungültig", en: "Amount in sats invalid" },
  "pf.rueckKurs": { de: "Kurs ungültig", en: "Rate invalid" },
  "pf.rueckGebuehr": { de: "Gebühr ungültig", en: "Fee invalid" },
  // SOL-Trinkgeld (buildSolTrinkgeld)
  "pf.trinkgeldBetrag": { de: "Betrag muss eine positive ganze Zahl (Lamports) sein", en: "The amount must be a positive whole number (lamports)" },
  "pf.solAdresse": { de: "keine gültige SOL-Adresse", en: "not a valid SOL address" },
  "pf.trinkgeldNotiz": { de: "Notiz höchstens {max} Zeichen", en: "Note at most {max} characters" },
  // Zustandssicherung (buildStateBackup)
  "pf.sicherungGross": { de: "Sicherung zu groß ({kb} KB, höchstens {max} KB) – nichts gesendet.", en: "Backup too large ({kb} KB, at most {max} KB) – nothing sent." },
  // Identität und Inhalte (8.16i2): Bunker, Repos, Modellkataloge, Kontakte, Nachfolge, Geräte, Räume, Dateien
  "pf.bunkerAdresse": { de: "Keine gültige bunker://-Adresse", en: "Not a valid bunker:// address" },
  "pf.bunkerSigner": { de: "Signer-Pubkey ungültig (64 Zeichen hex erwartet)", en: "Signer pubkey invalid (64 hex characters expected)" },
  "pf.bunkerRelay": { de: "Keine Relay-Adresse (wss://) in der bunker://-Adresse", en: "No relay address (wss://) in the bunker:// address" },
  "pf.signerPubkey": { de: "Signer lieferte keinen gültigen Pubkey", en: "The signer returned no valid pubkey" },
  "pf.signerKeinEvent": { de: "Signer lieferte kein Event", en: "The signer returned no event" },
  "pf.signerEvent": { de: "Signer lieferte ein anderes oder ungültiges Event", en: "The signer returned a different or invalid event" },
  "pf.signerFreigabe": { de: "Signer verlangt eine Freigabe: {adresse}", en: "The signer asks for approval: {adresse}" },
  "pf.signerFreigabeOhne": { de: "Signer verlangt eine Freigabe: (ohne Adresse)", en: "The signer asks for approval: (no address)" },
  "pf.signerAblehnung": { de: "Signer lehnt ab: {grund}", en: "The signer refuses: {grund}" },
  "pf.signerAntwort": { de: "Signer lieferte keine gültige Antwort", en: "The signer returned no valid answer" },
  "pf.signerZeit": { de: "Keine Antwort vom Signer ({methode})", en: "No answer from the signer ({methode})" },
  "pf.repoKennung": { de: "Repo-Kennung: Buchstaben, Ziffern, . _ - (höchstens 64)", en: "Repo ID: letters, digits, . _ - (at most 64)" },
  "pf.repoKlon": { de: "Keine Klon-Adresse: {adresse}", en: "Not a clone address: {adresse}" },
  "pf.repoMaintainer": { de: "Maintainer muss ein 64-stelliger Hex-Schlüssel sein", en: "A maintainer must be a 64-character hex key" },
  "pf.repoErsterCommit": { de: "Erster Commit muss ein SHA-1 sein", en: "The first commit must be a SHA-1" },
  "pf.repoRaum": { de: "Kein öffentlicher Raum (34700:<Schlüssel>:space:<Kennung>)", en: "Not a public room (34700:<key>:space:<id>)" },
  "pf.patchGross": { de: "Patch zu groß (höchstens {kb} KB) – größere Änderungen als Bundle", en: "Patch too large (at most {kb} KB) – larger changes as a bundle" },
  "pf.patchFormat": { de: "Kein Patch aus `git format-patch` (erste Zeile „From <commit> …“ fehlt)", en: "Not a patch from `git format-patch` (first line “From <commit> …” is missing)" },
  "pf.patchBetreff": { de: "Patch ohne Betreff", en: "Patch without a subject" },
  "pf.patchDiff": { de: "Patch ohne Änderung (kein „diff --git“)", en: "Patch without a change (no “diff --git”)" },
  "pf.patchCommit": { de: "Commit muss ein SHA-1 sein", en: "A commit must be a SHA-1" },
  "pf.issueBetreff": { de: "Issue ohne Betreff", en: "Issue without a title" },
  "pf.issueGross": { de: "Issue zu groß (höchstens {kb} KB)", en: "Issue too large (at most {kb} KB)" },
  "pf.issueLabel": { de: "Label: ohne Leerzeichen und Komma, höchstens 40 Zeichen", en: "Label: no spaces or commas, at most 40 characters" },
  "pf.kommentarLeer": { de: "Kommentar ohne Text", en: "Comment without text" },
  "pf.kommentarGross": { de: "Kommentar zu groß (höchstens {kb} KB)", en: "Comment too large (at most {kb} KB)" },
  "pf.kommentarWurzel": { de: "Kommentare nur an Issues und Patches", en: "Comments only on issues and patches" },
  "pf.kommentarBezug": { de: "Kommentar ohne gültigen Bezug", en: "Comment without a valid reference" },
  "pf.reviewZeile": { de: "Zeilenbezug ungültig (Pfad, Seite oder Zeile)", en: "Invalid line reference (path, side or line)" },
  "pf.reviewPatch": { de: "Reviews nur an Patches", en: "Reviews only on patches" },
  "pf.reviewBewertung": { de: "Bewertung unbekannt", en: "Unknown review verdict" },
  "pf.releaseRepo": { de: "Release ohne gültiges Repo", en: "Release without a valid repository" },
  "pf.releaseVersion": { de: "Version wie ein Git-Tag (Buchstaben, Ziffern, . _ + - /, höchstens 100)", en: "Version like a Git tag (letters, digits, . _ + - /, at most 100)" },
  "pf.releaseTitel": { de: "Titel fehlt oder ist zu lang (höchstens 200 Zeichen)", en: "Title missing or too long (at most 200 characters)" },
  "pf.releaseGross": { de: "Notizen zu groß (höchstens {kb} KB)", en: "Notes too large (at most {kb} KB)" },
  "pf.releaseCommit": { de: "Commit muss ein SHA-1 sein", en: "Commit must be a SHA-1" },
  "pf.releaseBundle": { de: "Bundle ohne gültige Id oder Schlüssel", en: "Bundle without a valid id or key" },
  "pf.labelZiel": { de: "Labels nur an Issues und Patches", en: "Labels only on issues and patches" },
  "pf.labelArt": { de: "Unbekannte Art (Labels oder Zuständige)", en: "Unknown kind (labels or assignees)" },
  "pf.labelZustaendig": { de: "Zuständige als 64-stellige Hex-Schlüssel", en: "Assignees as 64-character hex keys" },
  "pf.labelViele": { de: "Höchstens {n} Einträge", en: "At most {n} entries" },
  "pf.repoFork": { de: "Fork nur von einem anderen Repo (30617:<Schlüssel>:<Kennung>)", en: "Fork only of another repository (30617:<key>:<id>)" },
  "pf.sternRepo": { de: "Stern nur an ein gültiges Repo", en: "Star only on a valid repository" },
  "pf.beobachtenListe": { de: "Beobachten nur für gültige Repos", en: "Watch only valid repositories" },
  "pf.katalogKennung": { de: "Kennung: 1–64 Zeichen aus Buchstaben, Ziffern, . _ -", en: "ID: 1–64 characters from letters, digits, . _ -" },
  "pf.katalogTitel": { de: "Titel: 1–{max} Zeichen", en: "Title: 1–{max} characters" },
  "pf.katalogBeschreibung": { de: "Beschreibung: höchstens {max} Zeichen", en: "Description: at most {max} characters" },
  "pf.katalogModelle": { de: "Höchstens {max} Modelle je Katalog", en: "At most {max} models per catalog" },
  "pf.katalogModell": { de: "Keine Modell-Kennung: {modell}", en: "Not a model ID: {modell}" },
  "pf.katalogDoppelt": { de: "Doppelt: {modell}", en: "Duplicate: {modell}" },
  "pf.katalogNotiz": { de: "Notiz zu {modell}: höchstens {max} Zeichen", en: "Note on {modell}: at most {max} characters" },
  "pf.kontakteMax": { de: "Höchstens {max} Kontakte", en: "At most {max} contacts" },
  "pf.kontakteUnlesbar": { de: "Kontaktliste nicht lesbar", en: "Contact list not readable" },
  "pf.kontakteKaputt": { de: "Kontaktliste beschädigt", en: "Contact list damaged" },
  "pf.schwelleMin": { de: "Schwelle muss mindestens 2 sein — bei 1 genügt ein Vertrauter allein.", en: "The threshold must be at least 2 — with 1, a single trusted person would be enough." },
  "pf.teileZuWenig": { de: "{n} Teile reichen für eine Schwelle von {k} nicht.", en: "{n} shares are not enough for a threshold of {k}." },
  "pf.teileMax": { de: "Höchstens 255 Teile.", en: "At most 255 shares." },
  "pf.teileMindestens": { de: "Mindestens zwei Teile nötig.", en: "At least two shares are needed." },
  "pf.teileLaengen": { de: "Teile haben verschiedene Längen.", en: "The shares have different lengths." },
  "pf.teileDoppelt": { de: "Doppelte Teile — sie tragen nichts bei.", en: "Duplicate shares — they add nothing." },
  "pf.teileFassungen": { de: "Teile verschiedener Fassungen passen nicht zusammen.", en: "Shares of different versions do not fit together." },
  "pf.geheimnisLeer": { de: "Ein leeres Geheimnis lässt sich nicht teilen.", en: "An empty secret cannot be split." },
  "pf.anteileZuWenig": { de: "Erst {n} von {schwelle} nötigen Anteilen", en: "Only {n} of {schwelle} required shares so far" },
  "pf.anteilePassenNicht": { de: "Die Anteile passen nicht zusammen oder nicht zum Plan", en: "The shares do not fit together or do not match the plan" },
  "pf.geraetSelbst": { de: "Ein Gerät kann sich nicht selbst bevollmächtigen.", en: "A device cannot authorize itself." },
  "pf.geraetOhneRechte": { de: "Eine Vollmacht ohne Rechte ist sinnlos.", en: "An authorization without permissions is pointless." },
  "pf.nachfolgerSelbst": { de: "Der Nachfolger darf nicht derselbe Schlüssel sein.", en: "The successor must not be the same key." },
  "pf.selbstwerbung": { de: "Selbstwerbung ist nicht möglich.", en: "You cannot refer yourself." },
  "pf.keinModerator": { de: "kein Moderator außer dir", en: "no moderator besides you" },
  "pf.planungUngueltig": { de: "Umfrage oder Termin ungültig: {was}", en: "Poll or event invalid: {was}" },
  "pf.raumKanal": { de: "Kanal ungültig", en: "Channel invalid" },
  "pf.kopplungKnoten": { de: "Kopplung: kein gültiger Schlüssel des Knotens", en: "Pairing: not a valid node key" },
  "pf.kopplungGeheimnis": { de: "Kopplung: kein gültiges Geheimnis", en: "Pairing: not a valid secret" },
  "pf.kopplungFremd": { de: "Besitzer-Nachweis nur an den gekoppelten Knoten", en: "Owner proof only to the paired node" },
  "pf.dateiSchluessel": { de: "Datei-Schlüssel ungültig", en: "File key invalid" },
  "pf.dateiKaputt": { de: "Datei beschädigt oder falscher Schlüssel", en: "File damaged or wrong key" },
  "pf.dateiHash": { de: "Datei passt nicht zum Hash", en: "File does not match the hash" },
  // Meshtastic (7.5c)
  "pf.meshtasticOhneKanal": { de: "Auf dem Meshtastic-Gerät fehlt der Kanal „freedom“ – nichts gesendet.", en: "The Meshtastic device has no “freedom” channel – nothing sent." },
  // QR-Code (11.1a)
  "pf.qrZuLang": { de: "Zu lang für einen QR-Code: {n} Byte, höchstens {max}", en: "Too long for a QR code: {n} bytes, at most {max}" },
};
