/** Texte der Abdeckungskarte (seit C.4a); Ebenen und Stufen stehen weiter unter `earn.*`. */
import type { Texte } from "../i18n.js";

export const karte: Texte = {
  "karte.aria": { de: "Abdeckungskarte – Pfeiltasten verschieben, Plus und Minus zoomen, 0 zeigt die ganze Welt, Tab springt zu den Gebieten", en: "Coverage map – arrow keys pan, plus and minus zoom, 0 shows the whole world, Tab jumps to the areas" },
  "karte.ansichtAria": { de: "Ansicht der Abdeckung", en: "Coverage view" },
  "karte.liste": { de: "Liste", en: "List" },
  "karte.ebenenAria": { de: "Ebenen ein- und ausblenden", en: "Show or hide layers" },
  "karte.naeher": { de: "Näher heran", en: "Zoom in" },
  "karte.weiter": { de: "Weiter weg", en: "Zoom out" },
  "karte.welt": { de: "Ganze Welt", en: "Whole world" },
  "karte.bedienung": { de: "Ziehen oder Pfeiltasten verschieben, Mausrad, zwei Finger oder Plus/Minus zoomen. Ein Gebiet antippen (oder Enter) zeigt seine Angaben.", en: "Drag or use the arrow keys to pan; mouse wheel, two fingers or plus/minus to zoom. Tap an area (or press Enter) to see its details." },
  "karte.gebiet": { de: "um {lat}° {ns}, {lon}° {ow}", en: "around {lat}° {ns}, {lon}° {ow}" },
  "karte.nord": { de: "N", en: "N" },
  "karte.sued": { de: "S", en: "S" },
  "karte.ost": { de: "O", en: "E" },
  "karte.west": { de: "W", en: "W" },
  "karte.zelle": { de: "{ebene}: {gebiet} – {stufe}", en: "{ebene}: {gebiet} – {stufe}" },
  "karte.schwelle": { de: "Funk und Bluetooth erscheinen erst ab {k} Einträgen je Gebiet, Provider im Netz ab einem – deren Adresse ist ohnehin öffentlich. Die Schwelle schützt nur die Anzeige: Auf den Relays ist jeder Eintrag einzeln sichtbar.", en: "Radio and Bluetooth only appear from {k} entries per area, online providers from one – their address is public anyway. The threshold only protects the display: on the relays every entry is visible individually." },
  // Seit C.4b: eigenes Gebiet, gerundet und nur lokal; Eintragen als Dialog
  "karte.meins": { de: "Mein Gebiet", en: "My area" },
  "karte.eigenesGebiet": { de: "Dein Gebiet (auf 0,5° gerundet) – nur auf diesem Gerät gezeichnet", en: "Your area (rounded to 0.5°) – drawn only on this device" },
  "karte.standortNutzen": { de: "mein Gebiet zeigen", en: "show my area" },
  "karte.standortVergessen": { de: "Gebiet vergessen", en: "forget area" },
  "karte.standortGemerkt": { de: "Gebiet gemerkt – nur auf diesem Gerät, auf 0,5° gerundet, nichts gesendet", en: "Area saved – only on this device, rounded to 0.5°, nothing sent" },
  "karte.standortVergessenOk": { de: "Gebiet vergessen", en: "Area forgotten" },
  "karte.ebene": { de: "Ebene", en: "Layer" },
  "karte.eintragenOk": { de: "Eintragen", en: "Add" },
  "karte.einwilligungTitel": { de: "Öffentlich eintragen?", en: "Add publicly?" },
  "karte.keineZellen": { de: "Noch kein Gebiet über der Schwelle. Eintragen ist freiwillig – es kann trotzdem Abdeckung geben.", en: "No area above the threshold yet. Adding yourself is voluntary – there may be coverage anyway." },
  "pruef.tab": { de: "Prüfung", en: "Checks" },
  "pruef.titel": { de: "Prüfung der Provider", en: "Provider checks" },
  "pruef.text": { de: "Wie zuverlässig Provider antworten – aus deiner eigenen Messung auf diesem Gerät, sobald sie 20 Anfragen hat; bis dahin gilt ein Provider als neu. Danach wählt die App die Provider aus.", en: "How reliably providers answer – from your own measurement on this device once it has 20 requests; until then a provider counts as new. The app picks providers by this." },
  "pruef.laden": { de: "aktualisieren", en: "refresh" },
  "pruef.lade": { de: "lade …", en: "loading …" },
  "pruef.keineProvider": { de: "Keine Provider gefunden.", en: "No providers found." },
  "pruef.zeile": { de: "{provider} · {stand} · {prozent} % beantwortet · {antwort} · {quelle}", en: "{provider} · {stand} · {prozent} % answered · {antwort} · {quelle}" },
  "pruef.zeileOhne": { de: "{provider} · {stand} – noch zu wenig Daten", en: "{provider} · {stand} – not enough data yet" },
  "pruef.antwortSek": { de: "Antwort nach {s} s", en: "answer after {s} s" },
  "pruef.antwortUnbekannt": { de: "Antwortzeit unbekannt", en: "response time unknown" },
  "pruef.quelleEigene": { de: "eigene Messung", en: "own measurement" },
  "pruef.standGeprueft": { de: "geprüft", en: "checked" },
  "pruef.standNeu": { de: "neu", en: "new" },
  "pruef.standHerabgestuft": { de: "herabgestuft", en: "downgraded" },
  "pruef.standAusgefallen": { de: "nur Rückfall", en: "fallback only" },
};
