/** Texte des Kommunikations-Tabs (8.16b): Direktnachrichten, Räume, Moderation. */
import type { Texte } from "../i18n.js";

export const kommunikation: Texte = {
  chatTitle: { de: "Direktnachrichten", en: "Messages" },
  chatPlaceholder: { de: "Nachricht…", en: "Message…" },
  // Seite (index.html)
  "komm.railAria": { de: "Direktnachrichten und Räume", en: "Direct messages and rooms" },
  "komm.raumAnlegen": { de: "Raum anlegen", en: "Create room" },
  "komm.raumBeitreten": { de: "Raum beitreten", en: "Join room" },
  "komm.neueNachricht": { de: "Neue Nachricht", en: "New message" },
  "komm.meshExport": { de: "Post für diesen Kontakt als Datei mitnehmen – nur verschlüsselt, ohne deinen Schlüssel", en: "Take mail for this contact along as a file – encrypted only, without your key" },
  "komm.meshImport": { de: "Mitgebrachte Post einlesen und ans Netz geben – nur Verschlüsseltes", en: "Read in mail brought along and pass it to the network – encrypted only" },
  "komm.neueCommunity": { de: "Neue Community", en: "New community" },
  "komm.suchePh": { de: "Suchen – nur auf diesem Gerät", en: "Search – only on this device" },
  "komm.sucheAria": { de: "Nachrichten durchsuchen – nur auf diesem Gerät", en: "Search messages – only on this device" },
  "komm.zurueckAria": { de: "Zurück zur Liste", en: "Back to the list" },
  "komm.zurueck": { de: "‹ Zurück", en: "‹ Back" },
  "komm.waehle": { de: "Wähl eine Unterhaltung.", en: "Pick a conversation." },
  "komm.dmE2e": { de: "Direktnachrichten sind Ende-zu-Ende verschlüsselt.", en: "Direct messages are end-to-end encrypted." },
  "komm.anhaengen": { de: "Bild, Video oder Datei anhängen (über das Chunk-Netz)", en: "Attach image, video or file (via the chunk network)" },
  "komm.ablaufTitel": { de: "Neue Nachrichten verschwinden nach … (NIP-40). Löschen ist eine Bitte an die Relays.", en: "New messages disappear after … (NIP-40). Deleting is a request to the relays." },
  "komm.ablaufAria": { de: "Ablauf neuer Nachrichten", en: "Expiry of new messages" },
  "komm.ablaufAus": { de: "⏱ aus", en: "⏱ off" },
  "komm.ablauf1h": { de: "⏱ 1 Stunde", en: "⏱ 1 hour" },
  "komm.ablauf1d": { de: "⏱ 1 Tag", en: "⏱ 1 day" },
  "komm.ablauf7d": { de: "⏱ 7 Tage", en: "⏱ 7 days" },
  "komm.ablauf30d": { de: "⏱ 30 Tage", en: "⏱ 30 days" },
  "komm.zapSenden": { de: "Zap senden", en: "Send zap" },
  // Kontakt prüfen (B-4)
  "komm.pruefen": { de: "Kontakt prüfen", en: "Verify contact" },
  "komm.pruefenTitel": { de: "Kontakt prüfen – Sicherheitscode vergleichen", en: "Verify contact – compare the safety code" },
  "komm.pruefTitel": { de: "{name} prüfen", en: "Verify {name}" },
  "komm.pruefText": { de: "Vergleicht diesen Code – vorlesen, am besten persönlich oder am Telefon, oder den QR-Code scannen. Stimmt er, sprecht ihr wirklich miteinander und nicht mit jemandem, der nur so aussieht.", en: "Compare this code – read it out, ideally in person or on the phone, or scan the QR code. If it matches, you are really talking to each other and not to someone who only looks alike." },
  "komm.pruefCode": { de: "Sicherheitscode", en: "Safety code" },
  "komm.pruefQr": { de: "Als QR-Code zeigen", en: "Show as QR code" },
  "komm.pruefEingabe": { de: "Code des Kontakts (scannen oder eintippen; leer lassen, wenn ihr vorgelesen habt)", en: "Your contact's code (scan or type; leave empty if you read it out)" },
  "komm.pruefOk": { de: "Stimmt überein – als geprüft merken", en: "It matches – remember as verified" },
  "komm.pruefFalsch": { de: "Der Code stimmt nicht überein. Ist das der richtige Kontakt? Nicht als geprüft merken.", en: "The code does not match. Is this the right contact? Do not mark as verified." },
  "komm.pruefGemerkt": { de: "{name} ist geprüft.", en: "{name} is verified." },
  "komm.pruefNur11": { de: "Prüfen geht nur in 1:1-Unterhaltungen", en: "Verifying only works in 1:1 conversations" },
  "komm.pruefUnmoeglich": { de: "Für diesen Kontakt lässt sich kein Sicherheitscode bilden.", en: "No safety code can be formed for this contact." },
  "komm.geprueftAm": { de: "✓ geprüft am {datum}", en: "✓ verified on {datum}" },
  "komm.nichtGeprueft": { de: "nicht geprüft", en: "not verified" },
  "komm.keinRaum": { de: "Kein Raum", en: "No room" },
  "komm.rauminfo": { de: "Rauminfo", en: "Room info" },
  "komm.einladen": { de: "einladen", en: "invite" },
  "komm.privatTitel": { de: "Ende-zu-Ende-verschlüsselt (MLS) – nur Eingeladene lesen mit", en: "End-to-end encrypted (MLS) – only invited people can read" },
  "komm.anlegenPrivat": { de: "Raum anlegen (privat)", en: "Create room (private)" },
  "komm.oeffentlichTitel": { de: "Jeder kann mitlesen, auch ohne diese App", en: "Anyone can read along, even without this app" },
  "komm.anlegenOeffentlich": { de: "öffentlichen Raum anlegen", en: "create public room" },
  "komm.moderatoren": { de: "Moderatoren", en: "Moderators" },
  "komm.oeffentlichHinweis": { de: "Öffentlicher Raum – jeder kann mitlesen, auch ohne diese App. Die Nachrichten liegen unverschlüsselt auf den Relays.", en: "Public room – anyone can read along, even without this app. The messages sit unencrypted on the relays." },
  "komm.suchen": { de: "Suchen", en: "Search" },
  "komm.nachricht": { de: "Nachricht", en: "Message" },
  "komm.mitglieder": { de: "Mitglieder", en: "Members" },
  "komm.meldungen": { de: "Meldungen", en: "Reports" },
  // Räume
  "komm.privaterRaum": { de: "privater Raum", en: "private room" },
  "komm.raumNichtVerfuegbar": { de: "privater Raum nicht verfügbar", en: "private room not available" },
  "komm.nichtErreichbar": { de: "nicht erreichbar: {grund}", en: "not reachable: {grund}" },
  "komm.raumNichtGefunden": { de: "Raum nicht gefunden.", en: "Room not found." },
  "komm.kanalVerschluesselt": { de: "verschlüsselt", en: "encrypted" },
  "komm.kanalOffen": { de: "offen — jeder kann mitlesen", en: "open — anyone can read along" },
  "komm.nochNichts": { de: "Noch nichts hier. Fang an.", en: "Nothing here yet. Get started." },
  "komm.eineAntwort": { de: "{n} Antwort", en: "{n} reply" },
  "komm.antworten": { de: "{n} Antworten", en: "{n} replies" },
  "komm.beteiligte": { de: "{n} Beteiligte", en: "{n} participants" },
  "komm.nurRollen": { de: "Hier dürfen nur bestimmte Rollen schreiben. Lesen kannst du alles.", en: "Only certain roles may write here. You can read everything." },
  "komm.loeschen": { de: "löschen", en: "delete" },
  "komm.moderieren": { de: "moderieren", en: "moderate" },
  "komm.melden": { de: "melden", en: "report" },
  "komm.entfernen": { de: "entfernen", en: "remove" },
  "komm.erledigtKnopf": { de: "erledigt", en: "done" },
  "komm.eigeneLoeschen": { de: "Eigene Nachricht löschen? Wer sie schon gelesen hat, hatte sie.", en: "Delete your message? Whoever already read it has seen it." },
  "komm.meldenNotiz": { de: "Kurze Notiz (optional, nur für die Moderatoren):", en: "Short note (optional, only for the moderators):" },
  "komm.gemeldet": { de: "Gemeldet – versiegelt an {n} Moderator(en)", en: "Reported – sealed to {n} moderator(s)" },
  "komm.nichtGemeldet": { de: "Nicht gemeldet – kein Moderator erreichbar", en: "Not reported – no moderator reachable" },
  "komm.erledigt": { de: "Erledigt", en: "Done" },
  "komm.nichtGeaendert": { de: "Nicht geändert – kein Relay der Gruppe nahm an", en: "Not changed – no relay of the group accepted" },
  "komm.meldungVon": { de: "Meldung von {von} über {autor} · {grund}", en: "Report by {von} about {autor} · {grund}" },
  "komm.gruender": { de: "Gründer", en: "Founder" },
  "komm.niemand": { de: "niemand eingetragen", en: "nobody listed" },
  "komm.nichtGesendet": { de: "Nicht gesendet – kein Relay der Gruppe nahm an", en: "Not sent – no relay of the group accepted" },
  "komm.nameOeffentlich": { de: "Name des öffentlichen Raums:", en: "Name of the public room:" },
  "komm.namePrivat": { de: "Name des privaten Raums:", en: "Name of the private room:" },
  "komm.privatAngelegt": { de: "Privater Raum angelegt – Mitglieder über „einladen“ hinzufügen", en: "Private room created – add members via “invite”" },
  "komm.raumAngelegt": { de: "Raum angelegt. Gib diese Adresse weiter – mit ihr zählt nur deine Definition des Raums, niemand kann ihn übernehmen.", en: "Room created. Share this address – with it only your definition of the room counts, nobody can take it over." },
  "komm.raumAdresse": { de: "Raum-Adresse", en: "Room address" },
  "komm.raumAdresseQr": { de: "Als QR-Code zeigen", en: "Show as QR code" },
  "komm.raumEingabe": { de: "Raum-Adresse (beginnt mit 34700:) oder Kennung", en: "Room address (starts with 34700:) or identifier" },
  "komm.raumUngueltig": { de: "Das ist weder eine Raum-Adresse noch eine Kennung.", en: "That is neither a room address nor an identifier." },
  "komm.raumMehrdeutig": { de: "Mehrere behaupten, diesen Raum gegründet zu haben. Frag nach der Raum-Adresse (beginnt mit 34700:) und tritt damit bei.", en: "Several people claim to have founded this room. Ask for the room address (starts with 34700:) and join with it." },
  "komm.oeffentlichWarnung": {
    de: "Öffentlicher Raum: Jeder kann mitlesen, auch ohne diese App – die Nachrichten liegen unverschlüsselt auf den Relays, mit deinem Schlüssel als Absender. Private Räume sind Ende-zu-Ende-verschlüsselt.\n\nTrotzdem öffentlich anlegen?",
    en: "Public room: anyone can read along, even without this app – the messages sit unencrypted on the relays, with your key as the sender. Private rooms are end-to-end encrypted.\n\nCreate it publicly anyway?",
  },
  "komm.einladenSchluessel": { de: "Wen einladen? Schlüssel (hex):", en: "Invite whom? Key (hex):" },
  "komm.keinSchluessel": { de: "Kein gültiger Schlüssel", en: "Not a valid key" },
  "komm.ladeEin": { de: "Lade ein …", en: "Inviting …" },
  "komm.eingeladen": { de: "{name} eingeladen – versiegelt an den Posteingang", en: "{name} invited – sealed to their inbox" },
  "komm.nichtEingeladen": { de: "Nicht eingeladen: {grund}", en: "Not invited: {grund}" },
  "komm.keinRecht": { de: "Dafür fehlt dir das Recht in diesem Raum", en: "You don't have the right to do that in this room" },
  "komm.welcheRolle": { de: "Welche Rolle? (mod / mitglied)", en: "Which role? (mod / mitglied)" },
  "komm.rolleVergeben": { de: "Rolle vergeben", en: "Role granted" },
  "komm.begruendung": { de: "Begründung (wird veröffentlicht):", en: "Reason (will be published):" },
  "komm.ohneBegruendung": { de: "Ohne Begründung nicht — sie gehört zur Maßnahme", en: "Not without a reason — it is part of the action" },
  "komm.ausgeblendet": { de: "Nachricht ausgeblendet", en: "Message hidden" },
  "komm.gesperrt": { de: "Absender gesperrt", en: "Sender blocked" },
  "komm.nurModsErnennen": { de: "Nur Moderatoren ernennen Moderatoren", en: "Only moderators appoint moderators" },
  "komm.modsNebenDir": { de: "{n} Moderator(en) neben dir", en: "{n} moderator(s) besides you" },
  "komm.modsBenannt": { de: "{n} Moderator(en) benannt", en: "{n} moderator(s) named" },
  "komm.moderatorRolle": { de: "Moderator", en: "moderator" },
  "komm.nurGruender": { de: "Nur der Gründer kann Moderatoren benennen", en: "Only the founder can name moderators" },
  "komm.modPubkeys": { de: "Pubkeys der Moderatoren, kommagetrennt:", en: "Moderators' pubkeys, comma-separated:" },
  "komm.regeln": { de: "Regeln dieses Raums (erscheinen bei jedem Mitglied):\nOhne Regeln wirkt Moderation willkürlich.", en: "Rules of this room (shown to every member):\nWithout rules, moderation looks arbitrary." },
  "komm.einladungRaum": { de: "Einladung in einen privaten Raum von {name} – in der Raumleiste", en: "Invitation to a private room from {name} – in the room bar" },
  // Direktnachrichten
  "komm.keinBlossom": { de: "Kein Blossom-Server erreichbar – Datei zu groß für die Nachricht", en: "No Blossom server reachable – file too large for the message" },
  "komm.verschluessele": { de: "{name}: verschlüssele…", en: "{name}: encrypting…" },
  "komm.blossomAusweg": { de: "{name}: über Blossom als Ausweg…", en: "{name}: via Blossom as a fallback…" },
  "komm.lade": { de: "lade…", en: "loading…" },
  "komm.zuWenigStuecke": { de: "Nicht genug Stücke im Netz gefunden", en: "Not enough pieces found in the network" },
  "komm.nichtGespeichert": { de: "Unterhaltungen nicht gespeichert: {grund}", en: "Conversations not saved: {grund}" },
  "komm.keineUnterhaltungen": { de: "Noch keine Unterhaltungen. Mit + beginnst du eine.", en: "No conversations yet. Start one with +." },
  "komm.eigenerName": { de: "Eigener Name für {pk}:", en: "Your own name for {pk}:" },
  "komm.nameVeroeffentlichen": {
    de: "„{name}“ auch veröffentlichen?\n\nDann sehen andere diesen Namen als Hinweis — und erfahren, dass du diese Person kennst. Abbrechen: gilt nur für dich.",
    en: "Also publish “{name}”?\n\nOthers then see this name as a hint — and learn that you know this person. Cancel: applies only to you.",
  },
  "komm.community": { de: "Community — Gruppe auf Zusage.", en: "Community — opt-in group." },
  "komm.nip17": { de: "1:1 — Ende-zu-Ende verschlüsselt (NIP-17). Relays sehen nicht, wer schreibt – nur, dass du Post bekommst.", en: "1:1 — end-to-end encrypted (NIP-17). Relays don't see who writes – only that you receive mail." },
  "komm.mitAblauf": { de: "Mit Ablauf bleibt es bei NIP-17.", en: "With expiry it stays on NIP-17." },
  "komm.mlsNicht": { de: "MLS geht hier nicht: {grund}.", en: "MLS doesn't work here: {grund}." },
  "komm.mlsNichtLesen": { de: "Was dein Kontakt über eure MLS-Gruppe schickt, liest die App erst, wenn MLS hier wieder geht – solange die Relays es halten.", en: "What your contact sends via your MLS group, the app only reads once MLS works here again – as long as the relays keep it." },
  "komm.mlsAn": {
    de: "1:1 — über MLS (Marmot): mit Vorwärtsgeheimnis. Relays sehen nur eine zufällige Gruppen-Id und für jede Nachricht einen neuen Schlüssel. Eure Geräte sind eigene Mitglieder; fehlt einem das KeyPackage, geht die Nachricht per NIP-17, damit jedes Gerät sie bekommt.",
    en: "1:1 — via MLS (Marmot): with forward secrecy. Relays only see a random group id and a new key for every message. Your devices are members of their own; if one lacks a KeyPackage, the message goes via NIP-17 so every device gets it.",
  },
  "komm.mlsKoennen": { de: "Können der Kontakt und eure Geräte MLS, geht deine nächste Nachricht darüber.", en: "If your contact and your devices support MLS, your next message goes that way." },
  "komm.ablaufAn": { de: "Neue Nachrichten laufen ab. Löschen ist eine Bitte an die Relays – wer sie schon hat, behält sie.", en: "New messages expire. Deleting is a request to the relays – whoever already has them keeps them." },
  "komm.ablaufAusToast": { de: "Neue Nachrichten laufen nicht mehr ab.", en: "New messages no longer expire." },
  "komm.entschluesselungFehlgeschlagen": { de: "[Entschlüsselung fehlgeschlagen]", en: "[decryption failed]" },
  "komm.neuerSchluessel": { de: "zum neuen Schlüssel wechseln ({pk})", en: "switch to the new key ({pk})" },
  "komm.alterSchluessel": { de: "(alter Schlüssel) {name}", en: "(old key) {name}" },
  "komm.weiterNeuerSchluessel": { de: "Weiter mit dem neuen Schlüssel {pk} – die alte Unterhaltung bleibt markiert", en: "Continuing with the new key {pk} – the old conversation stays marked" },
  "komm.ausgeblendetMarke": { de: "[ausgeblendet: {grund}]", en: "[hidden: {grund}]" },
  "komm.trotzdemZeigen": { de: "trotzdem zeigen", en: "show anyway" },
  "komm.diebstahlTitel": { de: "nach dem gemeldeten Diebstahl des Schlüssels", en: "after the reported theft of the key" },
  "komm.diebstahl": { de: "· ⚠ vielleicht nicht von dieser Person", en: "· ⚠ maybe not from this person" },
  "komm.altTitel": { de: "ältere Verschlüsselung (Kind 4): Relays sehen Absender und Empfänger", en: "older encryption (kind 4): relays see sender and recipient" },
  "komm.alt": { de: "· alt", en: "· old" },
  "komm.mlsTitel": { de: "MLS (Marmot): Gruppenschlüssel mit Vorwärtsgeheimnis", en: "MLS (Marmot): group key with forward secrecy" },
  "komm.wartetTitel": { de: "Jede Kopie geht mit eigener Zufallsverzögerung hinaus (Settings → Datenschutz)", en: "Each copy goes out with its own random delay (Settings → Privacy)" },
  "komm.wartet": { de: "· wird gesendet", en: "· sending" },
  "komm.du": { de: "du", en: "you" },
  "komm.keineVollmacht": { de: "Dieses Gerät hat keine gültige Vollmacht (mehr) – Settings → Geräte", en: "This device has no valid authorization (anymore) – Settings → Devices" },
  "komm.anfrage": { de: "Anfrage · {pk}", en: "Request · {pk}" },
  "komm.fehler": { de: "Fehler: {grund}", en: "Error: {grund}" },
  "komm.kontaktSchluessel": { de: "Schlüssel des Kontakts (npub oder hex):", en: "Contact's key (npub or hex):" },
  "komm.keinNpub": { de: "Das ist kein gültiger npub.", en: "That is not a valid npub." },
  "komm.npubOderHex": { de: "Bitte einen npub oder einen 64-stelligen Hex-Schlüssel eingeben.", en: "Please enter an npub or a 64-character hex key." },
  "komm.communityName": { de: "Name der Community:", en: "Name of the community:" },
  "komm.anhangFehler": { de: "Anhang: {fehler}", en: "Attachment: {fehler}" },
};
