/** Texte des Profil-Tabs (8.16; vollständig ab 8.16e). */
import type { Texte } from "../i18n.js";

export const profil: Texte = {
  trustLevel: { de: "Vertrauensstufe", en: "Trust level" },
  trustSub: { de: "Schätzung aus dem, was dein Knoten als erledigt meldet. Kunden stufen dich nach ihren eigenen Quittungen und denen ihrer Kontakte ein – Selbstauskünfte zählen dort nicht, bestätigte Reklamationen senken die Stufe.", en: "Estimate from what your node reports as completed. Customers rank you by their own receipts and their contacts' – self-reports don't count there, upheld complaints lower the tier." },
  // Seite (8.16f)
  "profil.teilen": { de: "Teilen", en: "Share" },
  "profil.bearbeiten": { de: "Profil bearbeiten", en: "Edit profile" },
  "profil.name": { de: "Name", en: "Name" },
  "profil.ueberDich": { de: "Über dich", en: "About you" },
  "profil.bild": { de: "Bild", en: "Picture" },
  "profil.bildPh": { de: "freedom-blob:… oder https://…", en: "freedom-blob:… or https://…" },
  "profil.lightningAdresse": { de: "Lightning-Adresse", en: "Lightning address" },
  "profil.lud16Ph": { de: "du@wallet.cash", en: "you@wallet.cash" },
  "profil.farbe": { de: "Farbe", en: "Color" },
  "profil.anordnung": { de: "Anordnung", en: "Layout" },
  "profil.muster": { de: "Muster", en: "Pattern" },
  "profil.speichern": { de: "Profil speichern", en: "Save profile" },
  "profil.classicAb": { de: "classic ab 10 XP", en: "classic from 10 XP" },
  "profil.proAb": { de: "pro ab 50 XP", en: "pro from 50 XP" },
  "profil.stufeClassic": { de: "Classic", en: "Classic" },
  "profil.stufePro": { de: "Pro", en: "Pro" },
  "profil.jobs": { de: "{n} Jobs", en: "{n} jobs" },
  "profil.abzeichen": { de: "Abzeichen", en: "Badges" },
  "profil.abzeichenVergebenKnopf": { de: "Abzeichen vergeben", en: "Award a badge" },
  "profil.identTitel": { de: "Öffentlicher Schlüssel – Klick exportiert den privaten", en: "Public key – click exports the private one" },
  // Stilwerte (die Werte selbst gehen so ins Profil)
  "profil.stilMessing": { de: "Messing", en: "brass" },
  "profil.stilOrange": { de: "Orange", en: "orange" },
  "profil.stilTinte": { de: "Tinte", en: "ink" },
  "profil.stilMoos": { de: "Moos", en: "moss" },
  "profil.stilPflaume": { de: "Pflaume", en: "plum" },
  "profil.stilStahl": { de: "Stahl", en: "steel" },
  "profil.stilSchlicht": { de: "schlicht", en: "plain" },
  "profil.stilKarte": { de: "Karte", en: "card" },
  "profil.stilBreit": { de: "breit", en: "wide" },
  "profil.stilKeines": { de: "keines", en: "none" },
  "profil.stilRaster": { de: "Raster", en: "grid" },
  "profil.stilWellen": { de: "Wellen", en: "waves" },
  "profil.stilVerlauf": { de: "Verlauf", en: "gradient" },
  // tabs/profil.ts
  "profil.abzeichenName": { de: "Name des Abzeichens:", en: "Badge name:" },
  "profil.abzeichenAnWen": { de: "An wen? (Pubkeys, kommagetrennt)", en: "To whom? (pubkeys, comma-separated)" },
  "profil.keinPubkey": { de: "Kein gültiger Pubkey dabei", en: "No valid pubkey included" },
  "profil.abzeichenWofuer": { de: "Wofür? (erscheint bei jedem Träger)", en: "What for? (shown with every holder)" },
  "profil.abzeichenVergeben": { de: "An {n} vergeben – wert so viel wie dein Ruf", en: "Awarded to {n} – worth as much as your reputation" },
  "profil.keineBeschreibung": { de: "Noch keine Beschreibung.", en: "No description yet." },
  "profil.bildNichtVerwendbar": { de: "Bildadresse nicht verwendbar", en: "Picture address not usable" },
  "profil.gespeichert": { de: "Profil gespeichert", en: "Profile saved" },
  "profil.keineAbzeichen": { de: "Noch keine. Verdiente Abzeichen entstehen aus Arbeit im Netz.", en: "None yet. Earned badges come from work in the network." },
  // Sätze des Protokolls (protokoll-texte.ts) – Deutsch wortgleich mit dem Protokoll
  "profil.offenName": { de: "Dein Name ist öffentlich und mit deinem Schlüssel verknüpft.", en: "Your name is public and linked to your key." },
  "profil.offenAbout": { de: "Deine Beschreibung ist öffentlich und bleibt auf den Relays.", en: "Your description is public and stays on the relays." },
  "profil.bildExtern": { de: "Das Bild liegt auf einem fremden Server. Wer es dort ablegt, sieht die IP-Adresse aller, die dein Profil ansehen.", en: "The picture is on someone else's server. Whoever put it there sees the IP address of everyone who views your profile." },
  "profil.offenBildNetz": { de: "Das Bild liegt im eigenen Netz — der Abruf verrät nichts an Dritte.", en: "The picture is in our own network — fetching it reveals nothing to third parties." },
  "profil.offenLud16": { de: "Deine Lightning-Adresse ist öffentlich. Wer sie kennt, kann dir zahlen.", en: "Your Lightning address is public. Whoever knows it can pay you." },
  "profil.offenWebsite": { de: "Die Webseite verknüpft dein Profil mit einer anderen Identität.", en: "The website links your profile to another identity." },
  "profil.offenSolana": { de: "Deine Solana-Adresse ist öffentlich — mitsamt ihrer gesamten Historie.", en: "Your Solana address is public — with its entire history." },
  "profil.offenLeer": { de: "Ein leeres Profil gibt nichts preis. Das ist eine gültige Wahl.", en: "An empty profile reveals nothing. That is a valid choice." },
  "profil.bildAbgelehnt": { de: "Nur Bilder aus dem Netz oder https-Adressen — alles andere wird nicht geladen.", en: "Only pictures from the network or https addresses — everything else is not loaded." },
  "profil.aufgabeZugang": { de: "Zugang gesichert", en: "Access secured" },
  "profil.aufgabeZugangText": { de: "Merkphrase notiert und bestätigt.", en: "Recovery phrase written down and confirmed." },
  "profil.aufgabeWoche": { de: "Eine Woche Provider", en: "One week as provider" },
  "profil.aufgabeWocheText": { de: "An sieben verschiedenen Tagen Jobs erledigt.", en: "Completed jobs on seven different days." },
  "profil.aufgabeMonat": { de: "Ein Monat Provider", en: "One month as provider" },
  "profil.aufgabeMonatText": { de: "An dreißig verschiedenen Tagen Jobs erledigt.", en: "Completed jobs on thirty different days." },
  "profil.aufgabeRelay": { de: "Relay betrieben", en: "Relay operated" },
  "profil.aufgabeRelayText": { de: "Sieben Tage lang einen erreichbaren Relay angekündigt.", en: "Announced a reachable relay for seven days." },
  "profil.aufgabeModell": { de: "Modell gesichert", en: "Model secured" },
  "profil.aufgabeModellText": { de: "Ein gefährdetes Modell vorgehalten, bis es wieder mehrere Seeder hat.", en: "Kept an endangered model available until it has several seeders again." },
  "profil.aufgabeGeworben": { de: "Drei aktive Geworbene", en: "Three active referrals" },
  "profil.aufgabeGeworbenText": { de: "Drei geworbene Provider, die tatsächlich arbeiten.", en: "Three referred providers who actually work." },
  "profil.standGesichert": { de: "Gesichert.", en: "Secured." },
  "profil.standUnbestaetigt": { de: "Noch nicht bestätigt.", en: "Not confirmed yet." },
  "profil.standTage": { de: "{ist} von {soll} Tagen.", en: "{ist} of {soll} days." },
  "profil.standRelay": { de: "{ist} von {soll} Tagen erreichbar.", en: "Reachable on {ist} of {soll} days." },
  "profil.standGeworben": { de: "{ist} von {soll} aktiv.", en: "{ist} of {soll} active." },
  "profil.standOffen": { de: "Noch offen.", en: "Still open." },
  "profil.quelleVerdient": { de: "verdient", en: "earned" },
  "profil.quelleVerliehen": { de: "verliehen", en: "awarded" },
  "profil.quelleSelbst": { de: "selbst", en: "self" },
  "profil.herkunftVerdient": { de: "Nachgerechnet: {basis}", en: "Recalculated: {basis}" },
  "profil.ausEreignissen": { de: "aus Protokoll-Ereignissen", en: "from protocol events" },
  "profil.herkunftVerliehen": { de: "Verliehen von {von}…", en: "Awarded by {von}…" },
  "profil.herkunftSelbst": { de: "Selbst vergeben — sagt nichts über irgendetwas aus.", en: "Self-awarded — says nothing about anything." },
  // Repositories nach NIP-34 (tabs/repos.ts, repo-ansicht.ts)
  "repo.offen": { de: "offen", en: "open" },
  "repo.angenommen": { de: "angenommen ✓", en: "accepted ✓" },
  "repo.geschlossen": { de: "geschlossen", en: "closed" },
  "repo.entwurf": { de: "Entwurf", en: "draft" },
  "repo.annehmen": { de: "annehmen", en: "accept" },
  "repo.schliessen": { de: "schließen", en: "close" },
  "repo.zurueckziehen": { de: "zurückziehen", en: "withdraw" },
  "repo.keineRepos": { de: "Noch keine Repos nach NIP-34 – kündige das erste an.", en: "No NIP-34 repos yet – announce the first one." },
  "repo.relaysWeg": { de: "Relays nicht erreichbar", en: "Relays not reachable" },
  "repo.patchSenden": { de: "Patch senden", en: "Send patch" },
  "repo.keinePatches": { de: "Keine Patches.", en: "No patches." },
  "repo.patchFrage": { de: "Patch „{betreff}“ an {repo} senden?\n\nÖffentlich und mit deinem Schlüssel signiert – wie bei jedem Git-Projekt.", en: "Send patch “{betreff}” to {repo}?\n\nPublic and signed with your key – like in every Git project." },
  "repo.patchGesendet": { de: "Patch gesendet: {betreff}", en: "Patch sent: {betreff}" },
  "repo.welcherCommit": { de: "Als welcher Commit eingespielt? (SHA-1, leer lassen, wenn noch nicht)", en: "Applied as which commit? (SHA-1, leave empty if not yet)" },
  "repo.patchAngenommen": { de: "Patch angenommen", en: "Patch accepted" },
  "repo.patchZurueckgezogen": { de: "Patch zurückgezogen", en: "Patch withdrawn" },
  "repo.patchGeschlossen": { de: "Patch geschlossen", en: "Patch closed" },
  "repo.ankuendigenFrage": { de: "Repo „{id}“ ankündigen?\n\nÖffentlich und mit deinem Schlüssel signiert.", en: "Announce repo “{id}”?\n\nPublic and signed with your key." },
  "repo.angekuendigt": { de: "Repo {id} angekündigt", en: "Repo {id} announced" },
};
