/** Texte der Räume, die seit C.2b neu sind; ältere stehen weiter unter `komm.*` (Schlüssel bleiben). */
import type { Texte } from "../i18n.js";

export const raeume: Texte = {
  "raum.anlegen": { de: "Anlegen", en: "Create" },
  "raum.hierBeitreten": { de: "Diesem Raum beitreten", en: "Join this room" },
  "raum.direktnachricht": { de: "Direktnachricht schreiben", en: "Send direct message" },
  "raum.neu": { de: "Neu", en: "New" },
  "raum.oeffentlichAnlegen": { de: "Öffentlich anlegen", en: "Create publicly" },
  "raum.angelegtTitel": { de: "Raum angelegt", en: "Room created" },
  "raum.einladenTitel": { de: "In den Raum einladen", en: "Invite to the room" },
  "raum.kontakt": { de: "Kontakt", en: "Contact" },
  "raum.oderSchluessel": { de: "… oder ein Schlüssel (hex)", en: "… or a key (hex)" },
  "raum.alleinImRaum": { de: "Außer dir ist noch niemand im Raum – erst einladen", en: "Nobody but you is in the room yet – invite someone first" },
  "raum.werModerator": { de: "Wer soll Moderator sein? Du bleibst es.", en: "Who should be a moderator? You stay one." },
  "raum.moderierenTitel": { de: "Nachricht moderieren", en: "Moderate message" },
  "raum.massnahme": { de: "Maßnahme", en: "Action" },
  "raum.ausblenden": { de: "Nachricht ausblenden", en: "Hide the message" },
  "raum.sperren": { de: "Absender sperren", en: "Block the sender" },
  "raum.fuerAlleLoeschen": { de: "Nachricht für alle löschen", en: "Delete the message for everyone" },
  "raum.ausRaumEntfernen": { de: "Absender aus dem Raum entfernen", en: "Remove the sender from the room" },
  "raum.entfernenHinweis": { de: "neuer Schlüssel für die Gruppe, keine Sperrliste", en: "new key for the group, no block list" },
  "raum.loeschenTitel": { de: "Nachricht löschen", en: "Delete message" },
  "raum.meldenTitel": { de: "Nachricht melden", en: "Report message" },
  "raum.meldenText": { de: "Nur die Moderatoren erfahren es – versiegelt, an jeden einzeln.", en: "Only the moderators learn about it – sealed, to each one separately." },
  "raum.grund": { de: "Grund", en: "Reason" },
  "raum.grundSpam": { de: "Spam", en: "Spam" },
  "raum.grundIllegal": { de: "Illegal", en: "Illegal" },
  "raum.grundNacktheit": { de: "Nacktheit", en: "Nudity" },
  "raum.grundBeleidigung": { de: "Beleidigung, Hass", en: "Profanity, hate" },
  "raum.grundIdentitaet": { de: "Gibt sich als jemand anderes aus", en: "Impersonation" },
  "raum.grundSchadsoftware": { de: "Schadsoftware", en: "Malware" },
  "raum.grundAnderes": { de: "Anderes", en: "Other" },
  "raum.rolleTitel": { de: "Rolle vergeben", en: "Grant a role" },
  // C.2b2: Verlauf, Menüs, Rauminfo
  "raum.ich": { de: "Du", en: "You" },
  "raum.aktionenAria": { de: "Aktionen zur Nachricht", en: "Message actions" },
  "raum.menueAria": { de: "Raum-Menü", en: "Room menu" },
  "raum.zuDenKanaelen": { de: "Zu den Kanälen", en: "To the channels" },
  // C.2c: Antworten und Threads
  "raum.antworten": { de: "Antworten", en: "Reply" },
  "raum.thread": { de: "Thread", en: "Thread" },
  "raum.threadSchliessen": { de: "Thread schließen", en: "Close thread" },
  "raum.imThreadAntworten": { de: "Im Thread antworten", en: "Reply in thread" },
  "raum.antwortAn": { de: "Antwort an {name}", en: "Replying to {name}" },
  "raum.antwortWeg": { de: "Nicht mehr darauf antworten", en: "Stop replying to this" },
  "raum.zitat": { de: "↪ {name}: {text}", en: "↪ {name}: {text}" },
  // C.2d1: Mitglieder
  "raum.mitgliedMenue": { de: "Aktionen für {name}", en: "Actions for {name}" },
  "raum.zumModerator": { de: "Zum Moderator machen", en: "Make moderator" },
  "raum.keinModeratorMehr": { de: "Moderator entfernen", en: "Remove as moderator" },
  "raum.entfernenText": { de: "{name} aus dem Raum entfernen? Die Gruppe bekommt einen neuen Schlüssel – was {name} vorher gelesen hat, bleibt gelesen. Eine Sperrliste gibt es nicht; eine neue Einladung holt {name} zurück.", en: "Remove {name} from the room? The group gets a new key – what {name} read before stays read. There is no block list; a new invitation brings {name} back." },
  "raum.mitgliederMeldungen": { de: "Mitglieder · {n} Meldung(en)", en: "Members · {n} report(s)" },
  "raum.mitgliederSchliessen": { de: "Mitglieder schließen", en: "Close members" },
  // C.2d2: Kanal anlegen
  "raum.kanalAnlegen": { de: "Kanal anlegen", en: "Create channel" },
  "raum.repoAnlegen": { de: "Repo anlegen", en: "Create repo" },
  "raum.repos": { de: "Repos", en: "Repos" },
  "raum.repoOffen": { de: "{name} – offene Patches: {n}", en: "{name} – open patches: {n}" },
  "raum.kanalName": { de: "Name des Kanals", en: "Channel name" },
  "raum.kanalSchreiben": { de: "Wer schreiben darf", en: "Who may write" },
  "raum.nurModsSchreiben": { de: "Nur Moderatoren (alle anderen lesen)", en: "Moderators only (everyone else reads)" },
  "raum.modRechte": { de: "Moderatoren bekommen die Rolle „Moderator“: Nachrichten ausblenden, sperren, Rollen vergeben, Repos pflegen und Kanäle verwalten – jeweils nur gegenüber Niedrigeren. Wer hier fehlt, verliert die Rolle.", en: "Moderators get the “Moderator” role: hide messages, ban, assign roles, maintain repos and manage channels – only towards lower ranks. Anyone missing here loses the role." },
  "raum.kanalAendern": { de: "Diesen Kanal ändern", en: "Edit this channel" },
  "raum.kanalAendernTitel": { de: "Kanal „{name}“ ändern", en: "Edit channel “{name}”" },
  "raum.kanalErstOeffnen": { de: "Erst einen Kanal öffnen", en: "Open a channel first" },
  "raum.kanalEntfernen": { de: "Kanal entfernen", en: "Remove channel" },
  "raum.kanalEntfernenText": { de: "Der Kanal „{name}“ verschwindet für alle. Seine Nachrichten bleiben auf den Relays, die App zeigt sie nicht mehr.", en: "The channel “{name}” disappears for everyone. Its messages stay on the relays; the app no longer shows them." },
  "raum.kanalLetzter": { de: "Der letzte Kanal bleibt – ein Raum braucht einen", en: "The last channel stays – a room needs one" },
  "raum.kanalUeberDir": { de: "In diesen Kanal schreiben nur Höhere – ändern darfst du ihn nicht", en: "Only higher ranks write in this channel – you may not change it" },
  "raum.kanalGeaendert": { de: "Kanal „{name}“ geändert", en: "Channel “{name}” changed" },
  "raum.kanalEntfernt": { de: "Kanal „{name}“ entfernt", en: "Channel “{name}” removed" },
  "raum.kanalAngelegt": { de: "Kanal „{name}“ angelegt", en: "Channel “{name}” created" },
  "raum.infoVerschluesselt": {
    de: "Verschlüsselt (MLS): Nur Mitglieder können mitlesen – alle Kanäle des Raums.\n\nGrenze: Wer entfernt wird, behält den Schlüssel für alles, was er vorher\ngesehen hat. Das Entfernen wechselt den Schlüssel – danach liest er nichts\nmehr. Neue Mitglieder lesen nur, was nach ihrem Eintritt kommt.",
    en: "Encrypted (MLS): only members can read along – all channels of the room.\n\nLimit: whoever is removed keeps the key for everything they saw before. Removing changes the key – after that they read nothing more. New members only read what comes after they joined.",
  },
  // B-19: Moderation in offenen Räumen
  "raum.modAusgeblendet": { de: "🛡 {n} Nachricht(en) von Moderatoren ausgeblendet", en: "🛡 {n} message(s) hidden by moderators" },
  "raum.modAlleSichtbar": { de: "🛡 {n} ausgeblendete Nachricht(en) werden gezeigt", en: "🛡 {n} hidden message(s) are shown" },
  "raum.modAnzeigen": { de: "anzeigen", en: "show" },
  "raum.modWiederAusblenden": { de: "wieder ausblenden", en: "hide again" },
  // B-15b: Umfragen und Termine in privaten Räumen
  "raum.planung": { de: "Umfragen und Termine", en: "Polls and events" },
  "raum.umfrageKnopf": { de: "Umfrage anlegen", en: "Create poll" },
  "raum.terminKnopf": { de: "Termin anlegen", en: "Create event" },
  "raum.umfrageNeu": { de: "Neue Umfrage", en: "New poll" },
  "raum.umfrageSenden": { de: "Umfrage senden", en: "Send poll" },
  "raum.umfrageFrage": { de: "Frage", en: "Question" },
  "raum.umfrageAntworten": { de: "Antworten – eine je Zeile (2 bis 20)", en: "Answers – one per line (2 to 20)" },
  "raum.umfrageArt": { de: "Art", en: "Type" },
  "raum.umfrageMehrfach": { de: "Mehrere Antworten erlaubt", en: "Allow several answers" },
  "raum.umfrageEnde": { de: "Endet", en: "Ends" },
  "raum.umfrageOhneEnde": { de: "nie", en: "never" },
  "raum.umfrageStunden": { de: "nach {n} Std.", en: "after {n} h" },
  "raum.umfrageFehlerFrage": { de: "Die Frage fehlt oder ist zu lang (höchstens 500 Zeichen).", en: "The question is missing or too long (at most 500 characters)." },
  "raum.umfrageFehlerZahl": { de: "Bitte 2 bis 20 Antworten, eine je Zeile.", en: "Please 2 to 20 answers, one per line." },
  "raum.umfrageFehlerLang": { de: "Eine Antwort ist zu lang (höchstens 100 Zeichen).", en: "An answer is too long (at most 100 characters)." },
  "raum.umfrageFehlerDoppelt": { de: "Zwei Antworten sind gleich.", en: "Two answers are the same." },
  "raum.umfrageVon": { de: "📊 Umfrage von {name}", en: "📊 Poll by {name}" },
  "raum.umfrageMehrfachVon": { de: "📊 Umfrage von {name} · mehrere Antworten", en: "📊 Poll by {name} · several answers" },
  "raum.umfrageStimmen": { de: "{n}", en: "{n}" },
  "raum.umfrageTeilnehmer": { de: "{n} abgestimmt", en: "{n} voted" },
  "raum.umfrageEndet": { de: "endet {wann}", en: "ends {wann}" },
  "raum.umfrageBeendet": { de: "beendet {wann}", en: "ended {wann}" },
  "raum.terminNeu": { de: "Neuer Termin", en: "New event" },
  "raum.terminSenden": { de: "Termin senden", en: "Send event" },
  "raum.terminTitel": { de: "Titel", en: "Title" },
  "raum.terminDatum": { de: "Datum", en: "Date" },
  "raum.terminUhrzeit": { de: "Uhrzeit – leer lassen für ganztägig", en: "Time – leave empty for all day" },
  "raum.terminDauer": { de: "Dauer", en: "Duration" },
  "raum.terminMinuten": { de: "{n} Min.", en: "{n} min" },
  "raum.terminOhneEnde": { de: "ohne Ende", en: "no end" },
  "raum.terminOrtFeld": { de: "Ort (freiwillig)", en: "Place (optional)" },
  "raum.terminBeschreibung": { de: "Beschreibung (freiwillig)", en: "Description (optional)" },
  "raum.terminFehlerDatum": { de: "Das Datum stimmt nicht.", en: "The date is not valid." },
  "raum.terminFehlerUhrzeit": { de: "Die Uhrzeit stimmt nicht (SS:MM).", en: "The time is not valid (HH:MM)." },
  "raum.terminFehlerDauer": { de: "Die Dauer stimmt nicht.", en: "The duration is not valid." },
  "raum.terminVon": { de: "📅 Termin von {name}", en: "📅 Event by {name}" },
  "raum.terminOrt": { de: "Ort: {ort}", en: "Place: {ort}" },
  "raum.terminZusagen": { de: "✓ Zusage · {n}", en: "✓ Going · {n}" },
  "raum.terminVielleicht": { de: "? Vielleicht · {n}", en: "? Maybe · {n}" },
  "raum.terminAbsagen": { de: "✗ Absage · {n}", en: "✗ Not going · {n}" },
  "raum.planungLoeschen": { de: "Löschen?", en: "Delete?" },
  "raum.planungLoeschenText": { de: "Für alle Mitglieder löschen? Wer sie schon gesehen hat, hat sie gesehen.", en: "Delete for all members? Whoever has already seen it has seen it." },
  "raum.schreibenAlle": { de: "Wer im Raum schreiben darf", en: "Who may write in this room" },
  "raum.schreibenText": {
    de: "Wie „@everyone“ bei Discord: Mit „Alle, die beitreten“ schreibt jeder in den Kanälen, die nicht auf Rollen beschränkt sind – #ankündigungen bleibt bei den Moderatoren. Moderieren, Rollen vergeben und Kanäle verwalten gibt es weiter nur über eine Rolle; Ausblenden und Sperren wirken wie bisher.",
    en: "Like “@everyone” on Discord: with “Everyone who joins”, anyone writes in the channels that are not limited to roles – #ankündigungen stays with the moderators. Moderating, assigning roles and managing channels still need a role; hiding and banning work as before.",
  },
  "raum.schreibenJeder": { de: "Alle, die beitreten", en: "Everyone who joins" },
  "raum.schreibenRolle": { de: "Nur wer eine Rolle hat (Mitglied, Moderator)", en: "Only those with a role (member, moderator)" },
  "raum.schreibenJederAn": { de: "Jetzt schreiben alle, die beitreten", en: "Everyone who joins can now write" },
  "raum.schreibenJederAus": { de: "Jetzt schreibt nur, wer eine Rolle hat", en: "Now only those with a role can write" },
  "raum.nurMitRolle": { de: "Hier schreibt nur, wer im Raum eine Rolle hat – wer den Raum gegründet hat, kann ihn für alle öffnen. Lesen kannst du alles.", en: "Only those with a role in this room can write here – whoever founded the room can open it to everyone. You can read everything." },
  "raum.infoOffen": {
    de: "Offen: Jeder kann mitlesen, auch ohne diese App.\n\nDie Rechte hier regeln, wer schreiben darf — nicht, wer lesen kann.\nNachrichten liegen unverschlüsselt auf den Relays.",
    en: "Open: anyone can read along, even without this app.\n\nThe rights here govern who may write — not who can read.\nMessages sit unencrypted on the relays.",
  },
};
