/** Texte der Räume, die seit C.2b neu sind; ältere stehen weiter unter `komm.*` (Schlüssel bleiben). */
import type { Texte } from "../i18n.js";

export const raeume: Texte = {
  "raum.anlegen": { de: "Anlegen", en: "Create" },
  "raum.oeffentlichAnlegen": { de: "Öffentlich anlegen", en: "Create publicly" },
  "raum.angelegtTitel": { de: "Raum angelegt", en: "Room created" },
  "raum.einladenTitel": { de: "In den Raum einladen", en: "Invite to the room" },
  "raum.kontakt": { de: "Kontakt", en: "Contact" },
  "raum.oderSchluessel": { de: "… oder ein Schlüssel (hex)", en: "… or a key (hex)" },
  "raum.alleinImRaum": { de: "Außer dir ist noch niemand im Raum – erst einladen", en: "Nobody but you is in the room yet – invite someone first" },
  "raum.werModerator": { de: "Wer soll Moderator sein? Du bleibst es.", en: "Who should be a moderator? You stay one." },
  "raum.moderierenTitel": { de: "Nachricht moderieren", en: "Moderate message" },
  "raum.massnahme": { de: "Maßnahme", en: "Action" },
  "raum.ausblenden": { de: "Nachricht ausblenden", en: "Hide the message" },
  "raum.sperren": { de: "Absender sperren", en: "Block the sender" },
  "raum.fuerAlleLoeschen": { de: "Nachricht für alle löschen", en: "Delete the message for everyone" },
  "raum.ausRaumEntfernen": { de: "Absender aus dem Raum entfernen", en: "Remove the sender from the room" },
  "raum.entfernenHinweis": { de: "neuer Schlüssel für die Gruppe, keine Sperrliste", en: "new key for the group, no block list" },
  "raum.loeschenTitel": { de: "Nachricht löschen", en: "Delete message" },
  "raum.meldenTitel": { de: "Nachricht melden", en: "Report message" },
  "raum.meldenText": { de: "Nur die Moderatoren erfahren es – versiegelt, an jeden einzeln.", en: "Only the moderators learn about it – sealed, to each one separately." },
  "raum.grund": { de: "Grund", en: "Reason" },
  "raum.grundSpam": { de: "Spam", en: "Spam" },
  "raum.grundIllegal": { de: "Illegal", en: "Illegal" },
  "raum.grundNacktheit": { de: "Nacktheit", en: "Nudity" },
  "raum.grundBeleidigung": { de: "Beleidigung, Hass", en: "Profanity, hate" },
  "raum.grundIdentitaet": { de: "Gibt sich als jemand anderes aus", en: "Impersonation" },
  "raum.grundSchadsoftware": { de: "Schadsoftware", en: "Malware" },
  "raum.grundAnderes": { de: "Anderes", en: "Other" },
  "raum.rolleTitel": { de: "Rolle vergeben", en: "Grant a role" },
  // C.2b2: Verlauf, Menüs, Rauminfo
  "raum.ich": { de: "Du", en: "You" },
  "raum.aktionenAria": { de: "Aktionen zur Nachricht", en: "Message actions" },
  "raum.menueAria": { de: "Raum-Menü", en: "Room menu" },
  "raum.zuDenKanaelen": { de: "Zu den Kanälen", en: "To the channels" },
  // C.2c: Antworten und Threads
  "raum.antworten": { de: "Antworten", en: "Reply" },
  "raum.thread": { de: "Thread", en: "Thread" },
  "raum.threadSchliessen": { de: "Thread schließen", en: "Close thread" },
  "raum.imThreadAntworten": { de: "Im Thread antworten", en: "Reply in thread" },
  "raum.antwortAn": { de: "Antwort an {name}", en: "Replying to {name}" },
  "raum.antwortWeg": { de: "Nicht mehr darauf antworten", en: "Stop replying to this" },
  "raum.zitat": { de: "↪ {name}: {text}", en: "↪ {name}: {text}" },
  // C.2d1: Mitglieder
  "raum.mitgliedMenue": { de: "Aktionen für {name}", en: "Actions for {name}" },
  "raum.zumModerator": { de: "Zum Moderator machen", en: "Make moderator" },
  "raum.keinModeratorMehr": { de: "Moderator entfernen", en: "Remove as moderator" },
  "raum.entfernenText": { de: "{name} aus dem Raum entfernen? Die Gruppe bekommt einen neuen Schlüssel – was {name} vorher gelesen hat, bleibt gelesen. Eine Sperrliste gibt es nicht; eine neue Einladung holt {name} zurück.", en: "Remove {name} from the room? The group gets a new key – what {name} read before stays read. There is no block list; a new invitation brings {name} back." },
  "raum.mitgliederMeldungen": { de: "Mitglieder · {n} Meldung(en)", en: "Members · {n} report(s)" },
  "raum.mitgliederSchliessen": { de: "Mitglieder schließen", en: "Close members" },
  // C.2d2: Kanal anlegen
  "raum.kanalAnlegen": { de: "Kanal anlegen", en: "Create channel" },
  "raum.kanalName": { de: "Name des Kanals", en: "Channel name" },
  "raum.kanalSchreiben": { de: "Wer schreiben darf", en: "Who may write" },
  "raum.nurModsSchreiben": { de: "Nur Moderatoren (alle anderen lesen)", en: "Moderators only (everyone else reads)" },
  "raum.kanalAngelegt": { de: "Kanal „{name}“ angelegt", en: "Channel “{name}” created" },
  "raum.infoVerschluesselt": {
    de: "Verschlüsselt (MLS): Nur Mitglieder können mitlesen – alle Kanäle des Raums.\n\nGrenze: Wer entfernt wird, behält den Schlüssel für alles, was er vorher\ngesehen hat. Das Entfernen wechselt den Schlüssel – danach liest er nichts\nmehr. Neue Mitglieder lesen nur, was nach ihrem Eintritt kommt.",
    en: "Encrypted (MLS): only members can read along – all channels of the room.\n\nLimit: whoever is removed keeps the key for everything they saw before. Removing changes the key – after that they read nothing more. New members only read what comes after they joined.",
  },
  "raum.infoOffen": {
    de: "Offen: Jeder kann mitlesen, auch ohne diese App.\n\nDie Rechte hier regeln, wer schreiben darf — nicht, wer lesen kann.\nNachrichten liegen unverschlüsselt auf den Relays.",
    en: "Open: anyone can read along, even without this app.\n\nThe rights here govern who may write — not who can read.\nMessages sit unencrypted on the relays.",
  },
};
