/** Texte der Seite „Repos“, die seit C.3a neu sind; ältere stehen weiter unter `repo.*` in `profil.ts` und `agent.*`. */
import type { Texte } from "../i18n.js";

export const repos: Texte = {
  "repo.suchen": { de: "Repos durchsuchen", en: "Search repos" },
  "repo.filterAria": { de: "Welche Repos", en: "Which repos" },
  "repo.alle": { de: "Alle", en: "All" },
  "repo.meine": { de: "Meine", en: "Mine" },
  "repo.nichtsGefunden": { de: "Kein Repo passt zur Suche.", en: "No repo matches the search." },
  "repo.markeBundle": { de: "Bundle", en: "Bundle" },
  "repo.karteFuss": { de: "Offene Patches: {n} · zuletzt {datum}", en: "Open patches: {n} · last {datum}" },
  "repo.beschreibung": { de: "Beschreibung (optional)", en: "Description (optional)" },
  "repo.alleRepos": { de: "‹ Alle Repos", en: "‹ All repos" },
  "repo.maintainer": { de: "Maintainer: {namen}", en: "Maintainers: {namen}" },
  "repo.nurBundle": { de: "Nur ein Bundle, keine Ankündigung nach NIP-34 – Patches gehen erst, wenn der Eigentümer das Repo ankündigt.", en: "Only a bundle, no NIP-34 announcement – patches only work once the owner announces the repo." },
  "repo.klonenTitel": { de: "Klonen", en: "Clone" },
  "repo.klonZeile": { de: "git clone {adresse}", en: "git clone {adresse}" },
  "repo.klonBefehl": { de: "Befehl zum Klonen", en: "Clone command" },
  "repo.bundleStand": { de: "Bundle vom {datum}", en: "Bundle from {datum}" },
  "repo.bundleLaden": { de: "Bundle laden", en: "Download bundle" },
  "repo.keineKlonAdresse": { de: "Keine Klon-Adresse und kein Bundle angegeben.", en: "No clone address and no bundle given." },
  "repo.code": { de: "Code", en: "Code" },
  "repo.patchesZahl": { de: "Patches ({n} offen)", en: "Patches ({n} open)" },
  "repo.codeMitBundle": { de: "Dateien und Commits zeigt die App noch nicht selbst. Lade das Bundle und öffne es mit git: git clone repo.bundle", en: "The app does not show files and commits itself yet. Download the bundle and open it with git: git clone repo.bundle" },
  "repo.codeOhneBundle": { de: "Dateien und Commits zeigt die App noch nicht selbst – klone das Repo mit einer der Adressen oben.", en: "The app does not show files and commits itself yet – clone the repo with one of the addresses above." },
  "repo.filterZahl": { de: "{status} ({n})", en: "{status} ({n})" },
  "repo.patchVon": { de: "von {name} · {datum}", en: "by {name} · {datum}" },
  "repo.annehmenTitel": { de: "„{betreff}“ annehmen", en: "Accept “{betreff}”" },
  "repo.keinSha1": { de: "Ein Commit ist ein SHA-1 mit 40 Zeichen (0–9, a–f)", en: "A commit is a SHA-1 with 40 characters (0–9, a–f)" },
  // Seit C.3a2: Mitwirkende und Einstellungen des Eigentümers
  "repo.einstellungen": { de: "Einstellungen", en: "Settings" },
  "repo.mitwirkendeKennung": { de: "Beiträge nennen nur die Kennung „{id}“, nicht den Eigentümer – gleichnamige Repos anderer zählen mit.", en: "Contributions only name the ID “{id}”, not the owner – other people's repos with the same ID count too." },
  "repo.kennungFest": { de: "Kennung: {id} – sie bleibt; eine andere wäre ein neues Repo.", en: "ID: {id} – it stays; a different one would be a new repo." },
  "repo.feldKlon": { de: "Klon-Adressen (https://…, ssh://…, rad:…), eine je Zeile", en: "Clone addresses (https://…, ssh://…, rad:…), one per line" },
  "repo.feldWeb": { de: "Web-Adressen, eine je Zeile (anklickbar nur mit https)", en: "Web addresses, one per line (clickable only with https)" },
  "repo.feldMaintainer": { de: "Maintainer: Schlüssel (64 Zeichen hex), einer je Zeile – sie dürfen Patches annehmen", en: "Maintainers: keys (64 hex characters), one per line – they may accept patches" },
  "repo.feldErsterCommit": { de: "Erster Commit (SHA-1, optional – verbindet Forks)", en: "First commit (SHA-1, optional – links forks)" },
  "repo.speichern": { de: "Ankündigung veröffentlichen", en: "Publish announcement" },
  "repo.speichernFrage": { de: "Die neue Ankündigung ersetzt die bisherige – öffentlich und mit deinem Schlüssel signiert.", en: "The new announcement replaces the previous one – public and signed with your key." },
  "repo.neueVersion": { de: "Neue Version hochladen", en: "Upload new version" },
  "repo.neueVersionText": { de: "Ein Bundle aus git bundle create repo.bundle --all. Es geht verschlüsselt ins Speichernetz; der Schlüssel steht öffentlich in der Referenz – lesen kann jeder, Speicherknoten halten nur Chiffrat.", en: "A bundle from git bundle create repo.bundle --all. It goes encrypted into the storage network; the key is public in the reference – anyone can read it, storage nodes only hold ciphertext." },
  // Seit C.3b1: Patch-Seite mit Änderungen, Vorschau vor dem Senden
  "repo.allePatches": { de: "‹ Alle Patches", en: "‹ All patches" },
  "repo.commitKurz": { de: "Commit {sha}", en: "Commit {sha}" },
  "repo.autorLautPatch": { de: "Autor laut Patch: {autor}", en: "Author per patch: {autor}" },
  "repo.alsDatei": { de: "Als Datei laden", en: "Download as file" },
  "repo.aenderungen": { de: "Änderungen", en: "Changes" },
  "repo.aenderungenZahl": { de: "Dateien: {dateien} · +{plus} −{minus}", en: "Files: {dateien} · +{plus} −{minus}" },
  "repo.diffGekuerzt": { de: "Sehr groß – hier gekürzt. „Als Datei laden“ enthält alles.", en: "Very large – shortened here. “Download as file” has everything." },
  "repo.dateiNeu": { de: "neu", en: "new" },
  "repo.dateiGeloescht": { de: "gelöscht", en: "deleted" },
  "repo.dateiUmbenannt": { de: "umbenannt", en: "renamed" },
  "repo.dateiBinaer": { de: "Binärdatei – hier nicht angezeigt", en: "Binary file – not shown here" },
  "repo.vorschau": { de: "Vorschau", en: "Preview" },
  "repo.verwerfen": { de: "Verwerfen", en: "Discard" },
};
