/** Texte der Seite „Repos“, die seit C.3a neu sind; ältere stehen weiter unter `repo.*` in `profil.ts` und `agent.*`. */
import type { Texte } from "../i18n.js";

export const repos: Texte = {
  "repo.suchen": { de: "Repos durchsuchen", en: "Search repos" },
  "repo.filterAria": { de: "Welche Repos", en: "Which repos" },
  "repo.alle": { de: "Alle", en: "All" },
  "repo.meine": { de: "Meine", en: "Mine" },
  "repo.nichtsGefunden": { de: "Kein Repo passt zur Suche.", en: "No repo matches the search." },
  "repo.markeBundle": { de: "Bundle", en: "Bundle" },
  "repo.karteFuss": { de: "Offene Patches: {n} · zuletzt {datum}", en: "Open patches: {n} · last {datum}" },
  "repo.beschreibung": { de: "Beschreibung (optional)", en: "Description (optional)" },
  "repo.alleRepos": { de: "‹ Alle Repos", en: "‹ All repos" },
  "repo.maintainer": { de: "Maintainer: {namen}", en: "Maintainers: {namen}" },
  "repo.nurBundle": { de: "Nur ein Bundle, keine Ankündigung nach NIP-34 – Patches gehen erst, wenn der Eigentümer das Repo ankündigt.", en: "Only a bundle, no NIP-34 announcement – patches only work once the owner announces the repo." },
  "repo.klonenTitel": { de: "Klonen", en: "Clone" },
  "repo.klonZeile": { de: "git clone {adresse}", en: "git clone {adresse}" },
  "repo.klonBefehl": { de: "Befehl zum Klonen", en: "Clone command" },
  "repo.bundleStand": { de: "Bundle vom {datum}", en: "Bundle from {datum}" },
  "repo.bundleLaden": { de: "Bundle laden", en: "Download bundle" },
  "repo.keineKlonAdresse": { de: "Keine Klon-Adresse und kein Bundle angegeben.", en: "No clone address and no bundle given." },
  "repo.code": { de: "Code", en: "Code" },
  "repo.patchesZahl": { de: "Patches ({n} offen)", en: "Patches ({n} open)" },
  "repo.codeOhneBundle": { de: "Ohne Bundle kann die App die Dateien nicht zeigen – klone das Repo mit einer der Adressen oben.", en: "Without a bundle the app cannot show the files – clone the repo with one of the addresses above." },
  "repo.filterZahl": { de: "{status} ({n})", en: "{status} ({n})" },
  "repo.patchVon": { de: "von {name} · {datum}", en: "by {name} · {datum}" },
  "repo.annehmenTitel": { de: "„{betreff}“ annehmen", en: "Accept “{betreff}”" },
  "repo.keinSha1": { de: "Ein Commit ist ein SHA-1 mit 40 Zeichen (0–9, a–f)", en: "A commit is a SHA-1 with 40 characters (0–9, a–f)" },
  // Seit C.3a2: Mitwirkende und Einstellungen des Eigentümers
  "repo.einstellungen": { de: "Einstellungen", en: "Settings" },
  "repo.mitwirkendeKennung": { de: "Beiträge nennen nur die Kennung „{id}“, nicht den Eigentümer – gleichnamige Repos anderer zählen mit.", en: "Contributions only name the ID “{id}”, not the owner – other people's repos with the same ID count too." },
  "repo.kennungFest": { de: "Kennung: {id} – sie bleibt; eine andere wäre ein neues Repo.", en: "ID: {id} – it stays; a different one would be a new repo." },
  "repo.feldKlon": { de: "Klon-Adressen (https://…, ssh://…, rad:…), eine je Zeile", en: "Clone addresses (https://…, ssh://…, rad:…), one per line" },
  "repo.feldWeb": { de: "Web-Adressen, eine je Zeile (anklickbar nur mit https)", en: "Web addresses, one per line (clickable only with https)" },
  "repo.feldMaintainer": { de: "Maintainer: Schlüssel (64 Zeichen hex), einer je Zeile – sie dürfen Patches annehmen", en: "Maintainers: keys (64 hex characters), one per line – they may accept patches" },
  "repo.markePrivat": { de: "privater Raum", en: "private room" },
  "repo.markeRaum": { de: "Raum: {name}", en: "Room: {name}" },
  "repo.issuesZahl": { de: "Issues ({n} offen)", en: "Issues ({n} open)" },
  "repo.neuesIssue": { de: "Neues Issue", en: "New issue" },
  "repo.issueAnlegen": { de: "Issue anlegen", en: "Create issue" },
  "repo.issueTitel": { de: "Titel", en: "Title" },
  "repo.issueText": { de: "Beschreibung", en: "Description" },
  "repo.issueLabels": { de: "Labels, durch Komma getrennt", en: "Labels, separated by commas" },
  "repo.issueHinweis": { de: "Öffentlich und mit deinem Schlüssel signiert – jeder kann das Issue lesen.", en: "Public and signed with your key – anyone can read the issue." },
  "repo.issueHinweisRaum": { de: "Nur im privaten Raum – verschlüsselt (MLS), nur Mitglieder lesen das Issue.", en: "Only in the private room – encrypted (MLS), only members read the issue." },
  "repo.issueAngelegt": { de: "Issue „{titel}“ angelegt", en: "Issue “{titel}” created" },
  "repo.issueOffen": { de: "offen", en: "open" },
  "repo.issueErledigt": { de: "erledigt ✓", en: "completed ✓" },
  "repo.issueGeschlossen": { de: "geschlossen", en: "closed" },
  "repo.keineIssues": { de: "Keine Issues.", en: "No issues." },
  "repo.alleIssues": { de: "‹ Alle Issues", en: "‹ All issues" },
  "repo.issueOhneText": { de: "Keine Beschreibung.", en: "No description." },
  "repo.kommentare": { de: "Kommentare", en: "Comments" },
  "repo.kommentareZahl": { de: "Kommentare: {n}", en: "Comments: {n}" },
  "repo.keineKommentare": { de: "Noch keine Kommentare.", en: "No comments yet." },
  "repo.kommentarSchreiben": { de: "Kommentar schreiben", en: "Write a comment" },
  "repo.kommentieren": { de: "Kommentieren", en: "Comment" },
  "repo.kommentarHinweis": { de: "Öffentlich und mit deinem Schlüssel signiert – jeder kann den Kommentar lesen.", en: "Public and signed with your key – anyone can read the comment." },
  "repo.kommentarHinweisRaum": { de: "Nur im privaten Raum – verschlüsselt (MLS), nur Mitglieder lesen den Kommentar.", en: "Only in the private room – encrypted (MLS), only members read the comment." },
  "repo.kommentarGesendet": { de: "Kommentar gesendet", en: "Comment sent" },
  "repo.issueSchliessenErledigt": { de: "Als erledigt schließen", en: "Close as completed" },
  "repo.issueSchliessenNichtGeplant": { de: "Als nicht geplant schließen", en: "Close as not planned" },
  "repo.issueWiederOeffnen": { de: "Wieder öffnen", en: "Reopen" },
  "repo.issueErledigtGemeldet": { de: "Issue als erledigt geschlossen", en: "Issue closed as completed" },
  "repo.issueGeschlossenGemeldet": { de: "Issue geschlossen", en: "Issue closed" },
  "repo.issueWiederOffenGemeldet": { de: "Issue wieder geöffnet", en: "Issue reopened" },
  "repo.imRaum": { de: "Im öffentlichen Raum „{name}“ – wer dort Repos pflegt, pflegt es mit.", en: "In the public room “{name}” – whoever maintains repos there maintains it too." },
  "repo.imPrivatenRaum": { de: "Im privaten Raum „{name}“ – nur Mitglieder sehen es, verschlüsselt (MLS).", en: "In the private room “{name}” – only members see it, encrypted (MLS)." },
  "repo.raumUnbestaetigt": { de: "Verweist auf einen Raum, gehört aber nicht dazu: Der Eigentümer pflegt dort keine Repos.", en: "Refers to a room but does not belong to it: the owner does not maintain repos there." },
  "repo.zumRaum": { de: "Zum Raum", en: "Go to room" },
  "repo.ankuendigenFrageOeffentlich": { de: "Repo „{id}“ im öffentlichen Raum „{raum}“ ankündigen?\n\nÖffentlich und mit deinem Schlüssel signiert. Wer im Raum Repos pflegt, pflegt es mit.", en: "Announce repo “{id}” in the public room “{raum}”?\n\nPublic and signed with your key. Whoever maintains repos in the room maintains it too." },
  "repo.wo": { de: "Wo", en: "Where" },
  "repo.woOeffentlich": { de: "öffentlich – jeder liest mit", en: "public – anyone can read" },
  "repo.privaterRaum": { de: "privater Raum", en: "private room" },
  "repo.nichtInRaum": { de: "Nicht in den Raum gesendet – der private Raum ist gerade nicht erreichbar. Nichts ging offen hinaus.", en: "Not sent to the room – the private room is not reachable right now. Nothing went out in the open." },
  "repo.statusImRaum": { de: "Nur im privaten Raum – verschlüsselt (MLS), nur Mitglieder sehen es.", en: "Only in the private room – encrypted (MLS), only members see it." },
  "repo.speichernFrageRaum": { de: "Die neue Ankündigung ersetzt die bisherige – nur im privaten Raum, verschlüsselt (MLS).", en: "The new announcement replaces the previous one – only in the private room, encrypted (MLS)." },
  "repo.neueVersionTextRaum": { de: "Ein Bundle aus git bundle create repo.bundle --all. Es geht verschlüsselt ins Speichernetz; den Schlüssel bekommen nur die Mitglieder des privaten Raums.", en: "A bundle from git bundle create repo.bundle --all. It goes encrypted into the storage network; only members of the private room get the key." },
  "repo.ladeVerschluesseltHoch": { de: "lade {name} verschlüsselt hoch ({kb} KB)…", en: "uploading {name} encrypted ({kb} KB)…" },
  "repo.bundleImRaum": { de: "{name}: neue Version im privaten Raum ({blob}…)", en: "{name}: new version in the private room ({blob}…)" },
  "repo.feldRaum": { de: "Öffentlicher Raum", en: "Public room" },
  "repo.keinRaum": { de: "kein Raum", en: "no room" },
  "repo.bisherigerRaum": { de: "bisheriger Raum", en: "current room" },
  "repo.raumHinweis": { de: "Gehört das Repo zu einem Raum, pflegen es alle mit dem Raum-Recht „Repos pflegen“ mit: Patches annehmen, als Entwurf markieren, schließen. Zur Auswahl stehen Räume, in denen du dieses Recht hast.", en: "If the repo belongs to a room, everyone with the room right “maintain repos” maintains it too: accept, mark as draft, close patches. You can choose rooms where you have this right." },
  "repo.feldErsterCommit": { de: "Erster Commit (SHA-1, optional – verbindet Forks)", en: "First commit (SHA-1, optional – links forks)" },
  "repo.speichern": { de: "Ankündigung veröffentlichen", en: "Publish announcement" },
  "repo.speichernFrage": { de: "Die neue Ankündigung ersetzt die bisherige – öffentlich und mit deinem Schlüssel signiert.", en: "The new announcement replaces the previous one – public and signed with your key." },
  "repo.neueVersion": { de: "Neue Version hochladen", en: "Upload new version" },
  "repo.neueVersionText": { de: "Ein Bundle aus git bundle create repo.bundle --all. Es geht verschlüsselt ins Speichernetz; der Schlüssel steht öffentlich in der Referenz – lesen kann jeder, Speicherknoten halten nur Chiffrat.", en: "A bundle from git bundle create repo.bundle --all. It goes encrypted into the storage network; the key is public in the reference – anyone can read it, storage nodes only hold ciphertext." },
  // Seit C.3b1: Patch-Seite mit Änderungen, Vorschau vor dem Senden
  "repo.allePatches": { de: "‹ Alle Patches", en: "‹ All patches" },
  "repo.commitKurz": { de: "Commit {sha}", en: "Commit {sha}" },
  "repo.autorLautPatch": { de: "Autor laut Patch: {autor}", en: "Author per patch: {autor}" },
  "repo.alsDatei": { de: "Als Datei laden", en: "Download as file" },
  "repo.aenderungen": { de: "Änderungen", en: "Changes" },
  "repo.aenderungenZahl": { de: "Dateien: {dateien} · +{plus} −{minus}", en: "Files: {dateien} · +{plus} −{minus}" },
  "repo.diffGekuerzt": { de: "Sehr groß – hier gekürzt. „Als Datei laden“ enthält alles.", en: "Very large – shortened here. “Download as file” has everything." },
  "repo.dateiNeu": { de: "neu", en: "new" },
  "repo.dateiGeloescht": { de: "gelöscht", en: "deleted" },
  "repo.dateiUmbenannt": { de: "umbenannt", en: "renamed" },
  "repo.dateiBinaer": { de: "Binärdatei – hier nicht angezeigt", en: "Binary file – not shown here" },
  "repo.vorschau": { de: "Vorschau", en: "Preview" },
  "repo.verwerfen": { de: "Verwerfen", en: "Discard" },
  // Seit C.3b2: Status mit Begründung, wieder öffnen, Entwurf
  "repo.alsEntwurf": { de: "als Entwurf", en: "mark as draft" },
  "repo.wiederOeffnen": { de: "wieder öffnen", en: "reopen" },
  "repo.patchEntwurf": { de: "Patch als Entwurf markiert", en: "Patch marked as draft" },
  "repo.patchWiederOffen": { de: "Patch wieder offen", en: "Patch reopened" },
  "repo.aktionTitel": { de: "„{betreff}“: {aktion}", en: "“{betreff}”: {aktion}" },
  "repo.statusOeffentlich": { de: "Öffentlich und mit deinem Schlüssel signiert – wie bei jedem Git-Projekt.", en: "Public and signed with your key – like in every Git project." },
  "repo.begruendung": { de: "Begründung (optional, öffentlich)", en: "Reason (optional, public)" },
  "repo.statusVon": { de: "{status} von {name} · {datum}", en: "{status} by {name} · {datum}" },
  "repo.alsCommits": { de: "Eingespielt als {commits}", en: "Applied as {commits}" },
  // Seit C.3c1: Bundle in der App lesen
  "repo.codeLaden": { de: "Code laden", en: "Load code" },
  "repo.codeLadenText": { de: "Das Bundle kommt verschlüsselt aus dem Speichernetz; die App liest es nur hier auf dem Gerät.", en: "The bundle comes encrypted from the storage network; the app reads it only here on the device." },
  "repo.commitZeile": { de: "{betreff} · {autor} · {datum} · {sha}", en: "{betreff} · {autor} · {datum} · {sha}" },
  "repo.keinKopf": { de: "Kein Commit, auf den HEAD zeigt – das Bundle setzt Commits voraus, die es nicht enthält.", en: "No commit that HEAD points to – the bundle requires commits it does not contain." },
  "repo.bundleFormat": { de: "Kein Git-Bundle – Kopf oder Pack passen nicht.", en: "Not a Git bundle – header or pack do not fit." },
  "repo.bundleGross": { de: "Zu groß für die App (Bundle höchstens 32 MB, je Datei 16 MB).", en: "Too large for the app (bundle at most 32 MB, 16 MB per file)." },
  "repo.bundleObjekte": { de: "Zu viele Objekte für die App (höchstens 10 000).", en: "Too many objects for the app (at most 10,000)." },
  "repo.bundleEntpacken": { de: "Ein Objekt im Bundle lässt sich nicht entpacken.", en: "An object in the bundle cannot be unpacked." },
  "repo.bundleDelta": { de: "Ein Delta im Bundle passt nicht zu seiner Basis.", en: "A delta in the bundle does not fit its base." },
  "repo.bundleTiefe": { de: "Delta-Ketten im Bundle sind zu tief.", en: "Delta chains in the bundle are too deep." },
  "repo.bundlePruefsumme": { de: "Die Prüfsumme des Bundles stimmt nicht – beschädigt?", en: "The bundle checksum does not match – damaged?" },
  "repo.bundleKaputt": { de: "Das Bundle ist beschädigt.", en: "The bundle is damaged." },
  // Seit C.3c2: Ordner, Dateien, Commits
  "repo.commits": { de: "Commits", en: "Commits" },
  "repo.pfadAria": { de: "Pfad im Repo", en: "Path in the repo" },
  "repo.pfadFehlt": { de: "Diesen Pfad gibt es im Bundle nicht.", en: "This path does not exist in the bundle." },
  "repo.submodul": { de: "{name} → Submodul {sha}", en: "{name} → submodule {sha}" },
  "repo.dateiGroesse": { de: "{bytes} Bytes", en: "{bytes} bytes" },
  "repo.linkZiel": { de: "Verweis auf {ziel}", en: "Link to {ziel}" },
  "repo.dateiGekuerzt": { de: "Sehr groß – hier gekürzt. „Bundle laden“ enthält alles.", en: "Very large – shortened here. “Download bundle” has everything." },
  "repo.commitMeta": { de: "{autor} · {datum} · {sha}", en: "{autor} · {datum} · {sha}" },
  "repo.commitsMehr": { de: "Die ersten {n} – ältere stehen im Bundle.", en: "The first {n} – older ones are in the bundle." },
  "repo.keineCommits": { de: "Ohne Bundle kennt die App keine Commits – und noch kein angenommener Patch nennt einen.", en: "Without a bundle the app knows no commits – and no accepted patch names one yet." },
  "repo.commitsOhneBundle": { de: "Ohne Bundle: die angenommenen Patches mit den Commits, als die sie eingespielt wurden.", en: "Without a bundle: the accepted patches with the commits they were applied as." },
  "repo.patchAlsCommit": { de: "{betreff} → {commits}", en: "{betreff} → {commits}" },
  "repo.mdBild": { de: "Bild: {alt} (nicht geladen)", en: "Image: {alt} (not loaded)" },
  "repo.mdErledigt": { de: "erledigt", en: "done" },
  "repo.mdOffen": { de: "offen", en: "open" },
  "repo.mdVorschau": { de: "Vorschau", en: "Preview" },
  "repo.mdQuelltext": { de: "Quelltext", en: "Code" },
  "repo.refWahl": { de: "Zweig oder Tag", en: "Branch or tag" },
  "repo.refKopf": { de: "HEAD", en: "HEAD" },
  "repo.zweige": { de: "Zweige", en: "Branches" },
  "repo.tags": { de: "Tags", en: "Tags" },
  "repo.refZahl": { de: "Zweige: {zweige} · Tags: {tags}", en: "Branches: {zweige} · Tags: {tags}" },
  "repo.verlauf": { de: "Verlauf", en: "History" },
  "repo.verlaufLeer": { de: "Kein Commit in diesem Bundle ändert die Datei.", en: "No commit in this bundle changes the file." },
  "repo.verlaufAbgeschnitten": { de: "Ältere Änderungen liegen nicht im Bundle.", en: "Older changes are not in the bundle." },
  "repo.aenderungNeu": { de: "neu", en: "added" },
  "repo.aenderungGeaendert": { de: "geändert", en: "changed" },
  "repo.aenderungGeloescht": { de: "gelöscht", en: "deleted" },
  "repo.sucheLabel": { de: "Im Code suchen", en: "Search the code" },
  "repo.sucheKnopf": { de: "Suchen", en: "Search" },
  "repo.sucheTreffer": { de: "Treffer: {n}", en: "Results: {n}" },
  "repo.sucheKeine": { de: "Keine Treffer für „{text}“.", en: "No results for “{text}”." },
  "repo.sucheKurz": { de: "Bitte mindestens zwei Zeichen.", en: "Please enter at least two characters." },
  "repo.sucheMehr": { de: "Mehr als {n} Treffer – bitte genauer suchen.", en: "More than {n} results – please narrow the search." },
  "repo.sucheOrt": { de: "{pfad}:{nr}", en: "{pfad}:{nr}" },
  "repo.sucheDateiname": { de: "Dateiname", en: "File name" },
  "repo.labelFilter": { de: "Nach Label filtern", en: "Filter by label" },
  "repo.alleLabels": { de: "Alle Labels", en: "All labels" },
  "repo.labelZahl": { de: "{label} ({n})", en: "{label} ({n})" },
  "repo.labelZeigen": { de: "Issues mit Label „{label}“ zeigen", en: "Show issues labelled “{label}”" },
  "repo.neu": { de: "Neu", en: "New" },
  "repo.markeNeu": { de: "{n} neu", en: "{n} new" },
  "repo.neuDetails": { de: "Seit deinem letzten Blick: Issues {issues}, Patches {patches}, Kommentare {kommentare}", en: "Since you last looked: issues {issues}, patches {patches}, comments {kommentare}" },
  "repo.nichtsNeues": { de: "Nichts Neues in Repos, an denen du beteiligt bist.", en: "Nothing new in repos you take part in." },
};
