/** Texte des Settings-Tabs (8.16f): Seite und tabs/settings.ts. */
import type { Texte } from "../i18n.js";

export const settings: Texte = {
  // Seite (index.html)
  "set.titel": { de: "Settings", en: "Settings" },
  "set.tabSicherheit": { de: "Sicherheit", en: "Security" },
  "set.tabGeraete": { de: "Geräte", en: "Devices" },
  "set.tabVerbindung": { de: "Verbindung", en: "Connection" },
  "set.tabDatenschutz": { de: "Datenschutz", en: "Privacy" },
  "set.tabGebuehren": { de: "Gebühren", en: "Fees" },
  "set.tabMesh": { de: "Mesh", en: "Mesh" },
  "set.tabWeitergeben": { de: "Weitergeben", en: "Share" },
  "set.lead": { de: "Zwei der fünf Schritte gehen nur vorher.", en: "Two of the five steps only work beforehand." },
  "set.schritt1": { de: "Merkphrase gesichert", en: "Recovery phrase secured" },
  "set.schritt1Text": { de: "Zwölf Wörter, beim ersten Start bestätigt.", en: "Twelve words, confirmed at first start." },
  "set.schritt2": { de: "Zustand gesichert", en: "State backed up" },
  "set.schritt2Text": { de: "Unterhaltungen, Räume und Namen, verschlüsselt.", en: "Conversations, rooms and names, encrypted." },
  "set.schritt3": { de: "Diebstahl vorbeugen", en: "Prevent theft" },
  "set.schritt3Text": { de: "Ein Ersatzschlüssel, getrennt aufbewahrt. Nur vorher einrichtbar.", en: "A spare key, kept separately. Can only be set up beforehand." },
  "set.schritt4": { de: "Nachfolge", en: "Succession" },
  "set.schritt4Text": { de: "Vertraute stellen deinen Zugang wieder her.", en: "Trusted people restore your access." },
  "set.schritt5": { de: "Tresor", en: "Vault" },
  "set.schritt5Text": { de: "Schlüssel, Wallet-Zugänge und Unterhaltungen mit einer Passphrase verschlüsselt, beim Start entsperren.", en: "Keys, wallet access and conversations encrypted with a passphrase, unlocked at start." },
  "set.einrichten": { de: "Einrichten", en: "Set up" },
  "set.details": { de: "Details", en: "Details" },
  "set.tresorText": { de: "Sperrt nach Minuten ohne Eingabe – nie, während ein Tausch, ein Deposit oder ein Auftrag läuft. 0 = nie.", en: "Locks after minutes without input – never while a swap, a deposit or a job is running. 0 = never." },
  "set.tresorMinutenAria": { de: "Minuten bis zur Sperre", en: "Minutes until lock" },
  "set.minuten": { de: "Minuten", en: "minutes" },
  "set.jetztSperren": { de: "jetzt sperren", en: "lock now" },
  "set.sicherungTitel": { de: "Sicherung & Schlüsselwechsel", en: "Backup & key rotation" },
  "set.jetztSichern": { de: "jetzt sichern", en: "back up now" },
  "set.wiederherstellen": { de: "wiederherstellen", en: "restore" },
  "set.widerrufen": { de: "Schlüssel widerrufen", en: "Revoke key" },
  "set.nachfolgeTitel": { de: "Nachfolge & Wiederherstellung", en: "Succession & recovery" },
  "set.nachfolgeText": { de: "Vertraute können deinen Zugang wiederherstellen, wenn du dein Gerät verlierst oder nicht mehr da bist. Jeder bekommt einen Teil deines Schlüssels versiegelt; zusammensetzen lässt die App erst nach einer Frist, und ein Lebenszeichen von dir bricht den Vorgang ab. Wer deine Vertrauten sind, steht öffentlich im Plan.", en: "Trusted people can restore your access if you lose your device or are no longer around. Each gets a part of your key, sealed; the app only lets them combine it after a waiting period, and a sign of life from you aborts the process. Who your trusted people are is public in the plan." },
  "set.einrichtenKlein": { de: "einrichten", en: "set up" },
  "set.lebenszeichen": { de: "Lebenszeichen senden", en: "Send sign of life" },
  "set.melden": { de: "für jemanden melden", en: "report for someone" },
  "set.notfallTitel": { de: "Notfall-Löschung", en: "Emergency wipe" },
  "set.notfallText": { de: "Löscht alles, was die App auf diesem Gerät hat – Schlüssel, Tresor, Unterhaltungen, Suchindex, Wallet-Zugänge – und prüft nach. Was auf Relays liegt, bleibt dort. Ohne Merkphrase gibt es kein Zurück. Vorher steht ein rechtlicher Hinweis.", en: "Deletes everything the app has on this device – keys, vault, conversations, search index, wallet access – and verifies it. What is on relays stays there. Without the recovery phrase there is no way back. A legal notice comes first." },
  "set.notfallKnopf": { de: "alles auf diesem Gerät löschen …", en: "delete everything on this device …" },
  "set.geraeteTitel": { de: "Verbundene Geräte", en: "Connected devices" },
  "set.geraetHinzufuegen": { de: "Gerät hinzufügen", en: "Add device" },
  // B-8c: Mein Knoten
  "set.knotenTitel": { de: "Mein Knoten", en: "My node" },
  "set.knotenText": { de: "Den eigenen Provider-Knoten koppeln: den Code aus „npm run koppeln“ scannen oder einfügen. Anfragen an ihn rechnet er dann gratis – erkannt nur an einem Nachweis im versiegelten Auftrag.", en: "Pair your own provider node: scan or paste the code from “npm run koppeln”. It then answers your requests for free – recognised only by a proof inside the sealed request." },
  "set.knotenKoppeln": { de: "Mein Knoten koppeln", en: "Pair my node" },
  "set.knotenNeu": { de: "neu koppeln", en: "pair again" },
  "set.knotenEntkoppeln": { de: "entkoppeln", en: "unpair" },
  "set.knotenKoppelnText": { de: "Der Code ist ein Schlüssel: Er liegt nur auf diesem Gerät, mit Tresor im Tresor, nie in der Sicherung.", en: "The code is a key: it stays on this device only, inside the vault if you have one, never in the backup." },
  "set.knotenCode": { de: "Kopplungscode (freedom-kopplung:1:…)", en: "Pairing code (freedom-kopplung:1:…)" },
  "set.knotenCodeFalsch": { de: "Kein Kopplungscode – er beginnt mit freedom-kopplung:1:", en: "Not a pairing code – it starts with freedom-kopplung:1:" },
  "set.knotenErsetzen": { de: "Dieses Gerät ist mit dem Knoten {knoten} gekoppelt. Ersetzen?", en: "This device is paired with node {knoten}. Replace it?" },
  "set.knotenGekoppelt": { de: "Gekoppelt mit {knoten}", en: "Paired with {knoten}" },
  "set.knotenGekoppeltToast": { de: "Knoten gekoppelt", en: "Node paired" },
  "set.knotenHalten": { de: "Meine Dateien bei meinem Knoten halten – nach jedem Hochladen (Repo-Bundles, Anhänge) bittet die App ihn versiegelt, die verschlüsselten Stücke dauerhaft zu behalten", en: "Keep my files on my node – after every upload (repo bundles, attachments) the app asks it, sealed, to keep the encrypted pieces for good" },
  "set.knotenHaltenAlle": { de: "Mein Knoten hält die Datei ({n} Stücke)", en: "My node keeps the file ({n} pieces)" },
  "set.knotenHaltenTeil": { de: "Mein Knoten hält nur {n} von {m} Stücken – sein Speicher ist voll, oder die Relays lieferten nicht alle", en: "My node keeps only {n} of {m} pieces – its storage is full, or the relays did not deliver all of them" },
  "set.knotenHaltenKeins": { de: "Mein Knoten hält die Datei nicht (0 von {m} Stücken) – er fand sie auf seinen Relays nicht", en: "My node does not keep the file (0 of {m} pieces) – it did not find it on its relays" },
  "set.knotenHaltenSchweigt": { de: "Mein Knoten antwortet nicht – die Datei liegt nur im Netz", en: "My node does not answer – the file is only on the network" },
  "set.knotenHaltenAbgelehnt": { de: "Mein Knoten hält die Datei nicht: {grund}", en: "My node does not keep the file: {grund}" },
  "set.knotenHaltenFehler": { de: "Halten bei meinem Knoten gescheitert: {fehler}", en: "Keeping on my node failed: {fehler}" },
  "set.knotenNicht": { de: "Nicht gekoppelt", en: "Not paired" },
  "set.knotenEntkoppelnText": { de: "Den Code auf diesem Gerät vergessen? Für alle Geräte ungültig wird er erst mit „npm run koppeln -- --neu“ am Knoten.", en: "Forget the code on this device? It becomes invalid for all devices only with “npm run koppeln -- --neu” on the node." },
  "set.bunkerTitel": { de: "Anmelden per Bunker (NIP-46)", en: "Sign in with a bunker (NIP-46)" },
  "set.bunkerText": { de: "Dein Schlüssel bleibt in einem Signer, z. B. Amber oder nsecBunker; die App fragt jede Unterschrift dort an. Ohne den Schlüssel selbst gehen nicht: Sicherungsdatei, Schlüssel-Export, Zustandssicherung, Nachfolge und abgeleitete Swap-Adressen – der Datenexport geht.", en: "Your key stays in a signer, e.g. Amber or nsecBunker; the app requests every signature there. Without the key itself these don't work: backup file, key export, state backup, succession and derived swap addresses – the data export works." },
  "set.bunkerAria": { de: "bunker://-Adresse", en: "bunker:// address" },
  "set.verbinden": { de: "verbinden", en: "connect" },
  "set.abmelden": { de: "abmelden", en: "sign out" },
  "set.endpunkteTitel": { de: "Eigene Endpunkte", en: "Own endpoints" },
  "set.endpunkteText": { de: "Eigene Solana-Endpunkte, kommagetrennt. Sie werden zuerst benutzt; fällt einer aus, nimmt die App den nächsten. Voreingestellt sind vier Anbieter verschiedener Betreiber. Ab und zu fragt die App einen zweiten Anbieter nach demselben (Netz, letzter Blockhash, ein Kontostand) und warnt, wenn die Antworten sich widersprechen.", en: "Your own Solana endpoints, comma-separated. They are used first; if one fails, the app takes the next. Preset are four providers from different operators. Now and then the app asks a second provider the same thing (network, latest blockhash, a balance) and warns if the answers contradict each other." },
  "set.endpunktePh": { de: "https://mein-knoten.example, https://…", en: "https://my-node.example, https://…" },
  "set.erreichbarkeit": { de: "erreichbarkeit prüfen", en: "check reachability" },
  "set.relaysTitel": { de: "Nostr-Relays (dein Satz)", en: "Nostr relays (your set)" },
  "set.relaysText": { de: "Hier veröffentlichst du (NIP-65), und hier liegt dein Posteingang (Kind 10050): Kontakte lesen dort, was du schreibst, und stellen dir dort Nachrichten zu. Dazu liest die App bei den Relays deiner Kontakte und je Sitzung bei ein paar wechselnden der Startliste. Eine Adresse je Zeile, nur wss:// (unverschlüsselt nur .onion), höchstens acht. Nach dem Veröffentlichen gilt der Satz für alle deine Geräte; wer noch die alte Liste kennt, schreibt bis zum Nachladen an die alten Relays.", en: "This is where you publish (NIP-65) and where your inbox is (kind 10050): contacts read there what you write and deliver messages to you there. In addition the app reads from your contacts' relays and, per session, from a few changing ones from the start list. One address per line, only wss:// (unencrypted only .onion), at most eight. After publishing, the set applies to all your devices; whoever still knows the old list writes to the old relays until they reload." },
  "set.relaysAria": { de: "Eigene Relays, eine Adresse je Zeile", en: "Your relays, one address per line" },
  "set.veroeffentlichen": { de: "veröffentlichen", en: "publish" },
  "set.zugangTitel": { de: "Relay-Zugang kaufen", en: "Buy relay access" },
  "set.zugangText": { de: "Manche Relays nehmen Post nur für Zahlende an und geben deine Umschläge nur an dich heraus, wenn du dich anmeldest (NIP-42). Die App meldet sich nur bei deinen eigenen Relays und bei Relays mit gekauftem Zugang an – nur, wenn der Relay es verlangt. Kaufen verrät dem Betreiber deinen Schlüssel und deine IP-Adresse; mit SOL auch deine Absenderadresse, und auf der Kette sieht jeder, dass sie diesen Relay bezahlt hat. Mit Sats sieht der Betreiber nur die Zahlung.", en: "Some relays only accept posts from paying users and only hand out your envelopes to you when you sign in (NIP-42). The app only signs in to your own relays and to relays with purchased access – and only if the relay asks. Buying reveals your key and your IP address to the operator; with SOL also your sender address, and on the chain everyone sees that it paid this relay. With sats the operator only sees the payment." },
  "set.zugangAria": { de: "Relay-Adresse", en: "Relay address" },
  "set.preisAbfragen": { de: "Preis abfragen", en: "Get price" },
  "set.mitSats": { de: "mit Sats kaufen", en: "buy with sats" },
  "set.mitSol": { de: "mit SOL kaufen", en: "buy with SOL" },
  "set.zahlungPruefen": { de: "Zahlung erneut prüfen", en: "Check payment again" },
  "set.sichtbarTitel": { de: "Was sichtbar ist", en: "What is visible" },
  "set.sichtbarText": { de: "Was in deiner Einstellung für andere sichtbar ist.", en: "What others can see with your settings." },
  "set.verbindungLabel": { de: "Verbindung", en: "Connection" },
  "set.netzKlar": { de: "direkt (Relays sehen deine IP)", en: "direct (relays see your IP)" },
  "set.netzTor": { de: ".onion-Relays bevorzugen (nur im Tor Browser wirksam)", en: "prefer .onion relays (only effective in Tor Browser)" },
  "set.netzMixnet": { de: "Mixnetz (nur wirksam, wenn du selbst eines nutzt)", en: "mixnet (only effective if you use one yourself)" },
  "set.onionText": { de: "Ob deine IP-Adresse verborgen ist, prüft die App, wenn du diesen Bericht öffnest: Erreicht sie ein .onion-Relay, läuft dein Browser über Tor. Sie versucht bis zu drei .onion-Relays, die sie kennt, höchstens 10 Sekunden.", en: "Whether your IP address is hidden is checked when you open this report: if the app reaches an .onion relay, your browser runs over Tor. It tries up to three .onion relays it knows, for at most 10 seconds." },
  "set.erneutPruefen": { de: "erneut prüfen", en: "check again" },
  "set.onionLabel": { de: ".onion-Relay zum Prüfen (optional – nur für diese Prüfung)", en: ".onion relay to check (optional – only for this check)" },
  "set.kontakteSichern": { de: "Kontakte verschlüsselt zwischen Geräten abgleichen (NIP-51)", en: "Sync contacts encrypted between devices (NIP-51)" },
  "set.kontakteText": { de: "Standard: aus. Die Liste liegt verschlüsselt auf den Relays – sie sehen, dass es sie gibt, nicht, wen sie enthält.", en: "Default: off. The list is stored encrypted on the relays – they see that it exists, not whom it contains." },
  "set.rufTeilen": { de: "Meine Erfahrung mit Providern versiegelt mit Kontakten teilen", en: "Share my experience with providers sealed with contacts" },
  "set.rufTeilenText": { de: "Standard: aus. Deine Kontakte erfahren, bei welchen Providern du wie viele Antworten bezahlt hast, in welchem Umfang und mit wie vielen bestätigten Reklamationen – ihre App reiht Provider danach, wie deine es mit ihren Zusammenfassungen tut. Jeder Kontakt bekommt einen eigenen Umschlag an seinen Posteingang, einer nach dem anderen im Abruftakt; Relays sehen nur, dass Kontakte Post bekommen. Als Gerät einer Person teilt die App nicht.", en: "Default: off. Your contacts learn with which providers you paid how many answers, how much and with how many upheld complaints – their app ranks providers by it, as yours does with their summaries. Each contact gets an envelope of their own at their inbox, one after the other with the fetch cycle; relays only see that contacts get mail. As a person's device the app doesn't share." },
  "set.rufStand": { de: "Geteilt mit {geteilt} Kontakten · Zusammenfassungen von {erhalten} Kontakten.", en: "Shared with {geteilt} contacts · summaries from {erhalten} contacts." },
  "set.rufAn": { de: "Deine Zusammenfassung geht nach und nach an deine Kontakte.", en: "Your summary goes to your contacts bit by bit." },
  "set.rufAus": { de: "Geteilt wird nichts mehr. Was schon hinausging, behalten deine Kontakte.", en: "Nothing is shared any more. What already went out, your contacts keep." },
  "set.verzoegerungLabel": { de: "Direktnachrichten verzögert senden", en: "Send direct messages delayed" },
  "set.verzoegerung0": { de: "aus – sofort", en: "off – immediately" },
  "set.verzoegerung5": { de: "bis 5 Sekunden", en: "up to 5 seconds" },
  "set.verzoegerung30": { de: "bis 30 Sekunden (Standard)", en: "up to 30 seconds (default)" },
  "set.verzoegerung120": { de: "bis 2 Minuten", en: "up to 2 minutes" },
  "set.verzoegerungText": { de: "Jede Kopie einer Nachricht (an den Empfänger, an dich, an deine Geräte) geht mit eigener Zufallsverzögerung hinaus – so sieht ein Relay nicht am gleichen Zeitpunkt, wer mit wem schreibt. Die Nachricht steht sofort in deinem Verlauf; verlässt du die Seite, geht Wartendes sofort hinaus. Deine IP-Adresse verbirgt das nicht.", en: "Every copy of a message (to the recipient, to you, to your devices) goes out with its own random delay – so a relay can't tell from the same moment who writes to whom. The message is in your history immediately; if you leave the page, anything waiting goes out immediately. This doesn't hide your IP address." },
  "set.mlsTitel": { de: "Gruppenverschlüsselung (MLS)", en: "Group encryption (MLS)" },
  "set.mlsText": { de: "Eingebaut (MLS nach Marmot), nur mit Tresor: 1:1-Nachrichten gehen darüber, wenn der Kontakt es kann – eure Geräte sind eigene Mitglieder. Sonst, mit Ablauf, mit Bunker, ohne Tresor oder wenn einem Gerät das KeyPackage fehlt, weiter über NIP-17. Der Selbsttest lädt die Engine in diesem Browser und spielt ohne Netz eine Gruppe mit zwei Wegwerf-Identitäten durch.", en: "Built in (MLS following Marmot), only with the vault: 1:1 messages go over it if the contact supports it – your devices are members of their own. Otherwise – with expiry, with a bunker, without a vault or if a device lacks a KeyPackage – messages continue over NIP-17. The self-test loads the engine in this browser and runs a group with two throwaway identities without a network." },
  "set.selbsttest": { de: "Selbsttest", en: "Self-test" },
  "set.aufteilungTitel": { de: "Aufteilung", en: "Split" },
  "set.aufteilungText": { de: "Jede KI-Zahlung ist fest aufgeteilt: 94 % Provider, 2,5 % Entwicklung, 1,5 % Relays, je 0,5 % für deinen Werber und den des Providers, 1 % Hosting. Kein Topf: Die App zahlt jeden Anteil selbst an seinen Empfänger – der Provider stellt nur seinen in Rechnung.", en: "Every AI payment is split in fixed shares: 94% provider, 2.5% development, 1.5% relays, 0.5% each for your referrer and the provider's, 1% hosting. No pool: the app pays each share itself to its recipient – the provider only invoices its own." },
  "set.aufteilungDetails": { de: "Fehlt ein Empfänger mit Lightning-Adresse, bekommt den Anteil der Provider – nie die Entwicklung. Heute gehen die weiteren Anteile an die Werber beider Seiten, wenn die App sie kennt (Angebot des Providers, dein Werbelink), und an bis zu drei Relays deines Pools, deren Betreiber per Selbstauskunft (NIP-11) und Profil eine Lightning-Adresse nennt, sowie an den Spiegel, von dem die App geladen wurde, wenn er eine Zahladresse nennt (Datei freedom-spiegel.json). Die Entwicklung hat noch keine eigene Adresse. Anteile unter 100 sats je Empfänger sammelt die App; bis dahin bleibt das Geld bei dir. SOL-Aufträge gehen ganz an den Provider, bis der Zahlkanal aufteilt. Ändern lässt sich die Aufteilung nur mit einem signierten Release. Beim Holen einer Rechnung sieht der Server hinter der Lightning-Adresse deine IP-Adresse und den Betrag – wie bei jedem Zap.", en: "If a recipient with a Lightning address is missing, the provider gets the share – never development. Today the other shares go to the referrers of both sides if the app knows them (provider's offer, your referral link), to up to three relays of your pool whose operator names a Lightning address via self-description (NIP-11) and profile, and to the mirror the app was loaded from if it names a payment address (file freedom-spiegel.json). Development has no address of its own yet. The app collects shares below 100 sats per recipient; until then the money stays with you. SOL jobs go entirely to the provider until the payment channel splits. The split can only be changed with a signed release. When fetching an invoice, the server behind the Lightning address sees your IP address and the amount – as with every zap." },
  "set.faelligeZahlen": { de: "Fällige jetzt zahlen", en: "Pay due shares now" },
  "set.zahlenTitel": { de: "Zahlen", en: "Payments" },
  "set.standardSchiene": { de: "Standard-Schiene", en: "Default rail" },
  "set.schieneText": { de: "Vorgabe für Zaps und Trinkgeld – bei jeder Zahlung änderbar. Die App zahlt nie still in der anderen Währung.", en: "Default for zaps and tips – changeable with every payment. The app never silently pays in the other currency." },
  "set.ohneInternet": { de: "Ohne Internet", en: "Without internet" },
  "set.meshText": { de: "Verschlüsselte Nachrichten über Funk oder per Datei, wenn das Netz weg ist – nur Umschläge, ohne deinen Schlüssel und ohne Klartext. Funk sendet höchstens 1 % der Zeit (EU 868 MHz): drei bis vier kurze Nachrichten je Stunde. SOL mit vorbereitetem Nonce-Konto (Wallet-Tab); empfangene SOL-Zahlungen reicht die App ein, sobald sie Netz hat. Lightning geht so nicht; KI nur kurz über ein Funk-Gateway (unten).", en: "Encrypted messages over radio or as a file when the network is down – only envelopes, without your key and without plaintext. Radio sends at most 1% of the time (EU 868 MHz): three to four short messages per hour. SOL with a prepared nonce account (wallet tab); the app submits received SOL payments as soon as it has a network. Lightning doesn't work this way; AI only briefly via a radio gateway (below)." },
  "set.funkGateway": { de: "KI über Funk", en: "AI via radio" },
  "set.funkGatewayText": { de: "Ohne Internet fragst du die KI über dein Funkgerät und ein Gateway – einen Knoten mit Netz und Funkgerät. Das Gateway sieht nur Umschläge: weder Frage noch Antwort noch wer du bist. Kurz: höchstens 500 Zeichen, rund zwei Antworten je Stunde und Gateway (1 % Sendezeit). Bezahlt nur über einen Zahlkanal zu diesem Provider oder gratis – Lightning braucht Netz. Wähle das Gateway, solange du Netz hast; die Antwort kommt nur an, solange die App offen bleibt.", en: "Without internet you ask the AI via your radio and a gateway – a node with network and radio. The gateway only sees envelopes: neither question nor answer nor who you are. Short: at most 500 characters, about two answers per hour and gateway (1% airtime). Paid only through a payment channel to this provider, or free – Lightning needs a network. Choose the gateway while you are online; the answer only arrives while the app stays open." },
  "set.funkGatewaySuchen": { de: "Gateways suchen", en: "Find gateways" },
  "set.funkGatewayVergessen": { de: "vergessen", en: "forget" },
  "set.funkGatewayKeins": { de: "Kein Gateway gemerkt.", en: "No gateway saved." },
  "set.funkGatewayGemerkt": { de: "Gemerkt: {pk}, Angebot vom {datum}.", en: "Saved: {pk}, offer from {datum}." },
  "set.funkGatewayNurGratis": { de: " Ohne SOL-Kurs – über Funk nur gratis.", en: " No SOL rate – via radio only free." },
  "set.funkGatewaySuche": { de: "suche …", en: "searching …" },
  "set.funkGatewayKeineGefunden": { de: "Kein Provider bietet gerade ein Funk-Gateway an.", en: "No provider currently offers a radio gateway." },
  "set.funkGatewayWahl": { de: "{pk} merken", en: "save {pk}" },
  "set.funkGatewayGespeichert": { de: "Gateway gemerkt.", en: "Gateway saved." },
  "set.funkGatewayUngeeignet": { de: "Dieses Angebot taugt nicht als Gateway (verlangt zu viel Rechenarbeit).", en: "This offer is not usable as a gateway (demands too much proof of work)." },
  "set.usbGeraet": { de: "USB-Gerät", en: "USB device" },
  "set.alsDatei": { de: "als Datei ausgeben", en: "export as file" },
  "set.dateiEinlesen": { de: "Datei einlesen", en: "Import file" },
  "set.wasOffline": { de: "Was geht ohne Internet?", en: "What works without internet?" },
  "set.warteschlange": { de: "Warteschlange", en: "Queue" },
  "set.nichtsZuSenden": { de: "nichts zu senden", en: "nothing to send" },
  "set.alsDateiTitel": { de: "Als Datei", en: "As a file" },
  "set.weitergebenText": { de: "Die App ist eine einzige Datei. Du kannst sie exportieren und weitergeben; ihre Echtheit lässt sich gegen das signierte Manifest prüfen.", en: "The app is a single file. You can export and share it; its authenticity can be checked against the signed manifest." },
  "set.appExportieren": { de: "App exportieren", en: "Export app" },
  "set.echtheitPruefen": { de: "eigene Echtheit prüfen", en: "check own authenticity" },
  "set.sprache": { de: "Sprache", en: "Language" },
  // tabs/settings.ts
  "set.nurHaupt": { de: "{was} geht nur mit der Hauptidentität, nicht auf einem Gerät", en: "{was} only works with the main identity, not on a device" },
  "set.wasNachfolge": { de: "Nachfolge einrichten", en: "Setting up succession" },
  "set.wasWechsel": { de: "Den Schlüsselwechsel vorbereiten", en: "Preparing key rotation" },
  "set.wasGeraete": { de: "Geräte hinzufügen", en: "Adding devices" },
  "set.nfNicht": { de: "Nicht eingerichtet. Ohne Nachfolge ist dein Zugang bei Geräteverlust endgültig weg.", en: "Not set up. Without succession your access is gone for good if you lose your device." },
  "set.nfPlan": { de: "{schwelle} von {von} Vertrauten, Frist {frist} Tage, Wartezeit {warte} Tage.", en: "{schwelle} of {von} trusted people, inactivity period {frist} days, waiting time {warte} days." },
  // Dialoge statt prompt()/confirm() (C-1c)
  "set.nachfolgeDialog": { de: "Nachfolge einrichten", en: "Set up succession" },
  "set.vertrauteText": { de: "Mindestens 3 Personen, die sich NICHT kennen und FreedomStack nutzen.", en: "At least 3 people who do NOT know each other and use FreedomStack." },
  "set.vertrauteKontakte": { de: "Aus deinen Kontakten", en: "From your contacts" },
  "set.weitereSchluessel": { de: "Weitere Schlüssel (npub oder hex), durch Komma oder je Zeile", en: "More keys (npub or hex), separated by commas or one per line" },
  "set.vertrauteSchluessel": { de: "Schlüssel der Vertrauten (npub oder hex), durch Komma oder je Zeile", en: "Keys of your trusted people (npub or hex), separated by commas or one per line" },
  "set.weiter": { de: "Weiter", en: "Continue" },
  "set.nachfolgeEinrichten": { de: "Einrichten", en: "Set up" },
  "set.ersatzErzeugen": { de: "Ersatzschlüssel erzeugen", en: "Create spare key" },
  "set.widerrufenKnopf": { de: "Widerrufen", en: "Revoke" },
  "set.entziehenTitel": { de: "Vollmacht entziehen", en: "Revoke the authorization" },
  "set.entziehenKnopf": { de: "Entziehen", en: "Revoke" },
  "set.meldenKnopf": { de: "Melden", en: "Report" },
  "set.neueVersionTitel": { de: "Neue Version", en: "New version" },
  "set.uebernehmen": { de: "Übernehmen", en: "Adopt" },
  "set.kaufen": { de: "Kaufen", en: "Buy" },
  "set.mindestensDrei": { de: "Mindestens drei Vertraute – bei weniger ist eine Absprache zu leicht", en: "At least three trusted people – with fewer, collusion is too easy" },
  "set.fuerNachfolge": { de: "Die Nachfolge", en: "Succession" },
  "set.fuerSicherung": { de: "Die Sicherung", en: "The backup" },
  "set.fuerWiederherstellung": { de: "Die Wiederherstellung", en: "Restoring" },
  "set.nfEingerichtet": { de: "Eingerichtet – {n} Vertraute haben ihren Teil versiegelt bekommen.", en: "Set up – {n} trusted people received their part, sealed." },
  "set.mitBunkerNicht": { de: "Mit Bunker nicht möglich – das braucht den Schlüssel selbst", en: "Not possible with a bunker – this needs the key itself" },
  "set.keineSicherung": { de: "Keine Sicherung gefunden", en: "No backup found" },
  // Zusammenführen statt überschreiben (B-5)
  "set.zusammenfuehren": { de: "Unterhaltungen, Räume, Namen, Lesestände, Kataloge und geprüfte Kontakte werden zusammengeführt – was nur auf diesem Gerät steht, bleibt. Sprache, Profil und Einstellungen werden übernommen.", en: "Conversations, rooms, names, read positions, catalogues and verified contacts are merged – what exists only on this device stays. Language, profile and settings are taken over." },
  "set.zusammenErhalten": { de: "{n} Einträge von diesem Gerät bleiben erhalten.", en: "{n} entries from this device are kept." },
  "set.zusammenKonflikte": { de: "{n} Namen stehen auf beiden Seiten verschieden – dort gilt der eingelesene.", en: "{n} names differ on both sides – the imported one wins there." },
  "set.zusammenfuehrenOk": { de: "Zusammenführen", en: "Merge" },
  "set.wiederhergestellt": { de: "Wiederhergestellt – die Seite wird neu geladen", en: "Restored – the page reloads" },
  // Datenexport (B-6)
  "set.exportDatei": { de: "als Datei exportieren", en: "export as a file" },
  "set.exportEinlesen": { de: "Datei einlesen", en: "import a file" },
  "set.exportTitel": { de: "Alles als Datei exportieren", en: "Export everything as a file" },
  "set.exportText": { de: "Unterhaltungen, Räume, Namen, Profil, Einstellungen, geprüfte Kontakte, KI-Verläufe und Quittungen – verschlüsselt mit einer Passphrase, die du hier wählst. Nie drin: dein Schlüssel, Wallet- und Relay-Zugänge, Geld-Geheimnisse, Teile der Nachfolge, Gruppenschlüssel. Die Datei bleibt, wo du sie ablegst.", en: "Conversations, rooms, names, profile, settings, verified contacts, AI histories and receipts – encrypted with a passphrase you choose here. Never included: your key, wallet and relay access, money secrets, succession shares, group keys. The file stays wherever you put it." },
  "set.exportPass": { de: "Passphrase für die Datei", en: "Passphrase for the file" },
  "set.exportPass2": { de: "Passphrase wiederholen", en: "Repeat passphrase" },
  "set.exportPassUngleich": { de: "Die beiden Passphrasen sind verschieden.", en: "The two passphrases differ." },
  "set.exportOk": { de: "Datei erstellen", en: "Create file" },
  "set.exportFertig": { de: "Export erstellt: {n} Einträge, verschlüsselt", en: "Export created: {n} entries, encrypted" },
  "set.exportZuGross": { de: "Die Datei ist zu groß für einen Export.", en: "The file is too large for an export." },
  "set.exportUngueltig": { de: "Das ist keine Export-Datei von FreedomStack.", en: "This is not a FreedomStack export file." },
  "set.einlesenTitel": { de: "Export einlesen", en: "Import an export" },
  "set.einlesenWeiter": { de: "Öffnen", en: "Open" },
  "set.einlesenFrage": { de: "Die Datei vom {datum} enthält {n} Einträge. Schlüssel und Zugänge auf diesem Gerät bleiben, wie sie sind.", en: "The file from {datum} contains {n} entries. Keys and access on this device stay as they are." },
  "set.einlesenOk": { de: "Einlesen", en: "Import" },
  "set.ersatzDatei": { de: "ERSATZSCHLÜSSEL – GETRENNT VON DEINEM GERÄT AUFBEWAHREN\n\nprivat: {privat}\nöffentlich: {oeffentlich}\n\nWer diesen Schlüssel UND deinen laufenden hat, ist du.\nAusdrucken oder auf einen Stick, nicht in die Cloud.\n", en: "SPARE KEY – KEEP IT SEPARATE FROM YOUR DEVICE\n\nprivate: {privat}\npublic: {oeffentlich}\n\nWhoever has this key AND your current one is you.\nPrint it or put it on a USB stick, not in the cloud.\n" },
  "set.vorbereitet": { de: "Vorbereitet. Bewahre den Ersatzschlüssel getrennt auf.", en: "Prepared. Keep the spare key separately." },
  "set.welcherGestohlen": { de: "Welcher Schlüssel wurde gestohlen? (öffentlicher Schlüssel, npub oder hex)", en: "Which key was stolen? (public key, npub or hex)" },
  "set.keinPubkey": { de: "Kein gültiger öffentlicher Schlüssel", en: "Not a valid public key" },
  "set.ersatzFrage": { de: "Privater Ersatzschlüssel aus deiner Vorbereitung (64 Zeichen hex)", en: "Private spare key from your preparation (64 hex characters)" },
  "set.ersatzHex": { de: "Der Ersatzschlüssel muss 64 Zeichen hex sein", en: "The spare key must be 64 hex characters" },
  "set.seitWann": { de: "Seit wann vermutest du den Diebstahl? (freiwillig – lieber zu früh; alles danach gilt als unglaubwürdig)", en: "Since when do you suspect the theft? (optional – better too early; everything after it counts as untrustworthy)" },
  "set.datumUnlesbar": { de: "Datum nicht lesbar (JJJJ-MM-TT)", en: "Date not readable (YYYY-MM-DD)" },
  "set.keinMandat": { de: "Kein Mandat nennt diesen Ersatzschlüssel – Kontakte würden den Widerruf nicht anerkennen. Nichts gesendet.", en: "No mandate names this spare key – contacts wouldn't accept the revocation. Nothing sent." },
  "set.widerrufenFertig": { de: "Widerrufen – melde dich mit dem Ersatzschlüssel an (Identität importieren) und sag es deinen Kontakten zusätzlich direkt", en: "Revoked – sign in with the spare key (import identity) and also tell your contacts directly" },
  "set.geraetSprichtFuer": { de: "Dieses Gerät spricht für {person} · {stand}", en: "This device speaks for {person} · {stand}" },
  "set.nurDiesesGeraet": { de: "Nur dieses Gerät. Ein zweites einzurichten ist sicherer, als den Schlüssel zu kopieren.", en: "Only this device. Setting up a second one is safer than copying the key." },
  "set.geraetAktiv": { de: "aktiv", en: "active" },
  "set.geraetAbgelaufen": { de: "abgelaufen", en: "expired" },
  "set.geraetEntzogen": { de: "entzogen", en: "revoked" },
  "set.geraetUnbekannt": { de: "unbekannt", en: "unknown" },
  "set.entziehen": { de: "entziehen", en: "revoke" },
  "set.geraetName": { de: "Name des Geräts, zum Beispiel: Handy", en: "Name of the device, for example: phone" },
  "set.geraetUmfang": { de: "Umfang", en: "Scope" },
  "set.umfangNurChat": { de: "Nur Chat", en: "Chat only" },
  "set.umfangLesenSchreiben": { de: "Lesen und schreiben", en: "Read and write" },
  "set.umfangVoll": { de: "Vollzugriff", en: "Full access" },
  "set.geraetAusstellen": { de: "Vollmacht ausstellen", en: "Issue authorization" },
  "set.geraetCodeTitel": { de: "Gerätecode für {name}", en: "Device code for {name}" },
  "set.geraetCode": { de: "Auf dem neuen Gerät unter „Importieren“ einfügen oder den QR-Code scannen. Er ersetzt NICHT deine Merkphrase – das Gerät schreibt nur in deinem Namen, bis du es entziehst. Nach dem Schließen ist der Code weg; er wird nirgends gespeichert.", en: "On the new device, paste it under “Import” or scan the QR code. It does NOT replace your recovery phrase – the device only writes in your name until you revoke it. Once closed, the code is gone; it is not stored anywhere." },
  "set.geraetCodeFeld": { de: "Gerätecode", en: "Device code" },
  "set.geraetCodeQr": { de: "Gerätecode als QR-Code", en: "Device code as QR code" },
  "set.entziehenFrage": { de: "Der Entzug erreicht nur Clients, die ihn sehen – bis dahin versiegeln sie weiter auch an dieses Gerät. Was das Gerät vorher geschrieben hat, bleibt gültig; zurückdatierte Nachrichten zeigen Kontakte mit Warnung.", en: "The revocation only reaches clients that see it – until then they keep sealing to this device too. What the device wrote before stays valid; contacts show backdated messages with a warning." },
  "set.entzogen": { de: "Entzogen", en: "Revoked" },
  "set.fuerWen": { de: "Für wen meldest du? (npub oder hex)", en: "Whom are you reporting for? (npub or hex)" },
  "set.warum": { de: "Warum? (wird veröffentlicht)", en: "Why? (will be published)" },
  "set.gemeldet": { de: "Gemeldet – ein Lebenszeichen der Person bricht den Vorgang ab", en: "Reported – a sign of life from the person aborts the process" },
  "set.solOfflineWartet": { de: "Offline-SOL-Zahlung empfangen – wird eingereicht, sobald hier Netz da ist", en: "Offline SOL payment received – it is submitted as soon as there is a network here" },
  "set.solOfflineEingereicht": { de: "Offline-SOL-Zahlung empfangen und eingereicht: {sig}…", en: "Offline SOL payment received and submitted: {sig}…" },
  "set.solOfflineFehler": { de: "Offline-SOL-Zahlung nicht eingereicht: {fehler}", en: "Offline SOL payment not submitted: {fehler}" },
  "set.funkEmpfangen": { de: "Verschlüsselte Nachricht über Funk empfangen und ans Netz gegeben", en: "Encrypted message received over radio and passed to the network" },
  "set.paketUnlesbar": { de: "Empfangenes Paket unlesbar", en: "Received packet unreadable" },
  "set.sendezeitAufgebraucht": { de: "Sendezeit aufgebraucht (1 % je Stunde) – weiter in etwa {min} min, {n} Pakete offen", en: "Airtime used up (1% per hour) – continuing in about {min} min, {n} packets pending" },
  "set.paketeOffen": { de: "{n} Pakete offen, etwa {s} s", en: "{n} packets pending, about {s} s" },
  "set.unvollstaendig": { de: "{n} Nachricht(en) unvollständig", en: "{n} message(s) incomplete" },
  "set.bereit": { de: "bereit", en: "ready" },
  "set.keinGeraetezugriff": { de: "kein Gerätezugriff", en: "no device access" },
  "set.verbundenMit": { de: "verbunden: {name}", en: "connected: {name}" },
  "set.funkVerbunden": { de: "Funkgerät verbunden", en: "Radio connected" },
  "set.bluetoothVerbunden": { de: "Bluetooth verbunden", en: "Bluetooth connected" },
  "set.keineOnion": { de: "Keine .onion-Relay-Adresse (ws://….onion oder wss://….onion)", en: "Not an .onion relay address (ws://….onion or wss://….onion)" },
  "set.laeuft": { de: "läuft …", en: "running …" },
  "set.selbsttestOk": { de: "bestanden: {text} ({ms} ms)", en: "passed: {text} ({ms} ms)" },
  "set.selbsttestFehler": { de: "gescheitert: {text} ({ms} ms)", en: "failed: {text} ({ms} ms)" },
  "set.schieneGesetzt": { de: "Standard-Schiene: {schiene}", en: "Default rail: {schiene}" },
  "set.kontakteGesichert": { de: "Kontakte verschlüsselt gesichert.", en: "Contacts backed up encrypted." },
  "set.kontakteGesichertNeu": { de: "Kontakte verschlüsselt gesichert – {n} von anderen Geräten übernommen.", en: "Contacts backed up encrypted – {n} taken over from other devices." },
  "set.abgleichAus": { de: "Abgleich aus – die Liste auf den Relays ist geleert.", en: "Sync off – the list on the relays has been emptied." },
  "set.kontaktlisteFehler": { de: "Kontaktliste: {fehler}", en: "Contact list: {fehler}" },
  "set.sofort": { de: "Direktnachrichten gehen sofort hinaus.", en: "Direct messages go out immediately." },
  "set.verzoegert": { de: "Direktnachrichten gehen bis zu {s} s verzögert hinaus – jede Kopie einzeln.", en: "Direct messages go out delayed by up to {s} s – each copy separately." },
  "set.paketeAusgegeben": { de: "{n} Pakete als Datei ausgegeben", en: "{n} packets exported as a file" },
  "set.nichtsZuSendenChat": { de: "Nichts zu senden – Post für einen Kontakt nimmst du im Chat mit (⇪).", en: "Nothing to send – you take mail for a contact along in the chat (⇪)." },
  "set.paketeEingelesen": { de: "{n} Pakete eingelesen", en: "{n} packets imported" },
  "set.ueber": { de: "Über {weg}:", en: "Over {weg}:" },
  "set.paketeOffenKurz": { de: "{n} Pakete offen", en: "{n} packets pending" },
  "set.leseDatei": { de: "lese die eigene Datei …", en: "reading the app's own file …" },
  "set.exportiertPruefsumme": { de: "Exportiert. Prüfsumme:", en: "Exported. Checksum:" },
  "set.exportiertText": { de: "Wer die Datei von dir bekommt, kann sie damit gegen das signierte Manifest auf den Relays prüfen.", en: "Whoever gets the file from you can check it against the signed manifest on the relays." },
  "set.appExportiert": { de: "App exportiert – jetzt bist du eine Bezugsquelle", en: "App exported – now you are a source" },
  "set.exportFehler": { de: "Selbst-Export nicht möglich ({fehler}). Im Einzeldatei-Build funktioniert er; hinter einem Server mit Zugriffsschutz kann die Seite sich nicht selbst lesen.", en: "Self-export not possible ({fehler}). It works in the single-file build; behind a server with access protection the page can't read itself." },
  "set.neuereVersion": { de: "Neuere Version verfügbar: {version}.", en: "Newer version available: {version}." },
  "set.bezugsquellen": { de: "Bezugsquellen: {quellen}", en: "Sources: {quellen}" },
  "set.fixiert": { de: "Fixiert: Version {version}.", en: "Pinned: version {version}." },
  "set.fixieren": { de: "Version {version} fixieren", en: "Pin version {version}" },
  "set.fixierungAufheben": { de: "Fixierung aufheben", en: "Unpin" },
  "set.echtheitFehler": { de: "Echtheit nicht prüfbar: {fehler}", en: "Authenticity can't be checked: {fehler}" },
  "set.versionFixiert": { de: "Version {version} fixiert", en: "Version {version} pinned" },
  "set.tresorGesperrt": { de: "Tresor gesperrt – erst entsperren.", en: "Vault locked – unlock it first." },
  "set.nichtsGesammelt": { de: "Nichts gesammelt.", en: "Nothing collected." },
  "set.gesammelt": { de: "{ziel}: {betrag} gesammelt", en: "{ziel}: {betrag} collected" },
  "set.ausgangUnklar": { de: "{ziel}: {betrag} – Ausgang unklar, sieh in deiner Wallet nach: ", en: "{ziel}: {betrag} – outcome unclear, check your wallet: " },
  "set.kamAn": { de: "kam an", en: "arrived" },
  "set.kamNichtAn": { de: "kam nicht an", en: "didn't arrive" },
  "set.anteileGezahlt": { de: "{betrag} an Anteile gezahlt", en: "{betrag} paid in shares" },
  "set.nichtsFaellig": { de: "Nichts fällig – oder keine Lightning-Wallet verbunden", en: "Nothing due – or no Lightning wallet connected" },
  "set.geraetKauftNicht": { de: "Als Gerät kauft die Person den Zugang – auf dem Hauptgerät.", en: "As a device: the person buys access – on the main device." },
  "set.zugangBis": { de: "Zugang bis {datum}.", en: "Access until {datum}." },
  "set.frageRelay": { de: "frage den Relay …", en: "asking the relay …" },
  "set.keinVerkauf": { de: "Dieser Relay verkauft keinen Zugang (oder ist nicht erreichbar).", en: "This relay doesn't sell access (or isn't reachable)." },
  "set.preisZeile": { de: "{tage} Tage: {preis}", en: "{tage} days: {preis}" },
  "set.oder": { de: " oder ", en: " or " },
  "set.nurZahlende": { de: " · nimmt nur Post von und an Zahlende an", en: " · only accepts posts from and to paying users" },
  "set.nurAngemeldete": { de: " · Umschläge nur an Angemeldete", en: " · envelopes only to signed-in users" },
  "set.hinweisSol": { de: "Der Betreiber sieht deine Absenderadresse, und auf der Kette sieht jeder, dass sie diesen Relay bezahlt hat.", en: "The operator sees your sender address, and on the chain everyone sees that it paid this relay." },
  "set.hinweisSats": { de: "Der Betreiber sieht nur die Zahlung.", en: "The operator only sees the payment." },
  "set.kaufFrage": { de: "Zugang zu {url} für {tage} Tage kaufen? {hinweis}", en: "Buy access to {url} for {tage} days? {hinweis}" },
  "set.holeUndZahle": { de: "hole Angebot und zahle …", en: "fetching offer and paying …" },
  "set.bezahltBis": { de: "Bezahlt – Zugang bis {datum}.", en: "Paid – access until {datum}." },
  "set.bezahltOffen": { de: "Bezahlt, aber der Relay bestätigt noch nicht – später „Zahlung erneut prüfen“.", en: "Paid, but the relay hasn't confirmed yet – later use “Check payment again”." },
  "set.nichtGekauft": { de: "Nicht gekauft: {fehler}", en: "Not bought: {fehler}" },
  "set.nochNichtBestaetigt": { de: "Noch nicht bestätigt.", en: "Not confirmed yet." },
  "set.nichtGeprueft": { de: "Nicht geprüft: {fehler}", en: "Not checked: {fehler}" },
  "set.geraetSatz": { de: "Als Gerät nutzt du den Satz der Person – ändern nur auf dem Hauptgerät.", en: "As a device you use the person's set – change it only on the main device." },
  "set.keinSatz": { de: "Noch kein eigener Satz – die App legt ihn beim ersten Verbinden an.", en: "No set of your own yet – the app creates it on the first connection." },
  "set.keineIdentitaet": { de: "Keine Identität.", en: "No identity." },
  "set.veroeffentliche": { de: "veröffentliche …", en: "publishing …" },
  "set.veroeffentlicht": { de: "Veröffentlicht: {n} Relays – NIP-65-Liste und Posteingang.", en: "Published: {n} relays – NIP-65 list and inbox." },
  "set.nichtVeroeffentlichtKeiner": { de: "Nicht veröffentlicht – kein Relay nahm die Liste an. Der alte Satz gilt weiter.", en: "Not published – no relay accepted the list. The old set stays in effect." },
  "set.nichtVeroeffentlicht": { de: "Nicht veröffentlicht: {fehler}", en: "Not published: {fehler}" },
};
