/** Texte des Settings-Tabs (8.16f): Seite und tabs/settings.ts. */
import type { Texte } from "../i18n.js";

export const settings: Texte = {
  // Seite (index.html)
  "set.titel": { de: "Settings", en: "Settings" },
  "set.tabSicherheit": { de: "Sicherheit", en: "Security" },
  "set.tabGeraete": { de: "Geräte", en: "Devices" },
  "set.tabVerbindung": { de: "Verbindung", en: "Connection" },
  "set.tabDatenschutz": { de: "Datenschutz", en: "Privacy" },
  "set.tabMesh": { de: "Mesh", en: "Mesh" },
  "set.tabWeitergeben": { de: "Weitergeben", en: "Share" },
  "set.lead": { de: "Zwei der fünf Schritte gehen nur vorher.", en: "Two of the five steps only work beforehand." },
  "set.schritt1": { de: "Merkphrase gesichert", en: "Recovery phrase secured" },
  "set.schritt1Text": { de: "Zwölf Wörter, beim ersten Start bestätigt.", en: "Twelve words, confirmed at first start." },
  "set.schritt2": { de: "Zustand gesichert", en: "State backed up" },
  "set.schritt2Text": { de: "Unterhaltungen, Räume und Namen, verschlüsselt.", en: "Conversations, rooms and names, encrypted." },
  "set.schritt3": { de: "Diebstahl vorbeugen", en: "Prevent theft" },
  "set.schritt3Text": { de: "Ein Ersatzschlüssel, getrennt aufbewahrt. Nur vorher einrichtbar.", en: "A spare key, kept separately. Can only be set up beforehand." },
  "set.schritt4": { de: "Nachfolge", en: "Succession" },
  "set.schritt4Text": { de: "Vertraute stellen deinen Zugang wieder her.", en: "Trusted people restore your access." },
  "set.schritt5": { de: "Tresor", en: "Vault" },
  "set.schritt5Text": { de: "Schlüssel, Wallet-Zugänge und Unterhaltungen mit einer Passphrase verschlüsselt, beim Start entsperren.", en: "Keys, wallet access and conversations encrypted with a passphrase, unlocked at start." },
  "set.einrichten": { de: "Einrichten", en: "Set up" },
  "set.details": { de: "Details", en: "Details" },
  "set.tresorText": { de: "Sperrt nach Minuten ohne Eingabe – nie, während ein Tausch, ein Deposit oder ein Auftrag läuft. 0 = nie.", en: "Locks after minutes without input – never while a swap, a deposit or a job is running. 0 = never." },
  "set.tresorMinutenAria": { de: "Minuten bis zur Sperre", en: "Minutes until lock" },
  "set.minuten": { de: "Minuten", en: "minutes" },
  "set.jetztSperren": { de: "jetzt sperren", en: "lock now" },
  "set.sicherungTitel": { de: "Sicherung & Schlüsselwechsel", en: "Backup & key rotation" },
  "set.jetztSichern": { de: "jetzt sichern", en: "back up now" },
  "set.wiederherstellen": { de: "wiederherstellen", en: "restore" },
  "set.widerrufen": { de: "Schlüssel widerrufen", en: "Revoke key" },
  "set.nachfolgeTitel": { de: "Nachfolge & Wiederherstellung", en: "Succession & recovery" },
  "set.nachfolgeText": { de: "Vertraute können deinen Zugang wiederherstellen, wenn du dein Gerät verlierst oder nicht mehr da bist. Jeder bekommt einen Teil deines Schlüssels versiegelt; zusammensetzen lässt die App erst nach einer Frist, und ein Lebenszeichen von dir bricht den Vorgang ab. Wer deine Vertrauten sind, steht öffentlich im Plan.", en: "Trusted people can restore your access if you lose your device or are no longer around. Each gets a part of your key, sealed; the app only lets them combine it after a waiting period, and a sign of life from you aborts the process. Who your trusted people are is public in the plan." },
  "set.einrichtenKlein": { de: "einrichten", en: "set up" },
  "set.lebenszeichen": { de: "Lebenszeichen senden", en: "Send sign of life" },
  "set.melden": { de: "für jemanden melden", en: "report for someone" },
  "set.notfallTitel": { de: "Notfall-Löschung", en: "Emergency wipe" },
  "set.notfallText": { de: "Löscht alles, was die App auf diesem Gerät hat – Schlüssel, Tresor, Unterhaltungen, Suchindex, Wallet-Zugänge – und prüft nach. Was auf Relays liegt, bleibt dort. Ohne Merkphrase gibt es kein Zurück. Vorher steht ein rechtlicher Hinweis.", en: "Deletes everything the app has on this device – keys, vault, conversations, search index, wallet access – and verifies it. What is on relays stays there. Without the recovery phrase there is no way back. A legal notice comes first." },
  "set.notfallKnopf": { de: "alles auf diesem Gerät löschen …", en: "delete everything on this device …" },
  "set.geraeteTitel": { de: "Verbundene Geräte", en: "Connected devices" },
  "set.geraetHinzufuegen": { de: "Gerät hinzufügen", en: "Add device" },
  // B-8c: Mein Knoten
  "set.knotenTitel": { de: "Mein Knoten", en: "My node" },
  "set.knotenText": { de: "Den eigenen Provider-Knoten koppeln: den Code aus „npm run koppeln“ scannen oder einfügen. Anfragen an ihn rechnet er dann gratis – erkannt nur an einem Nachweis im versiegelten Auftrag.", en: "Pair your own provider node: scan or paste the code from “npm run koppeln”. It then answers your requests for free – recognised only by a proof inside the sealed request." },
  "set.knotenKoppeln": { de: "Mein Knoten koppeln", en: "Pair my node" },
  "set.knotenNeu": { de: "neu koppeln", en: "pair again" },
  "set.knotenEntkoppeln": { de: "entkoppeln", en: "unpair" },
  "set.knotenKoppelnText": { de: "Der Code ist ein Schlüssel: Er liegt nur auf diesem Gerät, mit Tresor im Tresor, nie in der Sicherung.", en: "The code is a key: it stays on this device only, inside the vault if you have one, never in the backup." },
  "set.knotenCode": { de: "Kopplungscode (freedom-kopplung:1:…)", en: "Pairing code (freedom-kopplung:1:…)" },
  "set.knotenCodeFalsch": { de: "Kein Kopplungscode – er beginnt mit freedom-kopplung:1:", en: "Not a pairing code – it starts with freedom-kopplung:1:" },
  "set.knotenErsetzen": { de: "Dieses Gerät ist mit dem Knoten {knoten} gekoppelt. Ersetzen?", en: "This device is paired with node {knoten}. Replace it?" },
  "set.knotenGekoppelt": { de: "Gekoppelt mit {knoten}", en: "Paired with {knoten}" },
  "set.knotenGekoppeltToast": { de: "Knoten gekoppelt", en: "Node paired" },
  "set.knotenHalten": { de: "Meine Dateien bei meinem Knoten halten – nach jedem Hochladen (Repo-Bundles, Anhänge) bittet die App ihn versiegelt, die verschlüsselten Stücke dauerhaft zu behalten", en: "Keep my files on my node – after every upload (repo bundles, attachments) the app asks it, sealed, to keep the encrypted pieces for good" },
  "set.knotenHaltenAlle": { de: "Mein Knoten hält die Datei ({n} Stücke)", en: "My node keeps the file ({n} pieces)" },
  "set.knotenHaltenTeil": { de: "Mein Knoten hält nur {n} von {m} Stücken – sein Speicher ist voll, oder die Relays lieferten nicht alle", en: "My node keeps only {n} of {m} pieces – its storage is full, or the relays did not deliver all of them" },
  "set.knotenHaltenKeins": { de: "Mein Knoten hält die Datei nicht (0 von {m} Stücken) – er fand sie auf seinen Relays nicht", en: "My node does not keep the file (0 of {m} pieces) – it did not find it on its relays" },
  "set.knotenHaltenSchweigt": { de: "Mein Knoten antwortet nicht – die Datei liegt nur im Netz", en: "My node does not answer – the file is only on the network" },
  "set.knotenHaltenAbgelehnt": { de: "Mein Knoten hält die Datei nicht: {grund}", en: "My node does not keep the file: {grund}" },
  "set.knotenHaltenFehler": { de: "Halten bei meinem Knoten gescheitert: {fehler}", en: "Keeping on my node failed: {fehler}" },
  "set.knotenNur": { de: "Alles über meinen Knoten – KI-Anfragen und Halten nur über sein Relay, dort mit dem Sitzungsschlüssel angemeldet; ist es nicht erreichbar, geht nichts an ihn", en: "Everything through my node – AI requests and keeping only via its relay, signed in there with the session key; if it cannot be reached, nothing goes to it" },
  "set.knotenOhneRelay": { de: "Mein Knoten nennt kein Relay – mit „Alles über meinen Knoten“ geht nichts an ihn", en: "My node names no relay – with “Everything through my node” nothing goes to it" },
  "set.knotenStatusHolen": { de: "Status abfragen", en: "Check status" },
  "set.knotenWecken": { de: "Wecken – kommt Post für mich, weckt mein Knoten diesen Browser mit einer Meldung ohne Inhalt und Absender; der Push-Dienst des Browsers sieht, wann", en: "Wake-up – when mail arrives for me, my node wakes this browser with a notification without content or sender; the browser's push service sees when" },
  "set.weckenFragt": { de: "frage meinen Knoten …", en: "asking my node …" },
  "set.weckenKnotenNicht": { de: "Dein Knoten weckt nicht – er läuft ohne eigenes Relay oder auf einem älteren Stand", en: "Your node does not wake – it runs without its own relay or on an older version" },
  "set.weckenKeineErlaubnis": { de: "Ohne Erlaubnis für Meldungen weckt nichts – erlaube sie in den Einstellungen des Browsers", en: "Without permission for notifications nothing can wake you – allow them in the browser settings" },
  "set.weckenKeinWorker": { de: "Diese Auslieferung der App hat den Weck-Worker nicht (etwa die App vom eigenen Knoten) – öffne sie von der Website", en: "This copy of the app has no wake worker (e.g. the app served by your own node) – open it from the website" },
  "set.weckenEndpunkt": { de: "Der Browser gab eine Push-Adresse, die die App nicht weitergibt – nichts angemeldet", en: "The browser returned a push address the app does not pass on – nothing registered" },
  "set.weckenAn": { de: "Wecken an – dein Knoten beobachtet {n} Schlüssel und weckt diesen Browser ohne Inhalt und Absender", en: "Wake-up on – your node watches {n} keys and wakes this browser without content or sender" },
  "set.weckenAus": { de: "Wecken aus – beim Knoten abgemeldet", en: "Wake-up off – unregistered at the node" },
  "set.weckenAusOhneKnoten": { de: "Wecken aus – der Knoten antwortete nicht; er vergisst die Adresse beim nächsten Wecken", en: "Wake-up off – the node did not answer; it forgets the address the next time it wakes you" },
  "set.weckenRest": { de: "Nicht alles abgemeldet: {offen}", en: "Not everything unregistered: {offen}" },
  "set.weckenNichtHier": { de: "Hier geht Wecken nicht – nur über https (oder localhost) in einem Browser mit Push", en: "Wake-up does not work here – only over https (or localhost) in a browser with push" },
  "set.knotenRelayUebernehmen": { de: "Relay meines Knotens übernehmen", en: "Use my node's relay" },
  "set.knotenRelayFrage": { de: "{url} kommt in deinen eigenen Relay-Satz – als Schreib-Relay und als Posteingang, die übrigen bleiben. Beide Listen (NIP-65 und Posteingang) werden neu veröffentlicht: Wer sie liest, sieht dieses Relay und kann vermuten, dass der Knoten dir gehört.", en: "{url} joins your own relay set – as a write relay and as your inbox; the others stay. Both lists (NIP-65 and inbox) are published again: anyone reading them sees this relay and may guess that the node is yours." },
  "set.knotenRelayKeins": { de: "Mein Knoten nennt kein Relay – nichts übernommen", en: "My node names no relay – nothing changed" },
  "set.knotenRelaySchon": { de: "{url} steht schon in deinem Satz", en: "{url} is already in your set" },
  "set.knotenRelayUntauglich": { de: "Das Relay deines Knotens ({url}) taugt nicht für Kontakte – nur wss:// (unverschlüsselt nur .onion), kein lokales Netz", en: "Your node's relay ({url}) does not work for contacts – only wss:// (unencrypted only .onion), no local network" },
  "set.knotenRelayDrin": { de: "Übernommen: {url} – {n} Relays, NIP-65-Liste und Posteingang veröffentlicht", en: "Done: {url} – {n} relays, NIP-65 list and inbox published" },
  "set.statusFragt": { de: "Frage meinen Knoten …", en: "Asking my node …" },
  "set.statusSchweigt": { de: "Mein Knoten antwortet nicht", en: "My node does not answer" },
  "set.statusAbgelehnt": { de: "Mein Knoten gibt keinen Status: {grund}", en: "My node gives no status: {grund}" },
  "set.statusUnlesbar": { de: "Die Antwort meines Knotens ist nicht lesbar – vielleicht läuft dort eine ältere Fassung", en: "My node's answer cannot be read – maybe it runs an older version" },
  "set.statusFehler": { de: "Status nicht abgefragt: {fehler}", en: "Status not checked: {fehler}" },
  "set.statusFassung": { de: "Fassung {fassung}, läuft seit {seit}", en: "Version {fassung}, running since {seit}" },
  "set.statusRollen": { de: "Rollen: {rollen}", en: "Roles: {rollen}" },
  "set.statusModelle": { de: "Modelle: {modelle}", en: "Models: {modelle}" },
  "set.statusAuftraege": { de: "Aufträge seit dem Start: {erledigt} erledigt (davon {gratis} gratis), {abgelehnt} abgelehnt", en: "Jobs since start: {erledigt} done ({gratis} of them free), {abgelehnt} declined" },
  "set.statusAbgerechnet": { de: "Abgerechnet seit dem Start: {betrag} – verlangt, nicht unbedingt schon bezahlt", en: "Billed since start: {betrag} – charged, not necessarily paid yet" },
  "set.statusSpeicher": { de: "Speicher: {belegt} MB von {quota} MB belegt, {gehalten} Stücke für mich gehalten", en: "Storage: {belegt} MB of {quota} MB used, {gehalten} pieces kept for me" },
  "set.statusSpeicherOhne": { de: "Speicher: {belegt} MB belegt (ohne Grenze), {gehalten} Stücke für mich gehalten", en: "Storage: {belegt} MB used (no limit), {gehalten} pieces kept for me" },
  "set.statusRelay": { de: "Relay: {events} Events, {verbindungen} Verbindungen", en: "Relay: {events} events, {verbindungen} connections" },
  "set.statusKeine": { de: "keine", en: "none" },
  "set.rolleKi": { de: "KI", en: "AI" },
  "set.rolleRelay": { de: "Relay", en: "relay" },
  "set.rolleSpeicher": { de: "Speicher", en: "storage" },
  "set.rolleGateway": { de: "Funk-Gateway", en: "radio gateway" },
  "set.rolleZahlkanal": { de: "Zahlkanal (SOL)", en: "payment channel (SOL)" },
  "set.rolleLnurl": { de: "eigene Lightning-Adresse", en: "own Lightning address" },
  "set.rolleLp": { de: "Tausch (LP)", en: "swaps (LP)" },
  "set.rolleRelayer": { de: "Relayer", en: "relayer" },
  "set.rolleTor": { de: "Tor", en: "Tor" },
  "set.rolleApp": { de: "App ausliefern", en: "serving the app" },
  "set.rolleTurn": { de: "Vermittler für Anrufe (TURN)", en: "relay for calls (TURN)" },
  "set.statusEinrichtung": { de: "Einrichtung (Prüfung beim Start):", en: "Setup (check at start):" },
  "set.statusEinrichtungFehlt": { de: "Einrichtung: noch nicht geprüft – oder der Knoten ist älter als B-11c", en: "Setup: not checked yet – or the node is older than B-11c" },
  "set.einUnbekannt": { de: "Befund {fall} – diese App kennt ihn noch nicht", en: "Finding {fall} – this app does not know it yet" },
  "set.schieneLightning": { de: "Lightning", en: "Lightning" },
  "set.schieneSol": { de: "SOL", en: "SOL" },
  "set.einLnFehlt": { de: "NODE_LUD16 fehlt – ohne Lightning-Adresse startet der Knoten nicht", en: "NODE_LUD16 is missing – without a Lightning address the node does not start" },
  "set.einLnKeineAdresse": { de: "NODE_LUD16 ist keine Lightning-Adresse (name@domain)", en: "NODE_LUD16 is not a Lightning address (name@domain)" },
  "set.einLnHttp": { de: "Die Lightning-Adresse antwortet mit HTTP {status}", en: "The Lightning address answers with HTTP {status}" },
  "set.einLnCors": { de: "Die Lightning-Adresse erlaubt keine Abfrage aus dem Browser (CORS) – die App kann dort keine Rechnung holen", en: "The Lightning address does not allow requests from the browser (CORS) – the app cannot get an invoice there" },
  "set.einLnUnerreichbar": { de: "Die Lightning-Adresse ist nicht erreichbar ({fehler})", en: "The Lightning address cannot be reached ({fehler})" },
  "set.einLnKeinPay": { de: "Die Lightning-Adresse ist keine LNURL-pay-Adresse mit https-Callback", en: "The Lightning address is not an LNURL-pay address with an https callback" },
  "set.einLnBetraege": { de: "Die Lightning-Adresse nennt keine gültigen Beträge", en: "The Lightning address names no valid amounts" },
  "set.einLnMindestens": { de: "Die Lightning-Adresse nimmt erst ab {sats} sats an – kleinere Anteile kommen nicht an", en: "The Lightning address only accepts from {sats} sats – smaller shares do not arrive" },
  "set.einLnNimmtNicht": { de: "Die Lightning-Adresse nimmt {sats} sats nicht an", en: "The Lightning address does not accept {sats} sats" },
  "set.einLnKeineRechnung": { de: "Die Lightning-Adresse stellt keine Rechnung aus", en: "The Lightning address issues no invoice" },
  "set.einLnAndererBetrag": { de: "Die Lightning-Adresse stellt eine Rechnung über einen anderen Betrag aus", en: "The Lightning address issues an invoice for a different amount" },
  "set.einLnUngueltig": { de: "Die Lightning-Adresse stellt keine gültige Rechnung aus ({fehler})", en: "The Lightning address issues no valid invoice ({fehler})" },
  "set.einLnOk": { de: "Die Lightning-Adresse stellt Rechnungen aus ({min} bis {max} sats)", en: "The Lightning address issues invoices ({min} to {max} sats)" },
  "set.einSolKanalAus": { de: "Zahlkanal aus (ZAHLKANAL=1 setzen) – Kunden zahlen dann nur mit Lightning", en: "Payment channel off (set ZAHLKANAL=1) – customers then pay with Lightning only" },
  "set.einSolKanalAdresseFehlt": { de: "Zahlkanal: NODE_SOL_ADDRESS fehlt – Kunden zahlen dann nur mit Lightning", en: "Payment channel: NODE_SOL_ADDRESS is missing – customers then pay with Lightning only" },
  "set.einSolKanalSchluesselUnlesbar": { de: "Zahlkanal: der Solana-Schlüssel ist nicht lesbar – Kunden zahlen dann nur mit Lightning", en: "Payment channel: the Solana key cannot be read – customers then pay with Lightning only" },
  "set.einSolKanalSchluesselPasstNicht": { de: "Zahlkanal: der Schlüssel aus SOLANA_KEYPAIR passt nicht zu NODE_SOL_ADDRESS – Kunden zahlen dann nur mit Lightning", en: "Payment channel: the key from SOLANA_KEYPAIR does not match NODE_SOL_ADDRESS – customers then pay with Lightning only" },
  "set.einSolKanalAn": { de: "Zahlkanal an", en: "Payment channel on" },
  "set.einSolProgrammFehlt": { de: "Das Kanal-Programm liegt auf dieser Kette noch nicht – Kunden können noch keine Kanäle öffnen", en: "The channel program is not on this chain yet – customers cannot open channels yet" },
  "set.einSolWenigGuthaben": { de: "Die Adresse des Knotens hat {lamports} – für die Gebühren der Einlösungen braucht sie mindestens {mindestLamports}", en: "The node's address holds {lamports} – for the fees of redemptions it needs at least {mindestLamports}" },
  "set.einSolGuthaben": { de: "Guthaben der Adresse des Knotens: {lamports}", en: "Balance of the node's address: {lamports}" },
  "set.einSolKetteUnerreichbar": { de: "Kette nicht erreichbar ({fehler}) – Programm und Guthaben ungeprüft", en: "Chain not reachable ({fehler}) – program and balance unchecked" },
  "set.einSolAuszahlungProgramm": { de: "NODE_SOL_PAYOUT ist ein Programm – dorthin zahlt der Knoten nicht aus", en: "NODE_SOL_PAYOUT is a program – the node does not pay out there" },
  "set.einSolAuszahlung": { de: "Auszahlung an die eigene Adresse eingerichtet", en: "Payout to your own address set up" },
  "set.einSolAuszahlungAus": { de: "Auszahlung aus (NODE_SOL_PAYOUT setzen) – Eingelöstes bleibt auf dem Schlüssel des Knotens", en: "Payout off (set NODE_SOL_PAYOUT) – redeemed funds stay on the node's key" },
  "set.einSolAuszahlungTeilt": { de: "Auszahlung aus – LP oder Relayer nutzen denselben Schlüssel (SOLANA_KEYPAIR); Eingelöstes bleibt auf dem Schlüssel des Knotens", en: "Payout off – LP or relayer use the same key (SOLANA_KEYPAIR); redeemed funds stay on the node's key" },
  "set.einSolAuszahlungUngueltig": { de: "Auszahlung: NODE_SOL_PAYOUT ungültig", en: "Payout: NODE_SOL_PAYOUT is invalid" },
  "set.knotenNicht": { de: "Nicht gekoppelt", en: "Not paired" },
  "set.knotenEntkoppelnText": { de: "Den Code auf diesem Gerät vergessen? Für alle Geräte ungültig wird er erst mit „npm run koppeln -- --neu“ am Knoten.", en: "Forget the code on this device? It becomes invalid for all devices only with “npm run koppeln -- --neu” on the node." },
  "set.bunkerTitel": { de: "Anmelden per Bunker (NIP-46)", en: "Sign in with a bunker (NIP-46)" },
  "set.bunkerText": { de: "Dein Schlüssel bleibt in einem Signer, z. B. Amber oder nsecBunker; die App fragt jede Unterschrift dort an. Ohne den Schlüssel selbst gehen nicht: Sicherungsdatei, Schlüssel-Export, Zustandssicherung, Nachfolge und abgeleitete Swap-Adressen – der Datenexport geht.", en: "Your key stays in a signer, e.g. Amber or nsecBunker; the app requests every signature there. Without the key itself these don't work: backup file, key export, state backup, succession and derived swap addresses – the data export works." },
  "set.bunkerAria": { de: "bunker://-Adresse", en: "bunker:// address" },
  "set.verbinden": { de: "verbinden", en: "connect" },
  "set.abmelden": { de: "abmelden", en: "sign out" },
  "set.endpunkteTitel": { de: "Eigene Endpunkte", en: "Own endpoints" },
  "set.endpunkteText": { de: "Eigene Solana-Endpunkte, kommagetrennt. Sie werden zuerst benutzt; fällt einer aus, nimmt die App den nächsten. Voreingestellt sind vier Anbieter verschiedener Betreiber. Ab und zu fragt die App einen zweiten Anbieter nach demselben (Netz, letzter Blockhash, ein Kontostand) und warnt, wenn die Antworten sich widersprechen.", en: "Your own Solana endpoints, comma-separated. They are used first; if one fails, the app takes the next. Preset are four providers from different operators. Now and then the app asks a second provider the same thing (network, latest blockhash, a balance) and warns if the answers contradict each other." },
  "set.endpunktePh": { de: "https://mein-knoten.example, https://…", en: "https://my-node.example, https://…" },
  "set.erreichbarkeit": { de: "erreichbarkeit prüfen", en: "check reachability" },
  "set.relaysTitel": { de: "Nostr-Relays (dein Satz)", en: "Nostr relays (your set)" },
  "set.relaysText": { de: "Hier veröffentlichst du (NIP-65), und hier liegt dein Posteingang (Kind 10050): Kontakte lesen dort, was du schreibst, und stellen dir dort Nachrichten zu. Dazu liest die App bei den Relays deiner Kontakte und je Sitzung bei ein paar wechselnden der Startliste. Eine Adresse je Zeile, nur wss:// (unverschlüsselt nur .onion), höchstens acht. Nach dem Veröffentlichen gilt der Satz für alle deine Geräte; wer noch die alte Liste kennt, schreibt bis zum Nachladen an die alten Relays.", en: "This is where you publish (NIP-65) and where your inbox is (kind 10050): contacts read there what you write and deliver messages to you there. In addition the app reads from your contacts' relays and, per session, from a few changing ones from the start list. One address per line, only wss:// (unencrypted only .onion), at most eight. After publishing, the set applies to all your devices; whoever still knows the old list writes to the old relays until they reload." },
  "set.relaysAria": { de: "Eigene Relays, eine Adresse je Zeile", en: "Your relays, one address per line" },
  "set.veroeffentlichen": { de: "veröffentlichen", en: "publish" },
  "set.zugangTitel": { de: "Relay-Zugang kaufen", en: "Buy relay access" },
  "set.zugangText": { de: "Manche Relays nehmen Post nur für Zahlende an und geben deine Umschläge nur an dich heraus, wenn du dich anmeldest (NIP-42). Die App meldet sich nur bei deinen eigenen Relays und bei Relays mit gekauftem Zugang an – nur, wenn der Relay es verlangt. Kaufen verrät dem Betreiber deinen Schlüssel und deine IP-Adresse; mit SOL auch deine Absenderadresse, und auf der Kette sieht jeder, dass sie diesen Relay bezahlt hat. Mit Sats sieht der Betreiber nur die Zahlung.", en: "Some relays only accept posts from paying users and only hand out your envelopes to you when you sign in (NIP-42). The app only signs in to your own relays and to relays with purchased access – and only if the relay asks. Buying reveals your key and your IP address to the operator; with SOL also your sender address, and on the chain everyone sees that it paid this relay. With sats the operator only sees the payment." },
  "set.zugangAria": { de: "Relay-Adresse", en: "Relay address" },
  "set.preisAbfragen": { de: "Preis abfragen", en: "Get price" },
  "set.mitSats": { de: "mit Sats kaufen", en: "buy with sats" },
  "set.mitSol": { de: "mit SOL kaufen", en: "buy with SOL" },
  "set.zahlungPruefen": { de: "Zahlung erneut prüfen", en: "Check payment again" },
  "set.sichtbarTitel": { de: "Was sichtbar ist", en: "What is visible" },
  "set.sichtbarText": { de: "Was in deiner Einstellung für andere sichtbar ist.", en: "What others can see with your settings." },
  "set.verbindungLabel": { de: "Verbindung", en: "Connection" },
  "set.netzKlar": { de: "direkt (Relays sehen deine IP)", en: "direct (relays see your IP)" },
  "set.netzTor": { de: ".onion-Relays bevorzugen (nur über Tor wirksam: Tor Browser oder Tor in der Desktop-App)", en: "prefer .onion relays (only effective over Tor: Tor Browser or Tor in the desktop app)" },
  "set.netzMixnet": { de: "Mixnetz (nur wirksam, wenn du selbst eines nutzt)", en: "mixnet (only effective if you use one yourself)" },
  "set.onionText": { de: "Ob deine IP-Adresse verborgen ist, prüft die App, wenn du diesen Bericht öffnest: Erreicht sie ein .onion-Relay, läuft deine Verbindung über Tor. Sie versucht bis zu drei .onion-Relays, die sie kennt, höchstens 10 Sekunden.", en: "Whether your IP address is hidden is checked when you open this report: if the app reaches an .onion relay, your connection runs over Tor. It tries up to three .onion relays it knows, for at most 10 seconds." },
  "set.erneutPruefen": { de: "erneut prüfen", en: "check again" },
  "set.onionLabel": { de: ".onion-Relay zum Prüfen (optional – nur für diese Prüfung)", en: ".onion relay to check (optional – only for this check)" },
  "set.kontakteSichern": { de: "Kontakte verschlüsselt zwischen Geräten abgleichen (NIP-51)", en: "Sync contacts encrypted between devices (NIP-51)" },
  "set.kontakteText": { de: "Standard: aus. Die Liste liegt verschlüsselt auf den Relays – sie sehen, dass es sie gibt, nicht, wen sie enthält.", en: "Default: off. The list is stored encrypted on the relays – they see that it exists, not whom it contains." },
  "set.platzhalter": { de: "Persönliche Angaben in KI-Fragen durch Platzhalter ersetzen", en: "Replace personal details in AI questions with placeholders" },
  "set.platzhalterText": { de: "Standard: an. Vor dem Senden ersetzt die App E-Mail-Adressen, Telefonnummern, IBAN, Kartennummern, IP-Adressen, Nostr-Schlüssel, Lightning-Rechnungen und die Namen deiner Kontakte durch Platzhalter und setzt sie in der Antwort zurück. Was sie nicht erkennt – Namen außerhalb deines Adressbuchs, Adressen, Gesundheitsangaben, den Inhalt von Anhängen –, liest der Provider wie geschrieben. Für dieses Gerät und deinen eigenen Knoten gilt das nicht, dort liest niemand mit.", en: "Default: on. Before sending, the app replaces email addresses, phone numbers, IBANs, card numbers, IP addresses, Nostr keys, Lightning invoices and the names of your contacts with placeholders and puts them back into the answer. What it does not recognise – names outside your address book, addresses, health details, the content of attachments – the provider reads as written. This does not apply to this device or your own node; nobody else reads along there." },
  "set.platzhalterAn": { de: "Platzhalter an – persönliche Angaben werden vor dem Senden ersetzt.", en: "Placeholders on – personal details are replaced before sending." },
  "set.platzhalterAus": { de: "Platzhalter aus – KI-Fragen gehen unverändert hinaus.", en: "Placeholders off – AI questions go out unchanged." },
  "set.rufTeilen": { de: "Meine Erfahrung mit Providern versiegelt mit Kontakten teilen", en: "Share my experience with providers sealed with contacts" },
  "set.rufTeilenText": { de: "Standard: aus. Deine Kontakte erfahren, bei welchen Providern du wie viele Antworten bezahlt hast, in welchem Umfang und mit wie vielen bestätigten Reklamationen – ihre App reiht Provider danach, wie deine es mit ihren Zusammenfassungen tut. Jeder Kontakt bekommt einen eigenen Umschlag an seinen Posteingang, einer nach dem anderen im Abruftakt; Relays sehen nur, dass Kontakte Post bekommen. Als Gerät einer Person teilt die App nicht.", en: "Default: off. Your contacts learn with which providers you paid how many answers, how much and with how many upheld complaints – their app ranks providers by it, as yours does with their summaries. Each contact gets an envelope of their own at their inbox, one after the other with the fetch cycle; relays only see that contacts get mail. As a person's device the app doesn't share." },
  "set.rufStand": { de: "Geteilt mit {geteilt} Kontakten · Zusammenfassungen von {erhalten} Kontakten.", en: "Shared with {geteilt} contacts · summaries from {erhalten} contacts." },
  "set.rufAn": { de: "Deine Zusammenfassung geht nach und nach an deine Kontakte.", en: "Your summary goes to your contacts bit by bit." },
  "set.rufAus": { de: "Geteilt wird nichts mehr. Was schon hinausging, behalten deine Kontakte.", en: "Nothing is shared any more. What already went out, your contacts keep." },
  "set.verlaufLabel": { de: "Verlauf zu KI-Fragen mitschicken", en: "Send history with AI questions" },
  "set.verlaufAus": { de: "aus – nur die Frage", en: "off – the question only" },
  "set.verlaufKurz": { de: "kurz – letzte 6 Nachrichten, höchstens 3 000 Zeichen (Standard)", en: "short – last 6 messages, at most 3,000 characters (default)" },
  "set.verlaufLang": { de: "lang – letzte 12 Nachrichten, höchstens 6 000 Zeichen", en: "long – last 12 messages, at most 6,000 characters" },
  "set.verlaufText": { de: "Der Knoten merkt sich nichts – damit er Rückfragen versteht, schickt die App die letzten Nachrichten der Unterhaltung mit, versiegelt wie die Frage. Was mitgeht, liest der Provider. Weniger Verlauf heißt: er liest weniger, versteht Rückfragen aber schlechter.", en: "The node remembers nothing – so that it understands follow-up questions, the app sends the last messages of the conversation along, sealed like the question. Whatever is sent, the provider reads. Less history means it reads less but understands follow-ups less well." },
  "set.verlaufGesetzt": { de: "Verlauf zu KI-Fragen: {umfang}", en: "History with AI questions: {umfang}" },
  "set.verzoegerungLabel": { de: "Direktnachrichten verzögert senden", en: "Send direct messages delayed" },
  "set.verzoegerung0": { de: "aus – sofort", en: "off – immediately" },
  "set.verzoegerung5": { de: "bis 5 Sekunden", en: "up to 5 seconds" },
  "set.verzoegerung30": { de: "bis 30 Sekunden (Standard)", en: "up to 30 seconds (default)" },
  "set.verzoegerung120": { de: "bis 2 Minuten", en: "up to 2 minutes" },
  "set.verzoegerungText": { de: "Jede Kopie einer Nachricht (an den Empfänger, an dich, an deine Geräte) geht mit eigener Zufallsverzögerung hinaus – so sieht ein Relay nicht am gleichen Zeitpunkt, wer mit wem schreibt. Die Nachricht steht sofort in deinem Verlauf; verlässt du die Seite, geht Wartendes sofort hinaus. Deine IP-Adresse verbirgt das nicht.", en: "Every copy of a message (to the recipient, to you, to your devices) goes out with its own random delay – so a relay can't tell from the same moment who writes to whom. The message is in your history immediately; if you leave the page, anything waiting goes out immediately. This doesn't hide your IP address." },
  "set.mlsTitel": { de: "Gruppenverschlüsselung (MLS)", en: "Group encryption (MLS)" },
  "set.mlsText": { de: "Eingebaut (MLS nach Marmot), nur mit Tresor: 1:1-Nachrichten gehen darüber, wenn der Kontakt es kann – eure Geräte sind eigene Mitglieder. Sonst, mit Ablauf, mit Bunker, ohne Tresor oder wenn einem Gerät das KeyPackage fehlt, weiter über NIP-17. Der Selbsttest lädt die Engine in diesem Browser und spielt ohne Netz eine Gruppe mit zwei Wegwerf-Identitäten durch.", en: "Built in (MLS following Marmot), only with the vault: 1:1 messages go over it if the contact supports it – your devices are members of their own. Otherwise – with expiry, with a bunker, without a vault or if a device lacks a KeyPackage – messages continue over NIP-17. The self-test loads the engine in this browser and runs a group with two throwaway identities without a network." },
  "set.selbsttest": { de: "Selbsttest", en: "Self-test" },
  "set.aufteilungTitel": { de: "Aufteilung", en: "Split" },
  "set.aufteilungText": { de: "Jede KI-Zahlung ist fest aufgeteilt: 94 % Provider, 2 % Entwicklung, 1,5 % Relays, je 0,5 % für deinen Werber und den des Providers, 1 % Hosting; 0,5 % bleiben bei dir als Prüfbudget. Kein Topf: Die App zahlt jeden Anteil selbst an seinen Empfänger – der Provider stellt nur seinen in Rechnung.", en: "Every AI payment is split in fixed shares: 94% provider, 2% development, 1.5% relays, 0.5% each for your referrer and the provider's, 1% hosting; 0.5% stays with you as a check budget. No pool: the app pays each share itself to its recipient – the provider only invoices its own." },
  "set.aufteilungDetails": { de: "Fehlt ein Empfänger mit Lightning-Adresse, bekommt den Anteil der Provider – nie die Entwicklung. Heute gehen die weiteren Anteile an die Werber beider Seiten, wenn die App sie kennt (Angebot des Providers, dein Werbelink), und an bis zu drei Relays deines Pools, deren Betreiber per Selbstauskunft (NIP-11) und Profil eine Lightning-Adresse nennt, sowie an den Spiegel, von dem die App geladen wurde, wenn er eine Zahladresse nennt (Datei freedom-spiegel.json). Die Entwicklung hat noch keine eigene Adresse. Anteile unter 100 sats je Empfänger sammelt die App; bis dahin bleibt das Geld bei dir. SOL-Aufträge gehen ganz an den Provider, bis der Zahlkanal aufteilt. Ändern lässt sich die Aufteilung nur mit einem signierten Release. Beim Holen einer Rechnung sieht der Server hinter der Lightning-Adresse deine IP-Adresse und den Betrag – wie bei jedem Zap.", en: "If a recipient with a Lightning address is missing, the provider gets the share – never development. Today the other shares go to the referrers of both sides if the app knows them (provider's offer, your referral link), to up to three relays of your pool whose operator names a Lightning address via self-description (NIP-11) and profile, and to the mirror the app was loaded from if it names a payment address (file freedom-spiegel.json). Development has no address of its own yet. The app collects shares below 100 sats per recipient; until then the money stays with you. SOL jobs go entirely to the provider until the payment channel splits. The split can only be changed with a signed release. When fetching an invoice, the server behind the Lightning address sees your IP address and the amount – as with every zap." },
  "set.faelligeZahlen": { de: "Fällige jetzt zahlen", en: "Pay due shares now" },
  "set.zahlenTitel": { de: "Zahlen", en: "Payments" },
  "set.standardSchiene": { de: "Standard-Schiene", en: "Default rail" },
  "set.anzeigeEinheit": { de: "Beträge zuerst zeigen in", en: "Show amounts first in" },
  "set.einheitAuto": { de: "automatisch", en: "automatic" },
  "set.einheitSats": { de: "sats", en: "sats" },
  "set.einheitSol": { de: "SOL", en: "SOL" },
  "set.einheitText": { de: "Nur die Anzeige: Die andere Einheit steht mit „≈“ und dem Kurs von jetzt daneben, der genaue Betrag immer dabei. Ohne Kurs keine umgerechnete Zahl. „Automatisch“ zeigt SOL zuerst, wenn SOL deine Standard-Schiene ist, sonst jeden Betrag in seiner Einheit.", en: "Display only: the other unit is shown next to it with “≈” and the current rate, the exact amount always included. Without a rate, no converted number. “Automatic” shows SOL first if SOL is your default rail, otherwise each amount in its own unit." },
  "set.einheitGesetzt": { de: "Beträge zuerst in: {einheit} – gilt für alles, was ab jetzt gezeigt wird", en: "Amounts first in: {einheit} – applies to everything shown from now on" },
  "set.schieneText": { de: "Vorgabe für Zaps, Trinkgeld und KI – Zaps und Trinkgeld bei jeder Zahlung änderbar. KI zahlt mit SOL nur über einen Zahlkanal zum Provider. Die App zahlt nie still in der anderen Währung.", en: "Default for zaps, tips and AI – zaps and tips changeable with every payment. With SOL, AI pays only through a payment channel to the provider. The app never silently pays in the other currency." },
  "set.ohneInternet": { de: "Ohne Internet", en: "Without internet" },
  "set.meshText": { de: "Verschlüsselte Nachrichten über Funk oder per Datei, wenn das Netz weg ist – nur Umschläge, ohne deinen Schlüssel und ohne Klartext. Funkgeräte mit Meshtastic verbindet die App per USB oder Bluetooth und sendet auf dem Kanal „freedom“; das Gerät funkt dabei seine Nummer offen mit, je nach Einstellung auch Name und Position. Funk sendet höchstens 1 % der Zeit (EU 868 MHz): im Meshtastic-Standard etwa zwei kurze Nachrichten je Stunde. SOL mit vorbereitetem Nonce-Konto (Wallet-Tab); empfangene SOL-Zahlungen reicht die App ein, sobald sie Netz hat. Lightning geht so nicht; KI nur kurz über ein Funk-Gateway (unten).", en: "Encrypted messages over radio or as a file when the network is down – only envelopes, without your key and without plaintext. The app connects radios running Meshtastic via USB or Bluetooth and sends on the “freedom” channel; the device transmits its number in the clear, and depending on its settings also its name and position. Radio sends at most 1% of the time (EU 868 MHz): with Meshtastic's default about two short messages per hour. SOL with a prepared nonce account (wallet tab); the app submits received SOL payments as soon as it has a network. Lightning doesn't work this way; AI only briefly via a radio gateway (below)." },
  "set.funkGateway": { de: "KI über Funk", en: "AI via radio" },
  "set.funkGatewayText": { de: "Ohne Internet fragst du die KI über dein Funkgerät und ein Gateway – einen Knoten mit Netz und Funkgerät. Das Gateway sieht nur Umschläge: weder Frage noch Antwort noch wer du bist. Kurz: höchstens 500 Zeichen, rund zwei Antworten je Stunde und Gateway (1 % Sendezeit). Bezahlt nur über einen Zahlkanal zu diesem Provider oder gratis – Lightning braucht Netz. Wähle das Gateway, solange du Netz hast; die Antwort kommt nur an, solange die App offen bleibt.", en: "Without internet you ask the AI via your radio and a gateway – a node with network and radio. The gateway only sees envelopes: neither question nor answer nor who you are. Short: at most 500 characters, about two answers per hour and gateway (1% airtime). Paid only through a payment channel to this provider, or free – Lightning needs a network. Choose the gateway while you are online; the answer only arrives while the app stays open." },
  "set.funkGatewaySuchen": { de: "Gateways suchen", en: "Find gateways" },
  "set.funkGatewayVergessen": { de: "vergessen", en: "forget" },
  "set.funkGatewayKeins": { de: "Kein Gateway gemerkt.", en: "No gateway saved." },
  "set.funkGatewayGemerkt": { de: "Gemerkt: {pk}, Angebot vom {datum}.", en: "Saved: {pk}, offer from {datum}." },
  "set.funkGatewayNurGratis": { de: " Ohne SOL-Kurs – über Funk nur gratis.", en: " No SOL rate – via radio only free." },
  "set.funkGatewaySuche": { de: "suche …", en: "searching …" },
  "set.funkGatewayKeineGefunden": { de: "Kein Provider bietet gerade ein Funk-Gateway an.", en: "No provider currently offers a radio gateway." },
  "set.funkGatewayWahl": { de: "{pk} merken", en: "save {pk}" },
  "set.funkGatewayGespeichert": { de: "Gateway gemerkt.", en: "Gateway saved." },
  "set.funkGatewayUngeeignet": { de: "Dieses Angebot taugt nicht als Gateway (verlangt zu viel Rechenarbeit).", en: "This offer is not usable as a gateway (demands too much proof of work)." },
  "set.usbGeraet": { de: "USB-Gerät", en: "USB device" },
  "set.alsDatei": { de: "als Datei ausgeben", en: "export as file" },
  "set.dateiEinlesen": { de: "Datei einlesen", en: "Import file" },
  "set.wasOffline": { de: "Was geht ohne Internet?", en: "What works without internet?" },
  "set.warteschlange": { de: "Warteschlange", en: "Queue" },
  "set.nichtsZuSenden": { de: "nichts zu senden", en: "nothing to send" },
  "set.alsDateiTitel": { de: "Als Datei", en: "As a file" },
  "set.weitergebenText": { de: "Die App ist eine einzige Datei. Du kannst sie exportieren und weitergeben; ihre Echtheit lässt sich gegen das signierte Manifest prüfen.", en: "The app is a single file. You can export and share it; its authenticity can be checked against the signed manifest." },
  "set.appExportieren": { de: "App exportieren", en: "Export app" },
  "set.echtheitPruefen": { de: "eigene Echtheit prüfen", en: "check own authenticity" },
  "set.sprache": { de: "Sprache", en: "Language" },
  // tabs/settings.ts
  "set.nurHaupt": { de: "{was} geht nur mit der Hauptidentität, nicht auf einem Gerät", en: "{was} only works with the main identity, not on a device" },
  "set.wasNachfolge": { de: "Nachfolge einrichten", en: "Setting up succession" },
  "set.wasWechsel": { de: "Den Schlüsselwechsel vorbereiten", en: "Preparing key rotation" },
  "set.wasGeraete": { de: "Geräte hinzufügen", en: "Adding devices" },
  "set.nfNicht": { de: "Nicht eingerichtet. Ohne Nachfolge ist dein Zugang bei Geräteverlust endgültig weg.", en: "Not set up. Without succession your access is gone for good if you lose your device." },
  "set.nfPlan": { de: "{schwelle} von {von} Vertrauten, Frist {frist} Tage, Wartezeit {warte} Tage.", en: "{schwelle} of {von} trusted people, inactivity period {frist} days, waiting time {warte} days." },
  // Dialoge statt prompt()/confirm() (C-1c)
  "set.nachfolgeDialog": { de: "Nachfolge einrichten", en: "Set up succession" },
  "set.vertrauteText": { de: "Mindestens 3 Personen, die sich NICHT kennen und FreedomStack nutzen.", en: "At least 3 people who do NOT know each other and use FreedomStack." },
  "set.vertrauteKontakte": { de: "Aus deinen Kontakten", en: "From your contacts" },
  "set.weitereSchluessel": { de: "Weitere Schlüssel (npub oder hex), durch Komma oder je Zeile", en: "More keys (npub or hex), separated by commas or one per line" },
  "set.vertrauteSchluessel": { de: "Schlüssel der Vertrauten (npub oder hex), durch Komma oder je Zeile", en: "Keys of your trusted people (npub or hex), separated by commas or one per line" },
  "set.weiter": { de: "Weiter", en: "Continue" },
  "set.nachfolgeEinrichten": { de: "Einrichten", en: "Set up" },
  "set.ersatzErzeugen": { de: "Ersatzschlüssel erzeugen", en: "Create spare key" },
  "set.widerrufenKnopf": { de: "Widerrufen", en: "Revoke" },
  "set.entziehenTitel": { de: "Vollmacht entziehen", en: "Revoke the authorization" },
  "set.entziehenKnopf": { de: "Entziehen", en: "Revoke" },
  "set.meldenKnopf": { de: "Melden", en: "Report" },
  "set.neueVersionTitel": { de: "Neue Version", en: "New version" },
  "set.uebernehmen": { de: "Übernehmen", en: "Adopt" },
  "set.kaufen": { de: "Kaufen", en: "Buy" },
  "set.mindestensDrei": { de: "Mindestens drei Vertraute – bei weniger ist eine Absprache zu leicht", en: "At least three trusted people – with fewer, collusion is too easy" },
  "set.fuerNachfolge": { de: "Die Nachfolge", en: "Succession" },
  "set.fuerSicherung": { de: "Die Sicherung", en: "The backup" },
  "set.fuerWiederherstellung": { de: "Die Wiederherstellung", en: "Restoring" },
  "set.nfEingerichtet": { de: "Eingerichtet – {n} Vertraute haben ihren Teil versiegelt bekommen.", en: "Set up – {n} trusted people received their part, sealed." },
  "set.mitBunkerNicht": { de: "Mit Bunker nicht möglich – das braucht den Schlüssel selbst", en: "Not possible with a bunker – this needs the key itself" },
  "set.keineSicherung": { de: "Keine Sicherung gefunden", en: "No backup found" },
  // Zusammenführen statt überschreiben (B-5)
  "set.zusammenfuehren": { de: "Unterhaltungen, Räume, Namen, Lesestände, Kataloge und geprüfte Kontakte werden zusammengeführt – was nur auf diesem Gerät steht, bleibt. Sprache, Profil und Einstellungen werden übernommen.", en: "Conversations, rooms, names, read positions, catalogues and verified contacts are merged – what exists only on this device stays. Language, profile and settings are taken over." },
  "set.zusammenErhalten": { de: "{n} Einträge von diesem Gerät bleiben erhalten.", en: "{n} entries from this device are kept." },
  "set.zusammenKonflikte": { de: "{n} Namen stehen auf beiden Seiten verschieden – dort gilt der eingelesene.", en: "{n} names differ on both sides – the imported one wins there." },
  "set.zusammenfuehrenOk": { de: "Zusammenführen", en: "Merge" },
  "set.wiederhergestellt": { de: "Wiederhergestellt – die Seite wird neu geladen", en: "Restored – the page reloads" },
  // Datenexport (B-6)
  "set.exportDatei": { de: "als Datei exportieren", en: "export as a file" },
  "set.exportEinlesen": { de: "Datei einlesen", en: "import a file" },
  "set.exportTitel": { de: "Alles als Datei exportieren", en: "Export everything as a file" },
  "set.exportText": { de: "Unterhaltungen, Räume, Namen, Profil, Einstellungen, geprüfte Kontakte, KI-Verläufe und Quittungen – verschlüsselt mit einer Passphrase, die du hier wählst. Nie drin: dein Schlüssel, Wallet- und Relay-Zugänge, Geld-Geheimnisse, Teile der Nachfolge, Gruppenschlüssel. Die Datei bleibt, wo du sie ablegst.", en: "Conversations, rooms, names, profile, settings, verified contacts, AI histories and receipts – encrypted with a passphrase you choose here. Never included: your key, wallet and relay access, money secrets, succession shares, group keys. The file stays wherever you put it." },
  "set.exportPass": { de: "Passphrase für die Datei", en: "Passphrase for the file" },
  "set.exportPass2": { de: "Passphrase wiederholen", en: "Repeat passphrase" },
  "set.exportPassUngleich": { de: "Die beiden Passphrasen sind verschieden.", en: "The two passphrases differ." },
  "set.exportOk": { de: "Datei erstellen", en: "Create file" },
  "set.exportFertig": { de: "Export erstellt: {n} Einträge, verschlüsselt", en: "Export created: {n} entries, encrypted" },
  "set.exportZuGross": { de: "Die Datei ist zu groß für einen Export.", en: "The file is too large for an export." },
  "set.exportUngueltig": { de: "Das ist keine Export-Datei von FreedomStack.", en: "This is not a FreedomStack export file." },
  "set.einlesenTitel": { de: "Export einlesen", en: "Import an export" },
  "set.einlesenWeiter": { de: "Öffnen", en: "Open" },
  "set.einlesenFrage": { de: "Die Datei vom {datum} enthält {n} Einträge. Schlüssel und Zugänge auf diesem Gerät bleiben, wie sie sind.", en: "The file from {datum} contains {n} entries. Keys and access on this device stay as they are." },
  "set.einlesenOk": { de: "Einlesen", en: "Import" },
  "set.ersatzDatei": { de: "ERSATZSCHLÜSSEL – GETRENNT VON DEINEM GERÄT AUFBEWAHREN\n\nprivat: {privat}\nöffentlich: {oeffentlich}\n\nWer diesen Schlüssel UND deinen laufenden hat, ist du.\nAusdrucken oder auf einen Stick, nicht in die Cloud.\n", en: "SPARE KEY – KEEP IT SEPARATE FROM YOUR DEVICE\n\nprivate: {privat}\npublic: {oeffentlich}\n\nWhoever has this key AND your current one is you.\nPrint it or put it on a USB stick, not in the cloud.\n" },
  "set.vorbereitet": { de: "Vorbereitet. Bewahre den Ersatzschlüssel getrennt auf.", en: "Prepared. Keep the spare key separately." },
  "set.welcherGestohlen": { de: "Welcher Schlüssel wurde gestohlen? (öffentlicher Schlüssel, npub oder hex)", en: "Which key was stolen? (public key, npub or hex)" },
  "set.keinPubkey": { de: "Kein gültiger öffentlicher Schlüssel", en: "Not a valid public key" },
  "set.ersatzFrage": { de: "Privater Ersatzschlüssel aus deiner Vorbereitung (64 Zeichen hex)", en: "Private spare key from your preparation (64 hex characters)" },
  "set.ersatzHex": { de: "Der Ersatzschlüssel muss 64 Zeichen hex sein", en: "The spare key must be 64 hex characters" },
  "set.seitWann": { de: "Seit wann vermutest du den Diebstahl? (freiwillig – lieber zu früh; alles danach gilt als unglaubwürdig)", en: "Since when do you suspect the theft? (optional – better too early; everything after it counts as untrustworthy)" },
  "set.datumUnlesbar": { de: "Datum nicht lesbar (JJJJ-MM-TT)", en: "Date not readable (YYYY-MM-DD)" },
  "set.keinMandat": { de: "Kein Mandat nennt diesen Ersatzschlüssel – Kontakte würden den Widerruf nicht anerkennen. Nichts gesendet.", en: "No mandate names this spare key – contacts wouldn't accept the revocation. Nothing sent." },
  "set.widerrufenFertig": { de: "Widerrufen – melde dich mit dem Ersatzschlüssel an (Identität importieren) und sag es deinen Kontakten zusätzlich direkt", en: "Revoked – sign in with the spare key (import identity) and also tell your contacts directly" },
  "set.geraetSprichtFuer": { de: "Dieses Gerät spricht für {person} · {stand}", en: "This device speaks for {person} · {stand}" },
  "set.nurDiesesGeraet": { de: "Nur dieses Gerät. Ein zweites einzurichten ist sicherer, als den Schlüssel zu kopieren.", en: "Only this device. Setting up a second one is safer than copying the key." },
  "set.geraetAktiv": { de: "aktiv", en: "active" },
  "set.geraetAbgelaufen": { de: "abgelaufen", en: "expired" },
  "set.geraetEntzogen": { de: "entzogen", en: "revoked" },
  "set.geraetUnbekannt": { de: "unbekannt", en: "unknown" },
  "set.entziehen": { de: "entziehen", en: "revoke" },
  "set.geraetName": { de: "Name des Geräts, zum Beispiel: Handy", en: "Name of the device, for example: phone" },
  "set.geraetUmfang": { de: "Umfang", en: "Scope" },
  "set.umfangNurChat": { de: "Nur Chat", en: "Chat only" },
  "set.umfangLesenSchreiben": { de: "Lesen und schreiben", en: "Read and write" },
  "set.umfangVoll": { de: "Vollzugriff", en: "Full access" },
  "set.geraetAusstellen": { de: "Vollmacht ausstellen", en: "Issue authorization" },
  "set.geraetCodeTitel": { de: "Gerätecode für {name}", en: "Device code for {name}" },
  "set.geraetCode": { de: "Auf dem neuen Gerät unter „Importieren“ einfügen oder den QR-Code scannen. Er ersetzt NICHT deine Merkphrase – das Gerät schreibt nur in deinem Namen, bis du es entziehst. Nach dem Schließen ist der Code weg; er wird nirgends gespeichert.", en: "On the new device, paste it under “Import” or scan the QR code. It does NOT replace your recovery phrase – the device only writes in your name until you revoke it. Once closed, the code is gone; it is not stored anywhere." },
  "set.geraetCodeFeld": { de: "Gerätecode", en: "Device code" },
  "set.geraetCodeQr": { de: "Gerätecode als QR-Code", en: "Device code as QR code" },
  "set.entziehenFrage": { de: "Der Entzug erreicht nur Clients, die ihn sehen – bis dahin versiegeln sie weiter auch an dieses Gerät. Was das Gerät vorher geschrieben hat, bleibt gültig; zurückdatierte Nachrichten zeigen Kontakte mit Warnung.", en: "The revocation only reaches clients that see it – until then they keep sealing to this device too. What the device wrote before stays valid; contacts show backdated messages with a warning." },
  "set.entzogen": { de: "Entzogen", en: "Revoked" },
  "set.fuerWen": { de: "Für wen meldest du? (npub oder hex)", en: "Whom are you reporting for? (npub or hex)" },
  "set.warum": { de: "Warum? (wird veröffentlicht)", en: "Why? (will be published)" },
  "set.gemeldet": { de: "Gemeldet – ein Lebenszeichen der Person bricht den Vorgang ab", en: "Reported – a sign of life from the person aborts the process" },
  "set.solOfflineWartet": { de: "Offline-SOL-Zahlung empfangen – wird eingereicht, sobald hier Netz da ist", en: "Offline SOL payment received – it is submitted as soon as there is a network here" },
  "set.solOfflineEingereicht": { de: "Offline-SOL-Zahlung empfangen und eingereicht: {sig}…", en: "Offline SOL payment received and submitted: {sig}…" },
  "set.solOfflineFehler": { de: "Offline-SOL-Zahlung nicht eingereicht: {fehler}", en: "Offline SOL payment not submitted: {fehler}" },
  "set.funkEmpfangen": { de: "Verschlüsselte Nachricht über Funk empfangen und ans Netz gegeben", en: "Encrypted message received over radio and passed to the network" },
  "set.paketUnlesbar": { de: "Empfangenes Paket unlesbar", en: "Received packet unreadable" },
  "set.sendezeitAufgebraucht": { de: "Sendezeit aufgebraucht (1 % je Stunde) – weiter in etwa {min} min, {n} Pakete offen", en: "Airtime used up (1% per hour) – continuing in about {min} min, {n} packets pending" },
  "set.paketeOffen": { de: "{n} Pakete offen, etwa {s} s", en: "{n} packets pending, about {s} s" },
  "set.unvollstaendig": { de: "{n} Nachricht(en) unvollständig", en: "{n} message(s) incomplete" },
  "set.bereit": { de: "bereit", en: "ready" },
  "set.keinGeraetezugriff": { de: "kein Gerätezugriff", en: "no device access" },
  "set.verbundenMit": { de: "verbunden: {name}", en: "connected: {name}" },
  "set.meshtasticRegion": { de: "Am Gerät ist keine Region gesetzt – so sendet es nicht. Wähle sie in der Meshtastic-App (in Europa EU_868).", en: "No region is set on the device – it does not transmit like this. Choose it in the Meshtastic app (in Europe EU_868)." },
  "set.meshtasticSendenAus": { de: "Senden ist am Gerät ausgeschaltet – einschalten in den LoRa-Einstellungen der Meshtastic-App.", en: "Transmitting is switched off on the device – switch it on in the LoRa settings of the Meshtastic app." },
  "set.meshtasticKanalFehlt": { de: "Auf dem Gerät fehlt der Kanal „{name}“. Lege ihn mit dem Knopf an oder in der Meshtastic-App als zweiten Kanal: Name „{name}“, Schlüssel {psk}. Der Schlüssel ist öffentlich – geschützt sind die Nachrichten durch ihre Umschläge.", en: "The device has no “{name}” channel. Create it with the button or in the Meshtastic app as a second channel: name “{name}”, key {psk}. The key is public – the messages are protected by their envelopes." },
  "set.meshtasticKanalAnlegen": { de: "Kanal „freedom“ anlegen", en: "Create “freedom” channel" },
  "set.meshtasticKanalFrage": { de: "Kanal „freedom“ auf dem Gerät anlegen?", en: "Create the “freedom” channel on the device?" },
  "set.meshtasticKanalText": { de: "Die App legt auf deinem Meshtastic-Gerät einen zweiten Kanal „freedom“ an; der Hauptkanal bleibt, wie er ist. Ein Kanal „freedom“ mit anderem Schlüssel wird ersetzt. Der Schlüssel ist öffentlich – geschützt sind die Nachrichten durch ihre Umschläge.", en: "The app creates a second channel “freedom” on your Meshtastic device; the primary channel stays as it is. A “freedom” channel with a different key is replaced. The key is public – the messages are protected by their envelopes." },
  "set.meshtasticKanalAngelegt": { de: "Kanal „freedom“ angelegt.", en: "“freedom” channel created." },
  "set.meshtasticKanalNicht": { de: "Der Kanal ließ sich nicht anlegen – lege ihn in der Meshtastic-App an.", en: "The channel could not be created – create it in the Meshtastic app." },
  "set.meshtasticKanalFremd": { de: "Der Kanal „{name}“ auf dem Gerät hat einen anderen Schlüssel – andere Freedom-Geräte lesen ihn nicht. Ändere ihn in der Meshtastic-App auf {psk}.", en: "The “{name}” channel on the device has a different key – other Freedom devices cannot read it. Change it in the Meshtastic app to {psk}." },
  "set.funkVerbunden": { de: "Funkgerät verbunden", en: "Radio connected" },
  "set.bluetoothVerbunden": { de: "Bluetooth verbunden", en: "Bluetooth connected" },
  "set.keineOnion": { de: "Keine .onion-Relay-Adresse (ws://….onion oder wss://….onion)", en: "Not an .onion relay address (ws://….onion or wss://….onion)" },
  "set.laeuft": { de: "läuft …", en: "running …" },
  "set.selbsttestOk": { de: "bestanden: {text} ({ms} ms)", en: "passed: {text} ({ms} ms)" },
  "set.selbsttestFehler": { de: "gescheitert: {text} ({ms} ms)", en: "failed: {text} ({ms} ms)" },
  "set.schieneGesetzt": { de: "Standard-Schiene: {schiene}", en: "Default rail: {schiene}" },
  "set.kontakteGesichert": { de: "Kontakte verschlüsselt gesichert.", en: "Contacts backed up encrypted." },
  "set.kontakteGesichertNeu": { de: "Kontakte verschlüsselt gesichert – {n} von anderen Geräten übernommen.", en: "Contacts backed up encrypted – {n} taken over from other devices." },
  "set.abgleichAus": { de: "Abgleich aus – die Liste auf den Relays ist geleert.", en: "Sync off – the list on the relays has been emptied." },
  "set.kontaktlisteFehler": { de: "Kontaktliste: {fehler}", en: "Contact list: {fehler}" },
  "set.sofort": { de: "Direktnachrichten gehen sofort hinaus.", en: "Direct messages go out immediately." },
  "set.verzoegert": { de: "Direktnachrichten gehen bis zu {s} s verzögert hinaus – jede Kopie einzeln.", en: "Direct messages go out delayed by up to {s} s – each copy separately." },
  "set.paketeAusgegeben": { de: "{n} Pakete als Datei ausgegeben", en: "{n} packets exported as a file" },
  "set.nichtsZuSendenChat": { de: "Nichts zu senden – Post für einen Kontakt nimmst du im Chat mit (⇪).", en: "Nothing to send – you take mail for a contact along in the chat (⇪)." },
  "set.paketeEingelesen": { de: "{n} Pakete eingelesen", en: "{n} packets imported" },
  "set.ueber": { de: "Über {weg}:", en: "Over {weg}:" },
  "set.paketeOffenKurz": { de: "{n} Pakete offen", en: "{n} packets pending" },
  "set.leseDatei": { de: "lese die eigene Datei …", en: "reading the app's own file …" },
  "set.exportiertPruefsumme": { de: "Exportiert. Prüfsumme:", en: "Exported. Checksum:" },
  "set.exportiertText": { de: "Wer die Datei von dir bekommt, kann sie damit gegen das signierte Manifest auf den Relays prüfen.", en: "Whoever gets the file from you can check it against the signed manifest on the relays." },
  "set.appExportiert": { de: "App exportiert – jetzt bist du eine Bezugsquelle", en: "App exported – now you are a source" },
  "set.exportFehler": { de: "Selbst-Export nicht möglich ({fehler}). Im Einzeldatei-Build funktioniert er; hinter einem Server mit Zugriffsschutz kann die Seite sich nicht selbst lesen.", en: "Self-export not possible ({fehler}). It works in the single-file build; behind a server with access protection the page can't read itself." },
  "set.neuereVersion": { de: "Neuere Version verfügbar: {version}.", en: "Newer version available: {version}." },
  "set.bezugsquellen": { de: "Bezugsquellen: {quellen}", en: "Sources: {quellen}" },
  "set.fixiert": { de: "Fixiert: Version {version}.", en: "Pinned: version {version}." },
  "set.fixieren": { de: "Version {version} fixieren", en: "Pin version {version}" },
  "set.fixierungAufheben": { de: "Fixierung aufheben", en: "Unpin" },
  "set.echtheitFehler": { de: "Echtheit nicht prüfbar: {fehler}", en: "Authenticity can't be checked: {fehler}" },
  "set.versionFixiert": { de: "Version {version} fixiert", en: "Version {version} pinned" },
  "set.tresorGesperrt": { de: "Tresor gesperrt – erst entsperren.", en: "Vault locked – unlock it first." },
  "set.nichtsGesammelt": { de: "Nichts gesammelt.", en: "Nothing collected." },
  "set.pruefbudget": { de: "Prüfbudget: {betrag} – bleibt bei dir und bezahlt Prüfrunden.", en: "Check budget: {betrag} – stays with you and pays for check rounds." },
  "set.gesammelt": { de: "{ziel}: {betrag} gesammelt", en: "{ziel}: {betrag} collected" },
  "set.ausgangUnklar": { de: "{ziel}: {betrag} – Ausgang unklar, sieh in deiner Wallet nach: ", en: "{ziel}: {betrag} – outcome unclear, check your wallet: " },
  "set.kamAn": { de: "kam an", en: "arrived" },
  "set.kamNichtAn": { de: "kam nicht an", en: "didn't arrive" },
  "set.anteileGezahlt": { de: "{betrag} an Anteile gezahlt", en: "{betrag} paid in shares" },
  "set.nichtsFaellig": { de: "Nichts fällig – oder keine Lightning-Wallet verbunden", en: "Nothing due – or no Lightning wallet connected" },
  "set.geraetKauftNicht": { de: "Als Gerät kauft die Person den Zugang – auf dem Hauptgerät.", en: "As a device: the person buys access – on the main device." },
  "set.zugangBis": { de: "Zugang bis {datum}.", en: "Access until {datum}." },
  "set.verlaengern": { de: "Verlängern", en: "Renew" },
  "set.laeuftAb": { de: "Zugang zu {relay} läuft am {datum} ab – „Verlängern“ kauft neue Tage, nach einer Rückfrage.", en: "Access to {relay} expires on {datum} – “Renew” buys more days, after you confirm." },
  "set.abgelaufen": { de: "Zugang zu {relay} ist am {datum} abgelaufen – „Verlängern“ kauft neue Tage, nach einer Rückfrage.", en: "Access to {relay} expired on {datum} – “Renew” buys more days, after you confirm." },
  "set.erinnerung": { de: "Relay-Zugang läuft ab – verlängern unter Settings › Verbindung", en: "Relay access is expiring – renew it in Settings › Connection" },
  "set.frageRelay": { de: "frage den Relay …", en: "asking the relay …" },
  "set.keinVerkauf": { de: "Dieser Relay verkauft keinen Zugang (oder ist nicht erreichbar).", en: "This relay doesn't sell access (or isn't reachable)." },
  "set.preisZeile": { de: "{tage} Tage: {preis}", en: "{tage} days: {preis}" },
  "set.oder": { de: " oder ", en: " or " },
  "set.nurZahlende": { de: " · nimmt nur Post von und an Zahlende an", en: " · only accepts posts from and to paying users" },
  "set.nurAngemeldete": { de: " · Umschläge nur an Angemeldete", en: " · envelopes only to signed-in users" },
  "set.hinweisSol": { de: "Der Betreiber sieht deine Absenderadresse, und auf der Kette sieht jeder, dass sie diesen Relay bezahlt hat.", en: "The operator sees your sender address, and on the chain everyone sees that it paid this relay." },
  "set.hinweisSats": { de: "Der Betreiber sieht nur die Zahlung.", en: "The operator only sees the payment." },
  "set.kaufFrage": { de: "Zugang zu {url} für {tage} Tage kaufen? {hinweis}", en: "Buy access to {url} for {tage} days? {hinweis}" },
  "set.holeUndZahle": { de: "hole Angebot und zahle …", en: "fetching offer and paying …" },
  "set.bezahltBis": { de: "Bezahlt – Zugang bis {datum}.", en: "Paid – access until {datum}." },
  "set.bezahltOffen": { de: "Bezahlt, aber der Relay bestätigt noch nicht – später „Zahlung erneut prüfen“.", en: "Paid, but the relay hasn't confirmed yet – later use “Check payment again”." },
  "set.nichtGekauft": { de: "Nicht gekauft: {fehler}", en: "Not bought: {fehler}" },
  "set.nochNichtBestaetigt": { de: "Noch nicht bestätigt.", en: "Not confirmed yet." },
  "set.nichtGeprueft": { de: "Nicht geprüft: {fehler}", en: "Not checked: {fehler}" },
  "set.geraetSatz": { de: "Als Gerät nutzt du den Satz der Person – ändern nur auf dem Hauptgerät.", en: "As a device you use the person's set – change it only on the main device." },
  "set.keinSatz": { de: "Noch kein eigener Satz – die App legt ihn beim ersten Verbinden an.", en: "No set of your own yet – the app creates it on the first connection." },
  "set.keineIdentitaet": { de: "Keine Identität.", en: "No identity." },
  "set.veroeffentliche": { de: "veröffentliche …", en: "publishing …" },
  "set.veroeffentlicht": { de: "Veröffentlicht: {n} Relays – NIP-65-Liste und Posteingang.", en: "Published: {n} relays – NIP-65 list and inbox." },
  "set.nichtVeroeffentlichtKeiner": { de: "Nicht veröffentlicht – kein Relay nahm die Liste an. Der alte Satz gilt weiter.", en: "Not published – no relay accepted the list. The old set stays in effect." },
  "set.nichtVeroeffentlicht": { de: "Nicht veröffentlicht: {fehler}", en: "Not published: {fehler}" },
  // Neue Oberfläche in der Desktop-Hülle installieren (6.1a3c)
  "set.huelleBeigelegt": { de: "Oberfläche dieser App: wie beigelegt.", en: "Interface of this app: as bundled." },
  "set.huelleInstalliert": { de: "Oberfläche dieser App: installiert, Version {version}.", en: "Interface of this app: installed, version {version}." },
  "set.huelleNurBeigelegt": { de: "Diesmal mit der beigelegten Fassung gestartet (--oberflaeche=beigelegt) – die installierte bleibt.", en: "Started with the bundled version this time (--oberflaeche=beigelegt) – the installed one stays." },
  "set.huelleVorher": { de: "Zurück zur vorigen Fassung: die Desktop-App mit --oberflaeche=vorher starten.", en: "Back to the previous version: start the desktop app with --oberflaeche=vorher." },
  "set.huelleAndroidZurueck": { de: "Zurück zur beigelegten Fassung: in den Einstellungen von Android bei dieser App den Cache leeren (Daten und Tresor bleiben).", en: "Back to the bundled version: clear this app's cache in the Android settings (data and vault stay)." },
  "set.huelleRueckDesktop": { de: "Zurück geht es nur über den Start mit --oberflaeche=vorher.", en: "Going back is only possible by starting with --oberflaeche=vorher." },
  "set.huelleRueckAndroid": { de: "Zurück zur beigelegten Fassung geht es über „Cache leeren“ in den Einstellungen von Android.", en: "Going back to the bundled version works via “Clear cache” in the Android settings." },
  "set.huelleInstallieren": { de: "Version {version} installieren", en: "Install version {version}" },
  "set.huelleLaedt": { de: "Lade Version {version} und prüfe sie …", en: "Downloading version {version} and checking it …" },
  "set.huelleFrageTitel": { de: "Version {version} installieren?", en: "Install version {version}?" },
  "set.huelleFrageText": { de: "Die Datei ({mb} MB) ist geladen und passt zum signierten Manifest: {signierer} vertraute Signierer, erschienen am {datum}. Die App prüft die Signaturen noch einmal selbst; nach dem Neuladen läuft die neue Fassung. {rueckweg}", en: "The file ({mb} MB) is downloaded and matches the signed manifest: {signierer} trusted signers, released on {datum}. The app checks the signatures once more itself; after reloading, the new version runs. {rueckweg}" },
  "set.huelleOk": { de: "Installieren", en: "Install" },
  "set.huelleFertigTitel": { de: "Installiert", en: "Installed" },
  "set.huelleFertigText": { de: "Version {version} ist installiert. Die Seite lädt jetzt neu.", en: "Version {version} is installed. The page reloads now." },
  "set.huelleFLaden": { de: "Keine Quelle lieferte genau die bestätigte Datei – nicht installiert.", en: "No source delivered exactly the confirmed file – not installed." },
  "set.huelleFKodierung": { de: "Die Datei ist kein gültiges UTF-8 – nicht installiert.", en: "The file isn't valid UTF-8 – not installed." },
  "set.huelleFKeinBeleg": { de: "Keine signierten Belege – nicht installiert.", en: "No signed proofs – not installed." },
  "set.huelleFZuWenig": { de: "Die App findet nicht genug vertraute Signaturen – nicht installiert.", en: "The app doesn't find enough trusted signatures – not installed." },
  "set.huelleFAbweichend": { de: "Die Datei passt nicht zu den Signaturen – nicht installiert.", en: "The file doesn't match the signatures – not installed." },
  "set.huelleFNichtNeuer": { de: "Diese Fassung ist nicht neuer als die laufende oder die installierte – nicht installiert.", en: "This version isn't newer than the running or the installed one – not installed." },
  "set.huelleFZuGross": { de: "Die Datei ist zu groß – nicht installiert.", en: "The file is too large – not installed." },
  "set.huelleFKeineAblage": { de: "Die App hat keinen Ablageort – nicht installiert.", en: "The app has no storage location – not installed." },
  "set.huelleFAblage": { de: "Ablegen ist gescheitert – die bisherige Fassung bleibt.", en: "Storing failed – the previous version stays." },
  "set.huelleFKeineHuelle": { de: "Installieren geht nur in der App (Desktop oder Android), nicht im Browser.", en: "Installing only works in the app (desktop or Android), not in the browser." },
  "set.huelleFUnbekannt": { de: "Die App hat die Installation nicht bestätigt – nicht installiert.", en: "The app didn't confirm the installation – not installed." },
  // Direkt oder Tor in der Desktop-Hülle (6.1b1b)
  "set.torHaken": { de: "Tor in dieser App: der gesamte Verkehr über Tor (Desktop)", en: "Tor in this app: all traffic over Tor (desktop)" },
  "set.torText": { de: "Langsamer als direkt – Relays, Solana-RPC und Downloads sehen deine IP-Adresse nicht mehr. Anrufe laufen nicht über Tor. Ist Tor nicht verbunden, geht nichts hinaus – nie still direkt. Umschalten startet die App neu.", en: "Slower than direct – relays, Solana RPC and downloads no longer see your IP address. Calls don't go over Tor. If Tor isn't connected, nothing goes out – never silently direct. Switching restarts the app." },
  "set.torBereit": { de: "Tor: verbunden – der Verkehr dieser App geht über Tor.", en: "Tor: connected – this app's traffic goes over Tor." },
  "set.torVerbindet": { de: "Tor: verbindet … bis dahin geht nichts hinaus.", en: "Tor: connecting … until then nothing goes out." },
  "set.torFehlerStart": { de: "Tor startet nicht – es geht nichts hinaus. Neu starten oder auf direkt umstellen.", en: "Tor doesn't start – nothing goes out. Restart or switch to direct." },
  "set.torFehlerNetz": { de: "Tor erreicht das Tor-Netz nicht – es geht nichts hinaus. Neu starten oder auf direkt umstellen.", en: "Tor can't reach the Tor network – nothing goes out. Restart or switch to direct." },
  "set.torDirekt": { de: "Direkt: Relays und Dienste sehen deine IP-Adresse.", en: "Direct: relays and services see your IP address." },
  "set.torAbStart": { de: "Tor ist gewählt – gilt ab dem nächsten Start.", en: "Tor is selected – applies from the next start." },
  "set.direktAbStart": { de: "Direkt ist gewählt – gilt ab dem nächsten Start.", en: "Direct is selected – applies from the next start." },
  "set.torAnTitel": { de: "Über Tor verbinden?", en: "Connect over Tor?" },
  "set.torAnText": { de: "Die App startet neu und geht danach nur noch über Tor ins Netz – langsamer, dafür sehen Relays, Solana-RPC und Downloads deine IP-Adresse nicht. Anrufe laufen nicht über Tor. Ist Tor nicht verbunden, geht nichts hinaus.", en: "The app restarts and then only goes online over Tor – slower, but relays, Solana RPC and downloads don't see your IP address. Calls don't go over Tor. If Tor isn't connected, nothing goes out." },
  "set.torAusTitel": { de: "Wieder direkt verbinden?", en: "Connect directly again?" },
  "set.torAusText": { de: "Die App startet neu und verbindet sich danach direkt – Relays und Dienste sehen dann wieder deine IP-Adresse.", en: "The app restarts and then connects directly – relays and services see your IP address again." },
  "set.torNeustart": { de: "Neu starten", en: "Restart" },
  "set.torNichtGespeichert": { de: "Die Wahl ließ sich nicht speichern – es bleibt, wie es war.", en: "The choice couldn't be saved – it stays as it was." },
};
