/** Texte des Währung-Tabs (8.16e): Seite, tabs/waehrung.ts (seit C-5a auch tausch.ts, hinterlegen.ts), eingebaute Wallet, offline zahlen. */
import type { Texte } from "../i18n.js";

export const waehrung: Texte = {
  // Seite (index.html)
  "waehr.untertitel": { de: "Lightning, Solana, Tausch, Hinterlegen und Zahlen.", en: "Lightning, Solana, swaps, deposits and payments." },
  "waehr.walletVerbinden": { de: "Wallet verbinden", en: "Connect wallet" },
  "waehr.solDeposit": { de: "+ SOL hinterlegen", en: "+ SOL deposit" },
  "waehr.tabUebersicht": { de: "Übersicht", en: "Overview" },
  "waehr.tabTauschen": { de: "Tauschen", en: "Swap" },
  // C-8 (C.6a, E2): „Liquidität“ hieß der Reiter mit Deposit und Zahlkanal; „Zahlen“ kam aus Settings › Gebühren
  "waehr.tabHinterlegen": { de: "Hinterlegen", en: "Deposit" },
  "waehr.tabZahlen": { de: "Zahlen", en: "Pay" },
  "waehr.nwcPh": { de: "nostr+walletconnect://… (aus deiner Wallet)", en: "nostr+walletconnect://… (from your wallet)" },
  "waehr.trennen": { de: "trennen", en: "disconnect" },
  "waehr.nichtVerbunden": { de: "Nicht verbunden", en: "Not connected" },
  "waehr.solAdressePh": { de: "SOL-Adresse", en: "SOL address" },
  "waehr.verbinden": { de: "Verbinden", en: "Connect" },
  "waehr.eingebaut": { de: "Eingebaute Wallet", en: "Built-in wallet" },
  "waehr.eingebautText": { de: "– ohne Browser-Wallet. Schlüssel aus deinen 12 Wörtern, nur im Tresor. Zahlt Zaps und Trinkgeld und empfängt beim Tausch sats → SOL an einer frischen Adresse; SOL → sats und Deposit brauchen eine verbundene Wallet.", en: "– no browser wallet needed. Key from your 12 words, only in the vault. Pays zaps and tips and receives sats → SOL swaps at a fresh address; SOL → sats and deposits need a connected wallet." },
  "waehr.einrichten": { de: "einrichten", en: "set up" },
  "waehr.empfangenAn": { de: "Empfangen an:", en: "Receive at:" },
  "waehr.limitText": { de: "SOL in 24 Std. ohne Nachfrage", en: "SOL per 24 h without asking" },
  "waehr.speichern": { de: "speichern", en: "save" },
  "waehr.adresseKopieren": { de: "Adresse kopieren", en: "Copy address" },
  "waehr.frischeAdresse": { de: "frische Adresse", en: "fresh address" },
  "waehr.neueAbleiten": { de: "neue ableiten", en: "derive new ones" },
  "waehr.entfernen": { de: "von diesem Gerät entfernen", en: "remove from this device" },
  "waehr.offlineTitel": { de: "Ohne Internet zahlen", en: "Pay without internet" },
  "waehr.nonceAnlegen": { de: "Nonce-Konto anlegen", en: "Create nonce account" },
  "waehr.wertAuffrischen": { de: "Wert auffrischen", en: "Refresh value" },
  "waehr.offlineZahlen": { de: "offline zahlen", en: "pay offline" },
  "waehr.kontoSchliessen": { de: "Konto schließen", en: "Close account" },
  "waehr.nonceText": { de: "Ein Nonce-Konto hält einen Wert, mit dem eine Überweisung ohne Netz gültig bleibt. Signiert wird hier, eingereicht von einem Gerät mit Netz – über Funk oder per Datei. Ein Wert zahlt einmal. Wer mithört, sieht – wie später auf der Kette – Adressen und Betrag.", en: "A nonce account holds a value that keeps a transfer valid without a network. It is signed here and submitted by a device with a network – over radio or as a file. One value pays once. Anyone listening sees – as later on the chain – addresses and amount." },
  "waehr.tauschangebote": { de: "Tauschangebote", en: "Swap offers" },
  "waehr.inWalletZahlen": { de: "in Wallet zahlen", en: "pay in wallet" },
  "waehr.solEinloesen": { de: "SOL einlösen", en: "Claim SOL" },
  "waehr.preimageSicherung": { de: "Preimage-Sicherung", en: "Preimage backup" },
  "waehr.aktualisieren": { de: "Aktualisieren", en: "Refresh" },
  "waehr.solHinterlegen": { de: "SOL hinterlegen", en: "Deposit SOL" },
  "waehr.betragSolPh": { de: "Betrag in SOL", en: "Amount in SOL" },
  "waehr.providerPh": { de: "Pubkey des Providers (auto)", en: "provider pubkey (auto)" },
  "waehr.providerSolPh": { de: "SOL-Adresse des Providers (auto)", en: "provider's SOL address (auto)" },
  "waehr.hinterlegen": { de: "hinterlegen", en: "deposit" },
  "waehr.zurueckholen": { de: "zurückholen", en: "refund" },
  // Lightning (tabs/waehrung.ts)
  "waehr.lnHinweisHandy": { de: "Verbinde deine Wallet über einen NWC-Link oder QR-Code aus deiner Wallet-App.", en: "Connect your wallet with an NWC link or QR code from your wallet app." },
  "waehr.lnHinweisBrowser": { de: "Browser-Wallet erkannt. Ein NWC-Link funktioniert zusätzlich auf allen Geräten.", en: "Browser wallet detected. An NWC link also works on every device." },
  "waehr.lnHinweisNwc": { de: "Verbinde deine Wallet über einen NWC-Link aus deiner Wallet-App.", en: "Connect your wallet with an NWC link from your wallet app." },
  "waehr.nwcEinfuegen": { de: "Verbindungs-URI aus der Wallet einfügen (Alby Hub, Coinos, Mutiny …).", en: "Paste the connection URI from your wallet (Alby Hub, Coinos, Mutiny …)." },
  "waehr.fuerNwc": { de: "die Wallet-Verbindung (NWC)", en: "the wallet connection (NWC)" },
  "waehr.nurImTresor": { de: "Nicht verbunden: Die Verbindung wird nur im Tresor gespeichert.", en: "Not connected: the connection is only stored in the vault." },
  "waehr.verbinde": { de: "verbinde …", en: "connecting …" },
  "waehr.nwcNurPrivat": { de: "NWC nur über mein eigenes oder ein .onion-Relay – sonst sieht ein fremdes Relay, wann du zahlst", en: "NWC only via my own or an .onion relay – otherwise a third-party relay sees when you pay" },
  "waehr.nwcEigenesRelayPh": { de: "wss://… (dein eigenes Relay, optional)", en: "wss://… (your own relay, optional)" },
  "waehr.nwcKeinPrivatesRelay": { de: "Die Wallet-Verbindung nennt weder dein eigenes noch ein .onion-Relay. Trag es in der Wallet ein und füge die neue Verbindung ein – oder schalte „nur eigenes oder .onion“ aus.", en: "The wallet connection names neither your own nor an .onion relay. Add one in the wallet and paste the new connection – or turn off “only own or .onion”." },
  "waehr.nwcRelayFremd": { de: "über ein fremdes Relay", en: "via a third-party relay" },
  "waehr.nwcRelayPrivat": { de: "nur über eigenes oder .onion-Relay", en: "only via own or .onion relay" },
  "waehr.bolt12Ja": { de: "BOLT12 angeboten ({methoden}) – die App nutzt es noch nicht, Rechnungen gehen versiegelt", en: "BOLT12 offered ({methoden}) – the app does not use it yet, invoices go sealed" },
  "waehr.bolt12Nein": { de: "kein BOLT12 – Rechnungen gehen versiegelt", en: "no BOLT12 – invoices go sealed" },
  "waehr.nwcVerbunden": { de: "verbunden ({verschluesselung}, {n} Methoden)", en: "connected ({verschluesselung}, {n} methods)" },
  "waehr.nichtGeloescht": { de: "nicht gelöscht: {fehler}", en: "not deleted: {fehler}" },
  "waehr.getrennt": { de: "getrennt", en: "disconnected" },
  // Solana verbinden
  "waehr.welcheWallet": { de: "Welche Wallet?", en: "Which wallet?" },
  "waehr.phantomOeffnen": { de: "Phantom öffnen", en: "Open Phantom" },
  "waehr.solflareOeffnen": { de: "Solflare öffnen", en: "Open Solflare" },
  "waehr.verbunden": { de: "verbunden", en: "connected" },
  "waehr.knopfVerbunden": { de: "Verbunden", en: "Connected" },
  // Tausch sats → SOL
  "waehr.keineAngebote": { de: "keine LP-Angebote gefunden", en: "no LP offers found" },
  "waehr.tauschen": { de: "tauschen", en: "swap" },
  "waehr.veraltet": { de: "veraltet", en: "outdated" },
  "waehr.veraltetTitel": { de: "Dieser LP liest keine versiegelten Anfragen. Die App fragt ihn nicht an – Adresse bzw. Rechnung stünden sonst offen auf den Relays.", en: "This LP doesn't read sealed requests. The app doesn't ask it – address or invoice would otherwise be public on the relays." },
  "waehr.relayFehler": { de: "Relay-Fehler: {fehler}", en: "Relay error: {fehler}" },
  // Dialoge statt prompt()/confirm() (C-1a)
  "waehr.tauschTitel": { de: "sats gegen SOL tauschen", en: "Swap sats for SOL" },
  "waehr.betragSats": { de: "Betrag in sats", en: "Amount in sats" },
  "waehr.weiter": { de: "Weiter", en: "Continue" },
  "waehr.bevorTitel": { de: "Bevor du tauschst", en: "Before you swap" },
  "waehr.bevorDuTauschst": { de: "{befunde}\n\nEmpfohlen:\n{schritte}", en: "{befunde}\n\nRecommended:\n{schritte}" },
  "waehr.trotzdemWeiter": { de: "Trotzdem weiter", en: "Continue anyway" },
  "waehr.empfangsadresse": { de: "Deine Solana-Empfangsadresse", en: "Your Solana receiving address" },
  "waehr.empfangsadresseFrisch": { de: "Vorgeschlagen: eine frische Adresse deiner eingebauten Wallet – nur für diesen Tausch.", en: "Suggested: a fresh address of your built-in wallet – only for this swap." },
  "waehr.keineSolAdresse": { de: "Keine gültige Solana-Adresse", en: "Not a valid Solana address" },
  "waehr.tauschAnfragen": { de: "Tausch anfragen", en: "Request swap" },
  "waehr.fuerTausch": { de: "den Tausch", en: "the swap" },
  "waehr.anfrageGesendet": { de: "Tauschanfrage gesendet – warte auf die Rechnung …", en: "Swap request sent – waiting for the invoice …" },
  "waehr.fehler": { de: "Fehler: {fehler}", en: "Error: {fehler}" },
  "waehr.lpAbgelehnt": { de: "Der LP hat abgelehnt: {grund}", en: "The LP declined: {grund}" },
  "waehr.rechnungErhalten": { de: "Rechnung erhalten. Prüfe die Sperre auf der Kette – noch nicht zahlen.", en: "Invoice received. Checking the lock on the chain – don't pay yet." },
  "waehr.ohneSwapId": { de: "Der LP hat keine swap_id mitgeschickt – die Gegenleistung ist nicht prüfbar. Nicht zahlen.", en: "The LP sent no swap_id – the counterpart can't be checked. Don't pay." },
  "waehr.nichtZahlen": { de: "Nicht zahlen.", en: "Don't pay." },
  "waehr.geprueft": { de: "Geprüft.", en: "Checked." },
  "waehr.nachDemBezahlen": { de: "Nach dem Bezahlen unten einlösen – sonst läuft der Tausch zurück.", en: "After paying, claim below – otherwise the swap reverts." },
  "waehr.gegenleistungGeprueft": { de: "Gegenleistung geprüft – Rechnung kann bezahlt werden", en: "Counterpart checked – the invoice can be paid" },
  "waehr.pruefungUnmoeglich": { de: "Prüfung nicht möglich ({fehler}). Im Zweifel nicht zahlen.", en: "Check not possible ({fehler}). If in doubt, don't pay." },
  "waehr.keineLpAntwort": { de: "keine Antwort des LP in 90 s", en: "no LP answer within 90 s" },
  "waehr.nichtGezahlt": { de: "Nicht gezahlt: {grund}", en: "Not paid: {grund}" },
  "waehr.vorabTitel": { de: "Vorab-Gebühr", en: "Upfront fee" },
  "waehr.zahlen": { de: "Zahlen", en: "Pay" },
  "waehr.vorabFrage": { de: "Der LP verlangt vorab {sats} sats – nicht erstattbar, als Schutz gegen Anfragen, die nur Liquidität binden. Erst danach sperrt er die SOL. Zahlen?", en: "The LP asks for {sats} sats upfront – non-refundable, as protection against requests that only tie up liquidity. Only then does it lock the SOL. Pay?" },
  "waehr.vorabAbgelehnt": { de: "Vorab-Gebühr nicht gezahlt – der Tausch findet nicht statt.", en: "Upfront fee not paid – the swap won't happen." },
  "waehr.vorabFehler": { de: "Vorab-Gebühr nicht gezahlt: {fehler}", en: "Upfront fee not paid: {fehler}" },
  "waehr.vorabBezahlt": { de: "Vorab-Gebühr bezahlt – warte, bis der LP die SOL sperrt …", en: "Upfront fee paid – waiting for the LP to lock the SOL …" },
  "waehr.adresseOhneWallet": { de: "Die Empfangsadresse gehört keiner verbundenen Wallet – verbinde die Wallet mit dieser Adresse, um einzulösen.", en: "The receiving address belongs to no connected wallet – connect the wallet with this address to claim." },
  "waehr.preimageFehlt": { de: "Preimage nicht gefunden oder unpassend – ohne es ist kein Einlösen möglich.", en: "Preimage not found or not matching – claiming is impossible without it." },
  "waehr.eingeloest": { de: "Eingelöst.", en: "Claimed." },
  "waehr.solAufAdresse": { de: "Die SOL sind auf deiner Adresse.", en: "The SOL are on your address." },
  "waehr.keinRelayer": { de: "Du hast kein SOL für die Gebühr, und kein Relayer ist erreichbar. Lege etwas SOL auf deine Adresse und löse dann ein.", en: "You have no SOL for the fee, and no relayer is reachable. Put some SOL on your address and claim then." },
  "waehr.mieteReichtNicht": { de: "Der Betrag reicht nach der Erstattung nicht für ein neues Solana-Konto (Mindestmiete). Lege etwas SOL auf deine Adresse und löse dann selbst ein.", en: "After the refund the amount isn't enough for a new Solana account (minimum rent). Put some SOL on your address and claim yourself." },
  "waehr.relayerTitel": { de: "Über einen Relayer einlösen", en: "Claim via a relayer" },
  "waehr.einloesen": { de: "Einlösen", en: "Claim" },
  "waehr.relayerFrage": { de: "Du hast kein SOL für die Gebühr. Ein Relayer zahlt sie; du erstattest ihm höchstens {betrag} aus den eingelösten SOL. Einlösen?", en: "You have no SOL for the fee. A relayer pays it; you refund it at most {betrag} from the claimed SOL. Claim?" },
  "waehr.relayerLoestEin": { de: "Relayer löst ein …", en: "Relayer is claiming …" },
  "waehr.relayerLehntAb": { de: "Relayer lehnt ab: {grund} – nächster …", en: "Relayer declines: {grund} – next …" },
  "waehr.keinRelayerEingeloest": { de: "Kein Relayer hat eingelöst. Lege etwas SOL auf deine Adresse und löse selbst ein – vor Ablauf der Frist.", en: "No relayer claimed. Put some SOL on your address and claim yourself – before the deadline." },
  "waehr.sperrenZurueck": { de: "{n} Sperre(n) zurückgeholt: {betrag}", en: "{n} lock(s) refunded: {betrag}" },
  "waehr.sicherungGeladen": { de: "Sicherung heruntergeladen – sicher aufbewahren", en: "Backup downloaded – keep it safe" },
  // Tausch SOL → sats
  "waehr.angebotOhneKonto": { de: "Dieses Angebot nennt kein SOL-Konto oder keinen Kurs.", en: "This offer names no SOL account or no rate." },
  "waehr.erstSolanaWallet": { de: "Erst eine Solana-Wallet verbinden – mit ihr werden die SOL gesperrt.", en: "Connect a Solana wallet first – it locks the SOL." },
  "waehr.rueckTitel": { de: "SOL gegen sats tauschen", en: "Swap SOL for sats" },
  "waehr.wievieleSats": { de: "Wie viele sats möchtest du bekommen? ({min}–{max})", en: "How many sats do you want to receive? ({min}–{max})" },
  "waehr.betragBereich": { de: "Dieser LP tauscht {min} bis {max} sats", en: "This LP swaps {min} to {max} sats" },
  "waehr.rechnungFrage": { de: "Rechnung (bolt11) deiner Lightning-Wallet über genau {sats} sats", en: "Invoice (bolt11) from your Lightning wallet for exactly {sats} sats" },
  "waehr.rechnungNichtErstellt": { de: "Rechnung nicht erstellt: {fehler}", en: "Invoice not created: {fehler}" },
  "waehr.sperrenFrage": { de: "Du sperrst {betrag} (inkl. {gebuehr} % Gebühr) für {sats} sats. Zahlt der LP nicht, bekommst du die SOL ab {ab} zurück. Sperren?", en: "You lock {betrag} (incl. {gebuehr}% fee) for {sats} sats. If the LP doesn't pay, you get the SOL back from {ab}. Lock?" },
  "waehr.sperren": { de: "Sperren", en: "Lock" },
  "waehr.sperreNichtAngelegt": { de: "Sperre nicht angelegt: {fehler}", en: "Lock not created: {fehler}" },
  "waehr.keineAntwortLp": { de: "Keine Antwort des LP. {text}", en: "No answer from the LP. {text}" },
  // Deposit
  "waehr.erstSolanaVerbinden": { de: "Erst eine Solana-Wallet verbinden", en: "Connect a Solana wallet first" },
  "waehr.ungueltigerBetrag": { de: "Ungültiger Betrag", en: "Invalid amount" },
  "waehr.keinProvider": { de: "Kein Provider – erst eine KI-Anfrage stellen oder den Pubkey angeben", en: "No provider – make an AI request first or enter the pubkey" },
  "waehr.keinMarktkurs": { de: "Kein Marktkurs SOL/sats gefunden – ohne ihn wäre der Preis in SOL geraten.", en: "No SOL/sats market rate found – without it the SOL price would be a guess." },
  "waehr.keinAngebotProvider": { de: "Angebot des Providers nicht gefunden – sein Preis ist unbekannt.", en: "Provider offer not found – its price is unknown." },
  "waehr.trotzdemHinterlegen": { de: "{warnung} Trotzdem hinterlegen?", en: "{warnung} Deposit anyway?" },
  "waehr.hinterlegenTrotzdem": { de: "Trotzdem hinterlegen", en: "Deposit anyway" },
  "waehr.fuerDeposit": { de: "das Deposit", en: "the deposit" },
  "waehr.fuerKanal": { de: "den Zahlkanal", en: "the payment channel" },
  "waehr.kanalTitel": { de: "Zahlkanal (SOL)", en: "Payment channel (SOL)" },
  "waehr.kanalLaufzeitAria": { de: "Laufzeit des Zahlkanals", en: "Payment channel duration" },
  "waehr.kanalEinzahlen": { de: "Einzahlen", en: "Deposit" },
  "waehr.kanalErklaerung": { de: "Einmal SOL einzahlen, dann bezahlt jede KI-Antwort dieses Providers eine versiegelte Gutschrift – ohne Transaktion je Antwort. Die Anteile nach A+ teilt das Programm beim Einlösen auf: an Empfänger mit SOL-Adresse, sonst an den Provider. Bleibt eine Antwort aus, zählt ihr Gebot vorsichtshalber mit. Nach Ablauf holt die App zurück, was nicht verbraucht ist.", en: "Deposit SOL once, then every AI answer from this provider is paid with a sealed credit – no transaction per answer. When redeeming, the program splits the A+ shares: to recipients with a SOL address, otherwise to the provider. If an answer never arrives, its bid counts to be safe. After expiry the app reclaims whatever is unused." },
  "waehr.kanalEinTag": { de: "1 Tag", en: "1 day" },
  "waehr.kanalSiebenTage": { de: "7 Tage", en: "7 days" },
  "waehr.kanalDreissigTage": { de: "30 Tage", en: "30 days" },
  "waehr.kanalOeffnen": { de: "Kanal öffnen", en: "Open channel" },
  "waehr.kanalNichtAngeboten": { de: "Dieser Provider nimmt keinen Zahlkanal an.", en: "This provider does not accept a payment channel." },
  "waehr.kanalAnderesProgramm": { de: "Der Provider nennt ein anderes Kanal-Programm als diese App – nicht geöffnet.", en: "The provider names a different channel program than this app – not opened." },
  "waehr.kanalProgrammFehlt": { de: "Das Zahlkanal-Programm liegt auf dieser Kette noch nicht – nichts eingezahlt.", en: "The payment channel program is not on this chain yet – nothing deposited." },
  "waehr.kanalFrage": { de: "{betrag} in einen Zahlkanal bei {provider} einzahlen? Bis {bis} ist die Einlage gesperrt; danach holt die App zurück, was nicht verbraucht ist. Empfänger von Anteilen mit SOL-Adresse: {anteile}, der Rest geht an den Provider. Kanal, Einlage und Einlösungen stehen öffentlich auf der Kette.", en: "Deposit {betrag} into a payment channel with {provider}? The deposit is locked until {bis}; after that the app reclaims whatever is unused. Share recipients with a SOL address: {anteile}, the rest goes to the provider. Channel, deposit and redemptions are public on the chain." },
  "waehr.kanalOffen": { de: "Zahlkanal offen: {betrag} bis {bis}.", en: "Payment channel open: {betrag} until {bis}." },
  "waehr.kanalAufstocken": { de: "Aufstocken", en: "Top up" },
  "waehr.kanalAufstockenTitel": { de: "Zahlkanal zu {provider} aufstocken", en: "Top up payment channel to {provider}" },
  "waehr.kanalAufstockenBetrag": { de: "Betrag in SOL", en: "Amount in SOL" },
  "waehr.kanalAufstockenFrage": { de: "{betrag} zusätzlich in den Kanal einzahlen? Der Ablauf bleibt; was nach Ablauf übrig ist, kommt zurück.", en: "Deposit an additional {betrag} into the channel? The expiry stays; whatever is left after expiry comes back." },
  "waehr.kanalAufgestockt": { de: "Aufgestockt um {betrag}.", en: "Topped up by {betrag}." },
  "waehr.kanalAndereWallet": { de: "Aufstocken geht nur mit der Wallet, die eingezahlt hat ({adresse}) – verbinde sie.", en: "Topping up only works with the wallet that deposited ({adresse}) – connect it." },
  "waehr.kanalZeile": { de: "{provider}: {betrag} eingezahlt, {frei} frei, bis {bis}", en: "{provider}: {betrag} deposited, {frei} free, until {bis}" },
  "waehr.kanalAbgelaufen": { de: "{provider}: abgelaufen seit {bis} – der Rest wird zurückgeholt", en: "{provider}: expired since {bis} – the rest is being reclaimed" },
  "waehr.kannNichtSignieren": { de: "Diese Wallet kann keine Transaktionen signieren.", en: "This wallet can't sign transactions." },
  "waehr.providerSolUnbekannt": { de: "SOL-Adresse des Providers unbekannt – erst eine KI-Anfrage stellen, damit der Provider sie mitteilt.", en: "The provider's SOL address is unknown – make an AI request first so the provider shares it." },
  "waehr.depositGedeckt": { de: "Deposit gedeckt.", en: "Deposit covered." },
  "waehr.depositGesperrt": { de: "{sol} SOL auf der Kette gesperrt.", en: "{sol} SOL locked on the chain." },
  "waehr.rueckholbarAb": { de: "Zurückholbar ab {zeit}.", en: "Refundable from {zeit}." },
  "waehr.depositAngekuendigt": { de: "Deposit gesperrt und angekündigt", en: "Deposit locked and announced" },
  "waehr.keinDeposit": { de: "Kein Deposit aktiv", en: "No active deposit" },
  "waehr.walletZumZurueckholen": { de: "Wallet verbinden, um zurückzuholen.", en: "Connect a wallet to refund." },
  "waehr.timelockLaeuft": { de: "Der Timelock läuft noch {min} Minuten. Vorher kann die Kette nichts freigeben – das ist die Absicherung, die den Provider ohne Vertrauen arbeiten lässt. Danach hier erneut klicken.", en: "The timelock runs for {min} more minutes. Before that the chain can't release anything – that is the safeguard that lets the provider work without trust. Click here again afterwards." },
  "waehr.zurueckgeholt": { de: "Zurückgeholt.", en: "Refunded." },
  "waehr.htlcFrei": { de: "{n} HTLC(s) freigegeben.", en: "{n} HTLC(s) released." },
  "waehr.rueckholungUnmoeglich": { de: "Zurückholen nicht möglich.", en: "Refund not possible." },
  // Eingebaute Wallet (shell/eingebaute-wallet.ts)
  "waehr.ueberLimit": { de: "Über dem Tageslimit", en: "Above the daily limit" },
  "waehr.ueberLimitText": { de: "Diese Zahlung liegt über dem, was die eingebaute Wallet ohne Nachfrage sendet.", en: "This payment is above what the built-in wallet sends without asking." },
  "waehr.limBetrag": { de: "Betrag:", en: "Amount:" },
  "waehr.limAn": { de: "an:", en: "to:" },
  "waehr.limLimit": { de: "Limit:", en: "Limit:" },
  "waehr.limIn24": { de: "in 24 Stunden", en: "per 24 hours" },
  "waehr.limSchon": { de: "schon gesendet:", en: "already sent:" },
  "waehr.trotzdemSenden": { de: "trotzdem senden", en: "send anyway" },
  "waehr.mitBunker": { de: "Mit Bunker gesperrt: Die 12 Wörter gehören dann nicht auf dieses Gerät – verbinde eine externe Wallet.", en: "Locked with a bunker: the 12 words don't belong on this device then – connect an external wallet." },
  "waehr.vorratNoch": { de: "Frische Empfangsadressen: noch {n}", en: "Fresh receiving addresses: {n} left" },
  "waehr.vorratLeer": { de: "Keine frischen Empfangsadressen mehr – „neue ableiten“ (mit deinen 12 Wörtern).", en: "No fresh receiving addresses left – “derive new ones” (with your 12 words)." },
  "waehr.guthaben": { de: "Guthaben: {betrag}", en: "Balance: {betrag}" },
  "waehr.verteilt": { de: " – auf {n} Adressen verteilt", en: " – spread over {n} addresses" },
  "waehr.guthabenRpc": { de: "Guthaben: nicht abrufbar (RPC)", en: "Balance: not available (RPC)" },
  "waehr.rpcWiderspruch": { de: "RPC-Anbieter widersprechen sich – Details in der Wallet", en: "RPC providers contradict each other – details in the wallet" },
  "waehr.frischKopiert": { de: "Frische Adresse kopiert – gib sie nur für diesen einen Empfang heraus", en: "Fresh address copied – give it out only for this one payment" },
  "waehr.fuerEingebaute": { de: "die eingebaute Wallet", en: "the built-in wallet" },
  "waehr.ableitenTitel": { de: "Frische Adressen ableiten", en: "Derive fresh addresses" },
  "waehr.ableitenText": { de: "Gib deine 12 Wörter ein. Die App leitet die nächsten {n} Adressen ab (Phantoms Konten in derselben Reihenfolge) und speichert nur ihre Schlüssel im Tresor.", en: "Enter your 12 words. The app derives the next {n} addresses (Phantom's accounts in the same order) and stores only their keys in the vault." },
  "waehr.zwoelfWoerter": { de: "12 Wörter", en: "12 words" },
  "waehr.ableiten": { de: "ableiten", en: "derive" },
  "waehr.frischeBereit": { de: "{n} frische Adressen bereit", en: "{n} fresh addresses ready" },
  "waehr.einrichtenTitel": { de: "Eingebaute Wallet einrichten", en: "Set up the built-in wallet" },
  "waehr.einrichtenText": { de: "Gib deine 12 Wörter ein. Die App leitet daraus deine Solana-Adresse ab (dieselbe wie in Phantom) und speichert nur den Schlüssel dazu im Tresor – die Wörter nicht.", en: "Enter your 12 words. The app derives your Solana address from them (the same as in Phantom) and stores only its key in the vault – not the words." },
  "waehr.eingebauteBereit": { de: "Eingebaute Wallet bereit: {adresse}…", en: "Built-in wallet ready: {adresse}…" },
  "waehr.limitGesetzt": { de: "Ohne Nachfrage höchstens {betrag} in 24 Stunden", en: "Without asking at most {betrag} per 24 hours" },
  "waehr.entfernenFrage": { de: "Eingebaute Wallet von diesem Gerät entfernen? Das Guthaben bleibt auf der Kette – mit deinen 12 Wörtern richtest du sie wieder ein (hier oder in Phantom).", en: "Remove the built-in wallet from this device? The balance stays on the chain – with your 12 words you set it up again (here or in Phantom)." },
  "waehr.entfernenKnopf": { de: "Entfernen", en: "Remove" },
  "waehr.eingebauteEntfernt": { de: "Eingebaute Wallet entfernt", en: "Built-in wallet removed" },
  "waehr.adresseKopiert": { de: "Adresse kopiert", en: "Address copied" },
  // Ohne Internet zahlen (shell/offline-zahlung.ts)
  "waehr.offlineOhneKonto": { de: "Für eine SOL-Zahlung ohne Netz braucht die Wallet ein Nonce-Konto – einmal mit Netz anlegen.", en: "For a SOL payment without a network the wallet needs a nonce account – create it once with a network." },
  "waehr.offlineVerbraucht": { de: "Der Nonce-Wert ist verbraucht – mit Netz „Wert auffrischen“, dann geht die nächste Offline-Zahlung.", en: "The nonce value is used up – “refresh value” with a network, then the next offline payment works." },
  "waehr.offlineBereit": { de: "Bereit für eine Offline-Zahlung (Wert vom {vom}).", en: "Ready for an offline payment (value from {vom})." },
  "waehr.brauchtNetz": { de: "Dafür braucht es Netz.", en: "This needs a network." },
  "waehr.nonceAnlegenFrage": { de: "Nonce-Konto für Zahlungen ohne Internet anlegen?\n\nMiete: {miete} – bleibt im Konto, zurück beim Schließen\nGebühr: {gebuehr}\nZusammen: {gesamt}", en: "Create a nonce account for payments without internet?\n\nRent: {miete} – stays in the account, returned on closing\nFee: {gebuehr}\nTotal: {gesamt}" },
  "waehr.nonceAngelegt": { de: "Nonce-Konto angelegt – eine Offline-Zahlung ist vorbereitet", en: "Nonce account created – an offline payment is prepared" },
  "waehr.nonceAufgefrischt": { de: "Nonce-Wert aufgefrischt – die nächste Offline-Zahlung ist vorbereitet", en: "Nonce value refreshed – the next offline payment is prepared" },
  "waehr.nonceSchliessenFrage": { de: "Nonce-Konto schließen? Die Miete geht zurück an die eingebaute Wallet; eine vorbereitete Offline-Zahlung, die noch nicht eingereicht ist, wird damit ungültig.", en: "Close the nonce account? The rent goes back to the built-in wallet; a prepared offline payment that hasn't been submitted becomes invalid." },
  "waehr.nichtsGeaendert": { de: "Nichts geändert", en: "Nothing changed" },
  "waehr.nonceGeschlossen": { de: "Nonce-Konto geschlossen – {betrag} zurück an die Wallet", en: "Nonce account closed – {betrag} back to the wallet" },
  "waehr.anWelcheAdresse": { de: "An welche Solana-Adresse?", en: "To which Solana address?" },
  "waehr.wievielSol": { de: "Wie viel SOL?", en: "How much SOL?" },
  "waehr.signieren": { de: "Signieren", en: "Sign" },
  "waehr.funkName": { de: "SOL offline", en: "SOL offline" },
  "waehr.anFunkGegeben": { de: "{betrag} signiert und ans Funkgerät gegeben – ein Gerät mit Netz reicht die Zahlung ein.", en: "{betrag} signed and handed to the radio – a device with a network submits the payment." },
  "waehr.alsDateiGespeichert": { de: "{betrag} signiert und als Datei gespeichert – auf einem Gerät mit Netz unter „Netz“ → Mesh → „Datei einlesen“.", en: "{betrag} signed and saved as a file – on a device with a network under “Network” → Mesh → “Import file”." },
  "belege.titel": { de: "Belege", en: "Receipts" },
  "belege.text": { de: "Quittungen deiner KI-Zahlungen – die neuesten 500, aus dem Tresor. Als CSV nur auf diesem Gerät gespeichert, nie hochgeladen; Beträge in msat bzw. Lamports.", en: "Receipts of your AI payments – the latest 500, from the vault. Saved as CSV on this device only, never uploaded; amounts in msat or lamports." },
  "belege.speichern": { de: "Als CSV speichern", en: "Save as CSV" },
  "belege.warnung": { de: "{n} Quittungen. Die Datei ist nicht verschlüsselt: Wer sie hat, sieht, wen du wann wofür bezahlt hast – samt Rechnungen und Zahlungsnachweisen.", en: "{n} receipts. The file is not encrypted: whoever has it sees whom you paid when and for what – including invoices and payment proofs." },
  "belege.keine": { de: "Noch keine Quittungen – sie entstehen, sobald du eine KI-Antwort bezahlst. Ist der Tresor gesperrt, erst entsperren.", en: "No receipts yet – they are created once you pay for an AI answer. If the vault is locked, unlock it first." },
  "belege.gespeichert": { de: "{n} Quittungen gespeichert.", en: "{n} receipts saved." },
};
