/** Texte der Zahlwege und Swaps (8.16e): Zahlschienen, Lightning, Solana, Tausch, Belege, Zap-Dialog. */
import type { Texte } from "../i18n.js";

export const zahlung: Texte = {
  // Allgemein
  "zahl.abbrechen": { de: "abbrechen", en: "cancel" },
  "zahl.fehler": { de: "Fehler: {fehler}", en: "Error: {fehler}" },
  "zahl.und": { de: " und ", en: " and " },
  "zahl.keineAntwort": { de: "keine Antwort", en: "no answer" },
  "zahl.ungueltigerBetrag": { de: "Ungültiger Betrag", en: "Invalid amount" },
  "zahl.warteWallet": { de: "Warte auf Bestätigung in der Wallet …", en: "Waiting for confirmation in the wallet …" },
  "zahl.wirdGesendet": { de: "Transaktion wird gesendet …", en: "Sending transaction …" },
  "zahl.warteKette": { de: "Warte auf Bestätigung der Kette …", en: "Waiting for chain confirmation …" },
  // KI-Zahlung (shell/ki-zahlung.ts)
  "zahl.andererBetrag": { de: "Rechnung über einen anderen Betrag – nicht gezahlt", en: "Invoice for a different amount – not paid" },
  "zahl.providerOhneAdresse": { de: "der Provider nennt keine Lightning-Adresse", en: "the provider gives no Lightning address" },
  "zahl.keineLightningWallet": { de: "keine Lightning-Wallet verbunden", en: "no Lightning wallet connected" },
  // Lightning und Zaps (rails.ts, zap-zahlung.ts)
  "zahl.adresseNichtErreichbar": { de: "Lightning-Adresse nicht erreichbar (HTTP {status})", en: "Lightning address not reachable (HTTP {status})" },
  "zahl.adresseOhneAnfrage": { de: "Lightning-Adresse liefert keine gültige Zahlungsanfrage", en: "Lightning address returns no valid payment request" },
  "zahl.betragAusserhalb": { de: "Betrag außerhalb {min}–{max} msat", en: "Amount outside {min}–{max} msat" },
  "zahl.adresseOhneRechnung": { de: "Lightning-Adresse lieferte keine Rechnung", en: "Lightning address returned no invoice" },
  "zahl.rechnungUeber": { de: "Rechnung über {verlangt} msat, gewollt {gewollt} msat – nicht gezahlt", en: "Invoice for {verlangt} msat, intended {gewollt} msat – not paid" },
  "zahl.keineLightningVerbinden": { de: "Keine Lightning-Wallet verbunden – im Wallet-Tab per NWC verbinden.", en: "No Lightning wallet connected – connect one via NWC in the wallet tab." },
  "zahl.guthabenNurNwc": { de: "Guthaben nur über NWC abfragbar", en: "Balance can only be queried via NWC" },
  "zahl.empfaengerOhneAdresse": { de: "Empfänger hat keine gültige Lightning-Adresse", en: "Recipient has no valid Lightning address" },
  "zahl.adresseOhneCallback": { de: "Lightning-Adresse liefert keinen gültigen Callback", en: "Lightning address returns no valid callback" },
  "zahl.keineZaps": { de: "Empfänger nimmt keine Zaps an (allowsNostr fehlt)", en: "Recipient doesn't accept zaps (allowsNostr missing)" },
  "zahl.keineRechnungEmpfaenger": { de: "Keine Rechnung vom Empfänger", en: "No invoice from the recipient" },
  // Solana (rails.ts, sol-wallet.ts, sol-transfer.ts, wallet-standard.ts, solana-connect.ts)
  "zahl.keineSolanaVerbinden": { de: "Keine Solana-Wallet verbunden – im Wallet-Tab verbinden.", en: "No Solana wallet connected – connect one in the wallet tab." },
  "zahl.anSichSelbst": { de: "Überweisung an sich selbst", en: "Transfer to yourself" },
  "zahl.nichtFreigegeben": { de: "Zahlung nicht freigegeben – nichts gesendet.", en: "Payment not approved – nothing sent." },
  "zahl.keineSignatur": { de: "Wallet lieferte keine gültige Signatur", en: "Wallet returned no valid signature" },
  "zahl.guthabenNichtAbfragbar": { de: "Guthaben nicht abfragbar", en: "Balance not available" },
  "zahl.woerterFremd": { de: "Diese Wörter gehören nicht zu deiner Identität.", en: "These words don't belong to your identity." },
  "zahl.keineAdresseReicht": { de: "Keine einzelne deiner {n} Adressen deckt den Betrag. Die App legt sie nicht zusammen – das verbände sie auf der Kette.", en: "None of your {n} addresses covers the amount on its own. The app doesn't merge them – that would link them on the chain." },
  "zahl.nichtGenugSol": { de: "Nicht genug SOL in der eingebauten Wallet.", en: "Not enough SOL in the built-in wallet." },
  "zahl.andereWallet": { de: "Diese Wörter ergeben eine andere Wallet.", en: "These words result in a different wallet." },
  "zahl.keineFrischeAdresse": { de: "Keine frische Adresse mehr – gib deine 12 Wörter ein, um neue abzuleiten.", en: "No fresh address left – enter your 12 words to derive new ones." },
  "zahl.limitGanz": { de: "Limit muss eine nicht negative ganze Zahl sein", en: "The limit must be a non-negative integer" },
  "zahl.keineEingebaute": { de: "Keine eingebaute Wallet eingerichtet", en: "No built-in wallet set up" },
  "zahl.keineSignaturVerlangt": { de: "Die Transaktion verlangt keine Signatur dieser Wallet", en: "The transaction requires no signature from this wallet" },
  "zahl.eingebauteGesperrt": { de: "Eingebaute Wallet nicht verfügbar (Tresor gesperrt?)", en: "Built-in wallet not available (vault locked?)" },
  "zahl.walletKannNicht": { de: "{wallet} kann {was} nicht", en: "{wallet} can't do {was}" },
  "zahl.walletNichtVerbunden": { de: "Wallet nicht verbunden", en: "Wallet not connected" },
  "zahl.walletOhneKette": { de: "{wallet} unterstützt {kette} nicht", en: "{wallet} doesn't support {kette}" },
  "zahl.walletOhneKonto": { de: "{wallet} gab kein Solana-Konto frei", en: "{wallet} shared no Solana account" },
  "zahl.walletOhneSignatur": { de: "{wallet} lieferte keine gültige Signatur", en: "{wallet} returned no valid signature" },
  "zahl.walletErkannt": { de: "Wallet erkannt: {namen}.", en: "Wallet detected: {namen}." },
  "zahl.walletBrowser": { de: "Wallet-Browser erkannt – Verbinden funktioniert direkt.", en: "Wallet browser detected – connecting works directly." },
  "zahl.browserWallet": { de: "Browser-Wallet erkannt (Phantom/Solflare).", en: "Browser wallet detected (Phantom/Solflare)." },
  "zahl.android": { de: "Android erkannt – die Wallet-App wird zum Bestätigen geöffnet.", en: "Android detected – the wallet app opens for confirmation." },
  "zahl.handy": { de: "Auf dem Handy öffnet sich deine Wallet-App. Danach geht es hier weiter.", en: "On the phone your wallet app opens. Afterwards you continue here." },
  "zahl.keineSolanaWallet": { de: "Keine Solana-Wallet gefunden. Auf dem Desktop hilft eine Extension (Phantom oder Solflare), oder du nutzt die App auf dem Handy.", en: "No Solana wallet found. On desktop an extension helps (Phantom or Solflare), or use the app on your phone." },
  "zahl.verbindungAbgelehnt": { de: "Wallet hat die Verbindung abgelehnt: {fehler}", en: "Wallet declined the connection: {fehler}" },
  // Ohne Internet (sol-offline-zahlung.ts, shell/zahlschienen.ts)
  "zahl.keinNonceKonto": { de: "Kein Nonce-Konto – erst mit Netz anlegen (Wallet-Tab).", en: "No nonce account – create one with a network first (wallet tab)." },
  "zahl.nonceVerbraucht": { de: "Der Nonce-Wert ist schon verbraucht – mit Netz auffrischen.", en: "The nonce value is already used – refresh it with a network." },
  "zahl.keineSolanaAdresse": { de: "Das ist keine Solana-Adresse", en: "That's not a Solana address" },
  "zahl.nichtFreigegebenErstellt": { de: "Zahlung nicht freigegeben – nichts erstellt.", en: "Payment not approved – nothing created." },
  "zahl.walletKannNichtSignieren": { de: "Die Wallet kann keine Transaktion signieren", en: "The wallet can't sign a transaction" },
  "zahl.offlineNurEingebaut": { de: "Ohne Internet zahlt nur die eingebaute Wallet – im Wallet-Tab einrichten.", en: "Without internet only the built-in wallet pays – set it up in the wallet tab." },
  "zahl.nonceNichtGefunden": { de: "Nonce-Konto nicht gefunden", en: "Nonce account not found" },
  "zahl.abgebrochenNichtsGesendet": { de: "Abgebrochen – nichts gesendet.", en: "Cancelled – nothing sent." },
  "zahl.keinNonceAngelegt": { de: "Kein Nonce-Konto angelegt", en: "No nonce account created" },
  // Tausch sats → SOL (swap-client.ts)
  "zahl.nichtsGesperrt": { de: "Auf der Kette ist nichts gesperrt.", en: "Nothing is locked on the chain." },
  "zahl.nochKeineSol": { de: "Der LP hat noch keine SOL hinterlegt. Diese Rechnung jetzt zu zahlen hieße, für nichts zu bezahlen.", en: "The LP hasn't locked any SOL yet. Paying this invoice now would mean paying for nothing." },
  "zahl.htlcEingeloest": { de: "Das SOL-HTLC wurde bereits eingelöst.", en: "The SOL HTLC has already been claimed." },
  "zahl.htlcZurueck": { de: "Das SOL-HTLC wurde bereits zurückgeholt.", en: "The SOL HTLC has already been refunded." },
  "zahl.fremderHashlock": { de: "Der Hashlock auf der Kette ist nicht der eigene – das Geld wäre nicht einlösbar.", en: "The hashlock on the chain isn't yours – the money couldn't be claimed." },
  "zahl.falscherEmpfaengerIst": { de: "Empfänger ist {ist}…, erwartet war die eigene Adresse {soll}….", en: "Recipient is {ist}…, expected your own address {soll}…." },
  "zahl.zuWenigGesperrt": { de: "Gesperrt sind {ist} Lamports, zugesagt waren {soll}.", en: "{ist} lamports are locked, {soll} were promised." },
  "zahl.solFristAbgelaufen": { de: "Die SOL-Frist ist bereits abgelaufen.", en: "The SOL deadline has already passed." },
  "zahl.solFristKnapp": { de: "Die SOL-Frist läuft in {min} Minuten ab – zu knapp, um noch sicher einzulösen.", en: "The SOL deadline ends in {min} minutes – too close to claim safely." },
  "zahl.fristReihenfolge": { de: "Die SOL-Frist endet nicht vor der Lightning-Frist. In dieser Reihenfolge kann der Swap einseitig schieflaufen.", en: "The SOL deadline doesn't end before the Lightning deadline. In this order the swap can fail one-sidedly." },
  "zahl.fristAbstand": { de: "Zwischen SOL- und Lightning-Frist liegen nur {min} Minuten; nötig sind mindestens {noetig}.", en: "Only {min} minutes between the SOL and Lightning deadlines; at least {noetig} are needed." },
  "zahl.gegenleistungGeprueft": { de: "Gegenleistung geprüft: {lamports} Lamports gesperrt, einlösbar bis {bis}.", en: "Counterpart checked: {lamports} lamports locked, claimable until {bis}." },
  "zahl.preimageLaenge": { de: "Preimage muss 32 Bytes haben, hat {n}", en: "Preimage must be 32 bytes, has {n}" },
  "zahl.fristUnbekannt": { de: "Die Frist dieses Swaps ist unbekannt – ohne Frist wird nicht eingelöst.", en: "This swap's deadline is unknown – no claim without a deadline." },
  "zahl.fristAbgelaufen": { de: "Die Frist ist abgelaufen. Nicht mehr einlösen – deine Lightning-Zahlung läuft von selbst zurück.", en: "The deadline has passed. Don't claim anymore – your Lightning payment reverts by itself." },
  "zahl.fristZuKnapp": { de: "Die Frist endet in {min} Minuten – zu knapp, um sicher einzulösen. Deine Lightning-Zahlung läuft von selbst zurück.", en: "The deadline ends in {min} minutes – too close to claim safely. Your Lightning payment reverts by itself." },
  "zahl.htlc6000": { de: "Der Betrag muss größer als 0 sein.", en: "The amount must be greater than 0." },
  "zahl.htlc6001": { de: "Die Frist liegt in der Vergangenheit.", en: "The deadline is in the past." },
  "zahl.htlc6002": { de: "Der Swap ist bereits eingelöst oder zurückerstattet.", en: "The swap has already been claimed or refunded." },
  "zahl.htlc6003": { de: "Das Preimage passt nicht zum Hashlock.", en: "The preimage doesn't match the hashlock." },
  "zahl.htlc6004": { de: "Falscher Empfänger.", en: "Wrong recipient." },
  "zahl.htlc6005": { de: "Falscher Initiator.", en: "Wrong initiator." },
  "zahl.htlc6006": { de: "Die Frist ist noch nicht abgelaufen.", en: "The deadline hasn't passed yet." },
  "zahl.htlc6007": { de: "Frist abgelaufen – die SOL gehen an den Liquiditätsgeber zurück, deine Lightning-Zahlung wird erstattet.", en: "Deadline passed – the SOL go back to the liquidity provider, your Lightning payment is refunded." },
  "zahl.einloesungVorbereiten": { de: "Einlösung wird vorbereitet …", en: "Preparing the claim …" },
  "zahl.einloesungAbgelehnt": { de: "Einlösung abgelehnt: {fehler}", en: "Claim rejected: {fehler}" },
  "zahl.einloesungAbgelehntMeist": { de: "Einlösung abgelehnt: {fehler} – meist, weil die Frist abgelaufen ist oder das Preimage nicht passt.", en: "Claim rejected: {fehler} – usually because the deadline passed or the preimage doesn't match." },
  "zahl.sicherungHinweis": { de: "Diese Datei enthält die Preimages offener Swaps. Wer sie hat, kann die zugehörigen SOL einlösen. Sicher aufbewahren, nicht weitergeben.", en: "This file contains the preimages of open swaps. Whoever has it can claim the corresponding SOL. Keep it safe, don't share it." },
  "zahl.vorabNichtAngekuendigt": { de: "Das Angebot nannte keine Vorab-Gebühr.", en: "The offer named no upfront fee." },
  "zahl.vorabAnders": { de: "Verlangt sind {sats} sats, angekündigt waren {angekuendigt}.", en: "{sats} sats are asked, {angekuendigt} were announced." },
  "zahl.vorabZuHoch": { de: "Eine Vorab-Gebühr über {max} sats zahlt die App nicht.", en: "The app doesn't pay an upfront fee above {max} sats." },
  "zahl.vorabRechnungUngueltig": { de: "Die Rechnung für die Vorab-Gebühr ist ungültig.", en: "The invoice for the upfront fee is invalid." },
  "zahl.vorabBetragAnders": { de: "Die Rechnung nennt einen anderen Betrag als die Vorab-Gebühr.", en: "The invoice names a different amount than the upfront fee." },
  "zahl.schrittWarteLp": { de: "Warte auf die Antwort des Liquiditätsgebers.", en: "Waiting for the liquidity provider's answer." },
  "zahl.schrittPruefe": { de: "Rechnung ist da. Erst wird geprüft, ob die SOL wirklich gesperrt sind – noch nicht zahlen.", en: "The invoice is here. First we check that the SOL are really locked – don't pay yet." },
  "zahl.schrittZahlbar": { de: "Geprüft. Rechnung kann jetzt bezahlt werden.", en: "Checked. The invoice can be paid now." },
  "zahl.schrittBezahlt": { de: "Bezahlt. Jetzt die SOL einlösen, damit der Tausch abschließt.", en: "Paid. Now claim the SOL so the swap completes." },
  "zahl.schrittUnsicher": { de: "Einlösen ist nicht mehr sicher.", en: "Claiming is no longer safe." },
  "zahl.schrittJetzt": { de: "Jetzt einlösen – in {min} Minuten ist es zu spät.", en: "Claim now – in {min} minutes it's too late." },
  "zahl.schrittFertig": { de: "Fertig. Die SOL sind auf der eigenen Adresse.", en: "Done. The SOL are on your own address." },
  "zahl.schrittAbgelaufen": { de: "Die Frist ist abgelaufen. Der gezahlte Betrag läuft von selbst zurück.", en: "The deadline has passed. The paid amount reverts by itself." },
  // Prüfung vor dem Tausch (tauschPruefung)
  "zahl.pruefMuster": { de: "Eine Adresse wurde {n}-mal benutzt. Daraus lässt sich ein Muster ablesen – und Gewohnheiten identifizieren Menschen zuverlässiger als einzelne Vorgänge. Die Vergangenheit lässt sich nicht mehr trennen.", en: "An address was used {n} times. A pattern can be read from that – and habits identify people more reliably than single transactions. The past can't be separated anymore." },
  "zahl.pruefZweimal": { de: "Eine Adresse wurde zweimal benutzt. Damit sind diese beiden Vorgänge öffentlich miteinander verbunden. Ab jetzt eine frische nehmen.", en: "An address was used twice. This publicly links those two transactions. Use a fresh one from now on." },
  "zahl.pruefFrischeAdresse": { de: "Frische Adresse nehmen (Nummer {n}).", en: "Use a fresh address (number {n})." },
  "zahl.pruefRund": { de: "{sol} SOL ist ein runder Betrag. Wer mehrfach denselben runden Betrag bewegt, verbindet damit seine Adressen wieder – auch wenn jede frisch war. Ein kleiner Zuschlag bricht das Muster.", en: "{sol} SOL is a round amount. Moving the same round amount several times links your addresses again – even if each was fresh. A small surcharge breaks the pattern." },
  "zahl.pruefBetragAendern": { de: "Betrag auf {sol} SOL ändern.", en: "Change the amount to {sol} SOL." },
  "zahl.pruefZeitKnapp": { de: "Der letzte Swap war vor {min} Minuten. Zwei Vorgänge dicht hintereinander lassen sich über die Zeit verbinden, auch bei frischen Adressen. Wenn es darauf ankommt: warten.", en: "The last swap was {min} minutes ago. Two transactions close together can be linked by time, even with fresh addresses. If it matters: wait." },
  "zahl.pruefZeitMoeglich": { de: "Letzter Swap vor {min} Minuten – eine Verbindung ist möglich.", en: "Last swap {min} minutes ago – a link is possible." },
  "zahl.pruefWarten": { de: "Warten, wenn es darauf ankommt.", en: "Wait, if it matters." },
  // HTLC (sol-htlc.ts, refund-watcher.ts, relay-einloesung.ts)
  "zahl.hashlockLaenge": { de: "Hashlock muss 32 Bytes haben, hat {n}", en: "Hashlock must be 32 bytes, has {n}" },
  "zahl.lamportsGanz": { de: "Betrag muss eine positive ganze Zahl in Lamports sein", en: "The amount must be a positive integer in lamports" },
  "zahl.aufteilungUngueltig": { de: "Ungültige Aufteilung: der Verbrauchsanteil muss positiv sein.", en: "Invalid split: the spend share must be positive." },
  "zahl.timelockZehnMinuten": { de: "Der Timelock muss mindestens 10 Minuten in der Zukunft liegen.", en: "The timelock must be at least 10 minutes in the future." },
  "zahl.instruktionen": { de: "Instruktionen werden gebaut …", en: "Building instructions …" },
  "zahl.txAbgelehnt": { de: "Transaktion abgelehnt: {fehler}", en: "Transaction rejected: {fehler}" },
  "zahl.rechnungsHashUngueltig": { de: "Hash der Rechnung ungültig", en: "Invalid invoice hash" },
  "zahl.fristEineStunde": { de: "Die Frist muss mehr als eine Stunde in der Zukunft liegen.", en: "The deadline must be more than an hour in the future." },
  "zahl.sperreAbgelehnt": { de: "Sperre abgelehnt: {fehler}", en: "Lock rejected: {fehler}" },
  "zahl.rueckholungAbgelehnt": { de: "Zurückholen abgelehnt – meist, weil der Timelock noch läuft oder ein Teil bereits eingelöst wurde.", en: "Refund rejected – usually because the timelock is still running or part was already claimed." },
  "zahl.sperreAufgegeben": { de: "{sol} SOL: Zurückholen mehrfach abgelehnt. Meist heißt das, dass die Gegenseite bereits eingelöst hat – dann ist nichts mehr offen.", en: "{sol} SOL: refund rejected several times. Usually this means the other side already claimed – then nothing is open anymore." },
  "zahl.letzteMeldung": { de: "Letzte Meldung: {fehler}", en: "Last message: {fehler}" },
  "zahl.sperreLaeuft": { de: "{sol} SOL gesperrt, zurückholbar in {dauer}. Die Wartezeit ist die Absicherung – vorher kann die Kette nichts freigeben.", en: "{sol} SOL locked, refundable in {dauer}. The waiting time is the safeguard – before that the chain can't release anything." },
  "zahl.sperreFaellig": { de: "{sol} SOL sind fällig und werden zurückgeholt.", en: "{sol} SOL are due and are being refunded." },
  "zahl.relayerUnvollstaendig": { de: "Einlösung für den Relayer unvollständig: {grund}", en: "Claim for the relayer incomplete: {grund}" },
  // Tausch SOL → sats (rueck-swap.ts)
  "zahl.keinRueckAngebot": { de: "Dieses Angebot tauscht nicht SOL gegen sats.", en: "This offer doesn't swap SOL for sats." },
  "zahl.angebotAbgelaufen": { de: "Das Angebot ist abgelaufen.", en: "The offer has expired." },
  "zahl.lpTauscht": { de: "Der LP tauscht {min}–{max} sats.", en: "The LP swaps {min}–{max} sats." },
  "zahl.rechnungAndererBetrag": { de: "Die Rechnung nennt einen anderen Betrag.", en: "The invoice names a different amount." },
  "zahl.fristenPassenNicht": { de: "Die Fristen des Angebots passen nicht: {grund}", en: "The offer's deadlines don't fit: {grund}" },
  "zahl.sperreUeberWoche": { de: "Das Angebot verlangt eine Sperre von mehr als einer Woche.", en: "The offer requires a lock of more than a week." },
  "zahl.solKommenZurueck": { de: "Deine SOL kommen nach Ablauf der Sperre zurück (ab {ab}); solange die App offen ist, holt sie sie selbst zurück.", en: "Your SOL come back after the lock expires (from {ab}); while the app is open, it refunds them itself." },
  "zahl.gesperrtWarte": { de: "Gesperrt. Warte auf den LP … Zahlt er nicht, kommen deine SOL nach Ablauf der Sperre zurück (ab {ab}); solange die App offen ist, holt sie sie selbst zurück.", en: "Locked. Waiting for the LP … If it doesn't pay, your SOL come back after the lock expires (from {ab}); while the app is open, it refunds them itself." },
  "zahl.rueckFertig": { de: "Fertig: {sats} sats sind in deiner Lightning-Wallet.", en: "Done: {sats} sats are in your Lightning wallet." },
  "zahl.rueckZuSpaet": { de: "Der LP hat deine Rechnung bezahlt ({sats} sats), die SOL aber nicht rechtzeitig eingelöst. {zurueck}", en: "The LP paid your invoice ({sats} sats) but didn't claim the SOL in time. {zurueck}" },
  "zahl.rueckAbgelehnt": { de: "abgelehnt: {text}", en: "declined: {text}" },
  "zahl.rueckGescheitert": { de: "Zahlung gescheitert", en: "payment failed" },
  "zahl.rueckNichtGetauscht": { de: "Der LP hat nicht getauscht ({warum}). {zurueck}", en: "The LP didn't swap ({warum}). {zurueck}" },
  // Relay-Zugang kaufen (relay-kauf.ts)
  "zahl.relayAntwortet": { de: "Relay antwortet {status}", en: "Relay answers {status}" },
  "zahl.angebotPasstNicht": { de: "Angebot passt nicht zur Anfrage", en: "Offer doesn't match the request" },
  "zahl.angebotAndererPreis": { de: "Angebot nennt einen anderen Preis", en: "Offer names a different price" },
  "zahl.angebotOhneAdresse": { de: "Angebot ohne gültige Adresse oder Referenz", en: "Offer without a valid address or reference" },
  // RPC-Stichprobe (rpc-stichprobe.ts)
  "zahl.vergleichNetz": { de: "Netz", en: "network" },
  "zahl.vergleichBlockhash": { de: "letzter Blockhash", en: "latest blockhash" },
  "zahl.vergleichKontostand": { de: "Kontostand", en: "balance" },
  "zahl.rpcWiderspruch": { de: "Achtung, RPC-Anbieter widersprechen sich: {warnungen}", en: "Warning, RPC providers contradict each other: {warnungen}" },
  "zahl.stichprobeStimmt": { de: "Stichprobe {anbieter}: {was} stimmt überein.", en: "Spot check {anbieter}: {was} matches." },
  "zahl.stichprobeStimmen": { de: "Stichprobe {anbieter}: {was} stimmen überein.", en: "Spot check {anbieter}: {was} match." },
  "zahl.stichprobeUnmoeglich": { de: "Stichprobe nicht möglich: {grund}", en: "Spot check not possible: {grund}" },
  // SOL-Trinkgeld (trinkgeld-beleg.ts)
  "zahl.belegAndereKette": { de: "Beleg für {beleg}, eingestellt ist {kette}", en: "Receipt for {beleg}, {kette} is set" },
  "zahl.ketteNichtErreichbar": { de: "Kette nicht erreichbar ({fehler})", en: "Chain not reachable ({fehler})" },
  "zahl.wirdGeprueft": { de: "wird geprüft …", en: "checking …" },
  "zahl.belegt": { de: "belegt ✓", en: "confirmed ✓" },
  "zahl.unbestaetigt": { de: "unbestätigt ({grund})", en: "unconfirmed ({grund})" },
  "zahl.falsch": { de: "falsch: {grund}", en: "wrong: {grund}" },
  "zahl.trinkgeldZeile": { de: "◎ Trinkgeld {betrag} · {stand}", en: "◎ Tip {betrag} · {stand}" },
  "zahl.trinkgeldNotiz": { de: " – „{notiz}“", en: " – “{notiz}”" },
  // Preise (preis-anzeige.ts)
  "zahl.ohneKursSol": { de: "{betrag} (SOL: kein Kurs)", en: "{betrag} (SOL: no rate)" },
  "zahl.ohneKursSats": { de: "{betrag} (sats: kein Kurs)", en: "{betrag} (sats: no rate)" },
  "zahl.keinKurs": { de: "Kurs SOL/sats: keine Kurs-Events gefunden – SOL-Preise nicht verfügbar", en: "SOL/sats rate: no rate events found – SOL prices not available" },
  "zahl.kursEineQuelle": { de: "Kurs: 1 SOL ≈ {sats} sats (Median aus {n} Quelle)", en: "Rate: 1 SOL ≈ {sats} sats (median of {n} source)" },
  "zahl.kursQuellen": { de: "Kurs: 1 SOL ≈ {sats} sats (Median aus {n} Quellen)", en: "Rate: 1 SOL ≈ {sats} sats (median of {n} sources)" },
  "zahl.kursWenigeQuellen": { de: "Kurs aus nur {n} Quelle(n)", en: "Rate from only {n} source(s)" },
  "zahl.kursStreuung": { de: "Kursquellen weichen bis {prozent} % voneinander ab", en: "Rate sources differ by up to {prozent}%" },
  "zahl.anbieterOhnePreis": { de: "Anbieter nennt keinen Preis", en: "Provider names no price" },
  "zahl.anbieterKurs": { de: "Der Anbieter rechnet mit 1 SOL ≈ {anbieter} sats, der Markt mit {markt} sats ({prozent} % Abweichung).", en: "The provider assumes 1 SOL ≈ {anbieter} sats, the market {markt} sats ({prozent}% deviation)." },
  // Zap-Dialog im Chat (chat-zap.ts)
  "zahl.zapSenden": { de: "Zap senden", en: "Send zap" },
  "zahl.empfaenger": { de: "Empfänger", en: "Recipient" },
  "zahl.betrag": { de: "Betrag", en: "Amount" },
  "zahl.einheitSats": { de: "sats", en: "sats" },
  "zahl.einheitSol": { de: "SOL", en: "SOL" },
  "zahl.wallet": { de: "Wallet", en: "Wallet" },
  "zahl.optLightning": { de: "Lightning (sats)", en: "Lightning (sats)" },
  "zahl.optSolana": { de: "Solana (SOL)", en: "Solana (SOL)" },
  "zahl.belegOeffentlichWahl": { de: "Beleg öffentlich – verknüpft deine Identität für alle sichtbar mit Betrag, Adresse und Transaktion", en: "Public receipt – links your identity visibly for everyone to amount, address and transaction" },
  "zahl.rauschenWahl": { de: "runden Betrag leicht verrauschen (höchstens +0,3 %) – runde Beträge verbinden Adressen auf der Kette wieder", en: "add slight noise to round amounts (at most +0.3%) – round amounts link addresses on the chain again" },
  "zahl.holeZiel": { de: "hole Zahlungsziel …", en: "fetching payment target …" },
  "zahl.betragFehlt": { de: "Betrag fehlt", en: "Amount missing" },
  "zahl.lightningInSats": { de: "Lightning zahlt in sats", en: "Lightning pays in sats" },
  "zahl.zapAnonym": { de: "Der Zap geht anonym hinaus (NIP-57): Der Empfänger sieht den Betrag, aber nicht, von wem.", en: "The zap goes out anonymously (NIP-57): the recipient sees the amount, but not who sent it." },
  "zahl.frageRechnung": { de: "Frage {name} versiegelt nach einer Rechnung …", en: "Asking {name} for an invoice, sealed …" },
  "zahl.keineRechnungVersiegelt": { de: "{name} zeigt keine Lightning-Adresse öffentlich und hat nicht mit einer Rechnung geantwortet – vielleicht offline, ohne verbundene Wallet (NWC) oder du bist kein Kontakt.", en: "{name} shows no public Lightning address and did not answer with an invoice – maybe offline, without a connected wallet (NWC), or you are not a contact." },
  "zahl.nurGanzeSats": { de: "Ohne öffentliche Lightning-Adresse nur ganze sats", en: "Without a public Lightning address only whole sats" },
  "zahl.warteAufWallet": { de: "warte auf die Wallet …", en: "waiting for the wallet …" },
  "zahl.gezappt": { de: "gezappt! {sats} sats", en: "zapped! {sats} sats" },
  "zahl.solanaInSol": { de: "Solana zahlt in SOL", en: "Solana pays in SOL" },
  "zahl.frageAdresse": { de: "frage die Adresse versiegelt beim Empfänger an … (bis 75 s)", en: "asking the recipient for an address, sealed … (up to 75 s)" },
  "zahl.oeffentlicheAdresseFrage": { de: "{name} hat nicht geantwortet. Im Profil steht eine öffentliche SOL-Adresse – ein Trinkgeld dorthin ist für jeden sichtbar mit dieser Person verknüpft, und alle Trinkgelder landen auf derselben Adresse. Trotzdem dorthin?", en: "{name} didn't answer. The profile has a public SOL address – a tip there is visibly linked to this person for everyone, and all tips land on the same address. Send there anyway?" },
  "zahl.solAdresseVon": { de: "SOL-Adresse von {name}", en: "SOL address of {name}" },
  // Dialoge statt confirm()/prompt() (C-1d)
  "zahl.trinkgeldTitel": { de: "Trinkgeld in SOL", en: "Tip in SOL" },
  "zahl.trotzdemDorthin": { de: "Trotzdem dorthin", en: "Send there anyway" },
  "zahl.weiterZurZahlung": { de: "Weiter zur Zahlung", en: "Continue to payment" },
  "zahl.ohneEmpfaengerAdresse": { de: "abgebrochen – keine Empfänger-Adresse", en: "cancelled – no recipient address" },
  "zahl.warteAufSignatur": { de: "warte auf die Signatur der Wallet …", en: "waiting for the wallet signature …" },
  "zahl.gesendetSig": { de: "gesendet! sig: {sig}…", en: "sent! sig: {sig}…" },
  "zahl.belegOeffentlich": { de: "Beleg öffentlich", en: "public receipt" },
  "zahl.belegAnEmpfaenger": { de: "Beleg an den Empfänger", en: "receipt to the recipient" },
  "zahl.belegNichtGesendet": { de: "Beleg nicht gesendet ({fehler})", en: "receipt not sent ({fehler})" },
  "zahl.kanalLaufzeitZuKurz": { de: "Ein Zahlkanal muss mindestens zwei Stunden laufen.", en: "A payment channel must run for at least two hours." },
  "zahl.kanalNoetig": { de: "Mit SOL als Standard-Schiene zahlt die App KI nur über einen Zahlkanal – zu diesem Provider ist keiner offen. Nichts gesendet: Kanal öffnen (Währung › Hinterlegen) oder unter Währung › Zahlen Lightning als Standard-Schiene wählen.", en: "With SOL as default rail the app pays AI only through a payment channel – none is open to this provider. Nothing sent: open a channel (Wallet › Deposit) or choose Lightning as default rail under Wallet › Pay." },
  "zahl.kanalOhneKurs": { de: "Der Provider nennt in seinem Angebot keinen SOL-Kurs – ohne ihn lässt sich die Gutschrift nicht berechnen. Nichts gesendet.", en: "The provider's offer names no SOL rate – without it the credit cannot be computed. Nothing sent." },
  "zahl.kanalErschoepft": { de: "Der Zahlkanal zu diesem Provider deckt kein weiteres Gebot mehr. Nichts gesendet – stocke ihn auf (Währung › Hinterlegen), öffne einen neuen oder warte, bis er abläuft.", en: "The payment channel to this provider cannot cover another bid. Nothing sent – top it up (Wallet › Deposit), open a new one or wait until it expires." },
  "zahl.kanalKnapp": { de: "Der Zahlkanal wird knapp – noch {frei}. Stocke ihn auf (Währung › Hinterlegen), damit die Session nicht abbricht.", en: "The payment channel is running low – {frei} left. Top it up (Wallet › Deposit) so the session doesn't stop." },
  "zahl.kanalBezahlt": { de: "Über den Zahlkanal bezahlt: {betrag}", en: "Paid through the payment channel: {betrag}" },
  "anf.anfordern": { de: "Anfordern statt senden", en: "Request instead of send" },
  "anf.titel": { de: "Zahlung anfordern von {name}", en: "Request payment from {name}" },
  "anf.text": { de: "Die Anforderung kommt ins Eingabefeld und geht wie jede Nachricht versiegelt hinaus. In sats stellt deine Wallet (NWC) eine Rechnung aus; in SOL nennt die App deine Adresse für genau diesen Kontakt.", en: "The request goes into the input field and is sent sealed like any message. In sats your wallet (NWC) issues an invoice; in SOL the app gives your address for exactly this contact." },
  "anf.betrag": { de: "Betrag", en: "Amount" },
  "anf.einheit": { de: "Einheit", en: "Unit" },
  "anf.notiz": { de: "Wofür (optional)", en: "What for (optional)" },
  "anf.erstellen": { de: "Anforderung erstellen", en: "Create request" },
  "anf.betragUngueltig": { de: "Kein gültiger Betrag – sats als ganze Zahl, SOL mit höchstens 9 Nachkommastellen.", en: "Not a valid amount – sats as a whole number, SOL with at most 9 decimals." },
  "anf.ohneLnWallet": { de: "Für eine Anforderung in sats braucht die App eine verbundene Lightning-Wallet (NWC), die Rechnungen ausstellt.", en: "A request in sats needs a connected Lightning wallet (NWC) that issues invoices." },
  "anf.ohneSolWallet": { de: "Für eine Anforderung in SOL braucht die App die eingebaute Wallet – sie gibt jedem Kontakt eine eigene Adresse.", en: "A request in SOL needs the built-in wallet – it gives each contact its own address." },
  "anf.imFeld": { de: "Anforderung steht im Eingabefeld – mit Senden geht sie versiegelt an {name}.", en: "The request is in the input field – send it to deliver it sealed to {name}." },
  "anf.bezahlen": { de: "Bezahlen", en: "Pay" },
  "anf.bezahlenTitel": { de: "Anforderung von {name}", en: "Request from {name}" },
  "anf.womit": { de: "Womit bezahlen?", en: "Pay with?" },
  "anf.weiter": { de: "Weiter", en: "Continue" },
  "anf.bezahlenText": { de: "{name} fordert {betrag} an. Nur bezahlen, wenn du diese Anforderung erwartest – gezahlt ist gezahlt.", en: "{name} requests {betrag}. Only pay if you expect this request – a payment can't be undone." },
  "anf.bezahlt": { de: "Bezahlt: {betrag}", en: "Paid: {betrag}" },
};
